$axure.loadCurrentPage({
  "url":"里程统计.html",
  "generationDate":new Date(1558324042463.48),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"yys_name",
"car_chePai_card",
"car_chePai_color",
"car_leixing",
"car_ICcard",
"yy_leixing",
"car_InterNet_leixing",
"car_jingYingLuXian",
"car_zhuangTai",
"quYu",
"phone",
"mail",
"name",
"NewVariable"],
  "page":{
    "packageId":"1c98af3822d9424db84a7287906ba7aa",
    "type":"Axure:Page",
    "name":"里程统计",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"615133ba42ec48e79be3f1a5d3cf6cf6",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":36,
              "y":245},
            "size":{
              "width":898,
              "height":105}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ad179b29cde4daf8ae874c59dbef92b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":235,
                  "y":0},
                "size":{
                  "width":101,
                  "height":69}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bb7b48d5637b47398421b68c2d2ebb1e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":235,
                      "y":0},
                    "size":{
                      "width":101,
                      "height":69}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆基本信息/u13.png"}},
{
              "id":"c987e8e2c7d740afab3286da684388d5",
              "label":"所属区域格1",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":235,
                  "y":69},
                "size":{
                  "width":101,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4f7641bcd83145a49586f43073791a4c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":235,
                      "y":69},
                    "size":{
                      "width":101,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆基本信息/所属区域格4_u109.png"}},
{
              "id":"9707829120334059af175636f9edbd38",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "stateStyles":{
                  "mouseOver":{
}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":336,
                  "y":0},
                "size":{
                  "width":85,
                  "height":69}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d7a5e45fa22a42a2aa51fd76ca33f272",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseOver":{
}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":336,
                      "y":0},
                    "size":{
                      "width":85,
                      "height":69}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆基本信息/u17.png"}},
{
              "id":"b862b4f17a57437281b6cad5853f97ef",
              "label":"车牌号格1",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":336,
                  "y":69},
                "size":{
                  "width":85,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3319d049f7c84cd2b890f369bcdd2f9d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":336,
                      "y":69},
                    "size":{
                      "width":85,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆基本信息/车牌号格4_u113.png"}},
{
              "id":"abe6859476964c7aa882acb359cc8ab8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":421,
                  "y":0},
                "size":{
                  "width":61,
                  "height":69}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"53ee57e103f44e1bb43eaf83378ce05f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":421,
                      "y":0},
                    "size":{
                      "width":61,
                      "height":69}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆基本信息/u19.png"}},
{
              "id":"ed7aae2c15be4d42b48a587eac0ed2f4",
              "label":"车牌颜色格1",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":421,
                  "y":69},
                "size":{
                  "width":61,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"36e38ae7b4354b8394c519cc846a7230",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":421,
                      "y":69},
                    "size":{
                      "width":61,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆基本信息/车牌颜色格4_u115.png"}},
{
              "id":"e30f113728e446a69f36f66a122c0d38",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":547,
                  "y":0},
                "size":{
                  "width":82,
                  "height":69}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b9b188f35b4947bfa91497f73542078a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":547,
                      "y":0},
                    "size":{
                      "width":82,
                      "height":69}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆基本信息/u23.png"}},
{
              "id":"2b107c60e65c4a1da4ea99ca42f4dc65",
              "label":"IC卡号格1",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":547,
                  "y":69},
                "size":{
                  "width":82,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bcabf9b90fb7421fb466698c35f4c6d1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":547,
                      "y":69},
                    "size":{
                      "width":82,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆基本信息/ic卡号格4_u119.png"}},
{
              "id":"a41f18598f634a67803d38d4eb34860d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":482,
                  "y":0},
                "size":{
                  "width":65,
                  "height":69}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"10ea1b45ed0143c79e33c694be8c668a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":482,
                      "y":0},
                    "size":{
                      "width":65,
                      "height":69}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆基本信息/u21.png"}},
{
              "id":"2183356740ab44e9b18ca367489680d8",
              "label":"车辆类型格1",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":482,
                  "y":69},
                "size":{
                  "width":65,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c54a6bfef9cf4112943e5d63ab1ec12d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":482,
                      "y":69},
                    "size":{
                      "width":65,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆基本信息/车辆类型格4_u117.png"}},
{
              "id":"eda66400877c47729310a12c83a10d8b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":629,
                  "y":0},
                "size":{
                  "width":74,
                  "height":69}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"86ccd8e388e84da394f625167c9eb6c6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":629,
                      "y":0},
                    "size":{
                      "width":74,
                      "height":69}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆基本信息/u11.png"}},
{
              "id":"7cb3ad48cb9e41cd8382d8620176d868",
              "label":"运营类型格1",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":629,
                  "y":69},
                "size":{
                  "width":74,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2f4f9b06b8ed4d7098bfa59e6a4960dc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":629,
                      "y":69},
                    "size":{
                      "width":74,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆基本信息/u107.png"}},
{
              "id":"f03fe3746cff4ba2a56802a676947e9b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":703,
                  "y":0},
                "size":{
                  "width":93,
                  "height":69}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ef89ccf3be27403cb76379c97b4a5b05",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":703,
                      "y":0},
                    "size":{
                      "width":93,
                      "height":69}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/里程统计/u19.png"}},
{
              "id":"e7e1b5b028074f23b129ebb0a7ecb479",
              "label":"网络类型格1",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":703,
                  "y":69},
                "size":{
                  "width":93,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9bc20103b70148eb9ac484a6c152890c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":703,
                      "y":69},
                    "size":{
                      "width":93,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆保险信息管理/u41.png"}},
{
              "id":"0dd3915836db4b2a92f89230657d37f0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":796,
                  "y":0},
                "size":{
                  "width":102,
                  "height":69}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fe7b9b8a439644be9756a3dd8f295589",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":796,
                      "y":0},
                    "size":{
                      "width":102,
                      "height":69}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/里程统计/u21.png"}},
{
              "id":"e83c1781d81f444aa5a9c3747bc8a932",
              "label":"经营路线格1",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":796,
                  "y":69},
                "size":{
                  "width":102,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"70ba719634644f949a1df37594e7b0d2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":796,
                      "y":69},
                    "size":{
                      "width":102,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/里程统计/经营路线格1_u43.png"}},
{
              "id":"d96c7a4b7b8d4b3885af574fa73ea209",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":80,
                  "y":0},
                "size":{
                  "width":74,
                  "height":69}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"abdce76e38704cda8fd4d62a67a017b3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":80,
                      "y":0},
                    "size":{
                      "width":74,
                      "height":69}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆基本信息/u11.png"}},
{
              "id":"fd8c1891cc194bbab7b01605c8be7e1b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":80,
                  "y":69},
                "size":{
                  "width":74,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"279df38cd02c4959a210e91e7602154c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":80,
                      "y":69},
                    "size":{
                      "width":74,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆基本信息/u107.png"}},
{
              "id":"afef215c11e340dd8512d60c03c8060e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "size":{
                  "width":80,
                  "height":69}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"abc80042ec2d4daa9cea912a59ad2415",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "size":{
                      "width":80,
                      "height":69}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/里程统计/u1.png"}},
{
              "id":"1e0f6d9cab8447ab966b646989db364e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":69},
                "size":{
                  "width":80,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c3c3795689ad438baaa1675966182f91",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":69},
                    "size":{
                      "width":80,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/里程统计/u23.png"}},
{
              "id":"b38ad9d76e2242a0824d134e5991a960",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":154,
                  "y":0},
                "size":{
                  "width":81,
                  "height":69}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4b5fc82c2fa9402499aa7a2753e84dec",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":154,
                      "y":0},
                    "size":{
                      "width":81,
                      "height":69}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/里程统计/u5.png"}},
{
              "id":"f739db530e3e451abcca8881406581c2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":154,
                  "y":69},
                "size":{
                  "width":81,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"77f713ad43484ffab27e96919d730da0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":154,
                      "y":69},
                    "size":{
                      "width":81,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/里程统计/u27.png"}}]},
{
          "id":"4497303d9da44c2daa2762ec8dc9d2b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":35,
              "y":75},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2712df1809c4e9a87ac0a178713ab1f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":35,
                  "y":75},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"985c6fd93b6941fd95b52701ae4f0711",
          "label":"车牌颜色框",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":576,
              "y":75},
            "size":{
              "width":140,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"7225b46b005b4b0c88b771cf386826e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":511,
              "y":78},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3df98eda7334929a4ea508b6205731c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":511,
                  "y":78},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"55293a01df7940c4bf7cfeb584ae55d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":279,
              "y":75},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de735c461f5c4c1bbff05553f22b83cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":279,
                  "y":75},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"94e6658a02a94e129289435dadd777d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":35,
              "y":123},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e391c5a7aa147f884f1a82d5df46919",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":35,
                  "y":123},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"de49880e83ac44dd8be3fd37f63b3f71",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":304,
              "y":184},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"846fbf9768434deebed9c142d0083bb5",
          "label":"日期",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009DDA,
              "opacity":1},
            "location":{
              "x":101,
              "y":114},
            "size":{
              "width":140,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF009DDA},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b37c30613a714dc2a04b0df99baa3b36",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009DDA,
                  "opacity":1},
                "location":{
                  "x":101,
                  "y":114},
                "size":{
                  "width":140,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF009DDA},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设备回传/日期_u118.png"}},
{
          "id":"efa7fe644afa446eb9873d577f24203c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":226,
              "y":117},
            "size":{
              "width":15,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6705feee64f4469afedf17d58a9d4cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":226,
                  "y":117},
                "size":{
                  "width":15,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 变量 未指定 = &quot;[[Now.getFullYear()]]/[[Now...&quot;, 且<br> 变量 未指定 = &quot;[[rl_date.addDays(-1).getDa...&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":""},
{
                                "exprType":"stringLiteral",
                                "value":"[[Now.getFullYear()]]/[[Now.getMonth()]]/1",
                                "localVariables":{
},
                                "stos":[{
                                    "computedType":"int",
                                    "sto":"fCall",
                                    "thisSTO":{
                                      "desiredType":"date",
                                      "sto":"var",
                                      "name":"now"},
                                    "func":"getFullYear",
                                    "arguments":[]},
{
                                    "computedType":"int",
                                    "sto":"fCall",
                                    "thisSTO":{
                                      "desiredType":"date",
                                      "sto":"var",
                                      "name":"now"},
                                    "func":"getMonth",
                                    "arguments":[]}]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":""},
{
                                "exprType":"stringLiteral",
                                "value":"[[rl_date.addDays(-1).getDate()]]",
                                "localVariables":{
},
                                "stos":[{
                                    "computedType":"error",
                                    "sto":"error"}]}]}]}},
{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/设备回传/u120.png"}},
{
          "id":"56576f6710f34125b83d5badbc79e395",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":287,
              "y":123},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5b2fc9f031d4b92aac834138bd96b57",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":287,
                  "y":123},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aa70177c314a4f69a39a926868b3b601",
          "label":"日期",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009DDA,
              "opacity":1},
            "location":{
              "x":331,
              "y":114},
            "size":{
              "width":140,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF009DDA},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc3c14e8abff403987d560c81847a74d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009DDA,
                  "opacity":1},
                "location":{
                  "x":331,
                  "y":114},
                "size":{
                  "width":140,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF009DDA},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设备回传/日期_u118.png"}},
{
          "id":"70bfc61f352a44959a394df56e1c30c1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":456,
              "y":117},
            "size":{
              "width":15,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d173daf647b4a0cab4bcb23f032a636",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":456,
                  "y":117},
                "size":{
                  "width":15,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 变量 未指定 = &quot;[[Now.getFullYear()]]/[[Now...&quot;, 且<br> 变量 未指定 = &quot;[[rl_date.addDays(-1).getDa...&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":""},
{
                                "exprType":"stringLiteral",
                                "value":"[[Now.getFullYear()]]/[[Now.getMonth()]]/1",
                                "localVariables":{
},
                                "stos":[{
                                    "computedType":"int",
                                    "sto":"fCall",
                                    "thisSTO":{
                                      "desiredType":"date",
                                      "sto":"var",
                                      "name":"now"},
                                    "func":"getFullYear",
                                    "arguments":[]},
{
                                    "computedType":"int",
                                    "sto":"fCall",
                                    "thisSTO":{
                                      "desiredType":"date",
                                      "sto":"var",
                                      "name":"now"},
                                    "func":"getMonth",
                                    "arguments":[]}]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":""},
{
                                "exprType":"stringLiteral",
                                "value":"[[rl_date.addDays(-1).getDate()]]",
                                "localVariables":{
},
                                "stos":[{
                                    "computedType":"error",
                                    "sto":"error"}]}]}]}},
{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/设备回传/u120.png"}},
{
          "id":"52c96f4663ca49a294fabb9bfea6b46d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":35,
              "y":185},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"dc5e203f26d14def94b640e82deb7255",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":171,
              "y":184},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f01a6a83edb14550af24653a3bbca15d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":35,
              "y":24},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a4d6189bec840879c2979aca5733c33",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":35,
                  "y":24},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c41bb2897ad544e593a53a80bd55f773",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":98,
              "y":24},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22271f0c09d7449280c30946030ed3eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":98,
                  "y":24},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"09827f05d63d4157a72681dfd0d841a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":140,
              "y":24},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25ee4ff198a34aed9cb21cb996d32e18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":140,
                  "y":24},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"01e4fbf1f98b4aaaa09089a0da780aee",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":214,
              "y":24},
            "size":{
              "width":5,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27ffc00238a54c198ac4bceba58a5626",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":214,
                  "y":24},
                "size":{
                  "width":5,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e3dc9c4294c04548bd55d8f58e805ae8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":240,
              "y":24},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0bc50fc169648208979d8c6d1f48707",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":240,
                  "y":24},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0580c2b008c645b695a3a29111bd4666",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":304,
              "y":24},
            "size":{
              "width":5,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6183425a1bf24d16b1ba093b540509be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":304,
                  "y":24},
                "size":{
                  "width":5,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d3b6d3fdba584d33a6c22836bb64a57b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":24},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49bb4c92a6a54a758ab140cc2e06a7e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":340,
                  "y":24},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1b9bbe6d64db457483c822a17d668db9",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":98,
              "y":69},
            "size":{
              "width":143,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"1208142d86114ba08fa66894ba896d16",
          "label":"车牌号框",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":399,
              "y":69},
            "size":{
              "width":70,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"b9981b7ed39c48da975bb0951178d83b",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":329,
              "y":69},
            "size":{
              "width":35,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"83ed3500636e432781e88d3153f02b47",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":365,
              "y":69},
            "size":{
              "width":35,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"50b31f2ace9b4df5b5543916edf6ac8b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":498,
              "y":123},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9fb626e6aa714ff58df5f2349c3287bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":498,
                  "y":123},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d3814f8d92f5414d8ddbb1f250679422",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":576,
              "y":117},
            "size":{
              "width":140,
              "height":22}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "615133ba42ec48e79be3f1a5d3cf6cf6":{
      "scriptId":"u0"},
    "afef215c11e340dd8512d60c03c8060e":{
      "scriptId":"u1"},
    "abc80042ec2d4daa9cea912a59ad2415":{
      "scriptId":"u2"},
    "d96c7a4b7b8d4b3885af574fa73ea209":{
      "scriptId":"u3"},
    "abdce76e38704cda8fd4d62a67a017b3":{
      "scriptId":"u4"},
    "b38ad9d76e2242a0824d134e5991a960":{
      "scriptId":"u5"},
    "4b5fc82c2fa9402499aa7a2753e84dec":{
      "scriptId":"u6"},
    "4ad179b29cde4daf8ae874c59dbef92b":{
      "scriptId":"u7"},
    "bb7b48d5637b47398421b68c2d2ebb1e":{
      "scriptId":"u8"},
    "9707829120334059af175636f9edbd38":{
      "scriptId":"u9"},
    "d7a5e45fa22a42a2aa51fd76ca33f272":{
      "scriptId":"u10"},
    "abe6859476964c7aa882acb359cc8ab8":{
      "scriptId":"u11"},
    "53ee57e103f44e1bb43eaf83378ce05f":{
      "scriptId":"u12"},
    "a41f18598f634a67803d38d4eb34860d":{
      "scriptId":"u13"},
    "10ea1b45ed0143c79e33c694be8c668a":{
      "scriptId":"u14"},
    "e30f113728e446a69f36f66a122c0d38":{
      "scriptId":"u15"},
    "b9b188f35b4947bfa91497f73542078a":{
      "scriptId":"u16"},
    "eda66400877c47729310a12c83a10d8b":{
      "scriptId":"u17"},
    "86ccd8e388e84da394f625167c9eb6c6":{
      "scriptId":"u18"},
    "f03fe3746cff4ba2a56802a676947e9b":{
      "scriptId":"u19"},
    "ef89ccf3be27403cb76379c97b4a5b05":{
      "scriptId":"u20"},
    "0dd3915836db4b2a92f89230657d37f0":{
      "scriptId":"u21"},
    "fe7b9b8a439644be9756a3dd8f295589":{
      "scriptId":"u22"},
    "1e0f6d9cab8447ab966b646989db364e":{
      "scriptId":"u23"},
    "c3c3795689ad438baaa1675966182f91":{
      "scriptId":"u24"},
    "fd8c1891cc194bbab7b01605c8be7e1b":{
      "scriptId":"u25"},
    "279df38cd02c4959a210e91e7602154c":{
      "scriptId":"u26"},
    "f739db530e3e451abcca8881406581c2":{
      "scriptId":"u27"},
    "77f713ad43484ffab27e96919d730da0":{
      "scriptId":"u28"},
    "c987e8e2c7d740afab3286da684388d5":{
      "scriptId":"u29"},
    "4f7641bcd83145a49586f43073791a4c":{
      "scriptId":"u30"},
    "b862b4f17a57437281b6cad5853f97ef":{
      "scriptId":"u31"},
    "3319d049f7c84cd2b890f369bcdd2f9d":{
      "scriptId":"u32"},
    "ed7aae2c15be4d42b48a587eac0ed2f4":{
      "scriptId":"u33"},
    "36e38ae7b4354b8394c519cc846a7230":{
      "scriptId":"u34"},
    "2183356740ab44e9b18ca367489680d8":{
      "scriptId":"u35"},
    "c54a6bfef9cf4112943e5d63ab1ec12d":{
      "scriptId":"u36"},
    "2b107c60e65c4a1da4ea99ca42f4dc65":{
      "scriptId":"u37"},
    "bcabf9b90fb7421fb466698c35f4c6d1":{
      "scriptId":"u38"},
    "7cb3ad48cb9e41cd8382d8620176d868":{
      "scriptId":"u39"},
    "2f4f9b06b8ed4d7098bfa59e6a4960dc":{
      "scriptId":"u40"},
    "e7e1b5b028074f23b129ebb0a7ecb479":{
      "scriptId":"u41"},
    "9bc20103b70148eb9ac484a6c152890c":{
      "scriptId":"u42"},
    "e83c1781d81f444aa5a9c3747bc8a932":{
      "scriptId":"u43"},
    "70ba719634644f949a1df37594e7b0d2":{
      "scriptId":"u44"},
    "4497303d9da44c2daa2762ec8dc9d2b9":{
      "scriptId":"u45"},
    "a2712df1809c4e9a87ac0a178713ab1f":{
      "scriptId":"u46"},
    "985c6fd93b6941fd95b52701ae4f0711":{
      "scriptId":"u47"},
    "7225b46b005b4b0c88b771cf386826e5":{
      "scriptId":"u48"},
    "c3df98eda7334929a4ea508b6205731c":{
      "scriptId":"u49"},
    "55293a01df7940c4bf7cfeb584ae55d8":{
      "scriptId":"u50"},
    "de735c461f5c4c1bbff05553f22b83cf":{
      "scriptId":"u51"},
    "94e6658a02a94e129289435dadd777d8":{
      "scriptId":"u52"},
    "4e391c5a7aa147f884f1a82d5df46919":{
      "scriptId":"u53"},
    "de49880e83ac44dd8be3fd37f63b3f71":{
      "scriptId":"u54"},
    "846fbf9768434deebed9c142d0083bb5":{
      "scriptId":"u55"},
    "b37c30613a714dc2a04b0df99baa3b36":{
      "scriptId":"u56"},
    "efa7fe644afa446eb9873d577f24203c":{
      "scriptId":"u57"},
    "d6705feee64f4469afedf17d58a9d4cf":{
      "scriptId":"u58"},
    "56576f6710f34125b83d5badbc79e395":{
      "scriptId":"u59"},
    "d5b2fc9f031d4b92aac834138bd96b57":{
      "scriptId":"u60"},
    "aa70177c314a4f69a39a926868b3b601":{
      "scriptId":"u61"},
    "dc3c14e8abff403987d560c81847a74d":{
      "scriptId":"u62"},
    "70bfc61f352a44959a394df56e1c30c1":{
      "scriptId":"u63"},
    "5d173daf647b4a0cab4bcb23f032a636":{
      "scriptId":"u64"},
    "52c96f4663ca49a294fabb9bfea6b46d":{
      "scriptId":"u65"},
    "dc5e203f26d14def94b640e82deb7255":{
      "scriptId":"u66"},
    "f01a6a83edb14550af24653a3bbca15d":{
      "scriptId":"u67"},
    "7a4d6189bec840879c2979aca5733c33":{
      "scriptId":"u68"},
    "c41bb2897ad544e593a53a80bd55f773":{
      "scriptId":"u69"},
    "22271f0c09d7449280c30946030ed3eb":{
      "scriptId":"u70"},
    "09827f05d63d4157a72681dfd0d841a6":{
      "scriptId":"u71"},
    "25ee4ff198a34aed9cb21cb996d32e18":{
      "scriptId":"u72"},
    "01e4fbf1f98b4aaaa09089a0da780aee":{
      "scriptId":"u73"},
    "27ffc00238a54c198ac4bceba58a5626":{
      "scriptId":"u74"},
    "e3dc9c4294c04548bd55d8f58e805ae8":{
      "scriptId":"u75"},
    "f0bc50fc169648208979d8c6d1f48707":{
      "scriptId":"u76"},
    "0580c2b008c645b695a3a29111bd4666":{
      "scriptId":"u77"},
    "6183425a1bf24d16b1ba093b540509be":{
      "scriptId":"u78"},
    "d3b6d3fdba584d33a6c22836bb64a57b":{
      "scriptId":"u79"},
    "49bb4c92a6a54a758ab140cc2e06a7e0":{
      "scriptId":"u80"},
    "1b9bbe6d64db457483c822a17d668db9":{
      "scriptId":"u81"},
    "1208142d86114ba08fa66894ba896d16":{
      "scriptId":"u82"},
    "b9981b7ed39c48da975bb0951178d83b":{
      "scriptId":"u83"},
    "83ed3500636e432781e88d3153f02b47":{
      "scriptId":"u84"},
    "50b31f2ace9b4df5b5543916edf6ac8b":{
      "scriptId":"u85"},
    "9fb626e6aa714ff58df5f2349c3287bf":{
      "scriptId":"u86"},
    "d3814f8d92f5414d8ddbb1f250679422":{
      "scriptId":"u87"}}});