$axure.loadCurrentPage({
  "url":"修改页.html",
  "generationDate":new Date(1558324038684.48),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"yys_name",
"car_chePai_card",
"car_chePai_color",
"car_leixing",
"car_ICcard",
"yy_leixing",
"car_InterNet_leixing",
"car_jingYingLuXian",
"car_zhuangTai",
"quYu",
"phone",
"mail",
"name",
"NewVariable"],
  "page":{
    "packageId":"809ab3d603da403096484f8925a56227",
    "type":"Axure:Page",
    "name":"修改页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"61cd10cb40764184a8cc1793ed2baeff",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":30},
            "size":{
              "width":390,
              "height":350}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9623d68dd4884059b3faea64b68759cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":30},
                "size":{
                  "width":390,
                  "height":350}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增页/u0.png"}},
{
          "id":"60c29e56d54e4e4dbe97a7a008d858ed",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":152,
              "y":60},
            "size":{
              "width":304,
              "height":240}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7371a583b57470e9f7fc0d2fbcf0487",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":154,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e998d09ea4234e5293a14d4d903c6fe5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":154,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/司机基本信息新增页/u1.png"}},
{
              "id":"7d9e51d3e159409d9d85f2f4123ddb3f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":40},
                "size":{
                  "width":154,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3a9167c5f5a8435496b36cf7b918cfa6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":40},
                    "size":{
                      "width":154,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/司机基本信息新增页/u1.png"}},
{
              "id":"ab29ce5e46ac4436bb42ddf8885a650a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":80},
                "size":{
                  "width":154,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0e59439cb4ba40b89e9fcbadb6acf575",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":80},
                    "size":{
                      "width":154,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/司机基本信息新增页/u1.png"}},
{
              "id":"c64e8f52a7794e9b917c316326204542",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":120},
                "size":{
                  "width":154,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"77d5812a52804cb4be38c7ff76247cc9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":120},
                    "size":{
                      "width":154,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/司机基本信息新增页/u1.png"}},
{
              "id":"4361c17ab8df4a98a4ea65009d6d05c5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":160},
                "size":{
                  "width":154,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7ee28cffa34b47e88ee75e619ccafcdf",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":160},
                    "size":{
                      "width":154,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/司机基本信息新增页/u1.png"}},
{
              "id":"e0c4c3b449be4a1f8634f61e02f57997",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":200},
                "size":{
                  "width":154,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cb4b33995d494bdf839e891117992e00",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":200},
                    "size":{
                      "width":154,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/司机基本信息新增页/u65.png"}},
{
              "id":"4a4b6ee32cbf4759b9adda5769dda172",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":154,
                  "y":0},
                "size":{
                  "width":150,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9f66e8ac6352440d98403b0d6151c5c0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":154,
                      "y":0},
                    "size":{
                      "width":150,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/新增页/u5.png"}},
{
              "id":"b48bc51a3c4e4c79ba0d6c4ba2d831d6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":154,
                  "y":40},
                "size":{
                  "width":150,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d94ce31cc9414b4a86f023a7edbf24c8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":154,
                      "y":40},
                    "size":{
                      "width":150,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/新增页/u5.png"}},
{
              "id":"a9ccc4888fd34f9f8fc52011457e5df5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":154,
                  "y":80},
                "size":{
                  "width":150,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ca4c8f85f21244248b338cd3962955a6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":154,
                      "y":80},
                    "size":{
                      "width":150,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/新增页/u5.png"}},
{
              "id":"57d7bd874a074a848a4c13c30356684b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":154,
                  "y":120},
                "size":{
                  "width":150,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ffc5109c53cd4018b6707f2b3088d802",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":154,
                      "y":120},
                    "size":{
                      "width":150,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/新增页/u5.png"}},
{
              "id":"ccf8e7a366b94998ac451b47335f61a3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":154,
                  "y":160},
                "size":{
                  "width":150,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4509bb8bab9548f5bc4c1ad37648081c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":154,
                      "y":160},
                    "size":{
                      "width":150,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/新增页/u5.png"}},
{
              "id":"921f73e727e8448ab524b97261e0f127",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":154,
                  "y":200},
                "size":{
                  "width":150,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5de5578a675748ea86bd41eee99b847c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":154,
                      "y":200},
                    "size":{
                      "width":150,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/新增页/u25.png"}}]},
{
          "id":"9f5241db0fd443e0b96a0ba23147be20",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":179,
              "y":315},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"8d55453d70dd4f67819c948c3eafe552",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":329,
              "y":315},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"defca746e6d94f41b9d24bd6df22bbd3",
          "label":"必填",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":438,
              "y":69},
            "size":{
              "width":30,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4d9e7c47ad9412f881273028b0d52f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":438,
                  "y":69},
                "size":{
                  "width":30,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d823c53c3f384047955eb0796c06f11a",
          "label":"必填",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":438,
              "y":109},
            "size":{
              "width":30,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5e040d5e0bc44df8e12d0f67797efc2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":438,
                  "y":109},
                "size":{
                  "width":30,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5956f44aec9346d3a00a497ca6d64519",
          "label":"必填",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":438,
              "y":269},
            "size":{
              "width":30,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9de7b0afac04a15910ac9c9d16b2944",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":438,
                  "y":269},
                "size":{
                  "width":30,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9bc8fae6fec64d62afd9f216e78c4799",
          "label":"必填",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":438,
              "y":228},
            "size":{
              "width":30,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5348d008e5ea47ff9f612f4a5bdc4773",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":438,
                  "y":228},
                "size":{
                  "width":30,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9f1c5390e4f046f19b90bb7535ededac",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":324,
              "y":69},
            "size":{
              "width":105,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"4f17c5f3d7cc4bc1ab450490e18d9554",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":324,
              "y":109},
            "size":{
              "width":105,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"dd1d5d04107a47b9a1e7c3fd1b08118d",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":324,
              "y":148},
            "size":{
              "width":105,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"309d69a9f17e48d8a5291bdf3d6511a9",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":324,
              "y":186},
            "size":{
              "width":105,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"dc5a23e995ad47438fc2fc31bc8420bf",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":324,
              "y":226},
            "size":{
              "width":105,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"04ca39ac34484f7c8c1afdaa8d6059d8",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":324,
              "y":268},
            "size":{
              "width":105,
              "height":22}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "61cd10cb40764184a8cc1793ed2baeff":{
      "scriptId":"u0"},
    "9623d68dd4884059b3faea64b68759cc":{
      "scriptId":"u1"},
    "60c29e56d54e4e4dbe97a7a008d858ed":{
      "scriptId":"u2"},
    "b7371a583b57470e9f7fc0d2fbcf0487":{
      "scriptId":"u3"},
    "e998d09ea4234e5293a14d4d903c6fe5":{
      "scriptId":"u4"},
    "4a4b6ee32cbf4759b9adda5769dda172":{
      "scriptId":"u5"},
    "9f66e8ac6352440d98403b0d6151c5c0":{
      "scriptId":"u6"},
    "7d9e51d3e159409d9d85f2f4123ddb3f":{
      "scriptId":"u7"},
    "3a9167c5f5a8435496b36cf7b918cfa6":{
      "scriptId":"u8"},
    "b48bc51a3c4e4c79ba0d6c4ba2d831d6":{
      "scriptId":"u9"},
    "d94ce31cc9414b4a86f023a7edbf24c8":{
      "scriptId":"u10"},
    "ab29ce5e46ac4436bb42ddf8885a650a":{
      "scriptId":"u11"},
    "0e59439cb4ba40b89e9fcbadb6acf575":{
      "scriptId":"u12"},
    "a9ccc4888fd34f9f8fc52011457e5df5":{
      "scriptId":"u13"},
    "ca4c8f85f21244248b338cd3962955a6":{
      "scriptId":"u14"},
    "c64e8f52a7794e9b917c316326204542":{
      "scriptId":"u15"},
    "77d5812a52804cb4be38c7ff76247cc9":{
      "scriptId":"u16"},
    "57d7bd874a074a848a4c13c30356684b":{
      "scriptId":"u17"},
    "ffc5109c53cd4018b6707f2b3088d802":{
      "scriptId":"u18"},
    "4361c17ab8df4a98a4ea65009d6d05c5":{
      "scriptId":"u19"},
    "7ee28cffa34b47e88ee75e619ccafcdf":{
      "scriptId":"u20"},
    "ccf8e7a366b94998ac451b47335f61a3":{
      "scriptId":"u21"},
    "4509bb8bab9548f5bc4c1ad37648081c":{
      "scriptId":"u22"},
    "e0c4c3b449be4a1f8634f61e02f57997":{
      "scriptId":"u23"},
    "cb4b33995d494bdf839e891117992e00":{
      "scriptId":"u24"},
    "921f73e727e8448ab524b97261e0f127":{
      "scriptId":"u25"},
    "5de5578a675748ea86bd41eee99b847c":{
      "scriptId":"u26"},
    "9f5241db0fd443e0b96a0ba23147be20":{
      "scriptId":"u27"},
    "8d55453d70dd4f67819c948c3eafe552":{
      "scriptId":"u28"},
    "defca746e6d94f41b9d24bd6df22bbd3":{
      "scriptId":"u29"},
    "b4d9e7c47ad9412f881273028b0d52f8":{
      "scriptId":"u30"},
    "d823c53c3f384047955eb0796c06f11a":{
      "scriptId":"u31"},
    "b5e040d5e0bc44df8e12d0f67797efc2":{
      "scriptId":"u32"},
    "5956f44aec9346d3a00a497ca6d64519":{
      "scriptId":"u33"},
    "d9de7b0afac04a15910ac9c9d16b2944":{
      "scriptId":"u34"},
    "9bc8fae6fec64d62afd9f216e78c4799":{
      "scriptId":"u35"},
    "5348d008e5ea47ff9f612f4a5bdc4773":{
      "scriptId":"u36"},
    "9f1c5390e4f046f19b90bb7535ededac":{
      "scriptId":"u37"},
    "4f17c5f3d7cc4bc1ab450490e18d9554":{
      "scriptId":"u38"},
    "dd1d5d04107a47b9a1e7c3fd1b08118d":{
      "scriptId":"u39"},
    "309d69a9f17e48d8a5291bdf3d6511a9":{
      "scriptId":"u40"},
    "dc5a23e995ad47438fc2fc31bc8420bf":{
      "scriptId":"u41"},
    "04ca39ac34484f7c8c1afdaa8d6059d8":{
      "scriptId":"u42"}}});