$axure.loadCurrentPage({
  "url":"实时监控.html",
  "generationDate":new Date(1558324041329.48),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"yys_name",
"car_chePai_card",
"car_chePai_color",
"car_leixing",
"car_ICcard",
"yy_leixing",
"car_InterNet_leixing",
"car_jingYingLuXian",
"car_zhuangTai",
"quYu",
"phone",
"mail",
"name",
"NewVariable"],
  "page":{
    "packageId":"95e78486cdc44db7aa27e278a79c677f",
    "type":"Axure:Page",
    "name":"实时监控",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f46c0ccf733c420daa07664baf1ab9c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":-10,
              "y":180},
            "size":{
              "width":220,
              "height":550}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"706541a42efd426e954dbc4e26d5efe1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-10,
                  "y":180},
                "size":{
                  "width":220,
                  "height":550}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/实时监控/u0.png"}},
{
          "id":"abd277a9155941a2964e16334481f752",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":180},
            "size":{
              "width":1139,
              "height":371},
            "borderWidth":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba8591293d814fae89aebe8253df2b96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":180},
                "size":{
                  "width":1139,
                  "height":371},
                "borderWidth":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/实时监控/u2.png"}},
{
          "id":"a8f4df9e467a43f3ad6efffcb5079577",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":209,
              "y":614},
            "size":{
              "width":1140,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8decc9a8c19f4fff9e515178e8eb94dc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "size":{
                  "width":90,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"68fa69e0fea945f4aa4d4b564a0401b0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "size":{
                      "width":90,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/实时监控/u5.png"}},
{
              "id":"afc3ace6169a42b3bb26789522ab28e3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":90,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e1bea410ac0443829c63cc67cc57bcec",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":90,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/实时监控/u27.png"}},
{
              "id":"9f7d9f1e2961427c85b7c44fb7133365",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":90,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"92b8a0cc2e504494936594bba3a3b31d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":90,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/实时监控/u49.png"}},
{
              "id":"7b2fdc8ae1f14ed9bb14d6b4dc8d2802",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":90,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"678770b94c7d4e1c93ee111a40e2ad8a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":90,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/实时监控/u7.png"}},
{
              "id":"2d87ed526d9e4080ad6fd6607c94250a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":90,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4de955c16b1047ec8b401a1843a9f7d2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":90,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/实时监控/u29.png"}},
{
              "id":"67713c203741432bb0c0bef055a3394d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":90,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0232918f3ef54b8c869c1c184e10108b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":90,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/拆单页/u74.png"}},
{
              "id":"7ef72352e4fd46049a190668fbd4569e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":190,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4554ee05104244bc8492ec58f2e44e24",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":190,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/实时监控/u7.png"}},
{
              "id":"ccfe27ae4f5f4c53b5316e0629d336cc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":190,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ada003b9d3cf4aada493b22291e7c8f3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":190,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/实时监控/u29.png"}},
{
              "id":"d166763d0fcd48b29719e1326b031cd4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":190,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1a342e093d2e4e04b5efb9f534b59cc3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":190,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/拆单页/u74.png"}},
{
              "id":"145caa1890314f28aea551d37df6494a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":290,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fede846d6439481090fdfff1ba5cbd2a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":290,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/实时监控/u7.png"}},
{
              "id":"0596016d49ca4d0d8bf77dbc1fd9221e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":290,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c036cdd0ef3c417c879e259592b0e3e6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":290,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/实时监控/u29.png"}},
{
              "id":"5044299c2487412dbb7e17a319e97716",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":290,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8c254b5db11b4c99be7630d7070a5476",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":290,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/拆单页/u74.png"}},
{
              "id":"bab961ce382642cf9af063f5fe3cd1e8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":390,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5dd01c4ac27a4d5ebf4618c15da546ba",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":390,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/实时监控/u7.png"}},
{
              "id":"244735caddb548dbbfdd031cc58fa40c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":390,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3c3e489b42014591994a3e7c0c1a935e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":390,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/实时监控/u29.png"}},
{
              "id":"631d31aebf8645388d06e96b6fb2ec23",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":390,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e2c2813d629c4fe5af9558b8322a9291",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":390,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/拆单页/u74.png"}},
{
              "id":"62d4eaa9dbbf458e98cdaf926e366f4d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":490,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"edd05084894d4f8eb4ec126c54739afd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":490,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/实时监控/u7.png"}},
{
              "id":"0086934b2f1542fcb0f39bb612bdf88f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":490,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"970ece27177945be8153cda262470de9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":490,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/实时监控/u29.png"}},
{
              "id":"a897123910724601a409da214a68ce9d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":490,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a24642c3e5714361ada5ae6acf867636",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":490,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/拆单页/u74.png"}},
{
              "id":"293b0dba4c2e4c9395235df824319486",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":590,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b64dd98f738e49a28d52f4426df5108a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":590,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/实时监控/u7.png"}},
{
              "id":"20d5570e8dd54b0e8a2ee67582eb0d8d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":590,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2f5970db4f3d4fe5a4486f9b58287a9f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":590,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/实时监控/u29.png"}},
{
              "id":"e33b610d2f1d4b148624874119d9f19f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":590,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9dbce2608a2d43deb882c747f71adde0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":590,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/拆单页/u74.png"}},
{
              "id":"b9d6146931494fe68b1a100ac9362cbf",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":690,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"472137c3dea04ebc86bc1dbdd34efbdf",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":690,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/实时监控/u7.png"}},
{
              "id":"e28f2e22898b4fe8840ea8ef033381d6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":690,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e34e281f93ce45f7884b64dd6aaf5302",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":690,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/实时监控/u29.png"}},
{
              "id":"db4fdaaa77684430b4145d3801c2cf32",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":690,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9a1ec720db08475f962aedecd9fd6c15",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":690,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/拆单页/u74.png"}},
{
              "id":"9d357f430dda4115aeb94348447c073a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":790,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b8b3669b5c334bce8af0f6f80bff18e2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":790,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/实时监控/u7.png"}},
{
              "id":"7baba1d79c90443dbd111b01a8eab3dd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":790,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e7f763301a0f4c88b6cc6f8d626e353b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":790,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/实时监控/u29.png"}},
{
              "id":"46a11f42b5974e03b621fd00739d74d6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":790,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"184a3e99ec1b44a59ca86e58fe873459",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":790,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/拆单页/u74.png"}},
{
              "id":"04eb56f1e15b42e29670587001872691",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":890,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ff1c68d32c4247cdbc6f1754b1de75f6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":890,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/实时监控/u7.png"}},
{
              "id":"4118a547148d42f787d239c76821c84f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":890,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"63bb7b56222044baa151a7a2a5f5371d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":890,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/实时监控/u29.png"}},
{
              "id":"1f086322433549b590664383db458ac4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":890,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f98b870b75da436ca9271da716531aae",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":890,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/拆单页/u74.png"}},
{
              "id":"619a0d9b19c74bee89cdf59bcac790e2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":990,
                  "y":0},
                "size":{
                  "width":150,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b493007f7ce04595a73053ba7242a55b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":990,
                      "y":0},
                    "size":{
                      "width":150,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/实时监控/u25.png"}},
{
              "id":"c123daae533a40e592169d3a179bf554",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":990,
                  "y":30},
                "size":{
                  "width":150,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"80a5f247245d44ae87162ef99d14d693",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":990,
                      "y":30},
                    "size":{
                      "width":150,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/实时监控/u47.png"}},
{
              "id":"0d37c2c428f2439d8f9a0e8faa9effbf",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":990,
                  "y":60},
                "size":{
                  "width":150,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"eda6115f8090448bbc83dd73e8c142b9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":990,
                      "y":60},
                    "size":{
                      "width":150,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/实时监控/u69.png"}}]},
{
          "id":"17d80eaf0450442cafcbd08cd2b91155",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":850,
              "y":566},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f16d668af72e4c39bb727193ea358bc8",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":720,
              "y":566},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b08d4ad1d1cc4f8586494fce599450b6",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":590,
              "y":566},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"7721864c84894455a1db7c5080ab2fb6",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":12.5,
              "y":222},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6060a032c8fd446e86d6a02e72be171c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":12.5,
                  "y":222},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"2a1ac49d3829472193a20a0e1853a779",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":12,
              "y":248},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c65a392ad38141e799a7c296879ec916",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":12,
                  "y":248},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"0fb9101b2043460fa6395956c6b75002",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":92,
              "y":222},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be2fffd2974841aebd7b66692b784065",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":92,
                  "y":222},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"4e2bd33102e7419e9fdbd5da850ad319",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":569},
            "size":{
              "width":150,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"471f1cfc15534585a95625c3fa201606",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":566},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"0e2755435ef64533aa404941e574540c",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":190},
            "size":{
              "width":70,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"c4bc2ee7e4b4406fbd164f0911460263",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":190},
            "size":{
              "width":90,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"7b570d37bc0d445e8cbd3d56c6189028",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":188},
            "size":{
              "width":50,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"96ebb912e947447a95dab6a4edee1d12",
          "label":"",
          "type":"treeNodeObject",
          "styleType":"treeNodeObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":310},
            "size":{
              "width":87,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41aec25529bd4502b04e644edf751cb8",
              "label":"",
              "type":"treeNodeObject",
              "styleType":"treeNodeObject",
              "visible":true,
              "style":{
                "size":{
                  "width":67,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"686a1636a1ca460aa31090e438813d1f",
                  "label":"",
                  "isContained":true,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":67,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e463cae4c79b49d7b1568d9fe29e2649",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":67,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"6c576b2fcc23400f9e0ea0941e139829",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":20},
                    "size":{
                      "width":67,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"91306892d59d44e385677b8ed7416a8f",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":20},
                        "size":{
                          "width":67,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"b6b9f27a29624e93a90a1274e4c25c63",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":20,
                              "y":20},
                            "size":{
                              "width":67,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "buttonShapeId":"91306892d59d44e385677b8ed7416a8f"},
{
                  "id":"8fc4f8dfbb9f40d39bdd9cc9278d8960",
                  "label":"",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "stateStyles":{
                      "selected":{
}},
                    "location":{
                      "x":6,
                      "y":6},
                    "size":{
                      "width":9,
                      "height":9}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1f6a3daa612d43b1ba4d7b7198b6d268",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "selected":{
}},
                        "location":{
                          "x":6,
                          "y":6},
                        "size":{
                          "width":9,
                          "height":9}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/实时监控/u87.png",
                    "selected~":"images/实时监控/u87_selected.png"}},
{
                  "id":"004381c11c93428796cbde58a2b9b416",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":40},
                    "size":{
                      "width":67,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3988f1cdec8546b28f6a1fe7f4bc800d",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":40},
                        "size":{
                          "width":67,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"bb57181f34274a1885ea9063f5e8c155",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":20,
                              "y":40},
                            "size":{
                              "width":67,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "buttonShapeId":"3988f1cdec8546b28f6a1fe7f4bc800d"},
{
                  "id":"2545deafe8074d7b9ee8ac3930c2964e",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":60},
                    "size":{
                      "width":40,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"333121e0663d47c88c73eede391636cc",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":60},
                        "size":{
                          "width":40,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"b1220877ca5749c4bdfba8b3b490618d",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":20,
                              "y":60},
                            "size":{
                              "width":40,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "buttonShapeId":"333121e0663d47c88c73eede391636cc"}],
              "buttonShapeId":"686a1636a1ca460aa31090e438813d1f"}]},
{
          "id":"775ce6e4a8aa4b17b2aa63993d27c49c",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":92,
              "y":248},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0ab574fcee54234b9f6205b1c8d234a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":92,
                  "y":248},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"b26ff0c60c9a492ebd5443e995d78222",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":671},
            "size":{
              "width":58,
              "height":59}},
          "adaptiveStyles":{
}},
{
          "id":"ddd5ccedcba448f9b166bdac3e90c0ff",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":77,
              "y":671},
            "size":{
              "width":58,
              "height":59}},
          "adaptiveStyles":{
}},
{
          "id":"a5f2a1ff50ad402e8eade799a9056ae2",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":152,
              "y":671},
            "size":{
              "width":58,
              "height":59}},
          "adaptiveStyles":{
}},
{
          "id":"7d6b687bd3014186b8822ffacf7d3c37",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1109,
              "y":714},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02a1c6ebf8e54f6dab42836da130fe86",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1109,
                  "y":714},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5bb17c5e3477456f8e347a458d0f87db",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":1159,
              "y":714},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
}},
{
          "id":"249c9f5af4b54889915445d9669426c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1209,
              "y":714},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce52b89264fd4ff78aab2d1ffe75591d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1209,
                  "y":714},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"35c5575ca1fe402ab69207ba99a391ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0066FF,
                  "opacity":1}}},
            "location":{
              "x":1047,
              "y":714},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef68b38e1371463da1870d7cdbbb6f39",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "underline":true,
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0066FF,
                      "opacity":1}}},
                "location":{
                  "x":1047,
                  "y":714},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"c6ca84b682ef47a8acf286f374ff0ff3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "stateStyles":{
              "mouseOver":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0066FF,
                  "opacity":1}}},
            "location":{
              "x":1244,
              "y":714},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a21e1e6e2f11445ebac65ea3195cc1f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "stateStyles":{
                  "mouseOver":{
                    "underline":true,
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0066FF,
                      "opacity":1}}},
                "location":{
                  "x":1244,
                  "y":714},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"aa11ba834c064e078cf8cd8957b5bcae",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":714},
            "size":{
              "width":282,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f2c107e125045e896b1de0f6b644b19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":714},
                "size":{
                  "width":282,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2bcd9a7bfc8a45fab90fff140e94e33f",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":714},
            "size":{
              "width":72,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"c000ae959dfe40b584868b131c0864e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":593,
              "y":718},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"627f8bf694404803bb37832e91e69309",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":593,
                  "y":718},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"55ab54d74b08424d9e5e47315025098b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1307,
              "y":714},
            "size":{
              "width":42,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2f61e1ecda34d5cb816c03cf369d1fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1307,
                  "y":714},
                "size":{
                  "width":42,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "f46c0ccf733c420daa07664baf1ab9c2":{
      "scriptId":"u0"},
    "706541a42efd426e954dbc4e26d5efe1":{
      "scriptId":"u1"},
    "abd277a9155941a2964e16334481f752":{
      "scriptId":"u2"},
    "ba8591293d814fae89aebe8253df2b96":{
      "scriptId":"u3"},
    "a8f4df9e467a43f3ad6efffcb5079577":{
      "scriptId":"u4"},
    "8decc9a8c19f4fff9e515178e8eb94dc":{
      "scriptId":"u5"},
    "68fa69e0fea945f4aa4d4b564a0401b0":{
      "scriptId":"u6"},
    "7b2fdc8ae1f14ed9bb14d6b4dc8d2802":{
      "scriptId":"u7"},
    "678770b94c7d4e1c93ee111a40e2ad8a":{
      "scriptId":"u8"},
    "7ef72352e4fd46049a190668fbd4569e":{
      "scriptId":"u9"},
    "4554ee05104244bc8492ec58f2e44e24":{
      "scriptId":"u10"},
    "145caa1890314f28aea551d37df6494a":{
      "scriptId":"u11"},
    "fede846d6439481090fdfff1ba5cbd2a":{
      "scriptId":"u12"},
    "bab961ce382642cf9af063f5fe3cd1e8":{
      "scriptId":"u13"},
    "5dd01c4ac27a4d5ebf4618c15da546ba":{
      "scriptId":"u14"},
    "62d4eaa9dbbf458e98cdaf926e366f4d":{
      "scriptId":"u15"},
    "edd05084894d4f8eb4ec126c54739afd":{
      "scriptId":"u16"},
    "293b0dba4c2e4c9395235df824319486":{
      "scriptId":"u17"},
    "b64dd98f738e49a28d52f4426df5108a":{
      "scriptId":"u18"},
    "b9d6146931494fe68b1a100ac9362cbf":{
      "scriptId":"u19"},
    "472137c3dea04ebc86bc1dbdd34efbdf":{
      "scriptId":"u20"},
    "9d357f430dda4115aeb94348447c073a":{
      "scriptId":"u21"},
    "b8b3669b5c334bce8af0f6f80bff18e2":{
      "scriptId":"u22"},
    "04eb56f1e15b42e29670587001872691":{
      "scriptId":"u23"},
    "ff1c68d32c4247cdbc6f1754b1de75f6":{
      "scriptId":"u24"},
    "619a0d9b19c74bee89cdf59bcac790e2":{
      "scriptId":"u25"},
    "b493007f7ce04595a73053ba7242a55b":{
      "scriptId":"u26"},
    "afc3ace6169a42b3bb26789522ab28e3":{
      "scriptId":"u27"},
    "e1bea410ac0443829c63cc67cc57bcec":{
      "scriptId":"u28"},
    "2d87ed526d9e4080ad6fd6607c94250a":{
      "scriptId":"u29"},
    "4de955c16b1047ec8b401a1843a9f7d2":{
      "scriptId":"u30"},
    "ccfe27ae4f5f4c53b5316e0629d336cc":{
      "scriptId":"u31"},
    "ada003b9d3cf4aada493b22291e7c8f3":{
      "scriptId":"u32"},
    "0596016d49ca4d0d8bf77dbc1fd9221e":{
      "scriptId":"u33"},
    "c036cdd0ef3c417c879e259592b0e3e6":{
      "scriptId":"u34"},
    "244735caddb548dbbfdd031cc58fa40c":{
      "scriptId":"u35"},
    "3c3e489b42014591994a3e7c0c1a935e":{
      "scriptId":"u36"},
    "0086934b2f1542fcb0f39bb612bdf88f":{
      "scriptId":"u37"},
    "970ece27177945be8153cda262470de9":{
      "scriptId":"u38"},
    "20d5570e8dd54b0e8a2ee67582eb0d8d":{
      "scriptId":"u39"},
    "2f5970db4f3d4fe5a4486f9b58287a9f":{
      "scriptId":"u40"},
    "e28f2e22898b4fe8840ea8ef033381d6":{
      "scriptId":"u41"},
    "e34e281f93ce45f7884b64dd6aaf5302":{
      "scriptId":"u42"},
    "7baba1d79c90443dbd111b01a8eab3dd":{
      "scriptId":"u43"},
    "e7f763301a0f4c88b6cc6f8d626e353b":{
      "scriptId":"u44"},
    "4118a547148d42f787d239c76821c84f":{
      "scriptId":"u45"},
    "63bb7b56222044baa151a7a2a5f5371d":{
      "scriptId":"u46"},
    "c123daae533a40e592169d3a179bf554":{
      "scriptId":"u47"},
    "80a5f247245d44ae87162ef99d14d693":{
      "scriptId":"u48"},
    "9f7d9f1e2961427c85b7c44fb7133365":{
      "scriptId":"u49"},
    "92b8a0cc2e504494936594bba3a3b31d":{
      "scriptId":"u50"},
    "67713c203741432bb0c0bef055a3394d":{
      "scriptId":"u51"},
    "0232918f3ef54b8c869c1c184e10108b":{
      "scriptId":"u52"},
    "d166763d0fcd48b29719e1326b031cd4":{
      "scriptId":"u53"},
    "1a342e093d2e4e04b5efb9f534b59cc3":{
      "scriptId":"u54"},
    "5044299c2487412dbb7e17a319e97716":{
      "scriptId":"u55"},
    "8c254b5db11b4c99be7630d7070a5476":{
      "scriptId":"u56"},
    "631d31aebf8645388d06e96b6fb2ec23":{
      "scriptId":"u57"},
    "e2c2813d629c4fe5af9558b8322a9291":{
      "scriptId":"u58"},
    "a897123910724601a409da214a68ce9d":{
      "scriptId":"u59"},
    "a24642c3e5714361ada5ae6acf867636":{
      "scriptId":"u60"},
    "e33b610d2f1d4b148624874119d9f19f":{
      "scriptId":"u61"},
    "9dbce2608a2d43deb882c747f71adde0":{
      "scriptId":"u62"},
    "db4fdaaa77684430b4145d3801c2cf32":{
      "scriptId":"u63"},
    "9a1ec720db08475f962aedecd9fd6c15":{
      "scriptId":"u64"},
    "46a11f42b5974e03b621fd00739d74d6":{
      "scriptId":"u65"},
    "184a3e99ec1b44a59ca86e58fe873459":{
      "scriptId":"u66"},
    "1f086322433549b590664383db458ac4":{
      "scriptId":"u67"},
    "f98b870b75da436ca9271da716531aae":{
      "scriptId":"u68"},
    "0d37c2c428f2439d8f9a0e8faa9effbf":{
      "scriptId":"u69"},
    "eda6115f8090448bbc83dd73e8c142b9":{
      "scriptId":"u70"},
    "17d80eaf0450442cafcbd08cd2b91155":{
      "scriptId":"u71"},
    "f16d668af72e4c39bb727193ea358bc8":{
      "scriptId":"u72"},
    "b08d4ad1d1cc4f8586494fce599450b6":{
      "scriptId":"u73"},
    "7721864c84894455a1db7c5080ab2fb6":{
      "scriptId":"u74"},
    "6060a032c8fd446e86d6a02e72be171c":{
      "scriptId":"u75"},
    "2a1ac49d3829472193a20a0e1853a779":{
      "scriptId":"u76"},
    "c65a392ad38141e799a7c296879ec916":{
      "scriptId":"u77"},
    "0fb9101b2043460fa6395956c6b75002":{
      "scriptId":"u78"},
    "be2fffd2974841aebd7b66692b784065":{
      "scriptId":"u79"},
    "4e2bd33102e7419e9fdbd5da850ad319":{
      "scriptId":"u80"},
    "471f1cfc15534585a95625c3fa201606":{
      "scriptId":"u81"},
    "0e2755435ef64533aa404941e574540c":{
      "scriptId":"u82"},
    "c4bc2ee7e4b4406fbd164f0911460263":{
      "scriptId":"u83"},
    "7b570d37bc0d445e8cbd3d56c6189028":{
      "scriptId":"u84"},
    "96ebb912e947447a95dab6a4edee1d12":{
      "scriptId":"u85"},
    "41aec25529bd4502b04e644edf751cb8":{
      "scriptId":"u86"},
    "8fc4f8dfbb9f40d39bdd9cc9278d8960":{
      "scriptId":"u87"},
    "1f6a3daa612d43b1ba4d7b7198b6d268":{
      "scriptId":"u88"},
    "686a1636a1ca460aa31090e438813d1f":{
      "scriptId":"u89"},
    "e463cae4c79b49d7b1568d9fe29e2649":{
      "scriptId":"u90"},
    "6c576b2fcc23400f9e0ea0941e139829":{
      "scriptId":"u91"},
    "91306892d59d44e385677b8ed7416a8f":{
      "scriptId":"u92"},
    "b6b9f27a29624e93a90a1274e4c25c63":{
      "scriptId":"u93"},
    "004381c11c93428796cbde58a2b9b416":{
      "scriptId":"u94"},
    "3988f1cdec8546b28f6a1fe7f4bc800d":{
      "scriptId":"u95"},
    "bb57181f34274a1885ea9063f5e8c155":{
      "scriptId":"u96"},
    "2545deafe8074d7b9ee8ac3930c2964e":{
      "scriptId":"u97"},
    "333121e0663d47c88c73eede391636cc":{
      "scriptId":"u98"},
    "b1220877ca5749c4bdfba8b3b490618d":{
      "scriptId":"u99"},
    "775ce6e4a8aa4b17b2aa63993d27c49c":{
      "scriptId":"u100"},
    "b0ab574fcee54234b9f6205b1c8d234a":{
      "scriptId":"u101"},
    "b26ff0c60c9a492ebd5443e995d78222":{
      "scriptId":"u102"},
    "ddd5ccedcba448f9b166bdac3e90c0ff":{
      "scriptId":"u103"},
    "a5f2a1ff50ad402e8eade799a9056ae2":{
      "scriptId":"u104"},
    "7d6b687bd3014186b8822ffacf7d3c37":{
      "scriptId":"u105"},
    "02a1c6ebf8e54f6dab42836da130fe86":{
      "scriptId":"u106"},
    "5bb17c5e3477456f8e347a458d0f87db":{
      "scriptId":"u107"},
    "249c9f5af4b54889915445d9669426c8":{
      "scriptId":"u108"},
    "ce52b89264fd4ff78aab2d1ffe75591d":{
      "scriptId":"u109"},
    "35c5575ca1fe402ab69207ba99a391ca":{
      "scriptId":"u110"},
    "ef68b38e1371463da1870d7cdbbb6f39":{
      "scriptId":"u111"},
    "c6ca84b682ef47a8acf286f374ff0ff3":{
      "scriptId":"u112"},
    "a21e1e6e2f11445ebac65ea3195cc1f4":{
      "scriptId":"u113"},
    "aa11ba834c064e078cf8cd8957b5bcae":{
      "scriptId":"u114"},
    "5f2c107e125045e896b1de0f6b644b19":{
      "scriptId":"u115"},
    "2bcd9a7bfc8a45fab90fff140e94e33f":{
      "scriptId":"u116"},
    "c000ae959dfe40b584868b131c0864e2":{
      "scriptId":"u117"},
    "627f8bf694404803bb37832e91e69309":{
      "scriptId":"u118"},
    "55ab54d74b08424d9e5e47315025098b":{
      "scriptId":"u119"},
    "d2f61e1ecda34d5cb816c03cf369d1fc":{
      "scriptId":"u120"}}});