$axure.loadCurrentPage({
  "url":"订单分配.html",
  "generationDate":new Date(1557742051108.49),
  "isCanvasEnabled":false,
  "variables":["yys_name",
"car_chePai_card",
"car_chePai_color",
"car_leixing",
"car_ICcard",
"yy_leixing",
"car_InterNet_leixing",
"car_jingYingLuXian",
"car_zhuangTai",
"quYu",
"phone",
"mail",
"name"],
  "page":{
    "packageId":"dcb86dc31e5849e7810295541d8f03a1",
    "type":"Axure:Page",
    "name":"订单分配",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"84af9443b094494d86b4190fb79a5c87",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":120},
            "size":{
              "width":1038,
              "height":211}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3492f65912f466a926a8649bc4714ee",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "size":{
                  "width":104,
                  "height":47}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8c152a0503174bfcac5306058dbe23af",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "size":{
                      "width":104,
                      "height":47}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆事故/u1.png"}},
{
              "id":"25bdd34c7eff446f81edd2de19480f0d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":47},
                "size":{
                  "width":104,
                  "height":43}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d0725247c8074978b9e0f78cf869b37e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":47},
                    "size":{
                      "width":104,
                      "height":43}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆事故/u21.png"}},
{
              "id":"f102d954648d4673b8b358f8fce38caa",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":90},
                "size":{
                  "width":104,
                  "height":39}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e7205a197f6347de8b0cef060a7eb91f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":90},
                    "size":{
                      "width":104,
                      "height":39}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆事故/u41.png"}},
{
              "id":"48e7b034cfda4aeb8a00836b59cee8ce",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":104,
                  "y":0},
                "size":{
                  "width":108,
                  "height":47}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c2e0ec55e92846c99ea1260511e65082",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":104,
                      "y":0},
                    "size":{
                      "width":108,
                      "height":47}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆事故/u3.png"}},
{
              "id":"1f75477e1b544996a702e0fe28d9ebd5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":104,
                  "y":47},
                "size":{
                  "width":108,
                  "height":43}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bc619dc87bf14d88bad00c64daf47429",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":104,
                      "y":47},
                    "size":{
                      "width":108,
                      "height":43}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆事故/u23.png"}},
{
              "id":"3a41054f126d418fb85db7a2717df328",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":104,
                  "y":90},
                "size":{
                  "width":108,
                  "height":39}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e2be07df47b14ed8a303401b97c20104",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":104,
                      "y":90},
                    "size":{
                      "width":108,
                      "height":39}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆事故/u43.png"}},
{
              "id":"c9acd8653c09492aa03c1f5e441c3a99",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":212,
                  "y":0},
                "size":{
                  "width":99,
                  "height":47}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"98dc89a8c755412a829d89df94a43549",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":212,
                      "y":0},
                    "size":{
                      "width":99,
                      "height":47}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆事故/u5.png"}},
{
              "id":"c27117eb0b3f4abeb970658974d27900",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":212,
                  "y":47},
                "size":{
                  "width":99,
                  "height":43}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"680ced8ab42845e09930e6877c2003fb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":212,
                      "y":47},
                    "size":{
                      "width":99,
                      "height":43}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆事故/test_u25.png"}},
{
              "id":"9e0c778c9ef54bc7bfd1c7cb2a254fe0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":212,
                  "y":90},
                "size":{
                  "width":99,
                  "height":39}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b1a6ae33c724428480d5e4e1076fb00f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":212,
                      "y":90},
                    "size":{
                      "width":99,
                      "height":39}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆事故/u45.png"}},
{
              "id":"4800e5122fd742cc9921c54d685228f4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":129},
                "size":{
                  "width":104,
                  "height":42}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"28969db353be4d1b862735bd70ece958",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":129},
                    "size":{
                      "width":104,
                      "height":42}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆事故/u61.png"}},
{
              "id":"a98b6a4fce684ff68f9f545da3a9d2b1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":104,
                  "y":129},
                "size":{
                  "width":108,
                  "height":42}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9941f40a66dd4beda416618f3612c9ce",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":104,
                      "y":129},
                    "size":{
                      "width":108,
                      "height":42}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆事故/u63.png"}},
{
              "id":"3a52baeab9464708a8acb58ec2dcb6b6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":212,
                  "y":129},
                "size":{
                  "width":99,
                  "height":42}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a902d2487ea04fc69fe386c56e377b36",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":212,
                      "y":129},
                    "size":{
                      "width":99,
                      "height":42}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆事故/u65.png"}},
{
              "id":"2f31d10f1f914ccb878e09bc22120189",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":925,
                  "y":0},
                "size":{
                  "width":113,
                  "height":47}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c2f49aa38f9641c3bab51ff289247cb5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":925,
                      "y":0},
                    "size":{
                      "width":113,
                      "height":47}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆事故/u19.png"}},
{
              "id":"fbe0861fed4040de9be7e402470ab5df",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":925,
                  "y":47},
                "size":{
                  "width":113,
                  "height":43}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"01cc35fb5bd24c32baab2256f9a5e232",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":925,
                      "y":47},
                    "size":{
                      "width":113,
                      "height":43}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆事故/u39.png"}},
{
              "id":"870376d5874843d3afa3591119f4088d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":925,
                  "y":90},
                "size":{
                  "width":113,
                  "height":39}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"33e9f851888047c985a3b36a7f815194",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":925,
                      "y":90},
                    "size":{
                      "width":113,
                      "height":39}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆事故/u59.png"}},
{
              "id":"39c1e5612dc64461bd60434b31d76cec",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":925,
                  "y":129},
                "size":{
                  "width":113,
                  "height":42}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"12a372c0187848eea3607b1090c461f6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":925,
                      "y":129},
                    "size":{
                      "width":113,
                      "height":42}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆事故/u79.png"}},
{
              "id":"4c75fe4f6f864c9b854ba44a1a1e5f0f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":171},
                "size":{
                  "width":104,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a5dcfb183e5741d58bcd9068681205a5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":171},
                    "size":{
                      "width":104,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆事故/u81.png"}},
{
              "id":"3eefb5a0482b473c96e0e548d61ad319",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":104,
                  "y":171},
                "size":{
                  "width":108,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"940441a8cf1848ff9ae2328a80044590",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":104,
                      "y":171},
                    "size":{
                      "width":108,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆事故/u83.png"}},
{
              "id":"87b6c67b0d3c4f0782352912358c9b05",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":212,
                  "y":171},
                "size":{
                  "width":99,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"de87469d68c24f1599aee203f538b427",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":212,
                      "y":171},
                    "size":{
                      "width":99,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆事故/u85.png"}},
{
              "id":"ccd4e4ef77ec4d24b9752dcea5047cff",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":925,
                  "y":171},
                "size":{
                  "width":113,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"43b20b40884547aab6487dd37bd6eb7e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":925,
                      "y":171},
                    "size":{
                      "width":113,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆事故/u99.png"}},
{
              "id":"b3710e6a7388444888d9a4b34ece5998",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":415,
                  "y":0},
                "size":{
                  "width":102,
                  "height":47}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c2d9eda613714434ae0448331222951d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":415,
                      "y":0},
                    "size":{
                      "width":102,
                      "height":47}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆事故/u7.png"}},
{
              "id":"858efc8bdc624c94b59193546099fef4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":415,
                  "y":47},
                "size":{
                  "width":102,
                  "height":43}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9f56a443659b4476b876ae1bc325dd4a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":415,
                      "y":47},
                    "size":{
                      "width":102,
                      "height":43}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆事故/u27.png"}},
{
              "id":"bc85dcea3101465894175dc8a77cfc2b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":415,
                  "y":90},
                "size":{
                  "width":102,
                  "height":39}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1d35548c66a540fe8dd13c81adecc25d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":415,
                      "y":90},
                    "size":{
                      "width":102,
                      "height":39}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆事故/u47.png"}},
{
              "id":"9931b8bf80904968be7a67e1d675d54b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":415,
                  "y":129},
                "size":{
                  "width":102,
                  "height":42}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"83746ab9bdb349f6a9a2b68b6742c50d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":415,
                      "y":129},
                    "size":{
                      "width":102,
                      "height":42}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆事故/u67.png"}},
{
              "id":"ce4001ef712c4429914a3fad050cba6a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":415,
                  "y":171},
                "size":{
                  "width":102,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"19435a14121643149015fc095a61a0cb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":415,
                      "y":171},
                    "size":{
                      "width":102,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆事故/u87.png"}},
{
              "id":"a382e701f75e4bad8be073f74c84b518",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":517,
                  "y":0},
                "size":{
                  "width":102,
                  "height":47}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8153f4e1ff244f21a8b7542fdeab479f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":517,
                      "y":0},
                    "size":{
                      "width":102,
                      "height":47}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆事故/u7.png"}},
{
              "id":"f885ae429196411ba16a9f9f5b19fee0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":517,
                  "y":47},
                "size":{
                  "width":102,
                  "height":43}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0a718d6a66bb4f91bfa9a85d188842ee",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":517,
                      "y":47},
                    "size":{
                      "width":102,
                      "height":43}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆事故/u27.png"}},
{
              "id":"85c9d0fdf954402bacfdaed61b039cd6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":517,
                  "y":90},
                "size":{
                  "width":102,
                  "height":39}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"29a4f10c7fdc424a9b23c5ce00b748c9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":517,
                      "y":90},
                    "size":{
                      "width":102,
                      "height":39}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆事故/u47.png"}},
{
              "id":"7f690988a3d34de298bde113d9801875",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":517,
                  "y":129},
                "size":{
                  "width":102,
                  "height":42}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bd612790574f4978b663c2674a482e45",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":517,
                      "y":129},
                    "size":{
                      "width":102,
                      "height":42}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆事故/u67.png"}},
{
              "id":"6bf7df936e4b4bbbb290796e0eb49006",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":517,
                  "y":171},
                "size":{
                  "width":102,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"75a332be71f04ca795616479df6862b4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":517,
                      "y":171},
                    "size":{
                      "width":102,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆事故/u87.png"}},
{
              "id":"d5b6d09619e94e6dba7729ccd095eca7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":619,
                  "y":0},
                "size":{
                  "width":102,
                  "height":47}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"384d80b15b6c4ac181fe8a1727572e25",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":619,
                      "y":0},
                    "size":{
                      "width":102,
                      "height":47}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆事故/u7.png"}},
{
              "id":"84061b7dc7db4466a7edaa88df098d8f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":619,
                  "y":47},
                "size":{
                  "width":102,
                  "height":43}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fcdda28aa49e48b79fcf8886d8169247",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":619,
                      "y":47},
                    "size":{
                      "width":102,
                      "height":43}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆事故/u27.png"}},
{
              "id":"9e321d4972a04d6292c5f992d1cbbc95",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":619,
                  "y":90},
                "size":{
                  "width":102,
                  "height":39}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6bf2646b5ea34150ba0015f471897c07",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":619,
                      "y":90},
                    "size":{
                      "width":102,
                      "height":39}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆事故/u47.png"}},
{
              "id":"7560c4c87665459ca929a3346a819ed7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":619,
                  "y":129},
                "size":{
                  "width":102,
                  "height":42}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e6ea58b0498b481491e848cf9f75db79",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":619,
                      "y":129},
                    "size":{
                      "width":102,
                      "height":42}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆事故/u67.png"}},
{
              "id":"cecfba63ee3c4ae9b31a914c9e5217b3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":619,
                  "y":171},
                "size":{
                  "width":102,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ee00b5691e2349f8a59e50c78531f6cf",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":619,
                      "y":171},
                    "size":{
                      "width":102,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆事故/u87.png"}},
{
              "id":"33413d8c1ee14b15ada1434b9a92d5bf",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":721,
                  "y":0},
                "size":{
                  "width":102,
                  "height":47}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4a8d167ec24449cd8be259f44504faf9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":721,
                      "y":0},
                    "size":{
                      "width":102,
                      "height":47}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆事故/u7.png"}},
{
              "id":"25ac68b559bb41edbdfbffa4eaff17b7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":721,
                  "y":47},
                "size":{
                  "width":102,
                  "height":43}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e83c37da5a32413daa29348aba25bcb7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":721,
                      "y":47},
                    "size":{
                      "width":102,
                      "height":43}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆事故/u27.png"}},
{
              "id":"7deff9898a044428bcc6e86f7d01a7ca",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":721,
                  "y":90},
                "size":{
                  "width":102,
                  "height":39}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a9552a344363478fa96b6614a9171b21",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":721,
                      "y":90},
                    "size":{
                      "width":102,
                      "height":39}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆事故/u47.png"}},
{
              "id":"09420aef0fae4f02a9ff3454f78957f4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":721,
                  "y":129},
                "size":{
                  "width":102,
                  "height":42}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"86c4cc557f6f44c0890f4b7b4fe43428",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":721,
                      "y":129},
                    "size":{
                      "width":102,
                      "height":42}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆事故/u67.png"}},
{
              "id":"66d490ef960e46ac8dc89bd0927d216f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":721,
                  "y":171},
                "size":{
                  "width":102,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f8d72123add24b428f8d3357d6de96a0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":721,
                      "y":171},
                    "size":{
                      "width":102,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆事故/u87.png"}},
{
              "id":"03e487abff374dc5862cd3d51abbafbd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":823,
                  "y":0},
                "size":{
                  "width":102,
                  "height":47}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"278917b8ebec489b8f32f1ce17f467a3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":823,
                      "y":0},
                    "size":{
                      "width":102,
                      "height":47}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆事故/u7.png"}},
{
              "id":"600a138ed2da4a0ba6c5d89073b559c4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":823,
                  "y":47},
                "size":{
                  "width":102,
                  "height":43}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fe343a415d294f68b74081d2a4997c6f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":823,
                      "y":47},
                    "size":{
                      "width":102,
                      "height":43}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆事故/u27.png"}},
{
              "id":"fa684295797f47e4ab757e6101bbb1da",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":823,
                  "y":90},
                "size":{
                  "width":102,
                  "height":39}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c0ac345e37c74f1d91280b6bc197c16d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":823,
                      "y":90},
                    "size":{
                      "width":102,
                      "height":39}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆事故/u47.png"}},
{
              "id":"6a948a8e2c4547b499f4277ae78868e5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":823,
                  "y":129},
                "size":{
                  "width":102,
                  "height":42}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d8513ecf35ea420f984217298589f698",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":823,
                      "y":129},
                    "size":{
                      "width":102,
                      "height":42}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆事故/u67.png"}},
{
              "id":"c870501c624643c7add565311ac26112",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":823,
                  "y":171},
                "size":{
                  "width":102,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0eff8fe0c8044e41bb4e7f55d2c9bde2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":823,
                      "y":171},
                    "size":{
                      "width":102,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆事故/u87.png"}},
{
              "id":"129d45b8d7514f9d9b9ca8f26a79b768",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":311,
                  "y":0},
                "size":{
                  "width":104,
                  "height":47}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"55bc4a3d4f1642fd8abb039167dd5e6e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":311,
                      "y":0},
                    "size":{
                      "width":104,
                      "height":47}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆事故/u1.png"}},
{
              "id":"6f9df6e671134c6dbbe4b6cb0c1e0b51",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":311,
                  "y":47},
                "size":{
                  "width":104,
                  "height":43}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e02e493c334849d2b3b8e319c933291e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":311,
                      "y":47},
                    "size":{
                      "width":104,
                      "height":43}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆事故/u21.png"}},
{
              "id":"4b8f626546bc4397a6c598fd53c10939",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":311,
                  "y":90},
                "size":{
                  "width":104,
                  "height":39}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e303cbd771e6474095f93bf21e1975e5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":311,
                      "y":90},
                    "size":{
                      "width":104,
                      "height":39}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆事故/u41.png"}},
{
              "id":"1ac27ff702f74862a2c98317056adafb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":311,
                  "y":129},
                "size":{
                  "width":104,
                  "height":42}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e1593ebcd80d4f4a8f771c750ae4ff06",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":311,
                      "y":129},
                    "size":{
                      "width":104,
                      "height":42}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆事故/u61.png"}},
{
              "id":"eb0203a76b1d4220a4b7b1b7cf7c2dd5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":311,
                  "y":171},
                "size":{
                  "width":104,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1723884a0ad64193b422506dc3f675f1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":311,
                      "y":171},
                    "size":{
                      "width":104,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/车辆事故/u81.png"}}]},
{
          "id":"553e9c95c2914b4091ab11597c3cf951",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":842,
              "y":351},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b0e44484f20451abe7f99702a47da55",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":842,
                  "y":351},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8606c37fcb344cc28d3885f32938197f",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":892,
              "y":351},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
}},
{
          "id":"09c0c579ba34422bafc9f1b5f7dbd072",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":942,
              "y":351},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb9fdb6770ad43b4948dd1b36a8c4dc9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":942,
                  "y":351},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"30deda2725c74719bf04b17c21760c26",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0066FF,
                  "opacity":1}}},
            "location":{
              "x":780,
              "y":351},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1476c48acec245dcbbde18129ebe143f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "underline":true,
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0066FF,
                      "opacity":1}}},
                "location":{
                  "x":780,
                  "y":351},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"3144622f8bab4ccfb27a02abe0eb0a75",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "stateStyles":{
              "mouseOver":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0066FF,
                  "opacity":1}}},
            "location":{
              "x":977,
              "y":351},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f95219f6c7e44fa8f786d404771a73d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "stateStyles":{
                  "mouseOver":{
                    "underline":true,
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0066FF,
                      "opacity":1}}},
                "location":{
                  "x":977,
                  "y":351},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"2bcdcbce035b4ef88f461767dcdb1f8f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1040,
              "y":351},
            "size":{
              "width":42,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa64c2ced6a44a668914e3c2793a7ecb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1040,
                  "y":351},
                "size":{
                  "width":42,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b3d123a568a14ea7b36ba6cdbed6df61",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":348},
            "size":{
              "width":282,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45bea3cbd788491d802d2da89408cfc9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":348},
                "size":{
                  "width":282,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c521cb03be724b32ba06b1993a64fb6e",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":348},
            "size":{
              "width":72,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"d79d1044b22645cfb1ab4a3e1bec9b2a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":455,
              "y":348},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02e6582f48c44d188382d5400b39aaa5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":455,
                  "y":348},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f493ed9f2a86454290267fdcc01f522f",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1009,
              "y":180},
            "size":{
              "width":82,
              "height":20}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "84af9443b094494d86b4190fb79a5c87":{
      "scriptId":"u0"},
    "d3492f65912f466a926a8649bc4714ee":{
      "scriptId":"u1"},
    "8c152a0503174bfcac5306058dbe23af":{
      "scriptId":"u2"},
    "48e7b034cfda4aeb8a00836b59cee8ce":{
      "scriptId":"u3"},
    "c2e0ec55e92846c99ea1260511e65082":{
      "scriptId":"u4"},
    "c9acd8653c09492aa03c1f5e441c3a99":{
      "scriptId":"u5"},
    "98dc89a8c755412a829d89df94a43549":{
      "scriptId":"u6"},
    "129d45b8d7514f9d9b9ca8f26a79b768":{
      "scriptId":"u7"},
    "55bc4a3d4f1642fd8abb039167dd5e6e":{
      "scriptId":"u8"},
    "b3710e6a7388444888d9a4b34ece5998":{
      "scriptId":"u9"},
    "c2d9eda613714434ae0448331222951d":{
      "scriptId":"u10"},
    "a382e701f75e4bad8be073f74c84b518":{
      "scriptId":"u11"},
    "8153f4e1ff244f21a8b7542fdeab479f":{
      "scriptId":"u12"},
    "d5b6d09619e94e6dba7729ccd095eca7":{
      "scriptId":"u13"},
    "384d80b15b6c4ac181fe8a1727572e25":{
      "scriptId":"u14"},
    "33413d8c1ee14b15ada1434b9a92d5bf":{
      "scriptId":"u15"},
    "4a8d167ec24449cd8be259f44504faf9":{
      "scriptId":"u16"},
    "03e487abff374dc5862cd3d51abbafbd":{
      "scriptId":"u17"},
    "278917b8ebec489b8f32f1ce17f467a3":{
      "scriptId":"u18"},
    "2f31d10f1f914ccb878e09bc22120189":{
      "scriptId":"u19"},
    "c2f49aa38f9641c3bab51ff289247cb5":{
      "scriptId":"u20"},
    "25bdd34c7eff446f81edd2de19480f0d":{
      "scriptId":"u21"},
    "d0725247c8074978b9e0f78cf869b37e":{
      "scriptId":"u22"},
    "1f75477e1b544996a702e0fe28d9ebd5":{
      "scriptId":"u23"},
    "bc619dc87bf14d88bad00c64daf47429":{
      "scriptId":"u24"},
    "c27117eb0b3f4abeb970658974d27900":{
      "scriptId":"u25"},
    "680ced8ab42845e09930e6877c2003fb":{
      "scriptId":"u26"},
    "6f9df6e671134c6dbbe4b6cb0c1e0b51":{
      "scriptId":"u27"},
    "e02e493c334849d2b3b8e319c933291e":{
      "scriptId":"u28"},
    "858efc8bdc624c94b59193546099fef4":{
      "scriptId":"u29"},
    "9f56a443659b4476b876ae1bc325dd4a":{
      "scriptId":"u30"},
    "f885ae429196411ba16a9f9f5b19fee0":{
      "scriptId":"u31"},
    "0a718d6a66bb4f91bfa9a85d188842ee":{
      "scriptId":"u32"},
    "84061b7dc7db4466a7edaa88df098d8f":{
      "scriptId":"u33"},
    "fcdda28aa49e48b79fcf8886d8169247":{
      "scriptId":"u34"},
    "25ac68b559bb41edbdfbffa4eaff17b7":{
      "scriptId":"u35"},
    "e83c37da5a32413daa29348aba25bcb7":{
      "scriptId":"u36"},
    "600a138ed2da4a0ba6c5d89073b559c4":{
      "scriptId":"u37"},
    "fe343a415d294f68b74081d2a4997c6f":{
      "scriptId":"u38"},
    "fbe0861fed4040de9be7e402470ab5df":{
      "scriptId":"u39"},
    "01cc35fb5bd24c32baab2256f9a5e232":{
      "scriptId":"u40"},
    "f102d954648d4673b8b358f8fce38caa":{
      "scriptId":"u41"},
    "e7205a197f6347de8b0cef060a7eb91f":{
      "scriptId":"u42"},
    "3a41054f126d418fb85db7a2717df328":{
      "scriptId":"u43"},
    "e2be07df47b14ed8a303401b97c20104":{
      "scriptId":"u44"},
    "9e0c778c9ef54bc7bfd1c7cb2a254fe0":{
      "scriptId":"u45"},
    "b1a6ae33c724428480d5e4e1076fb00f":{
      "scriptId":"u46"},
    "4b8f626546bc4397a6c598fd53c10939":{
      "scriptId":"u47"},
    "e303cbd771e6474095f93bf21e1975e5":{
      "scriptId":"u48"},
    "bc85dcea3101465894175dc8a77cfc2b":{
      "scriptId":"u49"},
    "1d35548c66a540fe8dd13c81adecc25d":{
      "scriptId":"u50"},
    "85c9d0fdf954402bacfdaed61b039cd6":{
      "scriptId":"u51"},
    "29a4f10c7fdc424a9b23c5ce00b748c9":{
      "scriptId":"u52"},
    "9e321d4972a04d6292c5f992d1cbbc95":{
      "scriptId":"u53"},
    "6bf2646b5ea34150ba0015f471897c07":{
      "scriptId":"u54"},
    "7deff9898a044428bcc6e86f7d01a7ca":{
      "scriptId":"u55"},
    "a9552a344363478fa96b6614a9171b21":{
      "scriptId":"u56"},
    "fa684295797f47e4ab757e6101bbb1da":{
      "scriptId":"u57"},
    "c0ac345e37c74f1d91280b6bc197c16d":{
      "scriptId":"u58"},
    "870376d5874843d3afa3591119f4088d":{
      "scriptId":"u59"},
    "33e9f851888047c985a3b36a7f815194":{
      "scriptId":"u60"},
    "4800e5122fd742cc9921c54d685228f4":{
      "scriptId":"u61"},
    "28969db353be4d1b862735bd70ece958":{
      "scriptId":"u62"},
    "a98b6a4fce684ff68f9f545da3a9d2b1":{
      "scriptId":"u63"},
    "9941f40a66dd4beda416618f3612c9ce":{
      "scriptId":"u64"},
    "3a52baeab9464708a8acb58ec2dcb6b6":{
      "scriptId":"u65"},
    "a902d2487ea04fc69fe386c56e377b36":{
      "scriptId":"u66"},
    "1ac27ff702f74862a2c98317056adafb":{
      "scriptId":"u67"},
    "e1593ebcd80d4f4a8f771c750ae4ff06":{
      "scriptId":"u68"},
    "9931b8bf80904968be7a67e1d675d54b":{
      "scriptId":"u69"},
    "83746ab9bdb349f6a9a2b68b6742c50d":{
      "scriptId":"u70"},
    "7f690988a3d34de298bde113d9801875":{
      "scriptId":"u71"},
    "bd612790574f4978b663c2674a482e45":{
      "scriptId":"u72"},
    "7560c4c87665459ca929a3346a819ed7":{
      "scriptId":"u73"},
    "e6ea58b0498b481491e848cf9f75db79":{
      "scriptId":"u74"},
    "09420aef0fae4f02a9ff3454f78957f4":{
      "scriptId":"u75"},
    "86c4cc557f6f44c0890f4b7b4fe43428":{
      "scriptId":"u76"},
    "6a948a8e2c4547b499f4277ae78868e5":{
      "scriptId":"u77"},
    "d8513ecf35ea420f984217298589f698":{
      "scriptId":"u78"},
    "39c1e5612dc64461bd60434b31d76cec":{
      "scriptId":"u79"},
    "12a372c0187848eea3607b1090c461f6":{
      "scriptId":"u80"},
    "4c75fe4f6f864c9b854ba44a1a1e5f0f":{
      "scriptId":"u81"},
    "a5dcfb183e5741d58bcd9068681205a5":{
      "scriptId":"u82"},
    "3eefb5a0482b473c96e0e548d61ad319":{
      "scriptId":"u83"},
    "940441a8cf1848ff9ae2328a80044590":{
      "scriptId":"u84"},
    "87b6c67b0d3c4f0782352912358c9b05":{
      "scriptId":"u85"},
    "de87469d68c24f1599aee203f538b427":{
      "scriptId":"u86"},
    "eb0203a76b1d4220a4b7b1b7cf7c2dd5":{
      "scriptId":"u87"},
    "1723884a0ad64193b422506dc3f675f1":{
      "scriptId":"u88"},
    "ce4001ef712c4429914a3fad050cba6a":{
      "scriptId":"u89"},
    "19435a14121643149015fc095a61a0cb":{
      "scriptId":"u90"},
    "6bf7df936e4b4bbbb290796e0eb49006":{
      "scriptId":"u91"},
    "75a332be71f04ca795616479df6862b4":{
      "scriptId":"u92"},
    "cecfba63ee3c4ae9b31a914c9e5217b3":{
      "scriptId":"u93"},
    "ee00b5691e2349f8a59e50c78531f6cf":{
      "scriptId":"u94"},
    "66d490ef960e46ac8dc89bd0927d216f":{
      "scriptId":"u95"},
    "f8d72123add24b428f8d3357d6de96a0":{
      "scriptId":"u96"},
    "c870501c624643c7add565311ac26112":{
      "scriptId":"u97"},
    "0eff8fe0c8044e41bb4e7f55d2c9bde2":{
      "scriptId":"u98"},
    "ccd4e4ef77ec4d24b9752dcea5047cff":{
      "scriptId":"u99"},
    "43b20b40884547aab6487dd37bd6eb7e":{
      "scriptId":"u100"},
    "553e9c95c2914b4091ab11597c3cf951":{
      "scriptId":"u101"},
    "7b0e44484f20451abe7f99702a47da55":{
      "scriptId":"u102"},
    "8606c37fcb344cc28d3885f32938197f":{
      "scriptId":"u103"},
    "09c0c579ba34422bafc9f1b5f7dbd072":{
      "scriptId":"u104"},
    "eb9fdb6770ad43b4948dd1b36a8c4dc9":{
      "scriptId":"u105"},
    "30deda2725c74719bf04b17c21760c26":{
      "scriptId":"u106"},
    "1476c48acec245dcbbde18129ebe143f":{
      "scriptId":"u107"},
    "3144622f8bab4ccfb27a02abe0eb0a75":{
      "scriptId":"u108"},
    "3f95219f6c7e44fa8f786d404771a73d":{
      "scriptId":"u109"},
    "2bcdcbce035b4ef88f461767dcdb1f8f":{
      "scriptId":"u110"},
    "fa64c2ced6a44a668914e3c2793a7ecb":{
      "scriptId":"u111"},
    "b3d123a568a14ea7b36ba6cdbed6df61":{
      "scriptId":"u112"},
    "45bea3cbd788491d802d2da89408cfc9":{
      "scriptId":"u113"},
    "c521cb03be724b32ba06b1993a64fb6e":{
      "scriptId":"u114"},
    "d79d1044b22645cfb1ab4a3e1bec9b2a":{
      "scriptId":"u115"},
    "02e6582f48c44d188382d5400b39aaa5":{
      "scriptId":"u116"},
    "f493ed9f2a86454290267fdcc01f522f":{
      "scriptId":"u117"}}});