$axure.loadCurrentPage({
  "url":"运单信息评价新增页面.html",
  "generationDate":new Date(1558324042304.48),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"yys_name",
"car_chePai_card",
"car_chePai_color",
"car_leixing",
"car_ICcard",
"yy_leixing",
"car_InterNet_leixing",
"car_jingYingLuXian",
"car_zhuangTai",
"quYu",
"phone",
"mail",
"name",
"NewVariable"],
  "page":{
    "packageId":"a2630e1cb8dc40c4a3bbb5746e5d3441",
    "type":"Axure:Page",
    "name":"运单信息评价新增页面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
      "onLoad":{
        "description":"OnLoad",
        "cases":[{
            "description":"用例 1",
            "isNewIfGroup":false,
            "actions":[{
                "action":"fadeWidget",
                "description":"隐藏 新增未填提示",
                "objectsToFades":[{
                    "objectPath":["cfc294824ce04241b1918c9c101e2afd"],
                    "fadeInfo":{
                      "fadeType":"hide",
                      "options":{
                        "showType":"none"}}}]}]}]}},
    "diagram":{
      "objects":[{
          "id":"2aafc8511ca248ccb07b640cdfb34137",
          "label":"新增_",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":45,
              "y":117},
            "size":{
              "width":117,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d6952d3a06d4cd4acba38176723b671",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":45,
                  "y":117},
                "size":{
                  "width":117,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"95fd5f0a89f046d3ab55e3a304058987",
          "label":"新增_",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":82},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65dffacd13ed40178291669b83656752",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":82},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4d8adff86be6469c88cd8fc2765ed4fb",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":1074,
              "y":177},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"center",
          "fixedMarginHorizontal":0,
          "fixedVertical":"middle",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"35eeae21b28448fd8ca6fac033b5e906",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"cfc294824ce04241b1918c9c101e2afd",
                  "label":"新增未填提示",
                  "parentDynamicPanel":"4d8adff86be6469c88cd8fc2765ed4fb",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":286,
                      "height":120}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5da83d3f86154f3eade7a4b23860301f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4d8adff86be6469c88cd8fc2765ed4fb",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":286,
                          "height":120}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onMouseOver":{
                      "description":"OnMouseOver",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"wait",
                              "description":"等待1000毫秒",
                              "waitTime":1000},
{
                              "action":"fadeWidget",
                              "description":"隐藏 新增未填提示",
                              "objectsToFades":[{
                                  "objectPath":["cfc294824ce04241b1918c9c101e2afd"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "images":{
                    "normal~":"images/车辆维护保养新增页面/新增未填提示_u1.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"35e0d049aa9e407eb0b1166d4fce1c22",
          "label":"新增_车牌号",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":156,
              "y":82},
            "size":{
              "width":174,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"fb46979f5ded41978368d56cc3b7e523",
          "label":"新增_",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":57,
              "y":424},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67c3e4a5ade54497ac1a2658da76277c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":57,
                  "y":424},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dcb7afa0fc5e41ed943fc935ab8f84fe",
          "label":"新增_",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":418},
            "size":{
              "width":14,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b90f6e9129848aabaffde4b8c552426",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":418},
                "size":{
                  "width":14,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ba4af9f9daea436bbc09e20e4b986c67",
          "label":"新增_保存",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":169,
              "y":306},
            "size":{
              "width":121,
              "height":34}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"若某项为空<br> (If 部件文字 不明 = &quot;&quot; 或 部件文字 不明 = &quot;&quot; 或 选中项值 不明 = &quot;请选择&quot; 或 选中项值 不明 = &quot;请选择&quot; 或 选中项值 不明 = &quot;请选择&quot; 或 选中项值 不明 = &quot;全部&quot; 或 选中项值 不明 = &quot;请选择&quot; 或 选中项值 不明 = &quot;请选择&quot; 或 选中项值 不明 = &quot;请选择&quot; 或 选中项值 不明 = &quot;请选择&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"||",
                    "leftExpr":{
                      "exprType":"binaryOp",
                      "op":"==",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetWidgetText",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["205aa56a70094d68871dfb53ae1b370d"]}]},
                      "rightExpr":{
                        "exprType":"stringLiteral",
                        "value":"",
                        "stos":[]}},
                    "rightExpr":{
                      "exprType":"binaryOp",
                      "op":"||",
                      "leftExpr":{
                        "exprType":"binaryOp",
                        "op":"==",
                        "leftExpr":{
                          "exprType":"fcall",
                          "functionName":"GetWidgetText",
                          "arguments":[{
                              "exprType":"pathLiteral",
                              "isThis":false,
                              "isFocused":false,
                              "isTarget":false,
                              "value":["53279d324a474fddabc5ab5d3fc1d846"]}]},
                        "rightExpr":{
                          "exprType":"stringLiteral",
                          "value":"",
                          "stos":[]}},
                      "rightExpr":{
                        "exprType":"binaryOp",
                        "op":"||",
                        "leftExpr":{
                          "exprType":"binaryOp",
                          "op":"==",
                          "leftExpr":{
                            "exprType":"fcall",
                            "functionName":"GetSelectedOption",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["ed2d05c358ad461aa42b24262ca78e5e"]}]},
                          "rightExpr":{
                            "exprType":"stringLiteral",
                            "value":"请选择",
                            "stos":[]}},
                        "rightExpr":{
                          "exprType":"binaryOp",
                          "op":"||",
                          "leftExpr":{
                            "exprType":"binaryOp",
                            "op":"==",
                            "leftExpr":{
                              "exprType":"fcall",
                              "functionName":"GetSelectedOption",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["2e5d09a1b7ec445ea188ab353d2ccf72"]}]},
                            "rightExpr":{
                              "exprType":"stringLiteral",
                              "value":"请选择",
                              "stos":[]}},
                          "rightExpr":{
                            "exprType":"binaryOp",
                            "op":"||",
                            "leftExpr":{
                              "exprType":"binaryOp",
                              "op":"==",
                              "leftExpr":{
                                "exprType":"fcall",
                                "functionName":"GetSelectedOption",
                                "arguments":[{
                                    "exprType":"pathLiteral",
                                    "isThis":false,
                                    "isFocused":false,
                                    "isTarget":false,
                                    "value":["bf2437c09dd740fda8c39a7aa70527eb"]}]},
                              "rightExpr":{
                                "exprType":"stringLiteral",
                                "value":"请选择",
                                "stos":[]}},
                            "rightExpr":{
                              "exprType":"binaryOp",
                              "op":"||",
                              "leftExpr":{
                                "exprType":"binaryOp",
                                "op":"==",
                                "leftExpr":{
                                  "exprType":"fcall",
                                  "functionName":"GetSelectedOption",
                                  "arguments":[{
                                      "exprType":"pathLiteral",
                                      "isThis":false,
                                      "isFocused":false,
                                      "isTarget":false,
                                      "value":["8f1393abf5934e77a03acc069dc04b49"]}]},
                                "rightExpr":{
                                  "exprType":"stringLiteral",
                                  "value":"全部",
                                  "stos":[]}},
                              "rightExpr":{
                                "exprType":"binaryOp",
                                "op":"||",
                                "leftExpr":{
                                  "exprType":"binaryOp",
                                  "op":"==",
                                  "leftExpr":{
                                    "exprType":"fcall",
                                    "functionName":"GetSelectedOption",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":false,
                                        "isFocused":false,
                                        "isTarget":false,
                                        "value":["db7aae2299414ac9af71ff1c2529fb6e"]}]},
                                  "rightExpr":{
                                    "exprType":"stringLiteral",
                                    "value":"请选择",
                                    "stos":[]}},
                                "rightExpr":{
                                  "exprType":"binaryOp",
                                  "op":"||",
                                  "leftExpr":{
                                    "exprType":"binaryOp",
                                    "op":"==",
                                    "leftExpr":{
                                      "exprType":"fcall",
                                      "functionName":"GetSelectedOption",
                                      "arguments":[{
                                          "exprType":"pathLiteral",
                                          "isThis":false,
                                          "isFocused":false,
                                          "isTarget":false,
                                          "value":["dbc5031492c243159f28ade0847ba565"]}]},
                                    "rightExpr":{
                                      "exprType":"stringLiteral",
                                      "value":"请选择",
                                      "stos":[]}},
                                  "rightExpr":{
                                    "exprType":"binaryOp",
                                    "op":"||",
                                    "leftExpr":{
                                      "exprType":"binaryOp",
                                      "op":"==",
                                      "leftExpr":{
                                        "exprType":"fcall",
                                        "functionName":"GetSelectedOption",
                                        "arguments":[{
                                            "exprType":"pathLiteral",
                                            "isThis":false,
                                            "isFocused":false,
                                            "isTarget":false,
                                            "value":["50cb0f8762ee4c7180bd74a21e5a5c21"]}]},
                                      "rightExpr":{
                                        "exprType":"stringLiteral",
                                        "value":"请选择",
                                        "stos":[]}},
                                    "rightExpr":{
                                      "exprType":"binaryOp",
                                      "op":"==",
                                      "leftExpr":{
                                        "exprType":"fcall",
                                        "functionName":"GetSelectedOption",
                                        "arguments":[{
                                            "exprType":"pathLiteral",
                                            "isThis":false,
                                            "isFocused":false,
                                            "isTarget":false,
                                            "value":["22beeb103c22409a92adfcbf4e9ba188"]}]},
                                      "rightExpr":{
                                        "exprType":"stringLiteral",
                                        "value":"请选择",
                                        "stos":[]}}}}}}}}}}},
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 新增未填提示",
                      "objectsToFades":[{
                          "objectPath":["cfc294824ce04241b1918c9c101e2afd"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]},
{
                  "description":"若全有<br> (Else If True)",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 变量 yys_name = 选中项值 不明, 且<br> 变量 car_chePai_card = 部件文字 不明, 且<br> 变量 car_chePai_color = 选中项值 不明, 且<br> 变量 car_leixing = 选中项值 不明, 且<br> 变量 car_ICcard = 部件文字 不明, 且<br> 变量 yy_leixing = 选中项值 不明, 且<br> 变量 car_InterNet_leixing = 选中项值 不明, 且<br> 变量 car_jingYingLuXian = 选中项值 不明, 且<br> 变量 car_zhuangTai = 选中项值 不明, 且<br> 变量 quYu = 选中项值 不明",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[]}},
{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 运单评价信息",
                      "target":{
                        "targetType":"page",
                        "url":"运单评价信息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"59aeb488835444a99b79df03838096b5",
          "label":"运单评价新增关闭",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":311.5,
              "y":306},
            "size":{
              "width":119,
              "height":34}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 确认,<br>取消,<br>确认要关闭么",
                      "objectsToFades":[{
                          "objectPath":["abc58b2dd2fe4101aa109ca0ea5fa21b"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["f20711a879bb4c93b0da044954afa118"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["72b962a8d3dc49b0ba808e9176dac214"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"3b92cf4cbd414369ad3aa2334a57697e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":150},
            "size":{
              "width":163,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"449b4ac7eedd49d3b35a6decbb66a17c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":150},
                "size":{
                  "width":163,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"05f91e7406494c259fb11d4bdbe9586b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":184},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73bdee04462749aeaf33b4a85c559e1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":184},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"98126367c6cb4a549252507eb4ee41d1",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":156,
              "y":146},
            "size":{
              "width":24,
              "height":23}},
          "adaptiveStyles":{
}},
{
          "id":"ed8470d80227490d8cc5815504693c89",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":146},
            "size":{
              "width":25,
              "height":23}},
          "adaptiveStyles":{
}},
{
          "id":"8d3b5710d2aa40489b451020b5b3b16c",
          "label":"新增_车牌号",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":156,
              "y":117},
            "size":{
              "width":174,
              "height":19}},
          "adaptiveStyles":{
}},
{
          "id":"4d6c6e2212624c7ba0a8793b2d25c08a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":59,
              "y":220},
            "size":{
              "width":134,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7081a6b0d7e64ef18bfafd716ba76c24",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":59,
                  "y":220},
                "size":{
                  "width":134,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"211be2ed750d4a34b5e2675657aa2cf0",
          "label":"新增_车牌号",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":154,
              "y":220},
            "size":{
              "width":174,
              "height":19}},
          "adaptiveStyles":{
}},
{
          "id":"81b3c36212df489985009b89170dfbb7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":53,
              "y":256},
            "size":{
              "width":91,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"004463bd9e26489abfc310e28b7b6de5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":53,
                  "y":256},
                "size":{
                  "width":91,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8d85223aec6242ccb5742080ef2ca7fa",
          "label":"新增_车牌号",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":154,
              "y":254},
            "size":{
              "width":174,
              "height":19}},
          "adaptiveStyles":{
}},
{
          "id":"e43685d4b07e424690b1066b2c5008ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":146},
            "size":{
              "width":30,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52f2b87144b341b4b51007a6e7fcf055",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":146},
                "size":{
                  "width":30,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/运单信息评价新增页面/u27.png"}},
{
          "id":"6a102b78940b4fbcb31b50db9224347b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":154,
              "y":254},
            "size":{
              "width":174,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21cb3e73746b4a1aac7937a20e0fab45",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":154,
                  "y":254},
                "size":{
                  "width":174,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"217026c501a74c55b82f0313842ae480",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":156,
              "y":187},
            "size":{
              "width":24,
              "height":23}},
          "adaptiveStyles":{
}},
{
          "id":"6b5c46af99864276a5ea571095a7074f",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":187},
            "size":{
              "width":25,
              "height":23}},
          "adaptiveStyles":{
}},
{
          "id":"f6c3415765a84fc1b92ac2cc0194b5b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":187},
            "size":{
              "width":30,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c77402e553c43fcb13c3643d84ee0ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":187},
                "size":{
                  "width":30,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/运单信息评价新增页面/u27.png"}},
{
          "id":"240cddffba364bed99fae5cb0507c69c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":340,
              "y":82},
            "size":{
              "width":62,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c954468ffa7848e7800c6b7d99578f63",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":340,
                  "y":82},
                "size":{
                  "width":62,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"765b1d555274466b9c642e9de47c60d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":340,
              "y":114},
            "size":{
              "width":62,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb7d6d5549a44ebf8f3b6b2a5327edac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":340,
                  "y":114},
                "size":{
                  "width":62,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a7b229f369af41d8ba5ed4a8f9a74d9d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":338,
              "y":220},
            "size":{
              "width":62,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2434bf9382a74e04a38f802dc0f136bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":338,
                  "y":220},
                "size":{
                  "width":62,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"abc58b2dd2fe4101aa109ca0ea5fa21b",
          "label":"确认",
          "type":"button",
          "styleType":"button",
          "visible":false,
          "style":{
            "location":{
              "x":364,
              "y":259.5},
            "size":{
              "width":100,
              "height":25},
            "visible":false},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"closeCurrent",
                      "description":"关闭当前窗口"}]}]}},
          "tabbable":true},
{
          "id":"f20711a879bb4c93b0da044954afa118",
          "label":"取消",
          "type":"button",
          "styleType":"button",
          "visible":false,
          "style":{
            "location":{
              "x":504,
              "y":259.5},
            "size":{
              "width":96,
              "height":25},
            "visible":false},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 确认要关闭么,<br>确认,<br>取消",
                      "objectsToFades":[{
                          "objectPath":["72b962a8d3dc49b0ba808e9176dac214"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["abc58b2dd2fe4101aa109ca0ea5fa21b"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["f20711a879bb4c93b0da044954afa118"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"72b962a8d3dc49b0ba808e9176dac214",
          "label":"确认要关闭么",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "horizontalAlignment":"center",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":364,
              "y":190},
            "size":{
              "width":236,
              "height":70},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c0c74f12a714eec9be48a2b9e95fbac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "horizontalAlignment":"center",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":364,
                  "y":190},
                "size":{
                  "width":236,
                  "height":70},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设备基本信息管理/确认要删除么_u76.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "2aafc8511ca248ccb07b640cdfb34137":{
      "scriptId":"u0"},
    "9d6952d3a06d4cd4acba38176723b671":{
      "scriptId":"u1"},
    "95fd5f0a89f046d3ab55e3a304058987":{
      "scriptId":"u2"},
    "65dffacd13ed40178291669b83656752":{
      "scriptId":"u3"},
    "4d8adff86be6469c88cd8fc2765ed4fb":{
      "scriptId":"u4"},
    "cfc294824ce04241b1918c9c101e2afd":{
      "scriptId":"u5"},
    "5da83d3f86154f3eade7a4b23860301f":{
      "scriptId":"u6"},
    "35e0d049aa9e407eb0b1166d4fce1c22":{
      "scriptId":"u7"},
    "fb46979f5ded41978368d56cc3b7e523":{
      "scriptId":"u8"},
    "67c3e4a5ade54497ac1a2658da76277c":{
      "scriptId":"u9"},
    "dcb7afa0fc5e41ed943fc935ab8f84fe":{
      "scriptId":"u10"},
    "0b90f6e9129848aabaffde4b8c552426":{
      "scriptId":"u11"},
    "ba4af9f9daea436bbc09e20e4b986c67":{
      "scriptId":"u12"},
    "59aeb488835444a99b79df03838096b5":{
      "scriptId":"u13"},
    "3b92cf4cbd414369ad3aa2334a57697e":{
      "scriptId":"u14"},
    "449b4ac7eedd49d3b35a6decbb66a17c":{
      "scriptId":"u15"},
    "05f91e7406494c259fb11d4bdbe9586b":{
      "scriptId":"u16"},
    "73bdee04462749aeaf33b4a85c559e1a":{
      "scriptId":"u17"},
    "98126367c6cb4a549252507eb4ee41d1":{
      "scriptId":"u18"},
    "ed8470d80227490d8cc5815504693c89":{
      "scriptId":"u19"},
    "8d3b5710d2aa40489b451020b5b3b16c":{
      "scriptId":"u20"},
    "4d6c6e2212624c7ba0a8793b2d25c08a":{
      "scriptId":"u21"},
    "7081a6b0d7e64ef18bfafd716ba76c24":{
      "scriptId":"u22"},
    "211be2ed750d4a34b5e2675657aa2cf0":{
      "scriptId":"u23"},
    "81b3c36212df489985009b89170dfbb7":{
      "scriptId":"u24"},
    "004463bd9e26489abfc310e28b7b6de5":{
      "scriptId":"u25"},
    "8d85223aec6242ccb5742080ef2ca7fa":{
      "scriptId":"u26"},
    "e43685d4b07e424690b1066b2c5008ee":{
      "scriptId":"u27"},
    "52f2b87144b341b4b51007a6e7fcf055":{
      "scriptId":"u28"},
    "6a102b78940b4fbcb31b50db9224347b":{
      "scriptId":"u29"},
    "21cb3e73746b4a1aac7937a20e0fab45":{
      "scriptId":"u30"},
    "217026c501a74c55b82f0313842ae480":{
      "scriptId":"u31"},
    "6b5c46af99864276a5ea571095a7074f":{
      "scriptId":"u32"},
    "f6c3415765a84fc1b92ac2cc0194b5b3":{
      "scriptId":"u33"},
    "8c77402e553c43fcb13c3643d84ee0ed":{
      "scriptId":"u34"},
    "240cddffba364bed99fae5cb0507c69c":{
      "scriptId":"u35"},
    "c954468ffa7848e7800c6b7d99578f63":{
      "scriptId":"u36"},
    "765b1d555274466b9c642e9de47c60d0":{
      "scriptId":"u37"},
    "cb7d6d5549a44ebf8f3b6b2a5327edac":{
      "scriptId":"u38"},
    "a7b229f369af41d8ba5ed4a8f9a74d9d":{
      "scriptId":"u39"},
    "2434bf9382a74e04a38f802dc0f136bd":{
      "scriptId":"u40"},
    "abc58b2dd2fe4101aa109ca0ea5fa21b":{
      "scriptId":"u41"},
    "f20711a879bb4c93b0da044954afa118":{
      "scriptId":"u42"},
    "72b962a8d3dc49b0ba808e9176dac214":{
      "scriptId":"u43"},
    "5c0c74f12a714eec9be48a2b9e95fbac":{
      "scriptId":"u44"}}});