$axure.loadCurrentPage({
  "url":"用户管理.html",
  "generationDate":new Date(1557742167339.36),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"NewVariable"],
  "page":{
    "packageId":"fcf133599fd44b89898020d5937cf3d0",
    "type":"Axure:Page",
    "name":"用户管理",
    "notes":{
      "默认":"<p><span>&nbsp;</span></p>"},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3550d9c32a1d499d81dffc3a296ae7d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":58},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86a3a131f1ad4320976665b6b3605458",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":48,
                  "y":58},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"305f3a9e0db4434995e7cc1505bbef3e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":741,
              "y":58},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd198299f0ea43aa819a5ee27e374e2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":741,
                  "y":58},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"be8f7fbd35ba49c89d4064b4f1e5fc2e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":91},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8fb179a3f5a04863a701dbcca190a31b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":48,
                  "y":91},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4520dd128e424a54b4db08597afac0f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":52,
              "y":123},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5839a1e859b6430a83c6bf2f4dc6270f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":52,
                  "y":123},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"149981cc51ee4c8a9934695b927574ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":515,
              "y":89},
            "size":{
              "width":35,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb0e8cb1f7ce47279f1b0f1a2074c0a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":515,
                  "y":89},
                "size":{
                  "width":35,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0d72f45d0b45474dac00cdbfb8005d23",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":506,
              "y":123},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ecfdddf2a6f14d46a4fa8fb1cc4a6e6d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":506,
                  "y":123},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8b1d3cf8918345d7be00aa9b0218da00",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":122},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a5ee23ec3994f0aa4ad2922949139e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":122},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4775653b47474ff4aab6f0f158efabe3",
          "label":"车牌号框",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":111,
              "y":56},
            "size":{
              "width":140,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"c276a2979a774b8f9f40476aa2ac0c97",
          "label":"司机姓名框",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":569,
              "y":84},
            "size":{
              "width":140,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"785d974e34ec43d3bdfd62e17fbf922a",
          "label":"IC卡号框",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":111,
              "y":120},
            "size":{
              "width":140,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"b65d7174820a4181aa4bf9ab1e9b91c5",
          "label":"司机姓名框",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":343,
              "y":119},
            "size":{
              "width":140,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"61dd0a3fbe074345975500e4c6fe897f",
          "label":"运营商框",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":111,
              "y":88},
            "size":{
              "width":140,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"9d6e488cdb5b4521a9ca7acaf7edf6c6",
          "label":"运营商框",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":569,
              "y":120},
            "size":{
              "width":140,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"49bda22499d14669aa2663777f2b8420",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":998,
              "y":357},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"381e6264b35d4c91b385884dad57a785",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":998,
                  "y":357},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e27d119775804c73aed8ee23abcbcedf",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":1054,
              "y":357},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
}},
{
          "id":"d1d0bce69a454f3caf68c1bdbc738f66",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1119,
              "y":357},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c97cda9c205f46529cd834f6287c211a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1119,
                  "y":357},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"49fec81f4c3f4e52becfa23e2d1aa24a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0066FF,
                  "opacity":1}}},
            "location":{
              "x":946,
              "y":358},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8826c0f495fc442ab6da1ce81538abff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "underline":true,
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0066FF,
                      "opacity":1}}},
                "location":{
                  "x":946,
                  "y":358},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"8e70b80f6ee54e14ac3d4b99e9fa2c47",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "stateStyles":{
              "mouseOver":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0066FF,
                  "opacity":1}}},
            "location":{
              "x":1146,
              "y":357},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee997b8434394d6188182070c67391f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "stateStyles":{
                  "mouseOver":{
                    "underline":true,
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0066FF,
                      "opacity":1}}},
                "location":{
                  "x":1146,
                  "y":357},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"bafacdc4b3e64011ab76e65594cf1080",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":226},
            "size":{
              "width":1196,
              "height":121}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2b255a9caf64fa29dfebe92adc00f73",
              "label":"11111111111111111",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":69},
                "size":{
                  "width":98,
                  "height":52}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"493c671bce3846ff9a30317c3a71fa6b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":69},
                    "size":{
                      "width":98,
                      "height":52}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/11111111111111111_u64.png"}},
{
              "id":"eef0c348ff8e4f99a8ff093a107a1bcb",
              "label":"运行商格1",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":819,
                  "y":69},
                "size":{
                  "width":82,
                  "height":52}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a19aaefaed8047fd82f9c063ac58100d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":819,
                      "y":69},
                    "size":{
                      "width":82,
                      "height":52}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/运行商格1_u88.png"}},
{
              "id":"17d9db4560c84034998b378770aaaa2b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":901,
                  "y":69},
                "size":{
                  "width":65,
                  "height":52}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"463b33ab03a840a48577c0dd00287520",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":901,
                      "y":69},
                    "size":{
                      "width":65,
                      "height":52}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u90.png"}},
{
              "id":"2f5d5ff882e84a10861946a04e34378d",
              "label":"IC卡号格1",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":966,
                  "y":69},
                "size":{
                  "width":64,
                  "height":52}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"38011aa6859b45879ad60cdf442d9ccd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":966,
                      "y":69},
                    "size":{
                      "width":64,
                      "height":52}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/ic卡号格1_u92.png"}},
{
              "id":"71cddc52d37944cdad571d91c071d4a0",
              "label":"运营类型格1",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":1030,
                  "y":69},
                "size":{
                  "width":66,
                  "height":52}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f849dc97910147de9b4676033873dba3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":1030,
                      "y":69},
                    "size":{
                      "width":66,
                      "height":52}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u68.png"}},
{
              "id":"ff89f16df25c4436afe93770e3373c8d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":1096,
                  "y":69},
                "size":{
                  "width":100,
                  "height":52}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0b690edabada42a7bf7bc1fa0cb746bc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":1096,
                      "y":69},
                    "size":{
                      "width":100,
                      "height":52}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u96.png"}},
{
              "id":"f0c8dde1279248748f63814adeece804",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "size":{
                  "width":98,
                  "height":69}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1649ec6eeae947028e0da03191342f48",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "size":{
                      "width":98,
                      "height":69}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u30.png"}},
{
              "id":"7da0a7ff7954433296c3c96708f7e5dd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":819,
                  "y":0},
                "size":{
                  "width":82,
                  "height":69}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5e9cc1ac990b446e9657da4dd64ed6cb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":819,
                      "y":0},
                    "size":{
                      "width":82,
                      "height":69}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u54.png"}},
{
              "id":"2604af739aec4b68b621fa21865d38df",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "stateStyles":{
                  "mouseOver":{
}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":901,
                  "y":0},
                "size":{
                  "width":65,
                  "height":69}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0c61e57f36514b438366629a39aef49a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseOver":{
}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":901,
                      "y":0},
                    "size":{
                      "width":65,
                      "height":69}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u56.png"}},
{
              "id":"2b97cc44110e43e4b6049ed12d68e4a8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":966,
                  "y":0},
                "size":{
                  "width":64,
                  "height":69}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3ce7f146b655476dbec8470bcef827d9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":966,
                      "y":0},
                    "size":{
                      "width":64,
                      "height":69}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u58.png"}},
{
              "id":"e40d12b72a134e1a9e2e76bc0584c050",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":1030,
                  "y":0},
                "size":{
                  "width":66,
                  "height":69}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ce59e1a8cdbc4de7ba3215dbe8fdafaa",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":1030,
                      "y":0},
                    "size":{
                      "width":66,
                      "height":69}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u34.png"}},
{
              "id":"daaa789a17f54529a67ebb0725b349db",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":1096,
                  "y":0},
                "size":{
                  "width":100,
                  "height":69}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b2134a79a4fa4a44b6954599df95857e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":1096,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":69}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u62.png"}},
{
              "id":"cc9b58a28244442287d0a97a3f8f3a32",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":98,
                  "y":0},
                "size":{
                  "width":90,
                  "height":69}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"361003fd2e3e431f8e03d44a48553110",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":98,
                      "y":0},
                    "size":{
                      "width":90,
                      "height":69}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u32.png"}},
{
              "id":"199946aeecb64f968fe6406c2ef31ade",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":98,
                  "y":69},
                "size":{
                  "width":90,
                  "height":52}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ef3df7eb89604ffdac184c0d7b6d5c9d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":98,
                      "y":69},
                    "size":{
                      "width":90,
                      "height":52}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u66.png"}},
{
              "id":"72eb8c68c1a34969919e4204f6905acf",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":188,
                  "y":0},
                "size":{
                  "width":66,
                  "height":69}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"36ada32fef9a41a1b84bfa56cf0682ed",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":188,
                      "y":0},
                    "size":{
                      "width":66,
                      "height":69}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u34.png"}},
{
              "id":"7f481399cf924c13b90c5aef7bb168d8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":188,
                  "y":69},
                "size":{
                  "width":66,
                  "height":52}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6dbaa93291024f479b5fbc8509374632",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":188,
                      "y":69},
                    "size":{
                      "width":66,
                      "height":52}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u68.png"}},
{
              "id":"3d1e5c3f9f8e4eb7b523a9515e3aa457",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":254,
                  "y":0},
                "size":{
                  "width":57,
                  "height":69}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6f2f8a83fec0483592417b8137ba64a5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":254,
                      "y":0},
                    "size":{
                      "width":57,
                      "height":69}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u36.png"}},
{
              "id":"413b87707542417788a2622179be6111",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":254,
                  "y":69},
                "size":{
                  "width":57,
                  "height":52}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9275f5b90dfc456197df3d7397a5e97d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":254,
                      "y":69},
                    "size":{
                      "width":57,
                      "height":52}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u70.png"}},
{
              "id":"a87be96a931e47d1b7c7cb47ec4268c4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":384,
                  "y":0},
                "size":{
                  "width":50,
                  "height":69}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"116b444b76714217bf6d0b17686d1bc8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":384,
                      "y":0},
                    "size":{
                      "width":50,
                      "height":69}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u40.png"}},
{
              "id":"f17f3d62d8ac406f906700d817c595ed",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":384,
                  "y":69},
                "size":{
                  "width":50,
                  "height":52}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3f7de4d1873643d9a6f22a12b0bc5a84",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":384,
                      "y":69},
                    "size":{
                      "width":50,
                      "height":52}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u74.png"}},
{
              "id":"4cb83ba395f642758065a4c3882e2ebd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":311,
                  "y":0},
                "size":{
                  "width":73,
                  "height":69}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d38dceb444e74571b537956850289e29",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":311,
                      "y":0},
                    "size":{
                      "width":73,
                      "height":69}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u38.png"}},
{
              "id":"7182922906244d1fb6ae24821d55ae95",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":311,
                  "y":69},
                "size":{
                  "width":73,
                  "height":52}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0bdfe448f4494d0796d9ccd6775e3f9e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":311,
                      "y":69},
                    "size":{
                      "width":73,
                      "height":52}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u72.png"}},
{
              "id":"0c221b6e50634bd2a12ae038157a1af8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":742,
                  "y":0},
                "size":{
                  "width":77,
                  "height":69}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dcccfe762d5a4de989a71c63f8ba7332",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":742,
                      "y":0},
                    "size":{
                      "width":77,
                      "height":69}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u52.png"}},
{
              "id":"c69a0c1393b84d3a9cff86436065290f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":742,
                  "y":69},
                "size":{
                  "width":77,
                  "height":52}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6a5ca0153481450395eff41ba24ea672",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":742,
                      "y":69},
                    "size":{
                      "width":77,
                      "height":52}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u86.png"}},
{
              "id":"5f8852de4d3e4d9da044b069178ce18e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":666,
                  "y":0},
                "size":{
                  "width":76,
                  "height":69}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9d1193d79ba54ba4bb32ce06d09573de",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":666,
                      "y":0},
                    "size":{
                      "width":76,
                      "height":69}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u50.png"}},
{
              "id":"fb2e955cb3794f9fbb39c9681d8226dc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":666,
                  "y":69},
                "size":{
                  "width":76,
                  "height":52}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"713748258c72405f80c9d2e320c8b79b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":666,
                      "y":69},
                    "size":{
                      "width":76,
                      "height":52}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u84.png"}},
{
              "id":"ce79e54e07114ef58f97d62bb9e52b9f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":592,
                  "y":0},
                "size":{
                  "width":74,
                  "height":69}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0b06dac1db7b4e10878bb8dfae1510ee",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":592,
                      "y":0},
                    "size":{
                      "width":74,
                      "height":69}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u48.png"}},
{
              "id":"60c1ee68ab024ab68604bedcab2d8071",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":592,
                  "y":69},
                "size":{
                  "width":74,
                  "height":52}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"67bff9d541e04c599795ac7f76caaf93",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":592,
                      "y":69},
                    "size":{
                      "width":74,
                      "height":52}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u82.png"}},
{
              "id":"0b8e4350807b4814ad51e055fc08b8a6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":540,
                  "y":0},
                "size":{
                  "width":52,
                  "height":69}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7e236bcde7d44180beb349ca1c7f882d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":540,
                      "y":0},
                    "size":{
                      "width":52,
                      "height":69}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u46.png"}},
{
              "id":"9965f7d317e0480baf2a9e66be64076c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":540,
                  "y":69},
                "size":{
                  "width":52,
                  "height":52}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4a8a0960f4634977bf61a3018df2e729",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":540,
                      "y":69},
                    "size":{
                      "width":52,
                      "height":52}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u80.png"}},
{
              "id":"b0a31b989e7d4884910b636a455c1024",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":495,
                  "y":0},
                "size":{
                  "width":45,
                  "height":69}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6636e72acc1c42be9892ae84d713cf2c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":495,
                      "y":0},
                    "size":{
                      "width":45,
                      "height":69}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u44.png"}},
{
              "id":"43135c19d5ed4d50ad676790a90f3ab5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":495,
                  "y":69},
                "size":{
                  "width":45,
                  "height":52}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"337c0290dda042a69d124c6259004992",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":495,
                      "y":69},
                    "size":{
                      "width":45,
                      "height":52}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u78.png"}},
{
              "id":"61997126510242d892f30f5a74687d58",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":434,
                  "y":0},
                "size":{
                  "width":61,
                  "height":69}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e835e2612001491d8e9a46a349fa3311",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":434,
                      "y":0},
                    "size":{
                      "width":61,
                      "height":69}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u42.png"}},
{
              "id":"dfa39fa6187b4d2eafd94a870cc43ae4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":434,
                  "y":69},
                "size":{
                  "width":61,
                  "height":52}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b7e64cccf02741bdb3d1ba85c22db70c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":434,
                      "y":69},
                    "size":{
                      "width":61,
                      "height":52}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理/u76.png"}}]},
{
          "id":"dbd5488262174fee850dbcf5bd319607",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":355},
            "size":{
              "width":282,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47ad8e2a6d6d4b75b241cf5887d37828",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":48,
                  "y":355},
                "size":{
                  "width":282,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7021da6f74c44db8bef3be7c9e8f12bf",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":354},
            "size":{
              "width":72,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"f6a558d0ebbd4bb5a4056476e1ee6047",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":357},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e28b6674bd5421db5f3f6dfb51b3dae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":357},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"99d461aa52664bcd894ccd3a2835fbe1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1202,
              "y":357},
            "size":{
              "width":42,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12c6d145a9dd48b49faf5ff945477860",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1202,
                  "y":357},
                "size":{
                  "width":42,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"78ae88ffe227404d95357a5384bb423a",
          "label":"运营商框",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":804,
              "y":55},
            "size":{
              "width":140,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"c407618acdac45a6be55413e75c540eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":57},
            "size":{
              "width":53,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec9bade3b3bb47d7b4c178df7dbd4028",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":57},
                "size":{
                  "width":53,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"29061f46741f4ab4b03d84499d3cba13",
          "label":"车牌号框",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":343,
              "y":55},
            "size":{
              "width":140,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"0d01dc89c5cf462780cca7c6cb0a76ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":506,
              "y":58},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0bdbce636a5470e9b06c331ae38fa67",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":506,
                  "y":58},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"727fa3a067474d7d9516559f20b4b3cc",
          "label":"车牌号框",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":569,
              "y":52},
            "size":{
              "width":140,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"ed230742f1f84304861fb2b713e45188",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":91},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27acd5490a3f416d91b7a4d67abde8b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":91},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ba911b579a1b45bcbd8f18e9c29155aa",
          "label":"运营商框",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":343,
              "y":87},
            "size":{
              "width":140,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"be9b877a6e4e4f998bbd9d011e994122",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":741,
              "y":89},
            "size":{
              "width":27,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ce8f8096b3345189216af2a36554103",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":741,
                  "y":89},
                "size":{
                  "width":27,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"99f55bace27c4def90a81ae9b18d76cf",
          "label":"运营商框",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":804,
              "y":89},
            "size":{
              "width":140,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"eec41447badc4a4dac34cfb813a91b54",
          "label":"编辑1",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1149,
              "y":306},
            "size":{
              "width":41,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 2",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 用户信息修改页面",
                      "target":{
                        "targetType":"page",
                        "url":"用户信息修改页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"352caf6c41ea41c4811117fe312d9616",
          "label":"删除1",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1203,
              "y":306},
            "size":{
              "width":41,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 确定要删除吗,<br>确定,<br>取消",
                      "objectsToFades":[{
                          "objectPath":["63dc97b751a742f28bb674a8278c8800"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["118f2e93ff0d44deaaaa0e9a9a1adbfa"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["ab80549c316b4234b29741ddc070a99d"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"914246e446df440b80f6f1abd5b778fb",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":506,
              "y":186.5},
            "size":{
              "width":200,
              "height":200}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"e4beb21d9b584bdab3bdba89c989914e",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"63dc97b751a742f28bb674a8278c8800",
          "label":"确定要删除吗",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":false,
          "style":{
            "location":{
              "x":609,
              "y":220},
            "size":{
              "width":221,
              "height":60},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"009e0992b55e4d92928c47de76bc2e86",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":609,
                  "y":220},
                "size":{
                  "width":221,
                  "height":60},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户管理/确定要删除吗_u121.png"}},
{
          "id":"118f2e93ff0d44deaaaa0e9a9a1adbfa",
          "label":"确定",
          "type":"button",
          "styleType":"button",
          "visible":false,
          "style":{
            "location":{
              "x":606,
              "y":280},
            "size":{
              "width":100,
              "height":25},
            "visible":false},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 确定要删除吗,<br>确定,<br>取消",
                      "objectsToFades":[{
                          "objectPath":["63dc97b751a742f28bb674a8278c8800"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["118f2e93ff0d44deaaaa0e9a9a1adbfa"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["ab80549c316b4234b29741ddc070a99d"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"setFunction",
                      "description":"设置 部件文字 11111111111111111 = &quot;&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["493c671bce3846ff9a30317c3a71fa6b"]},
{
                                "exprType":"stringLiteral",
                                "value":"",
                                "stos":[]},
{
                                "exprType":"booleanLiteral",
                                "value":true}]}]}}]}]}},
          "tabbable":true},
{
          "id":"ab80549c316b4234b29741ddc070a99d",
          "label":"取消",
          "type":"button",
          "styleType":"button",
          "visible":false,
          "style":{
            "location":{
              "x":730,
              "y":280},
            "size":{
              "width":100,
              "height":25},
            "visible":false},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 确定要删除吗,<br>确定,<br>取消",
                      "objectsToFades":[{
                          "objectPath":["63dc97b751a742f28bb674a8278c8800"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["118f2e93ff0d44deaaaa0e9a9a1adbfa"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["ab80549c316b4234b29741ddc070a99d"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"52393f308e8943df9070fee9e34d585c",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":524,
              "y":165},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"06f7ca99dff4423d8b8e8434669a840d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":640,
              "y":165},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"df4df082293842088bf91efb2c88cc8d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":404,
              "y":165},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"1d93409e9bde4161b2fddd4b6cde427d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":287,
              "y":165},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"722e6a3a8329493eaafd759c44ab27cd",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":172,
              "y":165},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 用户信息新增页面",
                      "target":{
                        "targetType":"page",
                        "url":"用户信息新增页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "3550d9c32a1d499d81dffc3a296ae7d0":{
      "scriptId":"u0"},
    "86a3a131f1ad4320976665b6b3605458":{
      "scriptId":"u1"},
    "305f3a9e0db4434995e7cc1505bbef3e":{
      "scriptId":"u2"},
    "dd198299f0ea43aa819a5ee27e374e2c":{
      "scriptId":"u3"},
    "be8f7fbd35ba49c89d4064b4f1e5fc2e":{
      "scriptId":"u4"},
    "8fb179a3f5a04863a701dbcca190a31b":{
      "scriptId":"u5"},
    "4520dd128e424a54b4db08597afac0f6":{
      "scriptId":"u6"},
    "5839a1e859b6430a83c6bf2f4dc6270f":{
      "scriptId":"u7"},
    "149981cc51ee4c8a9934695b927574ed":{
      "scriptId":"u8"},
    "cb0e8cb1f7ce47279f1b0f1a2074c0a1":{
      "scriptId":"u9"},
    "0d72f45d0b45474dac00cdbfb8005d23":{
      "scriptId":"u10"},
    "ecfdddf2a6f14d46a4fa8fb1cc4a6e6d":{
      "scriptId":"u11"},
    "8b1d3cf8918345d7be00aa9b0218da00":{
      "scriptId":"u12"},
    "2a5ee23ec3994f0aa4ad2922949139e5":{
      "scriptId":"u13"},
    "4775653b47474ff4aab6f0f158efabe3":{
      "scriptId":"u14"},
    "c276a2979a774b8f9f40476aa2ac0c97":{
      "scriptId":"u15"},
    "785d974e34ec43d3bdfd62e17fbf922a":{
      "scriptId":"u16"},
    "b65d7174820a4181aa4bf9ab1e9b91c5":{
      "scriptId":"u17"},
    "61dd0a3fbe074345975500e4c6fe897f":{
      "scriptId":"u18"},
    "9d6e488cdb5b4521a9ca7acaf7edf6c6":{
      "scriptId":"u19"},
    "49bda22499d14669aa2663777f2b8420":{
      "scriptId":"u20"},
    "381e6264b35d4c91b385884dad57a785":{
      "scriptId":"u21"},
    "e27d119775804c73aed8ee23abcbcedf":{
      "scriptId":"u22"},
    "d1d0bce69a454f3caf68c1bdbc738f66":{
      "scriptId":"u23"},
    "c97cda9c205f46529cd834f6287c211a":{
      "scriptId":"u24"},
    "49fec81f4c3f4e52becfa23e2d1aa24a":{
      "scriptId":"u25"},
    "8826c0f495fc442ab6da1ce81538abff":{
      "scriptId":"u26"},
    "8e70b80f6ee54e14ac3d4b99e9fa2c47":{
      "scriptId":"u27"},
    "ee997b8434394d6188182070c67391f6":{
      "scriptId":"u28"},
    "bafacdc4b3e64011ab76e65594cf1080":{
      "scriptId":"u29"},
    "f0c8dde1279248748f63814adeece804":{
      "scriptId":"u30"},
    "1649ec6eeae947028e0da03191342f48":{
      "scriptId":"u31"},
    "cc9b58a28244442287d0a97a3f8f3a32":{
      "scriptId":"u32"},
    "361003fd2e3e431f8e03d44a48553110":{
      "scriptId":"u33"},
    "72eb8c68c1a34969919e4204f6905acf":{
      "scriptId":"u34"},
    "36ada32fef9a41a1b84bfa56cf0682ed":{
      "scriptId":"u35"},
    "3d1e5c3f9f8e4eb7b523a9515e3aa457":{
      "scriptId":"u36"},
    "6f2f8a83fec0483592417b8137ba64a5":{
      "scriptId":"u37"},
    "4cb83ba395f642758065a4c3882e2ebd":{
      "scriptId":"u38"},
    "d38dceb444e74571b537956850289e29":{
      "scriptId":"u39"},
    "a87be96a931e47d1b7c7cb47ec4268c4":{
      "scriptId":"u40"},
    "116b444b76714217bf6d0b17686d1bc8":{
      "scriptId":"u41"},
    "61997126510242d892f30f5a74687d58":{
      "scriptId":"u42"},
    "e835e2612001491d8e9a46a349fa3311":{
      "scriptId":"u43"},
    "b0a31b989e7d4884910b636a455c1024":{
      "scriptId":"u44"},
    "6636e72acc1c42be9892ae84d713cf2c":{
      "scriptId":"u45"},
    "0b8e4350807b4814ad51e055fc08b8a6":{
      "scriptId":"u46"},
    "7e236bcde7d44180beb349ca1c7f882d":{
      "scriptId":"u47"},
    "ce79e54e07114ef58f97d62bb9e52b9f":{
      "scriptId":"u48"},
    "0b06dac1db7b4e10878bb8dfae1510ee":{
      "scriptId":"u49"},
    "5f8852de4d3e4d9da044b069178ce18e":{
      "scriptId":"u50"},
    "9d1193d79ba54ba4bb32ce06d09573de":{
      "scriptId":"u51"},
    "0c221b6e50634bd2a12ae038157a1af8":{
      "scriptId":"u52"},
    "dcccfe762d5a4de989a71c63f8ba7332":{
      "scriptId":"u53"},
    "7da0a7ff7954433296c3c96708f7e5dd":{
      "scriptId":"u54"},
    "5e9cc1ac990b446e9657da4dd64ed6cb":{
      "scriptId":"u55"},
    "2604af739aec4b68b621fa21865d38df":{
      "scriptId":"u56"},
    "0c61e57f36514b438366629a39aef49a":{
      "scriptId":"u57"},
    "2b97cc44110e43e4b6049ed12d68e4a8":{
      "scriptId":"u58"},
    "3ce7f146b655476dbec8470bcef827d9":{
      "scriptId":"u59"},
    "e40d12b72a134e1a9e2e76bc0584c050":{
      "scriptId":"u60"},
    "ce59e1a8cdbc4de7ba3215dbe8fdafaa":{
      "scriptId":"u61"},
    "daaa789a17f54529a67ebb0725b349db":{
      "scriptId":"u62"},
    "b2134a79a4fa4a44b6954599df95857e":{
      "scriptId":"u63"},
    "a2b255a9caf64fa29dfebe92adc00f73":{
      "scriptId":"u64"},
    "493c671bce3846ff9a30317c3a71fa6b":{
      "scriptId":"u65"},
    "199946aeecb64f968fe6406c2ef31ade":{
      "scriptId":"u66"},
    "ef3df7eb89604ffdac184c0d7b6d5c9d":{
      "scriptId":"u67"},
    "7f481399cf924c13b90c5aef7bb168d8":{
      "scriptId":"u68"},
    "6dbaa93291024f479b5fbc8509374632":{
      "scriptId":"u69"},
    "413b87707542417788a2622179be6111":{
      "scriptId":"u70"},
    "9275f5b90dfc456197df3d7397a5e97d":{
      "scriptId":"u71"},
    "7182922906244d1fb6ae24821d55ae95":{
      "scriptId":"u72"},
    "0bdfe448f4494d0796d9ccd6775e3f9e":{
      "scriptId":"u73"},
    "f17f3d62d8ac406f906700d817c595ed":{
      "scriptId":"u74"},
    "3f7de4d1873643d9a6f22a12b0bc5a84":{
      "scriptId":"u75"},
    "dfa39fa6187b4d2eafd94a870cc43ae4":{
      "scriptId":"u76"},
    "b7e64cccf02741bdb3d1ba85c22db70c":{
      "scriptId":"u77"},
    "43135c19d5ed4d50ad676790a90f3ab5":{
      "scriptId":"u78"},
    "337c0290dda042a69d124c6259004992":{
      "scriptId":"u79"},
    "9965f7d317e0480baf2a9e66be64076c":{
      "scriptId":"u80"},
    "4a8a0960f4634977bf61a3018df2e729":{
      "scriptId":"u81"},
    "60c1ee68ab024ab68604bedcab2d8071":{
      "scriptId":"u82"},
    "67bff9d541e04c599795ac7f76caaf93":{
      "scriptId":"u83"},
    "fb2e955cb3794f9fbb39c9681d8226dc":{
      "scriptId":"u84"},
    "713748258c72405f80c9d2e320c8b79b":{
      "scriptId":"u85"},
    "c69a0c1393b84d3a9cff86436065290f":{
      "scriptId":"u86"},
    "6a5ca0153481450395eff41ba24ea672":{
      "scriptId":"u87"},
    "eef0c348ff8e4f99a8ff093a107a1bcb":{
      "scriptId":"u88"},
    "a19aaefaed8047fd82f9c063ac58100d":{
      "scriptId":"u89"},
    "17d9db4560c84034998b378770aaaa2b":{
      "scriptId":"u90"},
    "463b33ab03a840a48577c0dd00287520":{
      "scriptId":"u91"},
    "2f5d5ff882e84a10861946a04e34378d":{
      "scriptId":"u92"},
    "38011aa6859b45879ad60cdf442d9ccd":{
      "scriptId":"u93"},
    "71cddc52d37944cdad571d91c071d4a0":{
      "scriptId":"u94"},
    "f849dc97910147de9b4676033873dba3":{
      "scriptId":"u95"},
    "ff89f16df25c4436afe93770e3373c8d":{
      "scriptId":"u96"},
    "0b690edabada42a7bf7bc1fa0cb746bc":{
      "scriptId":"u97"},
    "dbd5488262174fee850dbcf5bd319607":{
      "scriptId":"u98"},
    "47ad8e2a6d6d4b75b241cf5887d37828":{
      "scriptId":"u99"},
    "7021da6f74c44db8bef3be7c9e8f12bf":{
      "scriptId":"u100"},
    "f6a558d0ebbd4bb5a4056476e1ee6047":{
      "scriptId":"u101"},
    "6e28b6674bd5421db5f3f6dfb51b3dae":{
      "scriptId":"u102"},
    "99d461aa52664bcd894ccd3a2835fbe1":{
      "scriptId":"u103"},
    "12c6d145a9dd48b49faf5ff945477860":{
      "scriptId":"u104"},
    "78ae88ffe227404d95357a5384bb423a":{
      "scriptId":"u105"},
    "c407618acdac45a6be55413e75c540eb":{
      "scriptId":"u106"},
    "ec9bade3b3bb47d7b4c178df7dbd4028":{
      "scriptId":"u107"},
    "29061f46741f4ab4b03d84499d3cba13":{
      "scriptId":"u108"},
    "0d01dc89c5cf462780cca7c6cb0a76ea":{
      "scriptId":"u109"},
    "b0bdbce636a5470e9b06c331ae38fa67":{
      "scriptId":"u110"},
    "727fa3a067474d7d9516559f20b4b3cc":{
      "scriptId":"u111"},
    "ed230742f1f84304861fb2b713e45188":{
      "scriptId":"u112"},
    "27acd5490a3f416d91b7a4d67abde8b2":{
      "scriptId":"u113"},
    "ba911b579a1b45bcbd8f18e9c29155aa":{
      "scriptId":"u114"},
    "be9b877a6e4e4f998bbd9d011e994122":{
      "scriptId":"u115"},
    "4ce8f8096b3345189216af2a36554103":{
      "scriptId":"u116"},
    "99f55bace27c4def90a81ae9b18d76cf":{
      "scriptId":"u117"},
    "eec41447badc4a4dac34cfb813a91b54":{
      "scriptId":"u118"},
    "352caf6c41ea41c4811117fe312d9616":{
      "scriptId":"u119"},
    "914246e446df440b80f6f1abd5b778fb":{
      "scriptId":"u120"},
    "63dc97b751a742f28bb674a8278c8800":{
      "scriptId":"u121"},
    "009e0992b55e4d92928c47de76bc2e86":{
      "scriptId":"u122"},
    "118f2e93ff0d44deaaaa0e9a9a1adbfa":{
      "scriptId":"u123"},
    "ab80549c316b4234b29741ddc070a99d":{
      "scriptId":"u124"},
    "52393f308e8943df9070fee9e34d585c":{
      "scriptId":"u125"},
    "06f7ca99dff4423d8b8e8434669a840d":{
      "scriptId":"u126"},
    "df4df082293842088bf91efb2c88cc8d":{
      "scriptId":"u127"},
    "1d93409e9bde4161b2fddd4b6cde427d":{
      "scriptId":"u128"},
    "722e6a3a8329493eaafd759c44ab27cd":{
      "scriptId":"u129"}}});