$axure.loadCurrentPage({
  "url":"登录.html",
  "generationDate":new Date(1557736362948),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a3d25d0ee4fa46eab0abef4f0fc2d376",
    "type":"Axure:Page",
    "name":"登录",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"06d92927eaad410a88162878334736b5",
          "label":"标签_账号",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":49},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64801d605437499e8f0d4559f62325c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":49},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"68ac29b6e3ed4db09af5eb5bae2fab0b",
          "label":"标签_密码",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":109},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f63422c0e934d9981e4196d0b1c05c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":109},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"147d9fd4b8b7406b9c04ec6d83dfd76e",
          "label":"文本框_账号_输入",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":430,
              "y":45},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onFocus":{
              "description":"OnFocus",
              "cases":[{
                  "description":"账号输入框获得焦点时",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]},
            "onLostFocus":{
              "description":"OnLostFocus",
              "cases":[{
                  "description":"账号输入文本框失去焦点<br> (If 部件文字 当前部件 = &quot;&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetWidgetText",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"",
                      "stos":[]}},
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"切换 文本框_账号_输入,<br>文本框_账号_显示",
                      "objectsToFades":[{
                          "objectPath":["147d9fd4b8b7406b9c04ec6d83dfd76e"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["0a1175c06f0a4067bd35ea75c5aa6955"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"0a1175c06f0a4067bd35ea75c5aa6955",
          "label":"文本框_账号_显示",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":430,
              "y":45},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onFocus":{
              "description":"OnFocus",
              "cases":[{
                  "description":"点击后提示文本小时",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"切换 文本框_账号_输入,<br>文本框_账号_显示",
                      "objectsToFades":[{
                          "objectPath":["147d9fd4b8b7406b9c04ec6d83dfd76e"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["0a1175c06f0a4067bd35ea75c5aa6955"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"setFocusOnWidget",
                      "description":"设置焦点在 文本框_账号_输入 上",
                      "objectPaths":[["147d9fd4b8b7406b9c04ec6d83dfd76e"]]}]}]},
            "onLostFocus":{
              "description":"OnLostFocus",
              "cases":[{
                  "description":"用例 1<br> (If 部件文字 当前部件 = &quot;&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetWidgetText",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"",
                      "stos":[]}},
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 部件文字 当前部件 = &quot;请输入账号&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetFormText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"请输入账号",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true},
{
          "id":"fc297d26a14740aaa83a0041e5a2c71d",
          "label":"文本框_密码_输入",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":430,
              "y":105},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onFocus":{
              "description":"OnFocus",
              "cases":[{
                  "description":"密码输入框获得焦点时",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]},
            "onLostFocus":{
              "description":"OnLostFocus",
              "cases":[{
                  "description":"密码输入文本框失去焦点<br> (If 部件文字 当前部件 = &quot;&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetWidgetText",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"",
                      "stos":[]}},
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"切换 文本框_密码_显示,<br>文本框_密码_输入",
                      "objectsToFades":[{
                          "objectPath":["0e6e212db2ef42ec843224ce766b5998"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["fc297d26a14740aaa83a0041e5a2c71d"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"0e6e212db2ef42ec843224ce766b5998",
          "label":"文本框_密码_显示",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":430,
              "y":105},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onFocus":{
              "description":"OnFocus",
              "cases":[{
                  "description":"密码显示文本框获得焦点",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"切换 文本框_密码_显示,<br>文本框_密码_输入",
                      "objectsToFades":[{
                          "objectPath":["0e6e212db2ef42ec843224ce766b5998"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["fc297d26a14740aaa83a0041e5a2c71d"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"setFocusOnWidget",
                      "description":"设置焦点在 文本框_密码_输入 上",
                      "objectPaths":[["fc297d26a14740aaa83a0041e5a2c71d"]]}]}]}},
          "tabbable":true},
{
          "id":"97e631eba0bf46758aa1501b57f08a80",
          "label":"按钮_登录",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":195},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"93651e763ef841ca860802c6d0e2c42b",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":540,
              "y":195},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"e727e196d1df4249a0b2f3ab52d0ad94",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":430,
              "y":149},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46479d7672244109a9902842081c0999",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":430,
                  "y":149},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "06d92927eaad410a88162878334736b5":{
      "scriptId":"u0"},
    "64801d605437499e8f0d4559f62325c1":{
      "scriptId":"u1"},
    "68ac29b6e3ed4db09af5eb5bae2fab0b":{
      "scriptId":"u2"},
    "9f63422c0e934d9981e4196d0b1c05c8":{
      "scriptId":"u3"},
    "147d9fd4b8b7406b9c04ec6d83dfd76e":{
      "scriptId":"u4"},
    "0a1175c06f0a4067bd35ea75c5aa6955":{
      "scriptId":"u5"},
    "fc297d26a14740aaa83a0041e5a2c71d":{
      "scriptId":"u6"},
    "0e6e212db2ef42ec843224ce766b5998":{
      "scriptId":"u7"},
    "97e631eba0bf46758aa1501b57f08a80":{
      "scriptId":"u8"},
    "93651e763ef841ca860802c6d0e2c42b":{
      "scriptId":"u9"},
    "e727e196d1df4249a0b2f3ab52d0ad94":{
      "scriptId":"u10"},
    "46479d7672244109a9902842081c0999":{
      "scriptId":"u11"}}});