$axure.loadCurrentPage({
  "url":"查看运单列表信息（签收）.html",
  "generationDate":new Date(1557736121008.25),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n",
"rl_date",
"rl_day"],
  "page":{
    "packageId":"8a890fa4820c4274a20fcf76f2d06dc6",
    "type":"Axure:Page",
    "name":"查看运单列表信息（签收）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"226701fac7b246f9a2fc34da910b3790",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":640,
              "y":172},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b01c9fa5bcf4978905d8717fb937bcd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":640,
                  "y":172},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"581bbe1f1ec74130be11680c3a639323",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
            "fontSize":"36px",
            "fontWeight":"500",
            "location":{
              "x":450,
              "y":176},
            "size":{
              "width":20,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc665838212c41599076c75edb86daa9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
                "fontSize":"36px",
                "fontWeight":"500",
                "location":{
                  "x":450,
                  "y":176},
                "size":{
                  "width":20,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/填写单据信息/u76.png"}},
{
          "id":"6ead10695b4d459a9246000fcb534818",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":748,
              "y":174},
            "size":{
              "width":32,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b37437aba7bd4d08bcf2353669ea1af6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":748,
                  "y":174},
                "size":{
                  "width":32,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1657d7f0dbeb46e09df6d13a8a9b15d7",
          "label":"border",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Cursiva', 'Arial'",
            "fontStyle":"italic",
            "location":{
              "x":760,
              "y":168},
            "size":{
              "width":190,
              "height":27},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF009DDA},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3821b3250ec2447d9f754a1825379d99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Cursiva', 'Arial'",
                "fontStyle":"italic",
                "location":{
                  "x":760,
                  "y":168},
                "size":{
                  "width":190,
                  "height":27},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF009DDA},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看运单列表信息（全部）/border_u6.png"}},
{
          "id":"0b273ca5c6de471890cefcdff5aadb37",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":923,
              "y":170},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90a002aff58b48d789b5c073f00a2a5d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":923,
                  "y":170},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看运单列表信息（全部）/u8.png"}},
{
          "id":"b319869ceb9045f9842e35f4dfba25c2",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":270},
            "size":{
              "width":506,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24d42f6c6353421080365111e4905754",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":506,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e64f6ed11d2f434dba0a2cea95068fb8",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0D0D0D,
                      "opacity":1},
                    "size":{
                      "width":96,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"200645ed191448e28508ff93ee5433b0",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0D0D0D,
                          "opacity":1},
                        "size":{
                          "width":96,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/查看运单列表信息（已发单）/u12.png"}},
{
                  "id":"33850c374421401fba1b51b9cbe2ccd6",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":117,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5882ed699fef43c6b418685cad697824",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":200,
                          "y":0},
                        "size":{
                          "width":117,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/查看运单列表信息（全部）/u16.png"}},
{
                  "id":"e5da3636cbb04d03a253053442cd4ef7",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":317,
                      "y":0},
                    "size":{
                      "width":90,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1cb98b0036174a3fa6480acc9800ef16",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":317,
                          "y":0},
                        "size":{
                          "width":90,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/查看运单列表信息（签收）/u18.png"}},
{
                  "id":"c0e0903dcfd04587b34273799b891406",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "location":{
                      "x":407,
                      "y":0},
                    "size":{
                      "width":99,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3887a83ce25c4a35aee484be3ec522a8",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF999999},
                        "location":{
                          "x":407,
                          "y":0},
                        "size":{
                          "width":99,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/查看运单列表信息（签收）/u20.png"}},
{
                  "id":"f93884b3a5f94680a50034768aa74137",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":96,
                      "y":0},
                    "size":{
                      "width":104,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"66e24952be66495d9838b77c5f6c9313",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":96,
                          "y":0},
                        "size":{
                          "width":104,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/查看运单列表信息（已接收）/u14.png"}}]}]},
{
          "id":"fbe1855815934b33a40fbb07500fba29",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":320},
            "size":{
              "width":506,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22fb353cfb0148c5a37ff7795080db31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":320},
                "size":{
                  "width":506,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看运单列表信息（全部）/u22.png"}},
{
          "id":"b6ca7a0b03fb4827ba38043f0d9da4c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":468,
              "y":344},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14c8cbf6619346de8c6c651afb3be3be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":468,
                  "y":344},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"05700fbbbc3b46b3b55d532588ddcd12",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":860,
              "y":344},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd527adafb31466d80363c6d502387cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":860,
                  "y":344},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fc176f919da14e31bc36cb00ccd18492",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":474,
              "y":394},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c8d037a491f4143aa4d544d97271684",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":474,
                  "y":394},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ff16dc2495ea4763851e2dd0d526b556",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":470},
            "size":{
              "width":506,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89be5cde8f944d67a3ac770964c39ff7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":470},
                "size":{
                  "width":506,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看运单列表信息（全部）/u30.png"}},
{
          "id":"307dc089d8a541a699c84afe95e620e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":480},
            "size":{
              "width":506,
              "height":160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c16ffb376ef24ec7a58e8cfb5f0ef909",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":480},
                "size":{
                  "width":506,
                  "height":160}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看运单列表信息（全部）/u32.png"}},
{
          "id":"916a60cff5f248bfa26c83cfea834c37",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Cursiva', 'Arial'",
            "fontStyle":"italic",
            "location":{
              "x":468,
              "y":552},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7cf50a7348d4f61b3e0470cd9489d7a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Cursiva', 'Arial'",
                "fontStyle":"italic",
                "location":{
                  "x":468,
                  "y":552},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4a20a18219604259b7133db133108bf7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":853,
              "y":394},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a2e481b6b784d3b87ac727f1658b3c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":853,
                  "y":394},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8d4032b1757e43829245e6ea6cab5074",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":832,
              "y":435},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f093ed97de0b4e7895e7218bb05a167b",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":700,
              "y":435},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "226701fac7b246f9a2fc34da910b3790":{
      "scriptId":"u0"},
    "1b01c9fa5bcf4978905d8717fb937bcd":{
      "scriptId":"u1"},
    "581bbe1f1ec74130be11680c3a639323":{
      "scriptId":"u2"},
    "dc665838212c41599076c75edb86daa9":{
      "scriptId":"u3"},
    "6ead10695b4d459a9246000fcb534818":{
      "scriptId":"u4"},
    "b37437aba7bd4d08bcf2353669ea1af6":{
      "scriptId":"u5"},
    "1657d7f0dbeb46e09df6d13a8a9b15d7":{
      "scriptId":"u6"},
    "3821b3250ec2447d9f754a1825379d99":{
      "scriptId":"u7"},
    "0b273ca5c6de471890cefcdff5aadb37":{
      "scriptId":"u8"},
    "90a002aff58b48d789b5c073f00a2a5d":{
      "scriptId":"u9"},
    "b319869ceb9045f9842e35f4dfba25c2":{
      "scriptId":"u10"},
    "24d42f6c6353421080365111e4905754":{
      "scriptId":"u11"},
    "e64f6ed11d2f434dba0a2cea95068fb8":{
      "scriptId":"u12"},
    "200645ed191448e28508ff93ee5433b0":{
      "scriptId":"u13"},
    "f93884b3a5f94680a50034768aa74137":{
      "scriptId":"u14"},
    "66e24952be66495d9838b77c5f6c9313":{
      "scriptId":"u15"},
    "33850c374421401fba1b51b9cbe2ccd6":{
      "scriptId":"u16"},
    "5882ed699fef43c6b418685cad697824":{
      "scriptId":"u17"},
    "e5da3636cbb04d03a253053442cd4ef7":{
      "scriptId":"u18"},
    "1cb98b0036174a3fa6480acc9800ef16":{
      "scriptId":"u19"},
    "c0e0903dcfd04587b34273799b891406":{
      "scriptId":"u20"},
    "3887a83ce25c4a35aee484be3ec522a8":{
      "scriptId":"u21"},
    "fbe1855815934b33a40fbb07500fba29":{
      "scriptId":"u22"},
    "22fb353cfb0148c5a37ff7795080db31":{
      "scriptId":"u23"},
    "b6ca7a0b03fb4827ba38043f0d9da4c5":{
      "scriptId":"u24"},
    "14c8cbf6619346de8c6c651afb3be3be":{
      "scriptId":"u25"},
    "05700fbbbc3b46b3b55d532588ddcd12":{
      "scriptId":"u26"},
    "fd527adafb31466d80363c6d502387cd":{
      "scriptId":"u27"},
    "fc176f919da14e31bc36cb00ccd18492":{
      "scriptId":"u28"},
    "7c8d037a491f4143aa4d544d97271684":{
      "scriptId":"u29"},
    "ff16dc2495ea4763851e2dd0d526b556":{
      "scriptId":"u30"},
    "89be5cde8f944d67a3ac770964c39ff7":{
      "scriptId":"u31"},
    "307dc089d8a541a699c84afe95e620e4":{
      "scriptId":"u32"},
    "c16ffb376ef24ec7a58e8cfb5f0ef909":{
      "scriptId":"u33"},
    "916a60cff5f248bfa26c83cfea834c37":{
      "scriptId":"u34"},
    "d7cf50a7348d4f61b3e0470cd9489d7a":{
      "scriptId":"u35"},
    "4a20a18219604259b7133db133108bf7":{
      "scriptId":"u36"},
    "2a2e481b6b784d3b87ac727f1658b3c9":{
      "scriptId":"u37"},
    "8d4032b1757e43829245e6ea6cab5074":{
      "scriptId":"u38"},
    "f093ed97de0b4e7895e7218bb05a167b":{
      "scriptId":"u39"}}});