$axure.loadCurrentPage({
  "url":"新增_3.html",
  "generationDate":new Date(1557741995852.31),
  "isCanvasEnabled":false,
  "variables":["yys_name",
"car_chePai_card",
"car_chePai_color",
"car_leixing",
"car_ICcard",
"yy_leixing",
"car_InterNet_leixing",
"car_jingYingLuXian",
"car_zhuangTai",
"quYu",
"phone",
"mail",
"name"],
  "page":{
    "packageId":"ba0141b5cb1a46008fc1f1db17ac3a09",
    "type":"Axure:Page",
    "name":"新增",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"dc81f31e88394ea3a2b60d4b56dc79a2",
          "label":"编辑_弹框",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":10,
              "y":26},
            "size":{
              "width":620,
              "height":863}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc09cf6986244120a95e7a595e380133",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":10,
                  "y":26},
                "size":{
                  "width":620,
                  "height":863}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增_3/编辑_弹框_u0.png"}},
{
          "id":"2b7c4a85e01a47ad86386fe72a6a24fc",
          "label":"新增_",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":61,
              "y":117},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"edbcdb9f637b4944900c2daaadcbe9d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":61,
                  "y":117},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ef80387c19f842229af48b14988572bb",
          "label":"新增_",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":61,
              "y":157},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45efa5ecfb5543dda548a3fc6fb26e8e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":61,
                  "y":157},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9b8d3feadf6c4a25b48db039b3137537",
          "label":"新增_",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":61,
              "y":196},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b9ff893d1a04eb699ca23f5c21748cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":61,
                  "y":196},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dbd1f6c7e46042e7ad92459ac07bcc8c",
          "label":"新增_",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":61,
              "y":235},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71c9c08758f7451698eb035b5ce3a5de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":61,
                  "y":235},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"201e9063d3184d54841e468966ee2a65",
          "label":"新增_",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":61,
              "y":273},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"522a4dd400ef45098a294f71e2715d9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":61,
                  "y":273},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3aabb54d86e34038ba33ce15ba038897",
          "label":"新增_",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":61,
              "y":313},
            "size":{
              "width":52,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1daa09c4ea9341c6b91963a8d8923b41",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":61,
                  "y":313},
                "size":{
                  "width":52,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"797858e8702047b79a9f4edeb9d64b97",
          "label":"新增_",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":61,
              "y":351},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69e7854f471141c98e481135df0a3f74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":61,
                  "y":351},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d9b7f89bb9b943cf9f7fd0ccc782d2ae",
          "label":"新增_",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":61,
              "y":392},
            "size":{
              "width":52,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"205508ee0ca3490bbe81907ad5d65e19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":61,
                  "y":392},
                "size":{
                  "width":52,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"50f0a5721cbb4a339b75fd9b3a23bf15",
          "label":"新增_IC卡号",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":155,
              "y":269},
            "size":{
              "width":120,
              "height":28}},
          "adaptiveStyles":{
}},
{
          "id":"4939bcae22524bb5a68a944d2b58d6a8",
          "label":"新增_",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":82},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ac899ae72a246fcba56d310959d18cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":82},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9bf88d638585451e9bb6f918cd9568be",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":1074,
              "y":177},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"center",
          "fixedMarginHorizontal":0,
          "fixedVertical":"middle",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"e32060c3c2464824854789a23465e6de",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"94ba24b44cf8481ea9d8d1d809412c3e",
                  "label":"新增未填提示",
                  "parentDynamicPanel":"9bf88d638585451e9bb6f918cd9568be",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":286,
                      "height":120}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3eed9f350a9c4375af16261919e17b05",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9bf88d638585451e9bb6f918cd9568be",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":286,
                          "height":120}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onMouseOver":{
                      "description":"OnMouseOver",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"wait",
                              "description":"等待1000毫秒",
                              "waitTime":1000},
{
                              "action":"fadeWidget",
                              "description":"隐藏 新增未填提示",
                              "objectsToFades":[{
                                  "objectPath":["94ba24b44cf8481ea9d8d1d809412c3e"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "images":{
                    "normal~":"images/车辆信息新增页面/新增未填提示_u35.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"e021cce3a700459f98635f49551ab8b6",
          "label":"新增_车牌号",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":156,
              "y":82},
            "size":{
              "width":218,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"707a0828666f4ad69852fc27b6ff8210",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":37},
            "size":{
              "width":152,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b2d6cfa20194f8c8dafa19e1fe38cab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":37},
                "size":{
                  "width":152,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"20627fa70ea949d59bdd8418e1d80526",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":156,
              "y":154},
            "size":{
              "width":104,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"f886092d4b3e4f0e88cb0d929979e6bb",
          "label":"新增_IC卡号",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":155,
              "y":193.5},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
}},
{
          "id":"0e411560a71b404cbc5cbea7303eac77",
          "label":"新增_IC卡号",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":155,
              "y":233.5},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
}},
{
          "id":"e69341679d9e4c74bfb73bb7400822e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":271,
              "y":271},
            "size":{
              "width":29,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e50733a2fc0248fb9619ec079bad72bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":271,
                  "y":271},
                "size":{
                  "width":29,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增_3/u30.png"}},
{
          "id":"63fca6ffe56e41fe86c1e8ef70396691",
          "label":"新增_IC卡号",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":148,
              "y":313},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"8f71eaa050064d8cb3fbd8b84ede90f2",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":148,
              "y":351},
            "size":{
              "width":132,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"e0b8257c8837470fa3fed7fa168f02b4",
          "label":"新增_IC卡号",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":148,
              "y":389},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"8ef1384785434df2b2785bcbb8517d9b",
          "label":"新增_",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":57,
              "y":424},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"259b620946e646f18b2f67a7e49a416c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":57,
                  "y":424},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8c9897d488564defa4035d0d630ee666",
          "label":"新增_",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":418},
            "size":{
              "width":14,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d49f4941ef6428197986ea7bc3e4eff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":418},
                "size":{
                  "width":14,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"326ab3bb8cae4b14ade932a44054dd7e",
          "label":"新增_",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":52,
              "y":432},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b64c8910fae44f5a52e0aeaf47ca9b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":52,
                  "y":432},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"429648e06e8c4c5299d38a4bf665fa0f",
          "label":"新增_IC卡号",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":148,
              "y":429},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"ff839916c03447458fb9bd001d15b9c2",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":156,
              "y":114},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"ab4c4e29fe56454399244937592da788",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":52,
              "y":470},
            "size":{
              "width":88,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6bd6e426c20f42249ecabbca6966389a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":52,
                  "y":470},
                "size":{
                  "width":88,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"952d6eaee39f4ba19ad8dc0cb29a139d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":466},
            "size":{
              "width":400,
              "height":174}},
          "adaptiveStyles":{
}},
{
          "id":"d16241ec79394c0bb3e81e5767e6ac0c",
          "label":"新增_保存",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":285,
              "y":560},
            "size":{
              "width":130,
              "height":28}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"若某项为空<br> (If 部件文字 不明 = &quot;&quot; 或 部件文字 新增_IC卡号 = &quot;&quot; 或 选中项值 不明 = &quot;请选择&quot; 或 选中项值 不明 = &quot;请选择&quot; 或 选中项值 不明 = &quot;请选择&quot; 或 选中项值 不明 = &quot;全部&quot; 或 选中项值 不明 = &quot;请选择&quot; 或 选中项值 不明 = &quot;请选择&quot; 或 选中项值 不明 = &quot;请选择&quot; 或 选中项值 不明 = &quot;请选择&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"||",
                    "leftExpr":{
                      "exprType":"binaryOp",
                      "op":"==",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetWidgetText",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["205aa56a70094d68871dfb53ae1b370d"]}]},
                      "rightExpr":{
                        "exprType":"stringLiteral",
                        "value":"",
                        "stos":[]}},
                    "rightExpr":{
                      "exprType":"binaryOp",
                      "op":"||",
                      "leftExpr":{
                        "exprType":"binaryOp",
                        "op":"==",
                        "leftExpr":{
                          "exprType":"fcall",
                          "functionName":"GetWidgetText",
                          "arguments":[{
                              "exprType":"pathLiteral",
                              "isThis":false,
                              "isFocused":false,
                              "isTarget":false,
                              "value":["50f0a5721cbb4a339b75fd9b3a23bf15"]}]},
                        "rightExpr":{
                          "exprType":"stringLiteral",
                          "value":"",
                          "stos":[]}},
                      "rightExpr":{
                        "exprType":"binaryOp",
                        "op":"||",
                        "leftExpr":{
                          "exprType":"binaryOp",
                          "op":"==",
                          "leftExpr":{
                            "exprType":"fcall",
                            "functionName":"GetSelectedOption",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["ed2d05c358ad461aa42b24262ca78e5e"]}]},
                          "rightExpr":{
                            "exprType":"stringLiteral",
                            "value":"请选择",
                            "stos":[]}},
                        "rightExpr":{
                          "exprType":"binaryOp",
                          "op":"||",
                          "leftExpr":{
                            "exprType":"binaryOp",
                            "op":"==",
                            "leftExpr":{
                              "exprType":"fcall",
                              "functionName":"GetSelectedOption",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["2e5d09a1b7ec445ea188ab353d2ccf72"]}]},
                            "rightExpr":{
                              "exprType":"stringLiteral",
                              "value":"请选择",
                              "stos":[]}},
                          "rightExpr":{
                            "exprType":"binaryOp",
                            "op":"||",
                            "leftExpr":{
                              "exprType":"binaryOp",
                              "op":"==",
                              "leftExpr":{
                                "exprType":"fcall",
                                "functionName":"GetSelectedOption",
                                "arguments":[{
                                    "exprType":"pathLiteral",
                                    "isThis":false,
                                    "isFocused":false,
                                    "isTarget":false,
                                    "value":["bf2437c09dd740fda8c39a7aa70527eb"]}]},
                              "rightExpr":{
                                "exprType":"stringLiteral",
                                "value":"请选择",
                                "stos":[]}},
                            "rightExpr":{
                              "exprType":"binaryOp",
                              "op":"||",
                              "leftExpr":{
                                "exprType":"binaryOp",
                                "op":"==",
                                "leftExpr":{
                                  "exprType":"fcall",
                                  "functionName":"GetSelectedOption",
                                  "arguments":[{
                                      "exprType":"pathLiteral",
                                      "isThis":false,
                                      "isFocused":false,
                                      "isTarget":false,
                                      "value":["8f1393abf5934e77a03acc069dc04b49"]}]},
                                "rightExpr":{
                                  "exprType":"stringLiteral",
                                  "value":"全部",
                                  "stos":[]}},
                              "rightExpr":{
                                "exprType":"binaryOp",
                                "op":"||",
                                "leftExpr":{
                                  "exprType":"binaryOp",
                                  "op":"==",
                                  "leftExpr":{
                                    "exprType":"fcall",
                                    "functionName":"GetSelectedOption",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":false,
                                        "isFocused":false,
                                        "isTarget":false,
                                        "value":["db7aae2299414ac9af71ff1c2529fb6e"]}]},
                                  "rightExpr":{
                                    "exprType":"stringLiteral",
                                    "value":"请选择",
                                    "stos":[]}},
                                "rightExpr":{
                                  "exprType":"binaryOp",
                                  "op":"||",
                                  "leftExpr":{
                                    "exprType":"binaryOp",
                                    "op":"==",
                                    "leftExpr":{
                                      "exprType":"fcall",
                                      "functionName":"GetSelectedOption",
                                      "arguments":[{
                                          "exprType":"pathLiteral",
                                          "isThis":false,
                                          "isFocused":false,
                                          "isTarget":false,
                                          "value":["dbc5031492c243159f28ade0847ba565"]}]},
                                    "rightExpr":{
                                      "exprType":"stringLiteral",
                                      "value":"请选择",
                                      "stos":[]}},
                                  "rightExpr":{
                                    "exprType":"binaryOp",
                                    "op":"||",
                                    "leftExpr":{
                                      "exprType":"binaryOp",
                                      "op":"==",
                                      "leftExpr":{
                                        "exprType":"fcall",
                                        "functionName":"GetSelectedOption",
                                        "arguments":[{
                                            "exprType":"pathLiteral",
                                            "isThis":false,
                                            "isFocused":false,
                                            "isTarget":false,
                                            "value":["50cb0f8762ee4c7180bd74a21e5a5c21"]}]},
                                      "rightExpr":{
                                        "exprType":"stringLiteral",
                                        "value":"请选择",
                                        "stos":[]}},
                                    "rightExpr":{
                                      "exprType":"binaryOp",
                                      "op":"==",
                                      "leftExpr":{
                                        "exprType":"fcall",
                                        "functionName":"GetSelectedOption",
                                        "arguments":[{
                                            "exprType":"pathLiteral",
                                            "isThis":false,
                                            "isFocused":false,
                                            "isTarget":false,
                                            "value":["22beeb103c22409a92adfcbf4e9ba188"]}]},
                                      "rightExpr":{
                                        "exprType":"stringLiteral",
                                        "value":"请选择",
                                        "stos":[]}}}}}}}}}}},
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 新增未填提示",
                      "objectsToFades":[{
                          "objectPath":["94ba24b44cf8481ea9d8d1d809412c3e"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]},
{
                  "description":"若全有<br> (Else If True)",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 变量 yys_name = 选中项值 不明, 且<br> 变量 car_chePai_card = 部件文字 不明, 且<br> 变量 car_chePai_color = 选中项值 不明, 且<br> 变量 car_leixing = 选中项值 不明, 且<br> 变量 car_ICcard = 部件文字 新增_IC卡号, 且<br> 变量 yy_leixing = 选中项值 不明, 且<br> 变量 car_InterNet_leixing = 选中项值 不明, 且<br> 变量 car_jingYingLuXian = 选中项值 不明, 且<br> 变量 car_zhuangTai = 选中项值 不明, 且<br> 变量 quYu = 选中项值 不明",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"car_ICcard"},
{
                                "exprType":"fcall",
                                "functionName":"GetWidgetText",
                                "arguments":[{
                                    "exprType":"pathLiteral",
                                    "isThis":false,
                                    "isFocused":false,
                                    "isTarget":false,
                                    "value":["50f0a5721cbb4a339b75fd9b3a23bf15"]}]}]}]}},
{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 车辆基本信息",
                      "target":{
                        "targetType":"page",
                        "url":"车辆基本信息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"44161ae573234c7ab1627af2a5cb29ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":72,
              "y":674},
            "size":{
              "width":29,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fcd39d8f61bc4101966dbb83ff02e356",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":72,
                  "y":674},
                "size":{
                  "width":29,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c8bb479bcf0e43f497951deb9495e263",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":148,
              "y":680},
            "size":{
              "width":402,
              "height":120}},
          "adaptiveStyles":{
}},
{
          "id":"0d145a4655df478ea4a62b20771d2265",
          "label":"新增_保存",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":156,
              "y":829},
            "size":{
              "width":130,
              "height":28}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"若某项为空<br> (If 部件文字 不明 = &quot;&quot; 或 部件文字 新增_IC卡号 = &quot;&quot; 或 选中项值 不明 = &quot;请选择&quot; 或 选中项值 不明 = &quot;请选择&quot; 或 选中项值 不明 = &quot;请选择&quot; 或 选中项值 不明 = &quot;全部&quot; 或 选中项值 不明 = &quot;请选择&quot; 或 选中项值 不明 = &quot;请选择&quot; 或 选中项值 不明 = &quot;请选择&quot; 或 选中项值 不明 = &quot;请选择&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"||",
                    "leftExpr":{
                      "exprType":"binaryOp",
                      "op":"==",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetWidgetText",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["205aa56a70094d68871dfb53ae1b370d"]}]},
                      "rightExpr":{
                        "exprType":"stringLiteral",
                        "value":"",
                        "stos":[]}},
                    "rightExpr":{
                      "exprType":"binaryOp",
                      "op":"||",
                      "leftExpr":{
                        "exprType":"binaryOp",
                        "op":"==",
                        "leftExpr":{
                          "exprType":"fcall",
                          "functionName":"GetWidgetText",
                          "arguments":[{
                              "exprType":"pathLiteral",
                              "isThis":false,
                              "isFocused":false,
                              "isTarget":false,
                              "value":["50f0a5721cbb4a339b75fd9b3a23bf15"]}]},
                        "rightExpr":{
                          "exprType":"stringLiteral",
                          "value":"",
                          "stos":[]}},
                      "rightExpr":{
                        "exprType":"binaryOp",
                        "op":"||",
                        "leftExpr":{
                          "exprType":"binaryOp",
                          "op":"==",
                          "leftExpr":{
                            "exprType":"fcall",
                            "functionName":"GetSelectedOption",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["ed2d05c358ad461aa42b24262ca78e5e"]}]},
                          "rightExpr":{
                            "exprType":"stringLiteral",
                            "value":"请选择",
                            "stos":[]}},
                        "rightExpr":{
                          "exprType":"binaryOp",
                          "op":"||",
                          "leftExpr":{
                            "exprType":"binaryOp",
                            "op":"==",
                            "leftExpr":{
                              "exprType":"fcall",
                              "functionName":"GetSelectedOption",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["2e5d09a1b7ec445ea188ab353d2ccf72"]}]},
                            "rightExpr":{
                              "exprType":"stringLiteral",
                              "value":"请选择",
                              "stos":[]}},
                          "rightExpr":{
                            "exprType":"binaryOp",
                            "op":"||",
                            "leftExpr":{
                              "exprType":"binaryOp",
                              "op":"==",
                              "leftExpr":{
                                "exprType":"fcall",
                                "functionName":"GetSelectedOption",
                                "arguments":[{
                                    "exprType":"pathLiteral",
                                    "isThis":false,
                                    "isFocused":false,
                                    "isTarget":false,
                                    "value":["bf2437c09dd740fda8c39a7aa70527eb"]}]},
                              "rightExpr":{
                                "exprType":"stringLiteral",
                                "value":"请选择",
                                "stos":[]}},
                            "rightExpr":{
                              "exprType":"binaryOp",
                              "op":"||",
                              "leftExpr":{
                                "exprType":"binaryOp",
                                "op":"==",
                                "leftExpr":{
                                  "exprType":"fcall",
                                  "functionName":"GetSelectedOption",
                                  "arguments":[{
                                      "exprType":"pathLiteral",
                                      "isThis":false,
                                      "isFocused":false,
                                      "isTarget":false,
                                      "value":["8f1393abf5934e77a03acc069dc04b49"]}]},
                                "rightExpr":{
                                  "exprType":"stringLiteral",
                                  "value":"全部",
                                  "stos":[]}},
                              "rightExpr":{
                                "exprType":"binaryOp",
                                "op":"||",
                                "leftExpr":{
                                  "exprType":"binaryOp",
                                  "op":"==",
                                  "leftExpr":{
                                    "exprType":"fcall",
                                    "functionName":"GetSelectedOption",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":false,
                                        "isFocused":false,
                                        "isTarget":false,
                                        "value":["db7aae2299414ac9af71ff1c2529fb6e"]}]},
                                  "rightExpr":{
                                    "exprType":"stringLiteral",
                                    "value":"请选择",
                                    "stos":[]}},
                                "rightExpr":{
                                  "exprType":"binaryOp",
                                  "op":"||",
                                  "leftExpr":{
                                    "exprType":"binaryOp",
                                    "op":"==",
                                    "leftExpr":{
                                      "exprType":"fcall",
                                      "functionName":"GetSelectedOption",
                                      "arguments":[{
                                          "exprType":"pathLiteral",
                                          "isThis":false,
                                          "isFocused":false,
                                          "isTarget":false,
                                          "value":["dbc5031492c243159f28ade0847ba565"]}]},
                                    "rightExpr":{
                                      "exprType":"stringLiteral",
                                      "value":"请选择",
                                      "stos":[]}},
                                  "rightExpr":{
                                    "exprType":"binaryOp",
                                    "op":"||",
                                    "leftExpr":{
                                      "exprType":"binaryOp",
                                      "op":"==",
                                      "leftExpr":{
                                        "exprType":"fcall",
                                        "functionName":"GetSelectedOption",
                                        "arguments":[{
                                            "exprType":"pathLiteral",
                                            "isThis":false,
                                            "isFocused":false,
                                            "isTarget":false,
                                            "value":["50cb0f8762ee4c7180bd74a21e5a5c21"]}]},
                                      "rightExpr":{
                                        "exprType":"stringLiteral",
                                        "value":"请选择",
                                        "stos":[]}},
                                    "rightExpr":{
                                      "exprType":"binaryOp",
                                      "op":"==",
                                      "leftExpr":{
                                        "exprType":"fcall",
                                        "functionName":"GetSelectedOption",
                                        "arguments":[{
                                            "exprType":"pathLiteral",
                                            "isThis":false,
                                            "isFocused":false,
                                            "isTarget":false,
                                            "value":["22beeb103c22409a92adfcbf4e9ba188"]}]},
                                      "rightExpr":{
                                        "exprType":"stringLiteral",
                                        "value":"请选择",
                                        "stos":[]}}}}}}}}}}},
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 新增未填提示",
                      "objectsToFades":[{
                          "objectPath":["94ba24b44cf8481ea9d8d1d809412c3e"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]},
{
                  "description":"若全有<br> (Else If True)",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 变量 yys_name = 选中项值 不明, 且<br> 变量 car_chePai_card = 部件文字 不明, 且<br> 变量 car_chePai_color = 选中项值 不明, 且<br> 变量 car_leixing = 选中项值 不明, 且<br> 变量 car_ICcard = 部件文字 新增_IC卡号, 且<br> 变量 yy_leixing = 选中项值 不明, 且<br> 变量 car_InterNet_leixing = 选中项值 不明, 且<br> 变量 car_jingYingLuXian = 选中项值 不明, 且<br> 变量 car_zhuangTai = 选中项值 不明, 且<br> 变量 quYu = 选中项值 不明",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"car_ICcard"},
{
                                "exprType":"fcall",
                                "functionName":"GetWidgetText",
                                "arguments":[{
                                    "exprType":"pathLiteral",
                                    "isThis":false,
                                    "isFocused":false,
                                    "isTarget":false,
                                    "value":["50f0a5721cbb4a339b75fd9b3a23bf15"]}]}]}]}},
{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 车辆基本信息",
                      "target":{
                        "targetType":"page",
                        "url":"车辆基本信息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"1182e9ee7fb14b25ade881cfbe60421a",
          "label":"新增_关闭",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":306,
              "y":826},
            "size":{
              "width":119,
              "height":34}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 变量 yys_name = &quot;&quot;, 且<br> 变量 car_chePai_card = &quot;&quot;, 且<br> 变量 car_chePai_color = &quot;&quot;, 且<br> 变量 car_leixing = &quot;&quot;, 且<br> 变量 car_ICcard = &quot;&quot;, 且<br> 变量 yy_leixing = &quot;&quot;, 且<br> 变量 car_InterNet_leixing = &quot;&quot;, 且<br> 变量 car_jingYingLuXian = &quot;&quot;, 且<br> 变量 car_zhuangTai = &quot;&quot;, 且<br> 变量 quYu = &quot;&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"yys_name"},
{
                                "exprType":"stringLiteral",
                                "value":"",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"car_chePai_card"},
{
                                "exprType":"stringLiteral",
                                "value":"",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"car_chePai_color"},
{
                                "exprType":"stringLiteral",
                                "value":"",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"car_leixing"},
{
                                "exprType":"stringLiteral",
                                "value":"",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"car_ICcard"},
{
                                "exprType":"stringLiteral",
                                "value":"",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"yy_leixing"},
{
                                "exprType":"stringLiteral",
                                "value":"",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"car_InterNet_leixing"},
{
                                "exprType":"stringLiteral",
                                "value":"",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"car_jingYingLuXian"},
{
                                "exprType":"stringLiteral",
                                "value":"",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"car_zhuangTai"},
{
                                "exprType":"stringLiteral",
                                "value":"",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"quYu"},
{
                                "exprType":"stringLiteral",
                                "value":"",
                                "stos":[]}]}]}},
{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 车辆基本信息",
                      "target":{
                        "targetType":"page",
                        "url":"车辆基本信息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "dc81f31e88394ea3a2b60d4b56dc79a2":{
      "scriptId":"u0"},
    "bc09cf6986244120a95e7a595e380133":{
      "scriptId":"u1"},
    "2b7c4a85e01a47ad86386fe72a6a24fc":{
      "scriptId":"u2"},
    "edbcdb9f637b4944900c2daaadcbe9d4":{
      "scriptId":"u3"},
    "ef80387c19f842229af48b14988572bb":{
      "scriptId":"u4"},
    "45efa5ecfb5543dda548a3fc6fb26e8e":{
      "scriptId":"u5"},
    "9b8d3feadf6c4a25b48db039b3137537":{
      "scriptId":"u6"},
    "7b9ff893d1a04eb699ca23f5c21748cd":{
      "scriptId":"u7"},
    "dbd1f6c7e46042e7ad92459ac07bcc8c":{
      "scriptId":"u8"},
    "71c9c08758f7451698eb035b5ce3a5de":{
      "scriptId":"u9"},
    "201e9063d3184d54841e468966ee2a65":{
      "scriptId":"u10"},
    "522a4dd400ef45098a294f71e2715d9b":{
      "scriptId":"u11"},
    "3aabb54d86e34038ba33ce15ba038897":{
      "scriptId":"u12"},
    "1daa09c4ea9341c6b91963a8d8923b41":{
      "scriptId":"u13"},
    "797858e8702047b79a9f4edeb9d64b97":{
      "scriptId":"u14"},
    "69e7854f471141c98e481135df0a3f74":{
      "scriptId":"u15"},
    "d9b7f89bb9b943cf9f7fd0ccc782d2ae":{
      "scriptId":"u16"},
    "205508ee0ca3490bbe81907ad5d65e19":{
      "scriptId":"u17"},
    "50f0a5721cbb4a339b75fd9b3a23bf15":{
      "scriptId":"u18"},
    "4939bcae22524bb5a68a944d2b58d6a8":{
      "scriptId":"u19"},
    "9ac899ae72a246fcba56d310959d18cd":{
      "scriptId":"u20"},
    "9bf88d638585451e9bb6f918cd9568be":{
      "scriptId":"u21"},
    "94ba24b44cf8481ea9d8d1d809412c3e":{
      "scriptId":"u22"},
    "3eed9f350a9c4375af16261919e17b05":{
      "scriptId":"u23"},
    "e021cce3a700459f98635f49551ab8b6":{
      "scriptId":"u24"},
    "707a0828666f4ad69852fc27b6ff8210":{
      "scriptId":"u25"},
    "3b2d6cfa20194f8c8dafa19e1fe38cab":{
      "scriptId":"u26"},
    "20627fa70ea949d59bdd8418e1d80526":{
      "scriptId":"u27"},
    "f886092d4b3e4f0e88cb0d929979e6bb":{
      "scriptId":"u28"},
    "0e411560a71b404cbc5cbea7303eac77":{
      "scriptId":"u29"},
    "e69341679d9e4c74bfb73bb7400822e4":{
      "scriptId":"u30"},
    "e50733a2fc0248fb9619ec079bad72bc":{
      "scriptId":"u31"},
    "63fca6ffe56e41fe86c1e8ef70396691":{
      "scriptId":"u32"},
    "8f71eaa050064d8cb3fbd8b84ede90f2":{
      "scriptId":"u33"},
    "e0b8257c8837470fa3fed7fa168f02b4":{
      "scriptId":"u34"},
    "8ef1384785434df2b2785bcbb8517d9b":{
      "scriptId":"u35"},
    "259b620946e646f18b2f67a7e49a416c":{
      "scriptId":"u36"},
    "8c9897d488564defa4035d0d630ee666":{
      "scriptId":"u37"},
    "8d49f4941ef6428197986ea7bc3e4eff":{
      "scriptId":"u38"},
    "326ab3bb8cae4b14ade932a44054dd7e":{
      "scriptId":"u39"},
    "6b64c8910fae44f5a52e0aeaf47ca9b3":{
      "scriptId":"u40"},
    "429648e06e8c4c5299d38a4bf665fa0f":{
      "scriptId":"u41"},
    "ff839916c03447458fb9bd001d15b9c2":{
      "scriptId":"u42"},
    "ab4c4e29fe56454399244937592da788":{
      "scriptId":"u43"},
    "6bd6e426c20f42249ecabbca6966389a":{
      "scriptId":"u44"},
    "952d6eaee39f4ba19ad8dc0cb29a139d":{
      "scriptId":"u45"},
    "d16241ec79394c0bb3e81e5767e6ac0c":{
      "scriptId":"u46"},
    "44161ae573234c7ab1627af2a5cb29ee":{
      "scriptId":"u47"},
    "fcd39d8f61bc4101966dbb83ff02e356":{
      "scriptId":"u48"},
    "c8bb479bcf0e43f497951deb9495e263":{
      "scriptId":"u49"},
    "0d145a4655df478ea4a62b20771d2265":{
      "scriptId":"u50"},
    "1182e9ee7fb14b25ade881cfbe60421a":{
      "scriptId":"u51"}}});