$axure.loadCurrentPage({
  "url":"车辆事故修改.html",
  "generationDate":new Date(1557741993998.1),
  "isCanvasEnabled":false,
  "variables":["yys_name",
"car_chePai_card",
"car_chePai_color",
"car_leixing",
"car_ICcard",
"yy_leixing",
"car_InterNet_leixing",
"car_jingYingLuXian",
"car_zhuangTai",
"quYu",
"phone",
"mail",
"name"],
  "page":{
    "packageId":"154dd807ce604f5f8cf40402e96a8776",
    "type":"Axure:Page",
    "name":"车辆事故修改",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"335a29a150cd4604bace20e77184595d",
          "label":"编辑_弹框",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":350,
              "height":425}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c4a57dd1903486f808f91cdc7942f37",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":350,
                  "height":425}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/车辆信息新增页面/编辑_弹框_u0.png"}},
{
          "id":"f550886420314a519805ff588f594f8e",
          "label":"新增_",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":38},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0fc12472fb224a168b84b0a9790b988c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":38},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7cbbda507cc345acaa696b07c8533004",
          "label":"新增_",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":83},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e50e507bba44bf0a531be8a6e0c1b6f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":83},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"380d73f27a034083809f214e27399450",
          "label":"新增_车牌号",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":118,
              "y":33},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"e723208bf2234f7bb5f5aeec96f2f85a",
          "label":"新增_IC卡号",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":118,
              "y":78},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"014a0410f38f4c44bb29b2b9a945e55f",
          "label":"新增_保存",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":374},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"71fc4fe97251412ab1086aa10a498084",
          "label":"新增_关闭",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":374},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"39da2a97621242c4ad9454bf59b68b79",
          "label":"新增_",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":133},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b591dd7dd3b14d80832b75bf6bc97208",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":133},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ad19d9067e9847d8a179358141010815",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":118,
              "y":128},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"a081eb8d2ca544afa3deef1598ccc26c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":241},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1afe0c5f2a54380af4fa09b2c263948",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":241},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1c6a968a1a174cfea2eb3058a2b04392",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":118,
              "y":241},
            "size":{
              "width":200,
              "height":99}},
          "adaptiveStyles":{
}},
{
          "id":"be00ab8ab3f04dc39b468176cc9e4eaa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":185},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44987aae1d8046929cd918c8a23b50b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":185},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d224e421a0ca4e0eaecea51efabf9e23",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":118,
              "y":181.5},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "335a29a150cd4604bace20e77184595d":{
      "scriptId":"u0"},
    "3c4a57dd1903486f808f91cdc7942f37":{
      "scriptId":"u1"},
    "f550886420314a519805ff588f594f8e":{
      "scriptId":"u2"},
    "0fc12472fb224a168b84b0a9790b988c":{
      "scriptId":"u3"},
    "7cbbda507cc345acaa696b07c8533004":{
      "scriptId":"u4"},
    "4e50e507bba44bf0a531be8a6e0c1b6f":{
      "scriptId":"u5"},
    "380d73f27a034083809f214e27399450":{
      "scriptId":"u6"},
    "e723208bf2234f7bb5f5aeec96f2f85a":{
      "scriptId":"u7"},
    "014a0410f38f4c44bb29b2b9a945e55f":{
      "scriptId":"u8"},
    "71fc4fe97251412ab1086aa10a498084":{
      "scriptId":"u9"},
    "39da2a97621242c4ad9454bf59b68b79":{
      "scriptId":"u10"},
    "b591dd7dd3b14d80832b75bf6bc97208":{
      "scriptId":"u11"},
    "ad19d9067e9847d8a179358141010815":{
      "scriptId":"u12"},
    "a081eb8d2ca544afa3deef1598ccc26c":{
      "scriptId":"u13"},
    "c1afe0c5f2a54380af4fa09b2c263948":{
      "scriptId":"u14"},
    "1c6a968a1a174cfea2eb3058a2b04392":{
      "scriptId":"u15"},
    "be00ab8ab3f04dc39b468176cc9e4eaa":{
      "scriptId":"u16"},
    "44987aae1d8046929cd918c8a23b50b9":{
      "scriptId":"u17"},
    "d224e421a0ca4e0eaecea51efabf9e23":{
      "scriptId":"u18"}}});