$axure.loadCurrentPage({
  "url":"路线绑定.html",
  "generationDate":new Date(1558324040795.48),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"yys_name",
"car_chePai_card",
"car_chePai_color",
"car_leixing",
"car_ICcard",
"yy_leixing",
"car_InterNet_leixing",
"car_jingYingLuXian",
"car_zhuangTai",
"quYu",
"phone",
"mail",
"name",
"NewVariable"],
  "page":{
    "packageId":"5a32f42c4c3243668125a674b3f9a4cc",
    "type":"Axure:Page",
    "name":"路线绑定",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3118754155f14a63bf5b671011f6b453",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":120},
            "size":{
              "width":1010,
              "height":220}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc0ccafe84dd48efa710e98c34c4a52a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":126,
                  "y":0},
                "size":{
                  "width":125,
                  "height":47}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f34ca41167e4448593c85ea853c89857",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":126,
                      "y":0},
                    "size":{
                      "width":125,
                      "height":47}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/路线绑定/u3.png"}},
{
              "id":"4913e10e56114782ba134032c6943a8b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":126,
                  "y":47},
                "size":{
                  "width":125,
                  "height":43}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5d5cac39537243f3a18a866d409f4c64",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":126,
                      "y":47},
                    "size":{
                      "width":125,
                      "height":43}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/路线绑定/u19.png"}},
{
              "id":"c9ddb1be34274bceb4203cf76e0752c5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":126,
                  "y":90},
                "size":{
                  "width":125,
                  "height":39}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9d8b6f77c653494684f227ef9c896c77",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":126,
                      "y":90},
                    "size":{
                      "width":125,
                      "height":39}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/路线绑定/u35.png"}},
{
              "id":"463b0aaf0e2347b59f13b2f6d5746be2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":251,
                  "y":0},
                "size":{
                  "width":130,
                  "height":47}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"197ee74a5c784c14801dfffc0de48be1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":251,
                      "y":0},
                    "size":{
                      "width":130,
                      "height":47}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/路线绑定/u5.png"}},
{
              "id":"10cf53ac24684221bd0d5e45a323edd8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":251,
                  "y":47},
                "size":{
                  "width":130,
                  "height":43}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bd5f9e138ff049df800651478afb12c2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":251,
                      "y":47},
                    "size":{
                      "width":130,
                      "height":43}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/路线绑定/u21.png"}},
{
              "id":"72f4cc1221d446359998a1364edac4ea",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":251,
                  "y":90},
                "size":{
                  "width":130,
                  "height":39}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e6a35bd920b3431f8c2d8151be2fac24",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":251,
                      "y":90},
                    "size":{
                      "width":130,
                      "height":39}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/路线绑定/u37.png"}},
{
              "id":"4a05d34cda1841d69ef2459d26ea1064",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":381,
                  "y":0},
                "size":{
                  "width":120,
                  "height":47}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4ede19b5e4a24034ba9a194a6a9f8650",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":381,
                      "y":0},
                    "size":{
                      "width":120,
                      "height":47}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/路线绑定/u7.png"}},
{
              "id":"05ef279a7a99433a90d191915c62b3e6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":381,
                  "y":47},
                "size":{
                  "width":120,
                  "height":43}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7c6367aa690a4902a15304d5f5d77601",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":381,
                      "y":47},
                    "size":{
                      "width":120,
                      "height":43}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/路线绑定/u23.png"}},
{
              "id":"ab3f1da64ad649fe811b2dfbeda59416",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":381,
                  "y":90},
                "size":{
                  "width":120,
                  "height":39}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"445d023de255400da8dd12da0812a20d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":381,
                      "y":90},
                    "size":{
                      "width":120,
                      "height":39}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/路线绑定/u39.png"}},
{
              "id":"2c502a4d9a0440e89a7c08c393916b62",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":126,
                  "y":129},
                "size":{
                  "width":125,
                  "height":42}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4a45d65079c94d1ca33ab49a8d0288aa",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":126,
                      "y":129},
                    "size":{
                      "width":125,
                      "height":42}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/路线绑定/u51.png"}},
{
              "id":"3afb33f97465432291704cff9cb0dc03",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":251,
                  "y":129},
                "size":{
                  "width":130,
                  "height":42}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fec7b588f1c344bcb60755ee282e5097",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":251,
                      "y":129},
                    "size":{
                      "width":130,
                      "height":42}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/路线绑定/u53.png"}},
{
              "id":"ef69fee0aa3a45a5802d01fa03de9ab1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":381,
                  "y":129},
                "size":{
                  "width":120,
                  "height":42}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"92f5397414c74d91b3dcd72a0971ff1e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":381,
                      "y":129},
                    "size":{
                      "width":120,
                      "height":42}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/路线绑定/u55.png"}},
{
              "id":"6066c7e3dac14592b29a81689ce42bee",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":871,
                  "y":0},
                "size":{
                  "width":139,
                  "height":47}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0474e4cdfd4747c88d1232d640ac8b29",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":871,
                      "y":0},
                    "size":{
                      "width":139,
                      "height":47}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/路线绑定/u15.png"}},
{
              "id":"63df18602b564614b767281d9e7a1402",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":871,
                  "y":47},
                "size":{
                  "width":139,
                  "height":43}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"682b79156b2e4d65a1a9bcb2512c8e23",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":871,
                      "y":47},
                    "size":{
                      "width":139,
                      "height":43}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/路线绑定/u31.png"}},
{
              "id":"80814bc370ed4a0d956839993d5bff3b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":871,
                  "y":90},
                "size":{
                  "width":139,
                  "height":39}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3470a6928f9f4501b9e2c4c64aeb6009",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":871,
                      "y":90},
                    "size":{
                      "width":139,
                      "height":39}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/路线绑定/u47.png"}},
{
              "id":"ca1bd5ebd7054187a9764d40d5c1396a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":871,
                  "y":129},
                "size":{
                  "width":139,
                  "height":42}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0e85f2c3f67247efb2d87b26f89fe8c4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":871,
                      "y":129},
                    "size":{
                      "width":139,
                      "height":42}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/路线绑定/u63.png"}},
{
              "id":"3c92c8e14e99405c8f585ec021eb822a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":126,
                  "y":171},
                "size":{
                  "width":125,
                  "height":49}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b3489ad35c2e43d999e99e34562a6d90",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":126,
                      "y":171},
                    "size":{
                      "width":125,
                      "height":49}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/路线绑定/u67.png"}},
{
              "id":"3e8429a03254483d919110f9358f4429",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":251,
                  "y":171},
                "size":{
                  "width":130,
                  "height":49}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2d0b54ef1b764b06a1654f8004c96d55",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":251,
                      "y":171},
                    "size":{
                      "width":130,
                      "height":49}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/路线绑定/u69.png"}},
{
              "id":"4e1513b17715494bb82a333d6eca863e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":381,
                  "y":171},
                "size":{
                  "width":120,
                  "height":49}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ef9dc59fa63943b5afdb8c6f0aeac6f0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":381,
                      "y":171},
                    "size":{
                      "width":120,
                      "height":49}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/路线绑定/u71.png"}},
{
              "id":"de773e5c6c6f4017a7fcd8eb4ead6db4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":871,
                  "y":171},
                "size":{
                  "width":139,
                  "height":49}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dc36087b1d5d45d3836030098ea7ca90",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":871,
                      "y":171},
                    "size":{
                      "width":139,
                      "height":49}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/路线绑定/u79.png"}},
{
              "id":"dc5b698be838403b9dc4f0183d0f54e7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":626,
                  "y":0},
                "size":{
                  "width":122,
                  "height":47}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"289de94762a74f179e6c5abbcdd5c053",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":626,
                      "y":0},
                    "size":{
                      "width":122,
                      "height":47}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/字典管理/u17.png"}},
{
              "id":"08c3f50913844bcca1d8056d1959f8af",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":626,
                  "y":47},
                "size":{
                  "width":122,
                  "height":43}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"67d67508a33e4b6594c81efc144a34a2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":626,
                      "y":47},
                    "size":{
                      "width":122,
                      "height":43}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/字典管理/u39.png"}},
{
              "id":"f213b210dea74e6dad01500a7c771b76",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":626,
                  "y":90},
                "size":{
                  "width":122,
                  "height":39}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2fbeee4dad034633bc98ea1c9ad7d55f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":626,
                      "y":90},
                    "size":{
                      "width":122,
                      "height":39}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/字典管理/u61.png"}},
{
              "id":"26f85adef215482b81b7578645970992",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":626,
                  "y":129},
                "size":{
                  "width":122,
                  "height":42}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c12861f7905546c7b376c80afc64b321",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":626,
                      "y":129},
                    "size":{
                      "width":122,
                      "height":42}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/路线绑定/u59.png"}},
{
              "id":"d210140b39c6440b83e01cec012096f7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":626,
                  "y":171},
                "size":{
                  "width":122,
                  "height":49}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f68cf640b3224f368850069cd40b010b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":626,
                      "y":171},
                    "size":{
                      "width":122,
                      "height":49}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/路线绑定/u75.png"}},
{
              "id":"4de773bf20d043bfb9d35816135b853f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":748,
                  "y":0},
                "size":{
                  "width":123,
                  "height":47}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"730f1f0a302b418a95603505a2e92cf4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":748,
                      "y":0},
                    "size":{
                      "width":123,
                      "height":47}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/路线绑定/u13.png"}},
{
              "id":"5d76b37169c74976aa08d00b479605cb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":748,
                  "y":47},
                "size":{
                  "width":123,
                  "height":43}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"907121bf11384c0688a86673f5a3396c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":748,
                      "y":47},
                    "size":{
                      "width":123,
                      "height":43}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/路线绑定/u29.png"}},
{
              "id":"aa50a07231b24a288b392572889adad4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":748,
                  "y":90},
                "size":{
                  "width":123,
                  "height":39}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0836e331f75b4816ad8f26f41ddf9fec",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":748,
                      "y":90},
                    "size":{
                      "width":123,
                      "height":39}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/路线绑定/u45.png"}},
{
              "id":"d9867960232342269363a80ba64d734e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":748,
                  "y":129},
                "size":{
                  "width":123,
                  "height":42}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dda91427a6754092ad7ecfdd38a57bc5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":748,
                      "y":129},
                    "size":{
                      "width":123,
                      "height":42}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/路线绑定/u61.png"}},
{
              "id":"f176a63191af456b974f3c7e6c4c8a34",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":748,
                  "y":171},
                "size":{
                  "width":123,
                  "height":49}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3918ca424f204fc480d9a968cce9ba56",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":748,
                      "y":171},
                    "size":{
                      "width":123,
                      "height":49}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/路线绑定/u77.png"}},
{
              "id":"94a5a29de7814bd99ab18c24f1e639ba",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":501,
                  "y":0},
                "size":{
                  "width":125,
                  "height":47}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"749646ccbd054ec3a359dd2f2e1fafe3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":501,
                      "y":0},
                    "size":{
                      "width":125,
                      "height":47}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/路线绑定/u3.png"}},
{
              "id":"2761ec2376874ef3913fc0622ddea97f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":501,
                  "y":47},
                "size":{
                  "width":125,
                  "height":43}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dab7bbe855834ce78f80b1939644b644",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":501,
                      "y":47},
                    "size":{
                      "width":125,
                      "height":43}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/路线绑定/u19.png"}},
{
              "id":"3c65515a2fc447c4ae2aefdf85ea2717",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":501,
                  "y":90},
                "size":{
                  "width":125,
                  "height":39}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"91076f9d51884ad49c733879e72b6fe9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":501,
                      "y":90},
                    "size":{
                      "width":125,
                      "height":39}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/路线绑定/u35.png"}},
{
              "id":"cf435a9f9f7f4c239c93a601195e2e5e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":501,
                  "y":129},
                "size":{
                  "width":125,
                  "height":42}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7f0d534035a54898885b9873515e763e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":501,
                      "y":129},
                    "size":{
                      "width":125,
                      "height":42}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/路线绑定/u51.png"}},
{
              "id":"98b5f1a674674a35a6d0b6022c9f1a6f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":501,
                  "y":171},
                "size":{
                  "width":125,
                  "height":49}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a49975f0c18a4ba2958c02bf1e09f4e0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":501,
                      "y":171},
                    "size":{
                      "width":125,
                      "height":49}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/路线绑定/u67.png"}},
{
              "id":"58f56ebecac64eb6992c953775f14635",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "size":{
                  "width":126,
                  "height":47}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e18c145cf5824ae8b087c67a46ec8b0a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "size":{
                      "width":126,
                      "height":47}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/路线绑定/u1.png"}},
{
              "id":"d8ea7b06ecc6454580afd5c975f7826d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":47},
                "size":{
                  "width":126,
                  "height":43}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dd727fe4ecfc478987a96f603bb2c545",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":47},
                    "size":{
                      "width":126,
                      "height":43}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/路线绑定/u17.png"}},
{
              "id":"726e04c5915943f3a9fcd4a6a3b80344",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":90},
                "size":{
                  "width":126,
                  "height":39}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9f0c4e5335304ab1b46717f7d5e83954",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":90},
                    "size":{
                      "width":126,
                      "height":39}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/路线绑定/u33.png"}},
{
              "id":"a572cdc704594712b78cdd7b94318c24",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":129},
                "size":{
                  "width":126,
                  "height":42}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"67af9f5468214a5da626ef92b4dec274",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":129},
                    "size":{
                      "width":126,
                      "height":42}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/路线绑定/u49.png"}},
{
              "id":"358dd99631d047efaa229a997bc34987",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":171},
                "size":{
                  "width":126,
                  "height":49}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"98ac5fa87aaa479f84b8e536f822101a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":171},
                    "size":{
                      "width":126,
                      "height":49}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/路线绑定/u65.png"}}]},
{
          "id":"b52c07041d7c468ea07f50fcbc2fecf6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":842,
              "y":351},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c27b17164b704a97bb1ea543ce501155",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":842,
                  "y":351},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3987c28678c34962bbaa45b07e1bc9d8",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":892,
              "y":351},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
}},
{
          "id":"9b9dd70e4a634fd0aa35a3b4650d3c3e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":942,
              "y":351},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d446c793f944d79a8d98e2d0f47c1aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":942,
                  "y":351},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fd2aec37644a4634b7c01cc1b0d419fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0066FF,
                  "opacity":1}}},
            "location":{
              "x":780,
              "y":351},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eda9eb694cb5457aa5f47dec113b1c90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "underline":true,
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0066FF,
                      "opacity":1}}},
                "location":{
                  "x":780,
                  "y":351},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"c8ce5f343ddf47e0951a3eb630e2265a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "stateStyles":{
              "mouseOver":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0066FF,
                  "opacity":1}}},
            "location":{
              "x":977,
              "y":351},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd5d7099178c4043a59f83c0482d8004",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "stateStyles":{
                  "mouseOver":{
                    "underline":true,
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0066FF,
                      "opacity":1}}},
                "location":{
                  "x":977,
                  "y":351},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"f47487b313d947ffaf2acfdfc6c21640",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1040,
              "y":351},
            "size":{
              "width":42,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f6d69720e10418a97f191c9447a646d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1040,
                  "y":351},
                "size":{
                  "width":42,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"73a92fe67a8f4687ba7fae6756cb781c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":348},
            "size":{
              "width":282,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc903d8b76824ec083247e185e8fe32a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":348},
                "size":{
                  "width":282,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6a310439062f4bc1a5983be07c2a10a1",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":348},
            "size":{
              "width":72,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"26ece13ebf174098921c37cfb010b681",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":455,
              "y":348},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5be83a9b70314da7a893968f1f50219d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":455,
                  "y":348},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b4abbe444f554a38b681337a7e25db78",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":973,
              "y":180},
            "size":{
              "width":82,
              "height":20}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 是否关闭,<br>是,<br>否",
                      "objectsToFades":[{
                          "objectPath":["90a81d44d87e4a01a61936c479ce9484"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["6ef78baed1af4a63835c624a36027c97"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["0664069996074c8b89ce25536faa94b2"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"8120b4b8f39f49889cf656d58a754cfa",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":50},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 订单管理",
                      "target":{
                        "targetType":"page",
                        "url":"订单管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"90a81d44d87e4a01a61936c479ce9484",
          "label":"是否关闭",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":530,
              "y":142},
            "size":{
              "width":150,
              "height":165},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9690eec3fb844db0a76c9f02ef9c18ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":530,
                  "y":142},
                "size":{
                  "width":150,
                  "height":165},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/车辆基本信息/是否删除_u181.png"}},
{
          "id":"6ef78baed1af4a63835c624a36027c97",
          "label":"是",
          "type":"button",
          "styleType":"button",
          "visible":false,
          "style":{
            "location":{
              "x":555,
              "y":217.5},
            "size":{
              "width":100,
              "height":25},
            "visible":false},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 订单管理",
                      "target":{
                        "targetType":"page",
                        "url":"订单管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"0664069996074c8b89ce25536faa94b2",
          "label":"否",
          "type":"button",
          "styleType":"button",
          "visible":false,
          "style":{
            "location":{
              "x":555,
              "y":262.5},
            "size":{
              "width":100,
              "height":25},
            "visible":false},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 是否关闭,<br>是,<br>否",
                      "objectsToFades":[{
                          "objectPath":["90a81d44d87e4a01a61936c479ce9484"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["6ef78baed1af4a63835c624a36027c97"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["0664069996074c8b89ce25536faa94b2"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "3118754155f14a63bf5b671011f6b453":{
      "scriptId":"u0"},
    "58f56ebecac64eb6992c953775f14635":{
      "scriptId":"u1"},
    "e18c145cf5824ae8b087c67a46ec8b0a":{
      "scriptId":"u2"},
    "cc0ccafe84dd48efa710e98c34c4a52a":{
      "scriptId":"u3"},
    "f34ca41167e4448593c85ea853c89857":{
      "scriptId":"u4"},
    "463b0aaf0e2347b59f13b2f6d5746be2":{
      "scriptId":"u5"},
    "197ee74a5c784c14801dfffc0de48be1":{
      "scriptId":"u6"},
    "4a05d34cda1841d69ef2459d26ea1064":{
      "scriptId":"u7"},
    "4ede19b5e4a24034ba9a194a6a9f8650":{
      "scriptId":"u8"},
    "94a5a29de7814bd99ab18c24f1e639ba":{
      "scriptId":"u9"},
    "749646ccbd054ec3a359dd2f2e1fafe3":{
      "scriptId":"u10"},
    "dc5b698be838403b9dc4f0183d0f54e7":{
      "scriptId":"u11"},
    "289de94762a74f179e6c5abbcdd5c053":{
      "scriptId":"u12"},
    "4de773bf20d043bfb9d35816135b853f":{
      "scriptId":"u13"},
    "730f1f0a302b418a95603505a2e92cf4":{
      "scriptId":"u14"},
    "6066c7e3dac14592b29a81689ce42bee":{
      "scriptId":"u15"},
    "0474e4cdfd4747c88d1232d640ac8b29":{
      "scriptId":"u16"},
    "d8ea7b06ecc6454580afd5c975f7826d":{
      "scriptId":"u17"},
    "dd727fe4ecfc478987a96f603bb2c545":{
      "scriptId":"u18"},
    "4913e10e56114782ba134032c6943a8b":{
      "scriptId":"u19"},
    "5d5cac39537243f3a18a866d409f4c64":{
      "scriptId":"u20"},
    "10cf53ac24684221bd0d5e45a323edd8":{
      "scriptId":"u21"},
    "bd5f9e138ff049df800651478afb12c2":{
      "scriptId":"u22"},
    "05ef279a7a99433a90d191915c62b3e6":{
      "scriptId":"u23"},
    "7c6367aa690a4902a15304d5f5d77601":{
      "scriptId":"u24"},
    "2761ec2376874ef3913fc0622ddea97f":{
      "scriptId":"u25"},
    "dab7bbe855834ce78f80b1939644b644":{
      "scriptId":"u26"},
    "08c3f50913844bcca1d8056d1959f8af":{
      "scriptId":"u27"},
    "67d67508a33e4b6594c81efc144a34a2":{
      "scriptId":"u28"},
    "5d76b37169c74976aa08d00b479605cb":{
      "scriptId":"u29"},
    "907121bf11384c0688a86673f5a3396c":{
      "scriptId":"u30"},
    "63df18602b564614b767281d9e7a1402":{
      "scriptId":"u31"},
    "682b79156b2e4d65a1a9bcb2512c8e23":{
      "scriptId":"u32"},
    "726e04c5915943f3a9fcd4a6a3b80344":{
      "scriptId":"u33"},
    "9f0c4e5335304ab1b46717f7d5e83954":{
      "scriptId":"u34"},
    "c9ddb1be34274bceb4203cf76e0752c5":{
      "scriptId":"u35"},
    "9d8b6f77c653494684f227ef9c896c77":{
      "scriptId":"u36"},
    "72f4cc1221d446359998a1364edac4ea":{
      "scriptId":"u37"},
    "e6a35bd920b3431f8c2d8151be2fac24":{
      "scriptId":"u38"},
    "ab3f1da64ad649fe811b2dfbeda59416":{
      "scriptId":"u39"},
    "445d023de255400da8dd12da0812a20d":{
      "scriptId":"u40"},
    "3c65515a2fc447c4ae2aefdf85ea2717":{
      "scriptId":"u41"},
    "91076f9d51884ad49c733879e72b6fe9":{
      "scriptId":"u42"},
    "f213b210dea74e6dad01500a7c771b76":{
      "scriptId":"u43"},
    "2fbeee4dad034633bc98ea1c9ad7d55f":{
      "scriptId":"u44"},
    "aa50a07231b24a288b392572889adad4":{
      "scriptId":"u45"},
    "0836e331f75b4816ad8f26f41ddf9fec":{
      "scriptId":"u46"},
    "80814bc370ed4a0d956839993d5bff3b":{
      "scriptId":"u47"},
    "3470a6928f9f4501b9e2c4c64aeb6009":{
      "scriptId":"u48"},
    "a572cdc704594712b78cdd7b94318c24":{
      "scriptId":"u49"},
    "67af9f5468214a5da626ef92b4dec274":{
      "scriptId":"u50"},
    "2c502a4d9a0440e89a7c08c393916b62":{
      "scriptId":"u51"},
    "4a45d65079c94d1ca33ab49a8d0288aa":{
      "scriptId":"u52"},
    "3afb33f97465432291704cff9cb0dc03":{
      "scriptId":"u53"},
    "fec7b588f1c344bcb60755ee282e5097":{
      "scriptId":"u54"},
    "ef69fee0aa3a45a5802d01fa03de9ab1":{
      "scriptId":"u55"},
    "92f5397414c74d91b3dcd72a0971ff1e":{
      "scriptId":"u56"},
    "cf435a9f9f7f4c239c93a601195e2e5e":{
      "scriptId":"u57"},
    "7f0d534035a54898885b9873515e763e":{
      "scriptId":"u58"},
    "26f85adef215482b81b7578645970992":{
      "scriptId":"u59"},
    "c12861f7905546c7b376c80afc64b321":{
      "scriptId":"u60"},
    "d9867960232342269363a80ba64d734e":{
      "scriptId":"u61"},
    "dda91427a6754092ad7ecfdd38a57bc5":{
      "scriptId":"u62"},
    "ca1bd5ebd7054187a9764d40d5c1396a":{
      "scriptId":"u63"},
    "0e85f2c3f67247efb2d87b26f89fe8c4":{
      "scriptId":"u64"},
    "358dd99631d047efaa229a997bc34987":{
      "scriptId":"u65"},
    "98ac5fa87aaa479f84b8e536f822101a":{
      "scriptId":"u66"},
    "3c92c8e14e99405c8f585ec021eb822a":{
      "scriptId":"u67"},
    "b3489ad35c2e43d999e99e34562a6d90":{
      "scriptId":"u68"},
    "3e8429a03254483d919110f9358f4429":{
      "scriptId":"u69"},
    "2d0b54ef1b764b06a1654f8004c96d55":{
      "scriptId":"u70"},
    "4e1513b17715494bb82a333d6eca863e":{
      "scriptId":"u71"},
    "ef9dc59fa63943b5afdb8c6f0aeac6f0":{
      "scriptId":"u72"},
    "98b5f1a674674a35a6d0b6022c9f1a6f":{
      "scriptId":"u73"},
    "a49975f0c18a4ba2958c02bf1e09f4e0":{
      "scriptId":"u74"},
    "d210140b39c6440b83e01cec012096f7":{
      "scriptId":"u75"},
    "f68cf640b3224f368850069cd40b010b":{
      "scriptId":"u76"},
    "f176a63191af456b974f3c7e6c4c8a34":{
      "scriptId":"u77"},
    "3918ca424f204fc480d9a968cce9ba56":{
      "scriptId":"u78"},
    "de773e5c6c6f4017a7fcd8eb4ead6db4":{
      "scriptId":"u79"},
    "dc36087b1d5d45d3836030098ea7ca90":{
      "scriptId":"u80"},
    "b52c07041d7c468ea07f50fcbc2fecf6":{
      "scriptId":"u81"},
    "c27b17164b704a97bb1ea543ce501155":{
      "scriptId":"u82"},
    "3987c28678c34962bbaa45b07e1bc9d8":{
      "scriptId":"u83"},
    "9b9dd70e4a634fd0aa35a3b4650d3c3e":{
      "scriptId":"u84"},
    "9d446c793f944d79a8d98e2d0f47c1aa":{
      "scriptId":"u85"},
    "fd2aec37644a4634b7c01cc1b0d419fe":{
      "scriptId":"u86"},
    "eda9eb694cb5457aa5f47dec113b1c90":{
      "scriptId":"u87"},
    "c8ce5f343ddf47e0951a3eb630e2265a":{
      "scriptId":"u88"},
    "fd5d7099178c4043a59f83c0482d8004":{
      "scriptId":"u89"},
    "f47487b313d947ffaf2acfdfc6c21640":{
      "scriptId":"u90"},
    "7f6d69720e10418a97f191c9447a646d":{
      "scriptId":"u91"},
    "73a92fe67a8f4687ba7fae6756cb781c":{
      "scriptId":"u92"},
    "dc903d8b76824ec083247e185e8fe32a":{
      "scriptId":"u93"},
    "6a310439062f4bc1a5983be07c2a10a1":{
      "scriptId":"u94"},
    "26ece13ebf174098921c37cfb010b681":{
      "scriptId":"u95"},
    "5be83a9b70314da7a893968f1f50219d":{
      "scriptId":"u96"},
    "b4abbe444f554a38b681337a7e25db78":{
      "scriptId":"u97"},
    "8120b4b8f39f49889cf656d58a754cfa":{
      "scriptId":"u98"},
    "90a81d44d87e4a01a61936c479ce9484":{
      "scriptId":"u99"},
    "9690eec3fb844db0a76c9f02ef9c18ca":{
      "scriptId":"u100"},
    "6ef78baed1af4a63835c624a36027c97":{
      "scriptId":"u101"},
    "0664069996074c8b89ce25536faa94b2":{
      "scriptId":"u102"}}});