$axure.loadCurrentPage({
  "url":"实时监控.html",
  "generationDate":new Date(1557741992006.03),
  "isCanvasEnabled":false,
  "variables":["yys_name",
"car_chePai_card",
"car_chePai_color",
"car_leixing",
"car_ICcard",
"yy_leixing",
"car_InterNet_leixing",
"car_jingYingLuXian",
"car_zhuangTai",
"quYu",
"phone",
"mail",
"name"],
  "page":{
    "packageId":"95e78486cdc44db7aa27e278a79c677f",
    "type":"Axure:Page",
    "name":"实时监控",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"abd277a9155941a2964e16334481f752",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":120},
            "size":{
              "width":1325,
              "height":432},
            "borderWidth":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba8591293d814fae89aebe8253df2b96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":120},
                "size":{
                  "width":1325,
                  "height":432},
                "borderWidth":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/实时监控/u0.png"}},
{
          "id":"a8f4df9e467a43f3ad6efffcb5079577",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":620},
            "size":{
              "width":1100,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8decc9a8c19f4fff9e515178e8eb94dc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "size":{
                  "width":100,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"68fa69e0fea945f4aa4d4b564a0401b0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "size":{
                      "width":100,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/实时监控/u3.png"}},
{
              "id":"afc3ace6169a42b3bb26789522ab28e3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e1bea410ac0443829c63cc67cc57bcec",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/实时监控/u25.png"}},
{
              "id":"9f7d9f1e2961427c85b7c44fb7133365",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"92b8a0cc2e504494936594bba3a3b31d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/运营商管理/u58.png"}},
{
              "id":"7b2fdc8ae1f14ed9bb14d6b4dc8d2802",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"678770b94c7d4e1c93ee111a40e2ad8a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/实时监控/u3.png"}},
{
              "id":"2d87ed526d9e4080ad6fd6607c94250a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4de955c16b1047ec8b401a1843a9f7d2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/实时监控/u25.png"}},
{
              "id":"67713c203741432bb0c0bef055a3394d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0232918f3ef54b8c869c1c184e10108b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/运营商管理/u58.png"}},
{
              "id":"7ef72352e4fd46049a190668fbd4569e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":200,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4554ee05104244bc8492ec58f2e44e24",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/实时监控/u3.png"}},
{
              "id":"ccfe27ae4f5f4c53b5316e0629d336cc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ada003b9d3cf4aada493b22291e7c8f3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/实时监控/u25.png"}},
{
              "id":"d166763d0fcd48b29719e1326b031cd4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1a342e093d2e4e04b5efb9f534b59cc3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/运营商管理/u58.png"}},
{
              "id":"145caa1890314f28aea551d37df6494a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":300,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fede846d6439481090fdfff1ba5cbd2a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/实时监控/u3.png"}},
{
              "id":"0596016d49ca4d0d8bf77dbc1fd9221e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c036cdd0ef3c417c879e259592b0e3e6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/实时监控/u25.png"}},
{
              "id":"5044299c2487412dbb7e17a319e97716",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8c254b5db11b4c99be7630d7070a5476",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/运营商管理/u58.png"}},
{
              "id":"bab961ce382642cf9af063f5fe3cd1e8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":400,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5dd01c4ac27a4d5ebf4618c15da546ba",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":400,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/实时监控/u3.png"}},
{
              "id":"244735caddb548dbbfdd031cc58fa40c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":400,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3c3e489b42014591994a3e7c0c1a935e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/实时监控/u25.png"}},
{
              "id":"631d31aebf8645388d06e96b6fb2ec23",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":400,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e2c2813d629c4fe5af9558b8322a9291",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/运营商管理/u58.png"}},
{
              "id":"62d4eaa9dbbf458e98cdaf926e366f4d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":500,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"edd05084894d4f8eb4ec126c54739afd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":500,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/实时监控/u3.png"}},
{
              "id":"0086934b2f1542fcb0f39bb612bdf88f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":500,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"970ece27177945be8153cda262470de9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":500,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/实时监控/u25.png"}},
{
              "id":"a897123910724601a409da214a68ce9d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":500,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a24642c3e5714361ada5ae6acf867636",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":500,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/运营商管理/u58.png"}},
{
              "id":"293b0dba4c2e4c9395235df824319486",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":600,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b64dd98f738e49a28d52f4426df5108a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":600,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/实时监控/u3.png"}},
{
              "id":"20d5570e8dd54b0e8a2ee67582eb0d8d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":600,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2f5970db4f3d4fe5a4486f9b58287a9f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":600,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/实时监控/u25.png"}},
{
              "id":"e33b610d2f1d4b148624874119d9f19f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":600,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9dbce2608a2d43deb882c747f71adde0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":600,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/运营商管理/u58.png"}},
{
              "id":"b9d6146931494fe68b1a100ac9362cbf",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":700,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"472137c3dea04ebc86bc1dbdd34efbdf",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":700,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/实时监控/u3.png"}},
{
              "id":"e28f2e22898b4fe8840ea8ef033381d6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":700,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e34e281f93ce45f7884b64dd6aaf5302",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":700,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/实时监控/u25.png"}},
{
              "id":"db4fdaaa77684430b4145d3801c2cf32",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":700,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9a1ec720db08475f962aedecd9fd6c15",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":700,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/运营商管理/u58.png"}},
{
              "id":"9d357f430dda4115aeb94348447c073a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":800,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b8b3669b5c334bce8af0f6f80bff18e2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":800,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/实时监控/u3.png"}},
{
              "id":"7baba1d79c90443dbd111b01a8eab3dd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":800,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e7f763301a0f4c88b6cc6f8d626e353b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":800,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/实时监控/u25.png"}},
{
              "id":"46a11f42b5974e03b621fd00739d74d6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":800,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"184a3e99ec1b44a59ca86e58fe873459",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":800,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/运营商管理/u58.png"}},
{
              "id":"04eb56f1e15b42e29670587001872691",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":900,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ff1c68d32c4247cdbc6f1754b1de75f6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":900,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/实时监控/u3.png"}},
{
              "id":"4118a547148d42f787d239c76821c84f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":900,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"63bb7b56222044baa151a7a2a5f5371d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":900,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/实时监控/u25.png"}},
{
              "id":"1f086322433549b590664383db458ac4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":900,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f98b870b75da436ca9271da716531aae",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":900,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/运营商管理/u58.png"}},
{
              "id":"619a0d9b19c74bee89cdf59bcac790e2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":1000,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b493007f7ce04595a73053ba7242a55b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":1000,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/实时监控/u23.png"}},
{
              "id":"c123daae533a40e592169d3a179bf554",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":1000,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"80a5f247245d44ae87162ef99d14d693",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":1000,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/实时监控/u45.png"}},
{
              "id":"0d37c2c428f2439d8f9a0e8faa9effbf",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":1000,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"eda6115f8090448bbc83dd73e8c142b9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":1000,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备基本信息管理/u82.png"}}]},
{
          "id":"17d80eaf0450442cafcbd08cd2b91155",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1160,
              "y":570},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f16d668af72e4c39bb727193ea358bc8",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1030,
              "y":570},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b08d4ad1d1cc4f8586494fce599450b6",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":900,
              "y":570},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"7721864c84894455a1db7c5080ab2fb6",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":574.5},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6060a032c8fd446e86d6a02e72be171c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":574.5},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"2a1ac49d3829472193a20a0e1853a779",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":574},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c65a392ad38141e799a7c296879ec916",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":574},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"0fb9101b2043460fa6395956c6b75002",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":574},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be2fffd2974841aebd7b66692b784065",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":574},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"4e2bd33102e7419e9fdbd5da850ad319",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":571},
            "size":{
              "width":150,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"471f1cfc15534585a95625c3fa201606",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":580,
              "y":571},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"90566c8d654d4750b17fadeb5d8554d2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":518,
              "y":574},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08b4e269dfb54810ac14934c0ba64f3d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":518,
                  "y":574},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "abd277a9155941a2964e16334481f752":{
      "scriptId":"u0"},
    "ba8591293d814fae89aebe8253df2b96":{
      "scriptId":"u1"},
    "a8f4df9e467a43f3ad6efffcb5079577":{
      "scriptId":"u2"},
    "8decc9a8c19f4fff9e515178e8eb94dc":{
      "scriptId":"u3"},
    "68fa69e0fea945f4aa4d4b564a0401b0":{
      "scriptId":"u4"},
    "7b2fdc8ae1f14ed9bb14d6b4dc8d2802":{
      "scriptId":"u5"},
    "678770b94c7d4e1c93ee111a40e2ad8a":{
      "scriptId":"u6"},
    "7ef72352e4fd46049a190668fbd4569e":{
      "scriptId":"u7"},
    "4554ee05104244bc8492ec58f2e44e24":{
      "scriptId":"u8"},
    "145caa1890314f28aea551d37df6494a":{
      "scriptId":"u9"},
    "fede846d6439481090fdfff1ba5cbd2a":{
      "scriptId":"u10"},
    "bab961ce382642cf9af063f5fe3cd1e8":{
      "scriptId":"u11"},
    "5dd01c4ac27a4d5ebf4618c15da546ba":{
      "scriptId":"u12"},
    "62d4eaa9dbbf458e98cdaf926e366f4d":{
      "scriptId":"u13"},
    "edd05084894d4f8eb4ec126c54739afd":{
      "scriptId":"u14"},
    "293b0dba4c2e4c9395235df824319486":{
      "scriptId":"u15"},
    "b64dd98f738e49a28d52f4426df5108a":{
      "scriptId":"u16"},
    "b9d6146931494fe68b1a100ac9362cbf":{
      "scriptId":"u17"},
    "472137c3dea04ebc86bc1dbdd34efbdf":{
      "scriptId":"u18"},
    "9d357f430dda4115aeb94348447c073a":{
      "scriptId":"u19"},
    "b8b3669b5c334bce8af0f6f80bff18e2":{
      "scriptId":"u20"},
    "04eb56f1e15b42e29670587001872691":{
      "scriptId":"u21"},
    "ff1c68d32c4247cdbc6f1754b1de75f6":{
      "scriptId":"u22"},
    "619a0d9b19c74bee89cdf59bcac790e2":{
      "scriptId":"u23"},
    "b493007f7ce04595a73053ba7242a55b":{
      "scriptId":"u24"},
    "afc3ace6169a42b3bb26789522ab28e3":{
      "scriptId":"u25"},
    "e1bea410ac0443829c63cc67cc57bcec":{
      "scriptId":"u26"},
    "2d87ed526d9e4080ad6fd6607c94250a":{
      "scriptId":"u27"},
    "4de955c16b1047ec8b401a1843a9f7d2":{
      "scriptId":"u28"},
    "ccfe27ae4f5f4c53b5316e0629d336cc":{
      "scriptId":"u29"},
    "ada003b9d3cf4aada493b22291e7c8f3":{
      "scriptId":"u30"},
    "0596016d49ca4d0d8bf77dbc1fd9221e":{
      "scriptId":"u31"},
    "c036cdd0ef3c417c879e259592b0e3e6":{
      "scriptId":"u32"},
    "244735caddb548dbbfdd031cc58fa40c":{
      "scriptId":"u33"},
    "3c3e489b42014591994a3e7c0c1a935e":{
      "scriptId":"u34"},
    "0086934b2f1542fcb0f39bb612bdf88f":{
      "scriptId":"u35"},
    "970ece27177945be8153cda262470de9":{
      "scriptId":"u36"},
    "20d5570e8dd54b0e8a2ee67582eb0d8d":{
      "scriptId":"u37"},
    "2f5970db4f3d4fe5a4486f9b58287a9f":{
      "scriptId":"u38"},
    "e28f2e22898b4fe8840ea8ef033381d6":{
      "scriptId":"u39"},
    "e34e281f93ce45f7884b64dd6aaf5302":{
      "scriptId":"u40"},
    "7baba1d79c90443dbd111b01a8eab3dd":{
      "scriptId":"u41"},
    "e7f763301a0f4c88b6cc6f8d626e353b":{
      "scriptId":"u42"},
    "4118a547148d42f787d239c76821c84f":{
      "scriptId":"u43"},
    "63bb7b56222044baa151a7a2a5f5371d":{
      "scriptId":"u44"},
    "c123daae533a40e592169d3a179bf554":{
      "scriptId":"u45"},
    "80a5f247245d44ae87162ef99d14d693":{
      "scriptId":"u46"},
    "9f7d9f1e2961427c85b7c44fb7133365":{
      "scriptId":"u47"},
    "92b8a0cc2e504494936594bba3a3b31d":{
      "scriptId":"u48"},
    "67713c203741432bb0c0bef055a3394d":{
      "scriptId":"u49"},
    "0232918f3ef54b8c869c1c184e10108b":{
      "scriptId":"u50"},
    "d166763d0fcd48b29719e1326b031cd4":{
      "scriptId":"u51"},
    "1a342e093d2e4e04b5efb9f534b59cc3":{
      "scriptId":"u52"},
    "5044299c2487412dbb7e17a319e97716":{
      "scriptId":"u53"},
    "8c254b5db11b4c99be7630d7070a5476":{
      "scriptId":"u54"},
    "631d31aebf8645388d06e96b6fb2ec23":{
      "scriptId":"u55"},
    "e2c2813d629c4fe5af9558b8322a9291":{
      "scriptId":"u56"},
    "a897123910724601a409da214a68ce9d":{
      "scriptId":"u57"},
    "a24642c3e5714361ada5ae6acf867636":{
      "scriptId":"u58"},
    "e33b610d2f1d4b148624874119d9f19f":{
      "scriptId":"u59"},
    "9dbce2608a2d43deb882c747f71adde0":{
      "scriptId":"u60"},
    "db4fdaaa77684430b4145d3801c2cf32":{
      "scriptId":"u61"},
    "9a1ec720db08475f962aedecd9fd6c15":{
      "scriptId":"u62"},
    "46a11f42b5974e03b621fd00739d74d6":{
      "scriptId":"u63"},
    "184a3e99ec1b44a59ca86e58fe873459":{
      "scriptId":"u64"},
    "1f086322433549b590664383db458ac4":{
      "scriptId":"u65"},
    "f98b870b75da436ca9271da716531aae":{
      "scriptId":"u66"},
    "0d37c2c428f2439d8f9a0e8faa9effbf":{
      "scriptId":"u67"},
    "eda6115f8090448bbc83dd73e8c142b9":{
      "scriptId":"u68"},
    "17d80eaf0450442cafcbd08cd2b91155":{
      "scriptId":"u69"},
    "f16d668af72e4c39bb727193ea358bc8":{
      "scriptId":"u70"},
    "b08d4ad1d1cc4f8586494fce599450b6":{
      "scriptId":"u71"},
    "7721864c84894455a1db7c5080ab2fb6":{
      "scriptId":"u72"},
    "6060a032c8fd446e86d6a02e72be171c":{
      "scriptId":"u73"},
    "2a1ac49d3829472193a20a0e1853a779":{
      "scriptId":"u74"},
    "c65a392ad38141e799a7c296879ec916":{
      "scriptId":"u75"},
    "0fb9101b2043460fa6395956c6b75002":{
      "scriptId":"u76"},
    "be2fffd2974841aebd7b66692b784065":{
      "scriptId":"u77"},
    "4e2bd33102e7419e9fdbd5da850ad319":{
      "scriptId":"u78"},
    "471f1cfc15534585a95625c3fa201606":{
      "scriptId":"u79"},
    "90566c8d654d4750b17fadeb5d8554d2":{
      "scriptId":"u80"},
    "08b4e269dfb54810ac14934c0ba64f3d":{
      "scriptId":"u81"}}});