$axure.loadCurrentPage({
  "url":"车辆信息新增页面.html",
  "generationDate":new Date(1557742047623.45),
  "isCanvasEnabled":false,
  "variables":["yys_name",
"car_chePai_card",
"car_chePai_color",
"car_leixing",
"car_ICcard",
"yy_leixing",
"car_InterNet_leixing",
"car_jingYingLuXian",
"car_zhuangTai",
"quYu",
"phone",
"mail",
"name"],
  "page":{
    "packageId":"cc24ea19451c47578e5e88bd51272062",
    "type":"Axure:Page",
    "name":"车辆信息新增页面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
      "onLoad":{
        "description":"OnLoad",
        "cases":[{
            "description":"用例 1",
            "isNewIfGroup":false,
            "actions":[{
                "action":"fadeWidget",
                "description":"显示/隐藏部件",
                "objectsToFades":[]}]}]}},
    "diagram":{
      "objects":[{
          "id":"3ecd3dd22a1642ab80e89acaa6156fdc",
          "label":"编辑_弹框",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":350,
              "height":425}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f386831158cc4248aff25f7e9557aece",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":350,
                  "height":425}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/车辆信息新增页面/编辑_弹框_u0.png"}},
{
          "id":"b952c7aaec12404ab24737026f6aa3db",
          "label":"新增_",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":42,
              "y":74},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6de8d1a0b0aa4562a3ba5c20667e2fd0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":42,
                  "y":74},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5ebe989ae80243b28a74a0cfa3b7e4f0",
          "label":"新增_",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":42,
              "y":110},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12cec4ef34d341aca638474f48741528",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":42,
                  "y":110},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"171cd4ed5aeb4f28a6d4442c69f87e75",
          "label":"新增_",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":42,
              "y":144},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79871af34ac14f5394fa77364f661eec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":42,
                  "y":144},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1cc7af41a8a74efdafa95cb717a3803d",
          "label":"新增_",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":42,
              "y":180},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bda58752249149c9996101ea5dbcc4b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":42,
                  "y":180},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"44daa50236594308892360ee9cc7f847",
          "label":"新增_",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":42,
              "y":214},
            "size":{
              "width":39,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11d3781c2fa244608d8b265623f23a49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":42,
                  "y":214},
                "size":{
                  "width":39,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c8e4a3ce59e847dfba011fec3b3f18cd",
          "label":"新增_",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":42,
              "y":250},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b2e1b1a9da54d5f85dc8ce0d5f63dd0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":42,
                  "y":250},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"566cecabeaeb446a9a10a091695f0cb6",
          "label":"新增_",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":42,
              "y":284},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"870a1fca99934bdfa952e6be651ca29e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":42,
                  "y":284},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"919e2a7014d747e8b19b150505a05382",
          "label":"新增_",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":42,
              "y":320},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38412ba1b44b46b68377cbe4442e64db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":42,
                  "y":320},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7b86c4a8e861426588a895bacf018de2",
          "label":"新增_",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":42,
              "y":354},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"273aaaf037214a2b9eb8d9d2fe45d345",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":42,
                  "y":354},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fe3819a4823344609f13195b5dbfa09f",
          "label":"新增_车牌号",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":128,
              "y":104},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b0b3d9676a404b4aa253ff1687b2e471",
          "label":"新增_IC卡号",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":128,
              "y":210},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"96da39ba3bbb41d190561ce81d3a6eab",
          "label":"新增_保存",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":395},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"若某项为空<br> (If 部件文字 新增_车牌号 = &quot;&quot; 或 部件文字 新增_IC卡号 = &quot;&quot; 或 选中项值 新增_运营商名称 = &quot;请选择&quot; 或 选中项值 新增_车牌颜色 = &quot;请选择&quot; 或 选中项值 新增_营运类型 = &quot;请选择&quot; 或 选中项值 新增_车辆类型 = &quot;全部&quot; 或 选中项值 新增_终端分类 = &quot;请选择&quot; 或 选中项值 新增_经营路线 = &quot;请选择&quot; 或 选中项值 新增_车辆状态 = &quot;请选择&quot; 或 选中项值 新增_所属区域 = &quot;请选择&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"||",
                    "leftExpr":{
                      "exprType":"binaryOp",
                      "op":"==",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetWidgetText",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["fe3819a4823344609f13195b5dbfa09f"]}]},
                      "rightExpr":{
                        "exprType":"stringLiteral",
                        "value":"",
                        "stos":[]}},
                    "rightExpr":{
                      "exprType":"binaryOp",
                      "op":"||",
                      "leftExpr":{
                        "exprType":"binaryOp",
                        "op":"==",
                        "leftExpr":{
                          "exprType":"fcall",
                          "functionName":"GetWidgetText",
                          "arguments":[{
                              "exprType":"pathLiteral",
                              "isThis":false,
                              "isFocused":false,
                              "isTarget":false,
                              "value":["b0b3d9676a404b4aa253ff1687b2e471"]}]},
                        "rightExpr":{
                          "exprType":"stringLiteral",
                          "value":"",
                          "stos":[]}},
                      "rightExpr":{
                        "exprType":"binaryOp",
                        "op":"||",
                        "leftExpr":{
                          "exprType":"binaryOp",
                          "op":"==",
                          "leftExpr":{
                            "exprType":"fcall",
                            "functionName":"GetSelectedOption",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["3f04c9334b254c21bc5aab58ca7a504d"]}]},
                          "rightExpr":{
                            "exprType":"stringLiteral",
                            "value":"请选择",
                            "stos":[]}},
                        "rightExpr":{
                          "exprType":"binaryOp",
                          "op":"||",
                          "leftExpr":{
                            "exprType":"binaryOp",
                            "op":"==",
                            "leftExpr":{
                              "exprType":"fcall",
                              "functionName":"GetSelectedOption",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["6df73869138d4d468f4ff229f2fe35e2"]}]},
                            "rightExpr":{
                              "exprType":"stringLiteral",
                              "value":"请选择",
                              "stos":[]}},
                          "rightExpr":{
                            "exprType":"binaryOp",
                            "op":"||",
                            "leftExpr":{
                              "exprType":"binaryOp",
                              "op":"==",
                              "leftExpr":{
                                "exprType":"fcall",
                                "functionName":"GetSelectedOption",
                                "arguments":[{
                                    "exprType":"pathLiteral",
                                    "isThis":false,
                                    "isFocused":false,
                                    "isTarget":false,
                                    "value":["eb820356548b4febb6e5aa2b81b5f063"]}]},
                              "rightExpr":{
                                "exprType":"stringLiteral",
                                "value":"请选择",
                                "stos":[]}},
                            "rightExpr":{
                              "exprType":"binaryOp",
                              "op":"||",
                              "leftExpr":{
                                "exprType":"binaryOp",
                                "op":"==",
                                "leftExpr":{
                                  "exprType":"fcall",
                                  "functionName":"GetSelectedOption",
                                  "arguments":[{
                                      "exprType":"pathLiteral",
                                      "isThis":false,
                                      "isFocused":false,
                                      "isTarget":false,
                                      "value":["0ce2e2bede8b4339b8ff03ce4eb6fb9c"]}]},
                                "rightExpr":{
                                  "exprType":"stringLiteral",
                                  "value":"全部",
                                  "stos":[]}},
                              "rightExpr":{
                                "exprType":"binaryOp",
                                "op":"||",
                                "leftExpr":{
                                  "exprType":"binaryOp",
                                  "op":"==",
                                  "leftExpr":{
                                    "exprType":"fcall",
                                    "functionName":"GetSelectedOption",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":false,
                                        "isFocused":false,
                                        "isTarget":false,
                                        "value":["2e2a010e431e41029350a1e650f90acb"]}]},
                                  "rightExpr":{
                                    "exprType":"stringLiteral",
                                    "value":"请选择",
                                    "stos":[]}},
                                "rightExpr":{
                                  "exprType":"binaryOp",
                                  "op":"||",
                                  "leftExpr":{
                                    "exprType":"binaryOp",
                                    "op":"==",
                                    "leftExpr":{
                                      "exprType":"fcall",
                                      "functionName":"GetSelectedOption",
                                      "arguments":[{
                                          "exprType":"pathLiteral",
                                          "isThis":false,
                                          "isFocused":false,
                                          "isTarget":false,
                                          "value":["37990de872714ee5b6a6931d9b667573"]}]},
                                    "rightExpr":{
                                      "exprType":"stringLiteral",
                                      "value":"请选择",
                                      "stos":[]}},
                                  "rightExpr":{
                                    "exprType":"binaryOp",
                                    "op":"||",
                                    "leftExpr":{
                                      "exprType":"binaryOp",
                                      "op":"==",
                                      "leftExpr":{
                                        "exprType":"fcall",
                                        "functionName":"GetSelectedOption",
                                        "arguments":[{
                                            "exprType":"pathLiteral",
                                            "isThis":false,
                                            "isFocused":false,
                                            "isTarget":false,
                                            "value":["fcd4f51386b148f7802e5421751ee145"]}]},
                                      "rightExpr":{
                                        "exprType":"stringLiteral",
                                        "value":"请选择",
                                        "stos":[]}},
                                    "rightExpr":{
                                      "exprType":"binaryOp",
                                      "op":"==",
                                      "leftExpr":{
                                        "exprType":"fcall",
                                        "functionName":"GetSelectedOption",
                                        "arguments":[{
                                            "exprType":"pathLiteral",
                                            "isThis":false,
                                            "isFocused":false,
                                            "isTarget":false,
                                            "value":["03c09b38fc9b452bbb718e9006097958"]}]},
                                      "rightExpr":{
                                        "exprType":"stringLiteral",
                                        "value":"请选择",
                                        "stos":[]}}}}}}}}}}},
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 新增未填提示",
                      "objectsToFades":[{
                          "objectPath":["70a9ab87d63846a2a6a35b1a1bec5597"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]},
{
                  "description":"若全有<br> (Else If True)",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 变量 yys_name = 选中项值 新增_运营商名称, 且<br> 变量 car_chePai_card = 部件文字 新增_车牌号, 且<br> 变量 car_chePai_color = 选中项值 新增_车牌颜色, 且<br> 变量 car_leixing = 选中项值 新增_车辆类型, 且<br> 变量 car_ICcard = 部件文字 新增_IC卡号, 且<br> 变量 yy_leixing = 选中项值 新增_营运类型, 且<br> 变量 car_InterNet_leixing = 选中项值 新增_终端分类, 且<br> 变量 car_jingYingLuXian = 选中项值 新增_经营路线, 且<br> 变量 car_zhuangTai = 选中项值 新增_车辆状态, 且<br> 变量 quYu = 选中项值 新增_所属区域",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"yys_name"},
{
                                "exprType":"fcall",
                                "functionName":"GetSelectedOption",
                                "arguments":[{
                                    "exprType":"pathLiteral",
                                    "isThis":false,
                                    "isFocused":false,
                                    "isTarget":false,
                                    "value":["3f04c9334b254c21bc5aab58ca7a504d"]}]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"car_chePai_card"},
{
                                "exprType":"fcall",
                                "functionName":"GetWidgetText",
                                "arguments":[{
                                    "exprType":"pathLiteral",
                                    "isThis":false,
                                    "isFocused":false,
                                    "isTarget":false,
                                    "value":["fe3819a4823344609f13195b5dbfa09f"]}]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"car_chePai_color"},
{
                                "exprType":"fcall",
                                "functionName":"GetSelectedOption",
                                "arguments":[{
                                    "exprType":"pathLiteral",
                                    "isThis":false,
                                    "isFocused":false,
                                    "isTarget":false,
                                    "value":["6df73869138d4d468f4ff229f2fe35e2"]}]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"car_leixing"},
{
                                "exprType":"fcall",
                                "functionName":"GetSelectedOption",
                                "arguments":[{
                                    "exprType":"pathLiteral",
                                    "isThis":false,
                                    "isFocused":false,
                                    "isTarget":false,
                                    "value":["0ce2e2bede8b4339b8ff03ce4eb6fb9c"]}]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"car_ICcard"},
{
                                "exprType":"fcall",
                                "functionName":"GetWidgetText",
                                "arguments":[{
                                    "exprType":"pathLiteral",
                                    "isThis":false,
                                    "isFocused":false,
                                    "isTarget":false,
                                    "value":["b0b3d9676a404b4aa253ff1687b2e471"]}]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"yy_leixing"},
{
                                "exprType":"fcall",
                                "functionName":"GetSelectedOption",
                                "arguments":[{
                                    "exprType":"pathLiteral",
                                    "isThis":false,
                                    "isFocused":false,
                                    "isTarget":false,
                                    "value":["eb820356548b4febb6e5aa2b81b5f063"]}]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"car_InterNet_leixing"},
{
                                "exprType":"fcall",
                                "functionName":"GetSelectedOption",
                                "arguments":[{
                                    "exprType":"pathLiteral",
                                    "isThis":false,
                                    "isFocused":false,
                                    "isTarget":false,
                                    "value":["2e2a010e431e41029350a1e650f90acb"]}]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"car_jingYingLuXian"},
{
                                "exprType":"fcall",
                                "functionName":"GetSelectedOption",
                                "arguments":[{
                                    "exprType":"pathLiteral",
                                    "isThis":false,
                                    "isFocused":false,
                                    "isTarget":false,
                                    "value":["37990de872714ee5b6a6931d9b667573"]}]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"car_zhuangTai"},
{
                                "exprType":"fcall",
                                "functionName":"GetSelectedOption",
                                "arguments":[{
                                    "exprType":"pathLiteral",
                                    "isThis":false,
                                    "isFocused":false,
                                    "isTarget":false,
                                    "value":["fcd4f51386b148f7802e5421751ee145"]}]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"quYu"},
{
                                "exprType":"fcall",
                                "functionName":"GetSelectedOption",
                                "arguments":[{
                                    "exprType":"pathLiteral",
                                    "isThis":false,
                                    "isFocused":false,
                                    "isTarget":false,
                                    "value":["03c09b38fc9b452bbb718e9006097958"]}]}]}]}},
{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 车辆基本信息",
                      "target":{
                        "targetType":"page",
                        "url":"车辆基本信息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"2ce7930a7fe14099a66911896fd3c71f",
          "label":"新增_",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":41,
              "y":43},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d228b8471f5a45729ea9b7e5afc2d432",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":41,
                  "y":43},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3f04c9334b254c21bc5aab58ca7a504d",
          "label":"新增_运营商名称",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":127,
              "y":72},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"6df73869138d4d468f4ff229f2fe35e2",
          "label":"新增_车牌颜色",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":127,
              "y":142},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"e330d9780817455bad9aa847f9dc8b37",
          "label":"新增_关闭",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":395},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 车辆基本信息",
                      "target":{
                        "targetType":"page",
                        "url":"车辆基本信息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"eb820356548b4febb6e5aa2b81b5f063",
          "label":"新增_营运类型",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":128,
              "y":246},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"2e2a010e431e41029350a1e650f90acb",
          "label":"新增_终端分类",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":128,
              "y":278},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"37990de872714ee5b6a6931d9b667573",
          "label":"新增_经营路线",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":128,
              "y":314},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"fcd4f51386b148f7802e5421751ee145",
          "label":"新增_车辆状态",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":128,
              "y":350},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"03c09b38fc9b452bbb718e9006097958",
          "label":"新增_所属区域",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":127,
              "y":40},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"0ce2e2bede8b4339b8ff03ce4eb6fb9c",
          "label":"新增_车辆类型",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":128,
              "y":174},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"7994f91a7366407fa9efb18d1a3c6c3b",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":464,
              "y":58},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"center",
          "fixedMarginHorizontal":0,
          "fixedVertical":"middle",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"d3c5c2440917465e8a164dfe7eab1c26",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"70a9ab87d63846a2a6a35b1a1bec5597",
                  "label":"新增未填提示",
                  "parentDynamicPanel":"7994f91a7366407fa9efb18d1a3c6c3b",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":286,
                      "height":120}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8c8785f6656f42a787c0a2992fcd1cc3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7994f91a7366407fa9efb18d1a3c6c3b",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":286,
                          "height":120}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onMouseOver":{
                      "description":"OnMouseOver",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"wait",
                              "description":"等待1000毫秒",
                              "waitTime":1000},
{
                              "action":"fadeWidget",
                              "description":"隐藏 新增未填提示",
                              "objectsToFades":[{
                                  "objectPath":["70a9ab87d63846a2a6a35b1a1bec5597"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "images":{
                    "normal~":"images/车辆信息新增页面/新增未填提示_u35.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"688ba94d93f84668b70b80ec7d90d31b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":327,
              "y":40},
            "size":{
              "width":23,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb7ad4e2a8c149c185e1d8592594fc24",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":327,
                  "y":40},
                "size":{
                  "width":23,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d723786f64c548209bea442b96794065",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":327,
              "y":74},
            "size":{
              "width":23,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"efb080d9034740e49b64d63b17b0ee59",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":327,
                  "y":74},
                "size":{
                  "width":23,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a6615baa7de14a0589db77179d051f9b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":328,
              "y":104},
            "size":{
              "width":23,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48e2b894860f47fa81482b1210ba4e7a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":328,
                  "y":104},
                "size":{
                  "width":23,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7ef3ddec250c4a8abada7eb711a66904",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":327,
              "y":144},
            "size":{
              "width":23,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d59646c7f2049748fdb36d7cb545a04",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":327,
                  "y":144},
                "size":{
                  "width":23,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"50ba02fef0fd4544a3f5af74b769d1fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":328,
              "y":174},
            "size":{
              "width":23,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8427c77bd304fa88038a8c161a26bae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":328,
                  "y":174},
                "size":{
                  "width":23,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e18e1524070c4406b241289efc222593",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":328,
              "y":212},
            "size":{
              "width":23,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2f72ce5c968461bab20d70c8437bf14",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":328,
                  "y":212},
                "size":{
                  "width":23,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"92cccabcbe894a8987b32d4334e90654",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":328,
              "y":248},
            "size":{
              "width":23,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc6c4e750cca4e2280426575a72208b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":328,
                  "y":248},
                "size":{
                  "width":23,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6866fcef3188452baf12ba040c41be36",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":328,
              "y":278},
            "size":{
              "width":23,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65ca98c4741c48d38d6f729486cd25cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":328,
                  "y":278},
                "size":{
                  "width":23,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b868de121e7f4409abe31475e50c0c83",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":328,
              "y":314},
            "size":{
              "width":23,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c1ad9c69e114da0ae6ab9f7b75f0e04",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":328,
                  "y":314},
                "size":{
                  "width":23,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"113536aeffb74243a194bf212401ed39",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":328,
              "y":350},
            "size":{
              "width":23,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13b98ec5d6c349bcb5ffff72af5d19e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":328,
                  "y":350},
                "size":{
                  "width":23,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "3ecd3dd22a1642ab80e89acaa6156fdc":{
      "scriptId":"u0"},
    "f386831158cc4248aff25f7e9557aece":{
      "scriptId":"u1"},
    "b952c7aaec12404ab24737026f6aa3db":{
      "scriptId":"u2"},
    "6de8d1a0b0aa4562a3ba5c20667e2fd0":{
      "scriptId":"u3"},
    "5ebe989ae80243b28a74a0cfa3b7e4f0":{
      "scriptId":"u4"},
    "12cec4ef34d341aca638474f48741528":{
      "scriptId":"u5"},
    "171cd4ed5aeb4f28a6d4442c69f87e75":{
      "scriptId":"u6"},
    "79871af34ac14f5394fa77364f661eec":{
      "scriptId":"u7"},
    "1cc7af41a8a74efdafa95cb717a3803d":{
      "scriptId":"u8"},
    "bda58752249149c9996101ea5dbcc4b7":{
      "scriptId":"u9"},
    "44daa50236594308892360ee9cc7f847":{
      "scriptId":"u10"},
    "11d3781c2fa244608d8b265623f23a49":{
      "scriptId":"u11"},
    "c8e4a3ce59e847dfba011fec3b3f18cd":{
      "scriptId":"u12"},
    "7b2e1b1a9da54d5f85dc8ce0d5f63dd0":{
      "scriptId":"u13"},
    "566cecabeaeb446a9a10a091695f0cb6":{
      "scriptId":"u14"},
    "870a1fca99934bdfa952e6be651ca29e":{
      "scriptId":"u15"},
    "919e2a7014d747e8b19b150505a05382":{
      "scriptId":"u16"},
    "38412ba1b44b46b68377cbe4442e64db":{
      "scriptId":"u17"},
    "7b86c4a8e861426588a895bacf018de2":{
      "scriptId":"u18"},
    "273aaaf037214a2b9eb8d9d2fe45d345":{
      "scriptId":"u19"},
    "fe3819a4823344609f13195b5dbfa09f":{
      "scriptId":"u20"},
    "b0b3d9676a404b4aa253ff1687b2e471":{
      "scriptId":"u21"},
    "96da39ba3bbb41d190561ce81d3a6eab":{
      "scriptId":"u22"},
    "2ce7930a7fe14099a66911896fd3c71f":{
      "scriptId":"u23"},
    "d228b8471f5a45729ea9b7e5afc2d432":{
      "scriptId":"u24"},
    "3f04c9334b254c21bc5aab58ca7a504d":{
      "scriptId":"u25"},
    "6df73869138d4d468f4ff229f2fe35e2":{
      "scriptId":"u26"},
    "e330d9780817455bad9aa847f9dc8b37":{
      "scriptId":"u27"},
    "eb820356548b4febb6e5aa2b81b5f063":{
      "scriptId":"u28"},
    "2e2a010e431e41029350a1e650f90acb":{
      "scriptId":"u29"},
    "37990de872714ee5b6a6931d9b667573":{
      "scriptId":"u30"},
    "fcd4f51386b148f7802e5421751ee145":{
      "scriptId":"u31"},
    "03c09b38fc9b452bbb718e9006097958":{
      "scriptId":"u32"},
    "0ce2e2bede8b4339b8ff03ce4eb6fb9c":{
      "scriptId":"u33"},
    "7994f91a7366407fa9efb18d1a3c6c3b":{
      "scriptId":"u34"},
    "70a9ab87d63846a2a6a35b1a1bec5597":{
      "scriptId":"u35"},
    "8c8785f6656f42a787c0a2992fcd1cc3":{
      "scriptId":"u36"},
    "688ba94d93f84668b70b80ec7d90d31b":{
      "scriptId":"u37"},
    "fb7ad4e2a8c149c185e1d8592594fc24":{
      "scriptId":"u38"},
    "d723786f64c548209bea442b96794065":{
      "scriptId":"u39"},
    "efb080d9034740e49b64d63b17b0ee59":{
      "scriptId":"u40"},
    "a6615baa7de14a0589db77179d051f9b":{
      "scriptId":"u41"},
    "48e2b894860f47fa81482b1210ba4e7a":{
      "scriptId":"u42"},
    "7ef3ddec250c4a8abada7eb711a66904":{
      "scriptId":"u43"},
    "6d59646c7f2049748fdb36d7cb545a04":{
      "scriptId":"u44"},
    "50ba02fef0fd4544a3f5af74b769d1fe":{
      "scriptId":"u45"},
    "b8427c77bd304fa88038a8c161a26bae":{
      "scriptId":"u46"},
    "e18e1524070c4406b241289efc222593":{
      "scriptId":"u47"},
    "e2f72ce5c968461bab20d70c8437bf14":{
      "scriptId":"u48"},
    "92cccabcbe894a8987b32d4334e90654":{
      "scriptId":"u49"},
    "fc6c4e750cca4e2280426575a72208b6":{
      "scriptId":"u50"},
    "6866fcef3188452baf12ba040c41be36":{
      "scriptId":"u51"},
    "65ca98c4741c48d38d6f729486cd25cd":{
      "scriptId":"u52"},
    "b868de121e7f4409abe31475e50c0c83":{
      "scriptId":"u53"},
    "3c1ad9c69e114da0ae6ab9f7b75f0e04":{
      "scriptId":"u54"},
    "113536aeffb74243a194bf212401ed39":{
      "scriptId":"u55"},
    "13b98ec5d6c349bcb5ffff72af5d19e1":{
      "scriptId":"u56"}}});