$axure.loadCurrentPage({
  "url":"拆单页.html",
  "generationDate":new Date(1557742088082.3),
  "isCanvasEnabled":false,
  "variables":["yys_name",
"car_chePai_card",
"car_chePai_color",
"car_leixing",
"car_ICcard",
"yy_leixing",
"car_InterNet_leixing",
"car_jingYingLuXian",
"car_zhuangTai",
"quYu",
"phone",
"mail",
"name"],
  "page":{
    "packageId":"2840c47bac574d9d9252d48a2f24f45c",
    "type":"Axure:Page",
    "name":"拆单页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b394281e5c4145c8a6783889c36a0cdb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":59,
              "y":125},
            "size":{
              "width":626,
              "height":215}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4358eb7504248649c4eca49f26ff66e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":59,
                  "y":125},
                "size":{
                  "width":626,
                  "height":215}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/拆单页/u0.png"}},
{
          "id":"254b9759ca2d42a790fd35c9e1bde87a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":253,
              "y":360},
            "size":{
              "width":270,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"689b07ffc7104bb9be2740f5a91ca4b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":253,
                  "y":360},
                "size":{
                  "width":270,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/拆单页/u2.png"}},
{
          "id":"f768e38fa2f84987976113aeb839b03d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":301,
              "y":390},
            "size":{
              "width":57,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 框,<br>确定,<br>取消,<br>文字",
                      "objectsToFades":[{
                          "objectPath":["80e885506f8c4e729efcbcd45fb03d89"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["9a52a40162cf4c6ab5f8d34e8e245173"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["8ffc5e28ff764d9d9a8b8474de5581b9"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["4925f81e09194ee8b9962e4b13463dfc"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"f03542aaafc147fd86cd9f3b7223c3e3",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":390},
            "size":{
              "width":57,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"c13b6976d552426d90056f7c6150ccf7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":86,
              "y":70},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9084cf590eab440eaf872fac997e738f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":86,
                  "y":70},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"96ec9e4477c848d69470c767509cf0db",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":204,
              "y":66},
            "size":{
              "width":40,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"6835bfc75dde48369fda6341056cf7d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":264,
              "y":70},
            "size":{
              "width":52,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"63c2b1b4813945ea936e1f17bcfb6bb9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":264,
                  "y":70},
                "size":{
                  "width":52,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"80e885506f8c4e729efcbcd45fb03d89",
          "label":"框",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "location":{
              "x":175,
              "y":360},
            "size":{
              "width":380,
              "height":142},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4167d58671dd4a7582be9adfef757099",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":175,
                  "y":360},
                "size":{
                  "width":380,
                  "height":142},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/拆单页/框_u11.png"}},
{
          "id":"4925f81e09194ee8b9962e4b13463dfc",
          "label":"文字",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "location":{
              "x":253,
              "y":392},
            "size":{
              "width":202,
              "height":16},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ece8190b3a847f79cc0de9a1fe1ef60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":253,
                  "y":392},
                "size":{
                  "width":202,
                  "height":16},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9a52a40162cf4c6ab5f8d34e8e245173",
          "label":"确定",
          "type":"button",
          "styleType":"button",
          "visible":false,
          "style":{
            "location":{
              "x":235,
              "y":455},
            "size":{
              "width":100,
              "height":25},
            "visible":false},
          "adaptiveStyles":{
}},
{
          "id":"8ffc5e28ff764d9d9a8b8474de5581b9",
          "label":"取消",
          "type":"button",
          "styleType":"button",
          "visible":false,
          "style":{
            "location":{
              "x":425,
              "y":455},
            "size":{
              "width":100,
              "height":25},
            "visible":false},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 框,<br>文字,<br>确定,<br>取消",
                      "objectsToFades":[{
                          "objectPath":["80e885506f8c4e729efcbcd45fb03d89"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["4925f81e09194ee8b9962e4b13463dfc"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["9a52a40162cf4c6ab5f8d34e8e245173"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["8ffc5e28ff764d9d9a8b8474de5581b9"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"35760f472f4f45478919a978f829aae1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "location":{
              "x":84,
              "y":132},
            "size":{
              "width":551,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f143a5561dda49229726c29e4631c67c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "location":{
                  "x":84,
                  "y":132},
                "size":{
                  "width":551,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7601d4eb80f6474483a2d4274124bd89",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":84,
              "y":175},
            "size":{
              "width":566,
              "height":95}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a57215343dd94a098bcafbff77b30bf7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "size":{
                  "width":175,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"50ec6c91033f491cb48240f831c40ad7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "size":{
                      "width":175,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/拆单页/u20.png"}},
{
              "id":"10ba73485f1a4d7d81303e8d72fdcba5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":175,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a17fc9373e754376819b0389295f834c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":175,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/拆单页/u20.png"}},
{
              "id":"f4591b34c31a46b4871de395f61a8aca",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":175,
                  "y":0},
                "size":{
                  "width":175,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"189fdd866c634c72a6f8641e179ca179",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":175,
                      "y":0},
                    "size":{
                      "width":175,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/拆单页/u20.png"}},
{
              "id":"f7d6bc2ddf3040878a205d4e40a7f947",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":175,
                  "y":30},
                "size":{
                  "width":175,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d329d0bcc79842a79a541a5c28c7e059",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":175,
                      "y":30},
                    "size":{
                      "width":175,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/拆单页/u20.png"}},
{
              "id":"b81110ef1a9a45d9b65698c77c965840",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":350,
                  "y":0},
                "size":{
                  "width":90,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f194026cfabb41c1adf5e85f6bb4c664",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":350,
                      "y":0},
                    "size":{
                      "width":90,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/拆单页/u24.png"}},
{
              "id":"fef4bf4dec09427a9f04105b1b5beeb2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":350,
                  "y":30},
                "size":{
                  "width":90,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b62ad4abf9ca48e0a5b36ab007945768",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":350,
                      "y":30},
                    "size":{
                      "width":90,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/拆单页/u24.png"}},
{
              "id":"3f835286f7894f6096d8ec88c7d8accd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":175,
                  "height":35}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dcc1f8179f8047b2ab4372efa898790e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":175,
                      "height":35}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/拆单页/u36.png"}},
{
              "id":"6e46017923a64f5cb53d878383554792",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":175,
                  "y":60},
                "size":{
                  "width":175,
                  "height":35}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e16db6677e384a53b22d9b2886671f5c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":175,
                      "y":60},
                    "size":{
                      "width":175,
                      "height":35}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/拆单页/u36.png"}},
{
              "id":"5bdc725e605349b88b7a901e1e0cd54b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":350,
                  "y":60},
                "size":{
                  "width":90,
                  "height":35}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c934ff67307a4e4da724e9676d715158",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":350,
                      "y":60},
                    "size":{
                      "width":90,
                      "height":35}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/拆单页/u40.png"}},
{
              "id":"1e8fff4401cd4d87890e2b2ee69e6dee",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":440,
                  "y":0},
                "size":{
                  "width":126,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"41a91c7e034a4f70a3f9993ba13e84cb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":440,
                      "y":0},
                    "size":{
                      "width":126,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/拆单页/u26.png"}},
{
              "id":"1f4b9fe9192c4647b4f7b3850ff0e97f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":440,
                  "y":30},
                "size":{
                  "width":126,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1273a1118ce14869bb2d92c795dddb80",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":440,
                      "y":30},
                    "size":{
                      "width":126,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/拆单页/u26.png"}},
{
              "id":"31f9acf82dcd401da3a619e9cd1191c9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":440,
                  "y":60},
                "size":{
                  "width":126,
                  "height":35}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"30f45ea8c4dc4f8cad117dfe8722f81c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":440,
                      "y":60},
                    "size":{
                      "width":126,
                      "height":35}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/拆单页/u42.png"}}]},
{
          "id":"54279046e69d40489f2c4c3e96c522db",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":439,
              "y":210},
            "size":{
              "width":66,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b4543049b23a4f93a808e4d23ede27ef",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":301,
              "y":205},
            "size":{
              "width":67,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f42c17e03eed42ab9bc1bdb50498e506",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":326,
              "y":70},
            "size":{
              "width":42,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34c97c7e15094ad1aa632ab35a5dc73c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":326,
                  "y":70},
                "size":{
                  "width":42,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"912b5ada66a54186aa750cd867321895",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":67,
              "y":50},
            "size":{
              "width":618,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/拆单页/u48_line.png"}},
{
          "id":"c47cbf45a62c468092674a35ac211e22",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":59,
              "y":52},
            "size":{
              "width":10,
              "height":58}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/拆单页/u49_line.png"}},
{
          "id":"8c9fdb16d4314788943427af0f1bc9f8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":105},
            "size":{
              "width":625,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/拆单页/u50_line.png"}},
{
          "id":"541b5514b1f1471a8d9a778293df9856",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":678,
              "y":56},
            "size":{
              "width":10,
              "height":54}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/拆单页/u51_line.png"}},
{
          "id":"efd3da12b82e419a9f102920fe83f0d3",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":301,
              "y":240},
            "size":{
              "width":67,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"c89f68c672c246aa8d71081513aa7d24",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":439,
              "y":235},
            "size":{
              "width":66,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"85c33ae4f7e54102804755b2143d1263",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":559,
              "y":208},
            "size":{
              "width":40,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"d7868016f96249cd89c9d522eb1e742f",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":559,
              "y":240},
            "size":{
              "width":40,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f1a21f3ee0ae423bae28ef70c922d1d9",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":480},
            "size":{
              "width":690,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/拆单页/u56_line.png"}},
{
          "id":"2e3802858d6e40109488666a2ed51dc5",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":22,
              "y":40},
            "size":{
              "width":10,
              "height":449}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/拆单页/u57_line.png"}},
{
          "id":"50fee4a8e90f4f088a7c5ffaa6df1c95",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":712,
              "y":40},
            "size":{
              "width":10,
              "height":449}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/拆单页/u57_line.png"}},
{
          "id":"a72c884de562450dacf0a6aa511ebbab",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":29,
              "y":37},
            "size":{
              "width":691,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/拆单页/u59_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "b394281e5c4145c8a6783889c36a0cdb":{
      "scriptId":"u0"},
    "a4358eb7504248649c4eca49f26ff66e":{
      "scriptId":"u1"},
    "254b9759ca2d42a790fd35c9e1bde87a":{
      "scriptId":"u2"},
    "689b07ffc7104bb9be2740f5a91ca4b7":{
      "scriptId":"u3"},
    "f768e38fa2f84987976113aeb839b03d":{
      "scriptId":"u4"},
    "f03542aaafc147fd86cd9f3b7223c3e3":{
      "scriptId":"u5"},
    "c13b6976d552426d90056f7c6150ccf7":{
      "scriptId":"u6"},
    "9084cf590eab440eaf872fac997e738f":{
      "scriptId":"u7"},
    "96ec9e4477c848d69470c767509cf0db":{
      "scriptId":"u8"},
    "6835bfc75dde48369fda6341056cf7d9":{
      "scriptId":"u9"},
    "63c2b1b4813945ea936e1f17bcfb6bb9":{
      "scriptId":"u10"},
    "80e885506f8c4e729efcbcd45fb03d89":{
      "scriptId":"u11"},
    "4167d58671dd4a7582be9adfef757099":{
      "scriptId":"u12"},
    "4925f81e09194ee8b9962e4b13463dfc":{
      "scriptId":"u13"},
    "7ece8190b3a847f79cc0de9a1fe1ef60":{
      "scriptId":"u14"},
    "9a52a40162cf4c6ab5f8d34e8e245173":{
      "scriptId":"u15"},
    "8ffc5e28ff764d9d9a8b8474de5581b9":{
      "scriptId":"u16"},
    "35760f472f4f45478919a978f829aae1":{
      "scriptId":"u17"},
    "f143a5561dda49229726c29e4631c67c":{
      "scriptId":"u18"},
    "7601d4eb80f6474483a2d4274124bd89":{
      "scriptId":"u19"},
    "a57215343dd94a098bcafbff77b30bf7":{
      "scriptId":"u20"},
    "50ec6c91033f491cb48240f831c40ad7":{
      "scriptId":"u21"},
    "f4591b34c31a46b4871de395f61a8aca":{
      "scriptId":"u22"},
    "189fdd866c634c72a6f8641e179ca179":{
      "scriptId":"u23"},
    "b81110ef1a9a45d9b65698c77c965840":{
      "scriptId":"u24"},
    "f194026cfabb41c1adf5e85f6bb4c664":{
      "scriptId":"u25"},
    "1e8fff4401cd4d87890e2b2ee69e6dee":{
      "scriptId":"u26"},
    "41a91c7e034a4f70a3f9993ba13e84cb":{
      "scriptId":"u27"},
    "10ba73485f1a4d7d81303e8d72fdcba5":{
      "scriptId":"u28"},
    "a17fc9373e754376819b0389295f834c":{
      "scriptId":"u29"},
    "f7d6bc2ddf3040878a205d4e40a7f947":{
      "scriptId":"u30"},
    "d329d0bcc79842a79a541a5c28c7e059":{
      "scriptId":"u31"},
    "fef4bf4dec09427a9f04105b1b5beeb2":{
      "scriptId":"u32"},
    "b62ad4abf9ca48e0a5b36ab007945768":{
      "scriptId":"u33"},
    "1f4b9fe9192c4647b4f7b3850ff0e97f":{
      "scriptId":"u34"},
    "1273a1118ce14869bb2d92c795dddb80":{
      "scriptId":"u35"},
    "3f835286f7894f6096d8ec88c7d8accd":{
      "scriptId":"u36"},
    "dcc1f8179f8047b2ab4372efa898790e":{
      "scriptId":"u37"},
    "6e46017923a64f5cb53d878383554792":{
      "scriptId":"u38"},
    "e16db6677e384a53b22d9b2886671f5c":{
      "scriptId":"u39"},
    "5bdc725e605349b88b7a901e1e0cd54b":{
      "scriptId":"u40"},
    "c934ff67307a4e4da724e9676d715158":{
      "scriptId":"u41"},
    "31f9acf82dcd401da3a619e9cd1191c9":{
      "scriptId":"u42"},
    "30f45ea8c4dc4f8cad117dfe8722f81c":{
      "scriptId":"u43"},
    "54279046e69d40489f2c4c3e96c522db":{
      "scriptId":"u44"},
    "b4543049b23a4f93a808e4d23ede27ef":{
      "scriptId":"u45"},
    "f42c17e03eed42ab9bc1bdb50498e506":{
      "scriptId":"u46"},
    "34c97c7e15094ad1aa632ab35a5dc73c":{
      "scriptId":"u47"},
    "912b5ada66a54186aa750cd867321895":{
      "scriptId":"u48"},
    "c47cbf45a62c468092674a35ac211e22":{
      "scriptId":"u49"},
    "8c9fdb16d4314788943427af0f1bc9f8":{
      "scriptId":"u50"},
    "541b5514b1f1471a8d9a778293df9856":{
      "scriptId":"u51"},
    "efd3da12b82e419a9f102920fe83f0d3":{
      "scriptId":"u52"},
    "c89f68c672c246aa8d71081513aa7d24":{
      "scriptId":"u53"},
    "85c33ae4f7e54102804755b2143d1263":{
      "scriptId":"u54"},
    "d7868016f96249cd89c9d522eb1e742f":{
      "scriptId":"u55"},
    "f1a21f3ee0ae423bae28ef70c922d1d9":{
      "scriptId":"u56"},
    "2e3802858d6e40109488666a2ed51dc5":{
      "scriptId":"u57"},
    "50fee4a8e90f4f088a7c5ffaa6df1c95":{
      "scriptId":"u58"},
    "a72c884de562450dacf0a6aa511ebbab":{
      "scriptId":"u59"}}});