$axure.loadCurrentPage({
  "url":"查看运单详情信息（已发单）.html",
  "generationDate":new Date(1557736120859.24),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n",
"rl_date",
"rl_day"],
  "page":{
    "packageId":"6eae0d2291564098bfe0e774bb8da139",
    "type":"Axure:Page",
    "name":"查看运单详情信息（已发单）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"efee3782620945db8b2c80e97fd6383b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
            "fontSize":"36px",
            "fontWeight":"500",
            "location":{
              "x":560,
              "y":171},
            "size":{
              "width":20,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9a4e6562fe0420ea53e1ea8969e1ed9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
                "fontSize":"36px",
                "fontWeight":"500",
                "location":{
                  "x":560,
                  "y":171},
                "size":{
                  "width":20,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/填写单据信息/u76.png"}},
{
          "id":"bbbb0046963d464faceb10b475bedf93",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":590,
              "y":171},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27c59437ef4345fe89dc5b93a4b0b961",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":590,
                  "y":171},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"957c0dfdf47d4cfe9ed0e3578d622a0e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":560,
              "y":233},
            "size":{
              "width":420,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47c282bd244a47d5944bcf0838ae3c65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":560,
                  "y":233},
                "size":{
                  "width":420,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看运单详情信息/u4.png"}},
{
          "id":"230cdf77a49e44ea8fdb9ac5609493ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":590,
              "y":244},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cbd3480bd9574fafba3def400d1ea96c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":590,
                  "y":244},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bde56a427e2e4efe820f3bc9c4145de7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":590,
              "y":290},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"774a4287fdb74c9a96f073b56c618ffb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":590,
                  "y":290},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4209655c134648668ccfc2fb1f783ddc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":660,
              "y":244},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8eaff675f4214aed8c40d9a0984b0659",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":660,
                  "y":244},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d42fa824165345b1957d046b94199fff",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":560,
              "y":567},
            "size":{
              "width":420,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e28bf693cd0e459d802379fa228ed624",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":560,
                  "y":567},
                "size":{
                  "width":420,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看运单详情信息/u4.png"}},
{
          "id":"cde42a4fdcaa4a21b7ace07e1f6b54f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":580,
              "y":586},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85d8381532a7491cb23f731964d9f1e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":580,
                  "y":586},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"74a523be3c1b4430b9718b486b9f48f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":580,
              "y":632},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f84aa9f3bf2646e8a3716889db945c51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":580,
                  "y":632},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8f3a84698a264e4ea83072fea004cfe6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":650,
              "y":586},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b053cab4b594087896e48ff01893f18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":650,
                  "y":586},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c7e1c48284cc4d91a32ee1094789f92c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":560,
              "y":343},
            "size":{
              "width":420,
              "height":214}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a9acf3475ec46e79f46a81a58cacb06",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":560,
                  "y":343},
                "size":{
                  "width":420,
                  "height":214}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看运单详情信息（已发单）/u20.png"}},
{
          "id":"ce53163ca09f46d9b5e50bbac83356a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":584,
              "y":350},
            "size":{
              "width":27,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6086e25e4c104fcebd0dcb932c4ec3df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":584,
                  "y":350},
                "size":{
                  "width":27,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9182e9904cdf4ccf9d278db41300824c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":584,
              "y":377},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42bdfd8785064e65bb894941b2b3eac9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":584,
                  "y":377},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d030f39591f14422a6e8d5d6b22d7fd0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":584,
              "y":410},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18eb001eb1d1434597bba19179467217",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":584,
                  "y":410},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1dcd0303fcd04a638bfedbbe59352f78",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":584,
              "y":484},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13efb292e21941b693b9cac52f6b97a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":584,
                  "y":484},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fd94cd669ad4423bbe44512948c54797",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":582,
              "y":442},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"750d046a7a8b48aa97dd4fb632deab2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":582,
                  "y":442},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9b96531e8ce741e2a30ae24aebde9800",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":584,
              "y":524},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e816f6f8929b49d1a5997923d6dd2691",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":584,
                  "y":524},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "efee3782620945db8b2c80e97fd6383b":{
      "scriptId":"u0"},
    "c9a4e6562fe0420ea53e1ea8969e1ed9":{
      "scriptId":"u1"},
    "bbbb0046963d464faceb10b475bedf93":{
      "scriptId":"u2"},
    "27c59437ef4345fe89dc5b93a4b0b961":{
      "scriptId":"u3"},
    "957c0dfdf47d4cfe9ed0e3578d622a0e":{
      "scriptId":"u4"},
    "47c282bd244a47d5944bcf0838ae3c65":{
      "scriptId":"u5"},
    "230cdf77a49e44ea8fdb9ac5609493ba":{
      "scriptId":"u6"},
    "cbd3480bd9574fafba3def400d1ea96c":{
      "scriptId":"u7"},
    "bde56a427e2e4efe820f3bc9c4145de7":{
      "scriptId":"u8"},
    "774a4287fdb74c9a96f073b56c618ffb":{
      "scriptId":"u9"},
    "4209655c134648668ccfc2fb1f783ddc":{
      "scriptId":"u10"},
    "8eaff675f4214aed8c40d9a0984b0659":{
      "scriptId":"u11"},
    "d42fa824165345b1957d046b94199fff":{
      "scriptId":"u12"},
    "e28bf693cd0e459d802379fa228ed624":{
      "scriptId":"u13"},
    "cde42a4fdcaa4a21b7ace07e1f6b54f0":{
      "scriptId":"u14"},
    "85d8381532a7491cb23f731964d9f1e3":{
      "scriptId":"u15"},
    "74a523be3c1b4430b9718b486b9f48f2":{
      "scriptId":"u16"},
    "f84aa9f3bf2646e8a3716889db945c51":{
      "scriptId":"u17"},
    "8f3a84698a264e4ea83072fea004cfe6":{
      "scriptId":"u18"},
    "2b053cab4b594087896e48ff01893f18":{
      "scriptId":"u19"},
    "c7e1c48284cc4d91a32ee1094789f92c":{
      "scriptId":"u20"},
    "0a9acf3475ec46e79f46a81a58cacb06":{
      "scriptId":"u21"},
    "ce53163ca09f46d9b5e50bbac83356a1":{
      "scriptId":"u22"},
    "6086e25e4c104fcebd0dcb932c4ec3df":{
      "scriptId":"u23"},
    "9182e9904cdf4ccf9d278db41300824c":{
      "scriptId":"u24"},
    "42bdfd8785064e65bb894941b2b3eac9":{
      "scriptId":"u25"},
    "d030f39591f14422a6e8d5d6b22d7fd0":{
      "scriptId":"u26"},
    "18eb001eb1d1434597bba19179467217":{
      "scriptId":"u27"},
    "1dcd0303fcd04a638bfedbbe59352f78":{
      "scriptId":"u28"},
    "13efb292e21941b693b9cac52f6b97a9":{
      "scriptId":"u29"},
    "fd94cd669ad4423bbe44512948c54797":{
      "scriptId":"u30"},
    "750d046a7a8b48aa97dd4fb632deab2c":{
      "scriptId":"u31"},
    "9b96531e8ce741e2a30ae24aebde9800":{
      "scriptId":"u32"},
    "e816f6f8929b49d1a5997923d6dd2691":{
      "scriptId":"u33"}}});