$axure.loadCurrentPage({
  "url":"home.html",
  "generationDate":new Date(1557736120239.21),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n",
"rl_date",
"rl_day"],
  "page":{
    "packageId":"4c0a9d592931476bbac0af6ca86c5a94",
    "type":"Axure:Page",
    "name":"Home",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"107faa7dd16446df976395cd265875f2",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF330033,
              "opacity":1},
            "location":{
              "x":410,
              "y":540},
            "size":{
              "width":70,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"d9f5520aed694da89e511dae4ab3cacb",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF330033,
              "opacity":1},
            "location":{
              "x":500,
              "y":540},
            "size":{
              "width":70,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"e0e1fc7c99554e66a66cab405c8401d9",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF330033,
              "opacity":1},
            "location":{
              "x":600,
              "y":540},
            "size":{
              "width":70,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"18b03c59023346edae6599b6e02750b3",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF330033,
              "opacity":1},
            "location":{
              "x":700,
              "y":540},
            "size":{
              "width":70,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"7e1657e1852f424c9f7f4ce219a37fd5",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF330033,
              "opacity":1},
            "location":{
              "x":800,
              "y":540},
            "size":{
              "width":70,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"2f267ccb917f4e5fac063bf6c2104fae",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":50},
            "size":{
              "width":460,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e2c409925cb4b6896ff12f428e6ef90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":50},
                "size":{
                  "width":460,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u5.png"}},
{
          "id":"5b123009cb5b4d79bd50b42432d5bd25",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta cursiva', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "fontStyle":"italic",
            "location":{
              "x":576.5,
              "y":100},
            "size":{
              "width":100,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12ce1ad0257c4858b2529cb8bf6bc89b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta cursiva', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "fontStyle":"italic",
                "location":{
                  "x":576.5,
                  "y":100},
                "size":{
                  "width":100,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u7.png"}},
{
          "id":"fd5e4e405c1a43fbb4747de0633c16b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":180},
            "size":{
              "width":460,
              "height":160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"417fc786cd4d4e84be23297eb30aed7f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":180},
                "size":{
                  "width":460,
                  "height":160}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u9.png"}},
{
          "id":"dc73d76e24ad426691a40a466b850186",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Cursiva', 'Arial'",
            "fontSize":"18px",
            "fontStyle":"italic",
            "location":{
              "x":420,
              "y":190},
            "size":{
              "width":109,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25bc8264147842b59d0775a8cd290a25",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Cursiva', 'Arial'",
                "fontSize":"18px",
                "fontStyle":"italic",
                "location":{
                  "x":420,
                  "y":190},
                "size":{
                  "width":109,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b405b8a49cf549b08d38980a3da49060",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":340},
            "size":{
              "width":460,
              "height":170}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2be08b5fa5534e1fa15e5fcdea0fee8e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":340},
                "size":{
                  "width":460,
                  "height":170}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u13.png"}},
{
          "id":"3ffff35d39014663aa5cb8b1ee4d0880",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Cursiva', 'Arial'",
            "fontSize":"18px",
            "fontStyle":"italic",
            "location":{
              "x":420,
              "y":350},
            "size":{
              "width":109,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce5130d368624724a36bc338812f62fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Cursiva', 'Arial'",
                "fontSize":"18px",
                "fontStyle":"italic",
                "location":{
                  "x":420,
                  "y":350},
                "size":{
                  "width":109,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"97bd1e4887744892a749eda941656a53",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":429,
              "y":390},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a875d657c9814da78a523a10d29b37d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":429,
                  "y":390},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aa264bd75c674fd484f8c27174fe7ae7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":691,
              "y":390},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc179c129f91414bbb66d9cab18649fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":691,
                  "y":390},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"503d342f867245bc8eb2916207587b64",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":429,
              "y":440},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"881ee046f6fe4bc8a435beacabcb3abc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":429,
                  "y":440},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d4bae4fb88a2486d82e80f9051d9d6d6",
          "label":"yellow",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":123,
              "y":208},
            "size":{
              "width":1,
              "height":40}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"78c680044a384b4ca21e0156d136288b",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"330fa670cfe442aca201bab7c1549eaa",
                  "label":"",
                  "parentDynamicPanel":"d4bae4fb88a2486d82e80f9051d9d6d6",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF00},
                    "size":{
                      "width":40,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"28e49ef42347476cb13409143ab16af1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d4bae4fb88a2486d82e80f9051d9d6d6",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF00},
                        "size":{
                          "width":40,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u24.png"}},
{
                  "id":"2e0ed4f8afa248afb3a3fe8f391fa5b6",
                  "label":"",
                  "parentDynamicPanel":"d4bae4fb88a2486d82e80f9051d9d6d6",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF00},
                    "location":{
                      "x":40,
                      "y":0},
                    "size":{
                      "width":40,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"61b80c4cc2044e298ca1ff33ce19a2a1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d4bae4fb88a2486d82e80f9051d9d6d6",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF00},
                        "location":{
                          "x":40,
                          "y":0},
                        "size":{
                          "width":40,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u24.png"}},
{
                  "id":"5ca419efd77047439fa7f79925f1e265",
                  "label":"",
                  "parentDynamicPanel":"d4bae4fb88a2486d82e80f9051d9d6d6",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF00},
                    "location":{
                      "x":80,
                      "y":0},
                    "size":{
                      "width":40,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"286b742952314e31b5333d7bab435a10",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d4bae4fb88a2486d82e80f9051d9d6d6",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF00},
                        "location":{
                          "x":80,
                          "y":0},
                        "size":{
                          "width":40,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u24.png"}},
{
                  "id":"638f96e140cd4afbb571b9a4a4f3db6c",
                  "label":"",
                  "parentDynamicPanel":"d4bae4fb88a2486d82e80f9051d9d6d6",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF00},
                    "location":{
                      "x":120,
                      "y":0},
                    "size":{
                      "width":40,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4982c62e54fb4df8b4d63ac4933cd102",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d4bae4fb88a2486d82e80f9051d9d6d6",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF00},
                        "location":{
                          "x":120,
                          "y":0},
                        "size":{
                          "width":40,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u24.png"}},
{
                  "id":"934f83386b914dc39ec5084911bbffa7",
                  "label":"",
                  "parentDynamicPanel":"d4bae4fb88a2486d82e80f9051d9d6d6",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF00},
                    "location":{
                      "x":160,
                      "y":0},
                    "size":{
                      "width":40,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dd074820a617405fae40a3277f689831",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d4bae4fb88a2486d82e80f9051d9d6d6",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF00},
                        "location":{
                          "x":160,
                          "y":0},
                        "size":{
                          "width":40,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u24.png"}},
{
                  "id":"cff5c8ff66f141f8808874fc833079bd",
                  "label":"选中状态",
                  "parentDynamicPanel":"d4bae4fb88a2486d82e80f9051d9d6d6",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":34,
                      "y":116},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1aac8bc40a80431da55bea5dd03310d0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d4bae4fb88a2486d82e80f9051d9d6d6",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":34,
                          "y":116},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"f9b3056672a6424cbc3a375676cddd3d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":750,
              "y":50},
            "size":{
              "width":120,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f230bec7e5ab499cab1b6a2c954e4eb2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":750,
                  "y":50},
                "size":{
                  "width":120,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u36.png"}},
{
          "id":"1e9c6e4aea214dcc8f34ab9ed5525557",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":429,
              "y":236},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f28acbdb9984c609c9e1ecaede9438c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":429,
                  "y":236},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0adbb4600862482db35fd27ca92503cb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":515,
              "y":236},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"875a91d8fbf8411282f063bc4ad10e1e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":515,
                  "y":236},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ecae8fd656644527885d3d3d91e5abb5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":610,
              "y":236},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58d3824cad58401fb8bd95ea8e40e832",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":610,
                  "y":236},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"58046997f13d4c71ae992a1fb07d203e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":691,
              "y":236},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c11be0ab84b4c60bc8c37612b0baa0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":691,
                  "y":236},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5bb0332e30fc46b68720794d6624a03c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":429,
              "y":284},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f631d59b655a43328040c03457711757",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":429,
                  "y":284},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"40ebb719a55548a9845cd0a036cc839a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":284},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77196d877c664be3b095198534eea471",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":510,
                  "y":284},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aced802593354297bff19c81b838acc6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":557,
              "y":440},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e598da263e749a69342d66dba20c0ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":557,
                  "y":440},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1b5d1886effe4c56b508b58694778059",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":557,
              "y":390},
            "size":{
              "width":53,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47145a1f6da5403d887860a419aed525",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":557,
                  "y":390},
                "size":{
                  "width":53,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "107faa7dd16446df976395cd265875f2":{
      "scriptId":"u0"},
    "d9f5520aed694da89e511dae4ab3cacb":{
      "scriptId":"u1"},
    "e0e1fc7c99554e66a66cab405c8401d9":{
      "scriptId":"u2"},
    "18b03c59023346edae6599b6e02750b3":{
      "scriptId":"u3"},
    "7e1657e1852f424c9f7f4ce219a37fd5":{
      "scriptId":"u4"},
    "2f267ccb917f4e5fac063bf6c2104fae":{
      "scriptId":"u5"},
    "8e2c409925cb4b6896ff12f428e6ef90":{
      "scriptId":"u6"},
    "5b123009cb5b4d79bd50b42432d5bd25":{
      "scriptId":"u7"},
    "12ce1ad0257c4858b2529cb8bf6bc89b":{
      "scriptId":"u8"},
    "fd5e4e405c1a43fbb4747de0633c16b1":{
      "scriptId":"u9"},
    "417fc786cd4d4e84be23297eb30aed7f":{
      "scriptId":"u10"},
    "dc73d76e24ad426691a40a466b850186":{
      "scriptId":"u11"},
    "25bc8264147842b59d0775a8cd290a25":{
      "scriptId":"u12"},
    "b405b8a49cf549b08d38980a3da49060":{
      "scriptId":"u13"},
    "2be08b5fa5534e1fa15e5fcdea0fee8e":{
      "scriptId":"u14"},
    "3ffff35d39014663aa5cb8b1ee4d0880":{
      "scriptId":"u15"},
    "ce5130d368624724a36bc338812f62fe":{
      "scriptId":"u16"},
    "97bd1e4887744892a749eda941656a53":{
      "scriptId":"u17"},
    "a875d657c9814da78a523a10d29b37d2":{
      "scriptId":"u18"},
    "aa264bd75c674fd484f8c27174fe7ae7":{
      "scriptId":"u19"},
    "bc179c129f91414bbb66d9cab18649fb":{
      "scriptId":"u20"},
    "503d342f867245bc8eb2916207587b64":{
      "scriptId":"u21"},
    "881ee046f6fe4bc8a435beacabcb3abc":{
      "scriptId":"u22"},
    "d4bae4fb88a2486d82e80f9051d9d6d6":{
      "scriptId":"u23"},
    "330fa670cfe442aca201bab7c1549eaa":{
      "scriptId":"u24"},
    "28e49ef42347476cb13409143ab16af1":{
      "scriptId":"u25"},
    "2e0ed4f8afa248afb3a3fe8f391fa5b6":{
      "scriptId":"u26"},
    "61b80c4cc2044e298ca1ff33ce19a2a1":{
      "scriptId":"u27"},
    "5ca419efd77047439fa7f79925f1e265":{
      "scriptId":"u28"},
    "286b742952314e31b5333d7bab435a10":{
      "scriptId":"u29"},
    "638f96e140cd4afbb571b9a4a4f3db6c":{
      "scriptId":"u30"},
    "4982c62e54fb4df8b4d63ac4933cd102":{
      "scriptId":"u31"},
    "934f83386b914dc39ec5084911bbffa7":{
      "scriptId":"u32"},
    "dd074820a617405fae40a3277f689831":{
      "scriptId":"u33"},
    "cff5c8ff66f141f8808874fc833079bd":{
      "scriptId":"u34"},
    "1aac8bc40a80431da55bea5dd03310d0":{
      "scriptId":"u35"},
    "f9b3056672a6424cbc3a375676cddd3d":{
      "scriptId":"u36"},
    "f230bec7e5ab499cab1b6a2c954e4eb2":{
      "scriptId":"u37"},
    "1e9c6e4aea214dcc8f34ab9ed5525557":{
      "scriptId":"u38"},
    "7f28acbdb9984c609c9e1ecaede9438c":{
      "scriptId":"u39"},
    "0adbb4600862482db35fd27ca92503cb":{
      "scriptId":"u40"},
    "875a91d8fbf8411282f063bc4ad10e1e":{
      "scriptId":"u41"},
    "ecae8fd656644527885d3d3d91e5abb5":{
      "scriptId":"u42"},
    "58d3824cad58401fb8bd95ea8e40e832":{
      "scriptId":"u43"},
    "58046997f13d4c71ae992a1fb07d203e":{
      "scriptId":"u44"},
    "8c11be0ab84b4c60bc8c37612b0baa0f":{
      "scriptId":"u45"},
    "5bb0332e30fc46b68720794d6624a03c":{
      "scriptId":"u46"},
    "f631d59b655a43328040c03457711757":{
      "scriptId":"u47"},
    "40ebb719a55548a9845cd0a036cc839a":{
      "scriptId":"u48"},
    "77196d877c664be3b095198534eea471":{
      "scriptId":"u49"},
    "aced802593354297bff19c81b838acc6":{
      "scriptId":"u50"},
    "7e598da263e749a69342d66dba20c0ac":{
      "scriptId":"u51"},
    "1b5d1886effe4c56b508b58694778059":{
      "scriptId":"u52"},
    "47145a1f6da5403d887860a419aed525":{
      "scriptId":"u53"}}});