$axure.loadCurrentPage({
  "url":"车辆保险新增页面.html",
  "generationDate":new Date(1557742124811.64),
  "isCanvasEnabled":false,
  "variables":["yys_name",
"car_chePai_card",
"car_chePai_color",
"car_leixing",
"car_ICcard",
"yy_leixing",
"car_InterNet_leixing",
"car_jingYingLuXian",
"car_zhuangTai",
"quYu",
"phone",
"mail",
"name"],
  "page":{
    "packageId":"cc24ea19451c47578e5e88bd51272062",
    "type":"Axure:Page",
    "name":"车辆保险新增页面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
      "onLoad":{
        "description":"OnLoad",
        "cases":[{
            "description":"用例 1",
            "isNewIfGroup":false,
            "actions":[{
                "action":"fadeWidget",
                "description":"隐藏 新增未填提示",
                "objectsToFades":[{
                    "objectPath":["cfc294824ce04241b1918c9c101e2afd"],
                    "fadeInfo":{
                      "fadeType":"hide",
                      "options":{
                        "showType":"none"}}}]}]}]}},
    "diagram":{
      "objects":[{
          "id":"e352ae0983e540809168db0fa728cdab",
          "label":"编辑_弹框",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":10,
              "y":26},
            "size":{
              "width":620,
              "height":863}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e784f2fc702143279635c0bddbaddb6f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":10,
                  "y":26},
                "size":{
                  "width":620,
                  "height":863}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/车辆保险新增页面/编辑_弹框_u0.png"}},
{
          "id":"2aafc8511ca248ccb07b640cdfb34137",
          "label":"新增_",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":61,
              "y":117},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d6952d3a06d4cd4acba38176723b671",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":61,
                  "y":117},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"77f0a614a1664931a0360ee4e4b5ef86",
          "label":"新增_",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":61,
              "y":157},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a4df2185ef14019aebb904656485b5c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":61,
                  "y":157},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"183e8f106c6f4ea3848cf7bff99eb7ee",
          "label":"新增_",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":61,
              "y":196},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc28d10125ef462da82bbbd930899962",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":61,
                  "y":196},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b5ec45c11ae3447c9967e2320dd78b63",
          "label":"新增_",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":61,
              "y":235},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60dc59ed8f73400a912e32351642d715",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":61,
                  "y":235},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4189794da15244319b48f72c634e12cb",
          "label":"新增_",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":61,
              "y":273},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb7730bf8dc6490c809eb63140be98df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":61,
                  "y":273},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d9b69d1febf6404782b2a25e72b76ff3",
          "label":"新增_",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":61,
              "y":313},
            "size":{
              "width":52,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4acbb01454b14bbdb41433744023b138",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":61,
                  "y":313},
                "size":{
                  "width":52,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4a0bfcf877a84b61b092da73ed720502",
          "label":"新增_",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":61,
              "y":351},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2561e3b28f6d460e89f5629a3fc0aadd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":61,
                  "y":351},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ecf591cc47a6420cb567429777279bd4",
          "label":"新增_",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":61,
              "y":392},
            "size":{
              "width":52,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d147a22984934636b32ee82b3eea1955",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":61,
                  "y":392},
                "size":{
                  "width":52,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"53279d324a474fddabc5ab5d3fc1d846",
          "label":"新增_IC卡号",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":155,
              "y":269},
            "size":{
              "width":120,
              "height":28}},
          "adaptiveStyles":{
}},
{
          "id":"95fd5f0a89f046d3ab55e3a304058987",
          "label":"新增_",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":82},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65dffacd13ed40178291669b83656752",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":82},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4d8adff86be6469c88cd8fc2765ed4fb",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":1074,
              "y":177},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"center",
          "fixedMarginHorizontal":0,
          "fixedVertical":"middle",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"35eeae21b28448fd8ca6fac033b5e906",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"cfc294824ce04241b1918c9c101e2afd",
                  "label":"新增未填提示",
                  "parentDynamicPanel":"4d8adff86be6469c88cd8fc2765ed4fb",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":286,
                      "height":120}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5da83d3f86154f3eade7a4b23860301f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4d8adff86be6469c88cd8fc2765ed4fb",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":286,
                          "height":120}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onMouseOver":{
                      "description":"OnMouseOver",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"wait",
                              "description":"等待1000毫秒",
                              "waitTime":1000},
{
                              "action":"fadeWidget",
                              "description":"隐藏 新增未填提示",
                              "objectsToFades":[{
                                  "objectPath":["cfc294824ce04241b1918c9c101e2afd"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "images":{
                    "normal~":"images/运单信息评价新增页面/新增未填提示_u5.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"35e0d049aa9e407eb0b1166d4fce1c22",
          "label":"新增_车牌号",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":156,
              "y":82},
            "size":{
              "width":218,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"60755fc0ef2d46039533731c8bb087fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":10.5,
              "y":37},
            "size":{
              "width":152,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2c84e5638874e4cae11e9655d29dd43",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10.5,
                  "y":37},
                "size":{
                  "width":152,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"726e8156ccb9454c809ff8929e0e9aa2",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":156,
              "y":154},
            "size":{
              "width":104,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"31cd5bd65d5a48ef86bc1297af0b3e08",
          "label":"新增_IC卡号",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":155,
              "y":193.5},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
}},
{
          "id":"c1c7841b607346ffaff7b3b90b13ce97",
          "label":"新增_IC卡号",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":155,
              "y":233.5},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
}},
{
          "id":"cda929809b5a4e21a874f0069b59f9dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":271,
              "y":271},
            "size":{
              "width":29,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb03e2b58f264739b0af239f236d4744",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":271,
                  "y":271},
                "size":{
                  "width":29,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/车辆保险新增页面/u30.png"}},
{
          "id":"80e6a55224534d87aaeb0ae24ee15e6a",
          "label":"新增_IC卡号",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":148,
              "y":313},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"6c8e2c9f74264933a779dcad94d4b482",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":148,
              "y":351},
            "size":{
              "width":132,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"3726b89e1be2463292b247b4452f0327",
          "label":"新增_IC卡号",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":148,
              "y":389},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"fb46979f5ded41978368d56cc3b7e523",
          "label":"新增_",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":57,
              "y":424},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67c3e4a5ade54497ac1a2658da76277c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":57,
                  "y":424},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dcb7afa0fc5e41ed943fc935ab8f84fe",
          "label":"新增_",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":418},
            "size":{
              "width":14,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b90f6e9129848aabaffde4b8c552426",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":418},
                "size":{
                  "width":14,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c54bd8a8c5124646a9b218c3723262df",
          "label":"新增_",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":52,
              "y":432},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c68f6543456469b98cd091e7c887224",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":52,
                  "y":432},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"380efbfa96614f729a59752762b4e8c9",
          "label":"新增_IC卡号",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":148,
              "y":429},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"b6ffcc5348a4445e98b41b018eedfe19",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":156,
              "y":114},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"a0f06529655240058b4ccfb01e44c573",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":52,
              "y":470},
            "size":{
              "width":88,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c714a568e9554a53a7b238d1a8150c36",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":52,
                  "y":470},
                "size":{
                  "width":88,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b258c860c37d4eafb54069f52826dec2",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":466},
            "size":{
              "width":400,
              "height":174}},
          "adaptiveStyles":{
}},
{
          "id":"a11a68e44a524e2ea6eb9e35febfb37c",
          "label":"新增_保存",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":285,
              "y":560},
            "size":{
              "width":130,
              "height":28}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"若某项为空<br> (If 部件文字 不明 = &quot;&quot; 或 部件文字 新增_IC卡号 = &quot;&quot; 或 选中项值 不明 = &quot;请选择&quot; 或 选中项值 不明 = &quot;请选择&quot; 或 选中项值 不明 = &quot;请选择&quot; 或 选中项值 不明 = &quot;全部&quot; 或 选中项值 不明 = &quot;请选择&quot; 或 选中项值 不明 = &quot;请选择&quot; 或 选中项值 不明 = &quot;请选择&quot; 或 选中项值 不明 = &quot;请选择&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"||",
                    "leftExpr":{
                      "exprType":"binaryOp",
                      "op":"==",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetWidgetText",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["205aa56a70094d68871dfb53ae1b370d"]}]},
                      "rightExpr":{
                        "exprType":"stringLiteral",
                        "value":"",
                        "stos":[]}},
                    "rightExpr":{
                      "exprType":"binaryOp",
                      "op":"||",
                      "leftExpr":{
                        "exprType":"binaryOp",
                        "op":"==",
                        "leftExpr":{
                          "exprType":"fcall",
                          "functionName":"GetWidgetText",
                          "arguments":[{
                              "exprType":"pathLiteral",
                              "isThis":false,
                              "isFocused":false,
                              "isTarget":false,
                              "value":["53279d324a474fddabc5ab5d3fc1d846"]}]},
                        "rightExpr":{
                          "exprType":"stringLiteral",
                          "value":"",
                          "stos":[]}},
                      "rightExpr":{
                        "exprType":"binaryOp",
                        "op":"||",
                        "leftExpr":{
                          "exprType":"binaryOp",
                          "op":"==",
                          "leftExpr":{
                            "exprType":"fcall",
                            "functionName":"GetSelectedOption",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["ed2d05c358ad461aa42b24262ca78e5e"]}]},
                          "rightExpr":{
                            "exprType":"stringLiteral",
                            "value":"请选择",
                            "stos":[]}},
                        "rightExpr":{
                          "exprType":"binaryOp",
                          "op":"||",
                          "leftExpr":{
                            "exprType":"binaryOp",
                            "op":"==",
                            "leftExpr":{
                              "exprType":"fcall",
                              "functionName":"GetSelectedOption",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["2e5d09a1b7ec445ea188ab353d2ccf72"]}]},
                            "rightExpr":{
                              "exprType":"stringLiteral",
                              "value":"请选择",
                              "stos":[]}},
                          "rightExpr":{
                            "exprType":"binaryOp",
                            "op":"||",
                            "leftExpr":{
                              "exprType":"binaryOp",
                              "op":"==",
                              "leftExpr":{
                                "exprType":"fcall",
                                "functionName":"GetSelectedOption",
                                "arguments":[{
                                    "exprType":"pathLiteral",
                                    "isThis":false,
                                    "isFocused":false,
                                    "isTarget":false,
                                    "value":["bf2437c09dd740fda8c39a7aa70527eb"]}]},
                              "rightExpr":{
                                "exprType":"stringLiteral",
                                "value":"请选择",
                                "stos":[]}},
                            "rightExpr":{
                              "exprType":"binaryOp",
                              "op":"||",
                              "leftExpr":{
                                "exprType":"binaryOp",
                                "op":"==",
                                "leftExpr":{
                                  "exprType":"fcall",
                                  "functionName":"GetSelectedOption",
                                  "arguments":[{
                                      "exprType":"pathLiteral",
                                      "isThis":false,
                                      "isFocused":false,
                                      "isTarget":false,
                                      "value":["8f1393abf5934e77a03acc069dc04b49"]}]},
                                "rightExpr":{
                                  "exprType":"stringLiteral",
                                  "value":"全部",
                                  "stos":[]}},
                              "rightExpr":{
                                "exprType":"binaryOp",
                                "op":"||",
                                "leftExpr":{
                                  "exprType":"binaryOp",
                                  "op":"==",
                                  "leftExpr":{
                                    "exprType":"fcall",
                                    "functionName":"GetSelectedOption",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":false,
                                        "isFocused":false,
                                        "isTarget":false,
                                        "value":["db7aae2299414ac9af71ff1c2529fb6e"]}]},
                                  "rightExpr":{
                                    "exprType":"stringLiteral",
                                    "value":"请选择",
                                    "stos":[]}},
                                "rightExpr":{
                                  "exprType":"binaryOp",
                                  "op":"||",
                                  "leftExpr":{
                                    "exprType":"binaryOp",
                                    "op":"==",
                                    "leftExpr":{
                                      "exprType":"fcall",
                                      "functionName":"GetSelectedOption",
                                      "arguments":[{
                                          "exprType":"pathLiteral",
                                          "isThis":false,
                                          "isFocused":false,
                                          "isTarget":false,
                                          "value":["dbc5031492c243159f28ade0847ba565"]}]},
                                    "rightExpr":{
                                      "exprType":"stringLiteral",
                                      "value":"请选择",
                                      "stos":[]}},
                                  "rightExpr":{
                                    "exprType":"binaryOp",
                                    "op":"||",
                                    "leftExpr":{
                                      "exprType":"binaryOp",
                                      "op":"==",
                                      "leftExpr":{
                                        "exprType":"fcall",
                                        "functionName":"GetSelectedOption",
                                        "arguments":[{
                                            "exprType":"pathLiteral",
                                            "isThis":false,
                                            "isFocused":false,
                                            "isTarget":false,
                                            "value":["50cb0f8762ee4c7180bd74a21e5a5c21"]}]},
                                      "rightExpr":{
                                        "exprType":"stringLiteral",
                                        "value":"请选择",
                                        "stos":[]}},
                                    "rightExpr":{
                                      "exprType":"binaryOp",
                                      "op":"==",
                                      "leftExpr":{
                                        "exprType":"fcall",
                                        "functionName":"GetSelectedOption",
                                        "arguments":[{
                                            "exprType":"pathLiteral",
                                            "isThis":false,
                                            "isFocused":false,
                                            "isTarget":false,
                                            "value":["22beeb103c22409a92adfcbf4e9ba188"]}]},
                                      "rightExpr":{
                                        "exprType":"stringLiteral",
                                        "value":"请选择",
                                        "stos":[]}}}}}}}}}}},
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 新增未填提示",
                      "objectsToFades":[{
                          "objectPath":["cfc294824ce04241b1918c9c101e2afd"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]},
{
                  "description":"若全有<br> (Else If True)",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 变量 yys_name = 选中项值 不明, 且<br> 变量 car_chePai_card = 部件文字 不明, 且<br> 变量 car_chePai_color = 选中项值 不明, 且<br> 变量 car_leixing = 选中项值 不明, 且<br> 变量 car_ICcard = 部件文字 新增_IC卡号, 且<br> 变量 yy_leixing = 选中项值 不明, 且<br> 变量 car_InterNet_leixing = 选中项值 不明, 且<br> 变量 car_jingYingLuXian = 选中项值 不明, 且<br> 变量 car_zhuangTai = 选中项值 不明, 且<br> 变量 quYu = 选中项值 不明",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"car_ICcard"},
{
                                "exprType":"fcall",
                                "functionName":"GetWidgetText",
                                "arguments":[{
                                    "exprType":"pathLiteral",
                                    "isThis":false,
                                    "isFocused":false,
                                    "isTarget":false,
                                    "value":["53279d324a474fddabc5ab5d3fc1d846"]}]}]}]}},
{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 车辆保险",
                      "target":{
                        "targetType":"page",
                        "url":"车辆保险_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"aa7e7fc299f543aabbab3ea7350f5bac",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":72,
              "y":674},
            "size":{
              "width":29,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ed25d4f92c64551b9f540689ea776d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":72,
                  "y":674},
                "size":{
                  "width":29,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b699262919af4efea4068e16c9e698ed",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":148,
              "y":680},
            "size":{
              "width":402,
              "height":120}},
          "adaptiveStyles":{
}},
{
          "id":"ba4af9f9daea436bbc09e20e4b986c67",
          "label":"新增_保存",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":156,
              "y":829},
            "size":{
              "width":130,
              "height":28}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"若某项为空<br> (If 部件文字 不明 = &quot;&quot; 或 部件文字 新增_IC卡号 = &quot;&quot; 或 选中项值 不明 = &quot;请选择&quot; 或 选中项值 不明 = &quot;请选择&quot; 或 选中项值 不明 = &quot;请选择&quot; 或 选中项值 不明 = &quot;全部&quot; 或 选中项值 不明 = &quot;请选择&quot; 或 选中项值 不明 = &quot;请选择&quot; 或 选中项值 不明 = &quot;请选择&quot; 或 选中项值 不明 = &quot;请选择&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"||",
                    "leftExpr":{
                      "exprType":"binaryOp",
                      "op":"==",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetWidgetText",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["205aa56a70094d68871dfb53ae1b370d"]}]},
                      "rightExpr":{
                        "exprType":"stringLiteral",
                        "value":"",
                        "stos":[]}},
                    "rightExpr":{
                      "exprType":"binaryOp",
                      "op":"||",
                      "leftExpr":{
                        "exprType":"binaryOp",
                        "op":"==",
                        "leftExpr":{
                          "exprType":"fcall",
                          "functionName":"GetWidgetText",
                          "arguments":[{
                              "exprType":"pathLiteral",
                              "isThis":false,
                              "isFocused":false,
                              "isTarget":false,
                              "value":["53279d324a474fddabc5ab5d3fc1d846"]}]},
                        "rightExpr":{
                          "exprType":"stringLiteral",
                          "value":"",
                          "stos":[]}},
                      "rightExpr":{
                        "exprType":"binaryOp",
                        "op":"||",
                        "leftExpr":{
                          "exprType":"binaryOp",
                          "op":"==",
                          "leftExpr":{
                            "exprType":"fcall",
                            "functionName":"GetSelectedOption",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["ed2d05c358ad461aa42b24262ca78e5e"]}]},
                          "rightExpr":{
                            "exprType":"stringLiteral",
                            "value":"请选择",
                            "stos":[]}},
                        "rightExpr":{
                          "exprType":"binaryOp",
                          "op":"||",
                          "leftExpr":{
                            "exprType":"binaryOp",
                            "op":"==",
                            "leftExpr":{
                              "exprType":"fcall",
                              "functionName":"GetSelectedOption",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["2e5d09a1b7ec445ea188ab353d2ccf72"]}]},
                            "rightExpr":{
                              "exprType":"stringLiteral",
                              "value":"请选择",
                              "stos":[]}},
                          "rightExpr":{
                            "exprType":"binaryOp",
                            "op":"||",
                            "leftExpr":{
                              "exprType":"binaryOp",
                              "op":"==",
                              "leftExpr":{
                                "exprType":"fcall",
                                "functionName":"GetSelectedOption",
                                "arguments":[{
                                    "exprType":"pathLiteral",
                                    "isThis":false,
                                    "isFocused":false,
                                    "isTarget":false,
                                    "value":["bf2437c09dd740fda8c39a7aa70527eb"]}]},
                              "rightExpr":{
                                "exprType":"stringLiteral",
                                "value":"请选择",
                                "stos":[]}},
                            "rightExpr":{
                              "exprType":"binaryOp",
                              "op":"||",
                              "leftExpr":{
                                "exprType":"binaryOp",
                                "op":"==",
                                "leftExpr":{
                                  "exprType":"fcall",
                                  "functionName":"GetSelectedOption",
                                  "arguments":[{
                                      "exprType":"pathLiteral",
                                      "isThis":false,
                                      "isFocused":false,
                                      "isTarget":false,
                                      "value":["8f1393abf5934e77a03acc069dc04b49"]}]},
                                "rightExpr":{
                                  "exprType":"stringLiteral",
                                  "value":"全部",
                                  "stos":[]}},
                              "rightExpr":{
                                "exprType":"binaryOp",
                                "op":"||",
                                "leftExpr":{
                                  "exprType":"binaryOp",
                                  "op":"==",
                                  "leftExpr":{
                                    "exprType":"fcall",
                                    "functionName":"GetSelectedOption",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":false,
                                        "isFocused":false,
                                        "isTarget":false,
                                        "value":["db7aae2299414ac9af71ff1c2529fb6e"]}]},
                                  "rightExpr":{
                                    "exprType":"stringLiteral",
                                    "value":"请选择",
                                    "stos":[]}},
                                "rightExpr":{
                                  "exprType":"binaryOp",
                                  "op":"||",
                                  "leftExpr":{
                                    "exprType":"binaryOp",
                                    "op":"==",
                                    "leftExpr":{
                                      "exprType":"fcall",
                                      "functionName":"GetSelectedOption",
                                      "arguments":[{
                                          "exprType":"pathLiteral",
                                          "isThis":false,
                                          "isFocused":false,
                                          "isTarget":false,
                                          "value":["dbc5031492c243159f28ade0847ba565"]}]},
                                    "rightExpr":{
                                      "exprType":"stringLiteral",
                                      "value":"请选择",
                                      "stos":[]}},
                                  "rightExpr":{
                                    "exprType":"binaryOp",
                                    "op":"||",
                                    "leftExpr":{
                                      "exprType":"binaryOp",
                                      "op":"==",
                                      "leftExpr":{
                                        "exprType":"fcall",
                                        "functionName":"GetSelectedOption",
                                        "arguments":[{
                                            "exprType":"pathLiteral",
                                            "isThis":false,
                                            "isFocused":false,
                                            "isTarget":false,
                                            "value":["50cb0f8762ee4c7180bd74a21e5a5c21"]}]},
                                      "rightExpr":{
                                        "exprType":"stringLiteral",
                                        "value":"请选择",
                                        "stos":[]}},
                                    "rightExpr":{
                                      "exprType":"binaryOp",
                                      "op":"==",
                                      "leftExpr":{
                                        "exprType":"fcall",
                                        "functionName":"GetSelectedOption",
                                        "arguments":[{
                                            "exprType":"pathLiteral",
                                            "isThis":false,
                                            "isFocused":false,
                                            "isTarget":false,
                                            "value":["22beeb103c22409a92adfcbf4e9ba188"]}]},
                                      "rightExpr":{
                                        "exprType":"stringLiteral",
                                        "value":"请选择",
                                        "stos":[]}}}}}}}}}}},
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 新增未填提示",
                      "objectsToFades":[{
                          "objectPath":["cfc294824ce04241b1918c9c101e2afd"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]},
{
                  "description":"若全有<br> (Else If True)",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 变量 yys_name = 选中项值 不明, 且<br> 变量 car_chePai_card = 部件文字 不明, 且<br> 变量 car_chePai_color = 选中项值 不明, 且<br> 变量 car_leixing = 选中项值 不明, 且<br> 变量 car_ICcard = 部件文字 新增_IC卡号, 且<br> 变量 yy_leixing = 选中项值 不明, 且<br> 变量 car_InterNet_leixing = 选中项值 不明, 且<br> 变量 car_jingYingLuXian = 选中项值 不明, 且<br> 变量 car_zhuangTai = 选中项值 不明, 且<br> 变量 quYu = 选中项值 不明",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"car_ICcard"},
{
                                "exprType":"fcall",
                                "functionName":"GetWidgetText",
                                "arguments":[{
                                    "exprType":"pathLiteral",
                                    "isThis":false,
                                    "isFocused":false,
                                    "isTarget":false,
                                    "value":["53279d324a474fddabc5ab5d3fc1d846"]}]}]}]}},
{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 车辆保险",
                      "target":{
                        "targetType":"page",
                        "url":"车辆保险_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"59aeb488835444a99b79df03838096b5",
          "label":"新增_关闭",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":306,
              "y":826},
            "size":{
              "width":119,
              "height":34}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 变量 yys_name = &quot;&quot;, 且<br> 变量 car_chePai_card = &quot;&quot;, 且<br> 变量 car_chePai_color = &quot;&quot;, 且<br> 变量 car_leixing = &quot;&quot;, 且<br> 变量 car_ICcard = &quot;&quot;, 且<br> 变量 yy_leixing = &quot;&quot;, 且<br> 变量 car_InterNet_leixing = &quot;&quot;, 且<br> 变量 car_jingYingLuXian = &quot;&quot;, 且<br> 变量 car_zhuangTai = &quot;&quot;, 且<br> 变量 quYu = &quot;&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"yys_name"},
{
                                "exprType":"stringLiteral",
                                "value":"",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"car_chePai_card"},
{
                                "exprType":"stringLiteral",
                                "value":"",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"car_chePai_color"},
{
                                "exprType":"stringLiteral",
                                "value":"",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"car_leixing"},
{
                                "exprType":"stringLiteral",
                                "value":"",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"car_ICcard"},
{
                                "exprType":"stringLiteral",
                                "value":"",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"yy_leixing"},
{
                                "exprType":"stringLiteral",
                                "value":"",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"car_InterNet_leixing"},
{
                                "exprType":"stringLiteral",
                                "value":"",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"car_jingYingLuXian"},
{
                                "exprType":"stringLiteral",
                                "value":"",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"car_zhuangTai"},
{
                                "exprType":"stringLiteral",
                                "value":"",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"quYu"},
{
                                "exprType":"stringLiteral",
                                "value":"",
                                "stos":[]}]}]}},
{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 车辆保险",
                      "target":{
                        "targetType":"page",
                        "url":"车辆保险_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"9a6adc92c25b42cdaedd42c266818b55",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":384,
              "y":82},
            "size":{
              "width":31,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"251bdd2fdef54b37b381d30e23284bd2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":384,
                  "y":82},
                "size":{
                  "width":31,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"02770c174efb468e8d5874dbe6f0edd4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":285,
              "y":194},
            "size":{
              "width":31,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b38e961e459b4993b8487150647af3ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":285,
                  "y":194},
                "size":{
                  "width":31,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"300f2bfdaf7f4eafa67c6da260a49427",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":285,
              "y":236},
            "size":{
              "width":31,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"613966362a1549228d3f86a753f26cc2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":285,
                  "y":236},
                "size":{
                  "width":31,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8cd2e8630495426db475e1601cc869d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":310,
              "y":273},
            "size":{
              "width":31,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42b8b46d71ff4b34ababfb2d58ff4139",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":310,
                  "y":273},
                "size":{
                  "width":31,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"340d0f63d60f469cb8a3d4a54eb6ee9f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":278,
              "y":313},
            "size":{
              "width":31,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"853f5043edc44b289d242d830eaffbbc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":278,
                  "y":313},
                "size":{
                  "width":31,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7dcf88e4665941cea301eea80a551518",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":299,
              "y":351},
            "size":{
              "width":31,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a4c5fc1eb0049de9c1f8dd045aa6f7d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":299,
                  "y":351},
                "size":{
                  "width":31,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "e352ae0983e540809168db0fa728cdab":{
      "scriptId":"u0"},
    "e784f2fc702143279635c0bddbaddb6f":{
      "scriptId":"u1"},
    "2aafc8511ca248ccb07b640cdfb34137":{
      "scriptId":"u2"},
    "9d6952d3a06d4cd4acba38176723b671":{
      "scriptId":"u3"},
    "77f0a614a1664931a0360ee4e4b5ef86":{
      "scriptId":"u4"},
    "4a4df2185ef14019aebb904656485b5c":{
      "scriptId":"u5"},
    "183e8f106c6f4ea3848cf7bff99eb7ee":{
      "scriptId":"u6"},
    "bc28d10125ef462da82bbbd930899962":{
      "scriptId":"u7"},
    "b5ec45c11ae3447c9967e2320dd78b63":{
      "scriptId":"u8"},
    "60dc59ed8f73400a912e32351642d715":{
      "scriptId":"u9"},
    "4189794da15244319b48f72c634e12cb":{
      "scriptId":"u10"},
    "fb7730bf8dc6490c809eb63140be98df":{
      "scriptId":"u11"},
    "d9b69d1febf6404782b2a25e72b76ff3":{
      "scriptId":"u12"},
    "4acbb01454b14bbdb41433744023b138":{
      "scriptId":"u13"},
    "4a0bfcf877a84b61b092da73ed720502":{
      "scriptId":"u14"},
    "2561e3b28f6d460e89f5629a3fc0aadd":{
      "scriptId":"u15"},
    "ecf591cc47a6420cb567429777279bd4":{
      "scriptId":"u16"},
    "d147a22984934636b32ee82b3eea1955":{
      "scriptId":"u17"},
    "53279d324a474fddabc5ab5d3fc1d846":{
      "scriptId":"u18"},
    "95fd5f0a89f046d3ab55e3a304058987":{
      "scriptId":"u19"},
    "65dffacd13ed40178291669b83656752":{
      "scriptId":"u20"},
    "4d8adff86be6469c88cd8fc2765ed4fb":{
      "scriptId":"u21"},
    "cfc294824ce04241b1918c9c101e2afd":{
      "scriptId":"u22"},
    "5da83d3f86154f3eade7a4b23860301f":{
      "scriptId":"u23"},
    "35e0d049aa9e407eb0b1166d4fce1c22":{
      "scriptId":"u24"},
    "60755fc0ef2d46039533731c8bb087fe":{
      "scriptId":"u25"},
    "c2c84e5638874e4cae11e9655d29dd43":{
      "scriptId":"u26"},
    "726e8156ccb9454c809ff8929e0e9aa2":{
      "scriptId":"u27"},
    "31cd5bd65d5a48ef86bc1297af0b3e08":{
      "scriptId":"u28"},
    "c1c7841b607346ffaff7b3b90b13ce97":{
      "scriptId":"u29"},
    "cda929809b5a4e21a874f0069b59f9dc":{
      "scriptId":"u30"},
    "fb03e2b58f264739b0af239f236d4744":{
      "scriptId":"u31"},
    "80e6a55224534d87aaeb0ae24ee15e6a":{
      "scriptId":"u32"},
    "6c8e2c9f74264933a779dcad94d4b482":{
      "scriptId":"u33"},
    "3726b89e1be2463292b247b4452f0327":{
      "scriptId":"u34"},
    "fb46979f5ded41978368d56cc3b7e523":{
      "scriptId":"u35"},
    "67c3e4a5ade54497ac1a2658da76277c":{
      "scriptId":"u36"},
    "dcb7afa0fc5e41ed943fc935ab8f84fe":{
      "scriptId":"u37"},
    "0b90f6e9129848aabaffde4b8c552426":{
      "scriptId":"u38"},
    "c54bd8a8c5124646a9b218c3723262df":{
      "scriptId":"u39"},
    "1c68f6543456469b98cd091e7c887224":{
      "scriptId":"u40"},
    "380efbfa96614f729a59752762b4e8c9":{
      "scriptId":"u41"},
    "b6ffcc5348a4445e98b41b018eedfe19":{
      "scriptId":"u42"},
    "a0f06529655240058b4ccfb01e44c573":{
      "scriptId":"u43"},
    "c714a568e9554a53a7b238d1a8150c36":{
      "scriptId":"u44"},
    "b258c860c37d4eafb54069f52826dec2":{
      "scriptId":"u45"},
    "a11a68e44a524e2ea6eb9e35febfb37c":{
      "scriptId":"u46"},
    "aa7e7fc299f543aabbab3ea7350f5bac":{
      "scriptId":"u47"},
    "2ed25d4f92c64551b9f540689ea776d3":{
      "scriptId":"u48"},
    "b699262919af4efea4068e16c9e698ed":{
      "scriptId":"u49"},
    "ba4af9f9daea436bbc09e20e4b986c67":{
      "scriptId":"u50"},
    "59aeb488835444a99b79df03838096b5":{
      "scriptId":"u51"},
    "9a6adc92c25b42cdaedd42c266818b55":{
      "scriptId":"u52"},
    "251bdd2fdef54b37b381d30e23284bd2":{
      "scriptId":"u53"},
    "02770c174efb468e8d5874dbe6f0edd4":{
      "scriptId":"u54"},
    "b38e961e459b4993b8487150647af3ce":{
      "scriptId":"u55"},
    "300f2bfdaf7f4eafa67c6da260a49427":{
      "scriptId":"u56"},
    "613966362a1549228d3f86a753f26cc2":{
      "scriptId":"u57"},
    "8cd2e8630495426db475e1601cc869d6":{
      "scriptId":"u58"},
    "42b8b46d71ff4b34ababfb2d58ff4139":{
      "scriptId":"u59"},
    "340d0f63d60f469cb8a3d4a54eb6ee9f":{
      "scriptId":"u60"},
    "853f5043edc44b289d242d830eaffbbc":{
      "scriptId":"u61"},
    "7dcf88e4665941cea301eea80a551518":{
      "scriptId":"u62"},
    "0a4c5fc1eb0049de9c1f8dd045aa6f7d":{
      "scriptId":"u63"}}});