$axure.loadCurrentPage({
  "url":"车辆保险新增页面.html",
  "generationDate":new Date(1558324040375.48),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"yys_name",
"car_chePai_card",
"car_chePai_color",
"car_leixing",
"car_ICcard",
"yy_leixing",
"car_InterNet_leixing",
"car_jingYingLuXian",
"car_zhuangTai",
"quYu",
"phone",
"mail",
"name",
"NewVariable"],
  "page":{
    "packageId":"0979b06aa63e459eaf106ae571f43e64",
    "type":"Axure:Page",
    "name":"车辆保险新增页面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f96743f327a44fdbbb042f4cd4ee9c38",
          "label":"编辑_弹框",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":30,
              "y":37},
            "size":{
              "width":1000,
              "height":1003}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14e84936092d41a58ae31e7cc86b598f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":30,
                  "y":37},
                "size":{
                  "width":1000,
                  "height":1003}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/车辆保险新增页面/编辑_弹框_u0.png"}},
{
          "id":"9726f5ad526341d6b744b284bbf96bc9",
          "label":"新增_",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":61,
              "y":117},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"348d48641bad4fddba0ee836f9eaba76",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":61,
                  "y":117},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c26272bb6a62410a9f5bd6ea121fbf82",
          "label":"新增_",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":61,
              "y":196},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eade1ae6d43a49a48138d96275504a7f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":61,
                  "y":196},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8df12f10104745848e5a11462edfdc23",
          "label":"新增_",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":61,
              "y":235},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3cbe2675a944e2ea8556111b7ff8c1e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":61,
                  "y":235},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e2e21b5c5a454aabbd816bfc26f6a80f",
          "label":"新增_",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":61,
              "y":273},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e3d016a25f54f74b5181bf2aaaff65b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":61,
                  "y":273},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1318c0a12b484a38bdb639e3961a26da",
          "label":"新增_",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":61,
              "y":313},
            "size":{
              "width":52,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6abdbdc13a44079b0bf452d0063f3e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":61,
                  "y":313},
                "size":{
                  "width":52,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"41bf881c347e4e228595c32f74cb7fae",
          "label":"新增_",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":61,
              "y":351},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cace349f305b4a9dbcd0788af0e7c4ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":61,
                  "y":351},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4d5054b14c1e48c8936bfc44af1095ec",
          "label":"新增_",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":73,
              "y":395},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c843d2666eb1454d8dfe1b8198f58260",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":73,
                  "y":395},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"76775f7f5ba54e93975b0489256f07d2",
          "label":"新增_IC卡号",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":156,
              "y":267},
            "size":{
              "width":120,
              "height":28}},
          "adaptiveStyles":{
}},
{
          "id":"f6cd598c2ebe41439e2bbd9b11618505",
          "label":"新增_",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":74,
              "y":85},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"236a46e22ec946c49c56a293a1583276",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":74,
                  "y":85},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"28912a0317fd440987f583a7e6c9239a",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":1074,
              "y":177},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"center",
          "fixedMarginHorizontal":0,
          "fixedVertical":"middle",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"f325bea129ed4421a8b12e73a4448d5f",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"066cb00cef654cfdb2c2c47ce6b35d25",
                  "label":"新增未填提示",
                  "parentDynamicPanel":"28912a0317fd440987f583a7e6c9239a",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":286,
                      "height":120}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f6b4f9a28c5c47bbae8d3c63452db4eb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"28912a0317fd440987f583a7e6c9239a",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":286,
                          "height":120}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onMouseOver":{
                      "description":"OnMouseOver",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"wait",
                              "description":"等待1000毫秒",
                              "waitTime":1000},
{
                              "action":"fadeWidget",
                              "description":"隐藏 新增未填提示",
                              "objectsToFades":[{
                                  "objectPath":["066cb00cef654cfdb2c2c47ce6b35d25"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "images":{
                    "normal~":"images/车辆维护保养新增页面/新增未填提示_u1.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"9bcb74889495492082ee3ef01967800a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":276,
              "y":267},
            "size":{
              "width":29,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cccfb1430a384fef83b2332ebdc2012c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":276,
                  "y":267},
                "size":{
                  "width":29,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/车辆保险新增页面/u22.png"}},
{
          "id":"86d3daec7cca4e9f90365d57377f350b",
          "label":"新增_IC卡号",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":156,
              "y":305},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"e4f2ed862eb441528ba93165997442a0",
          "label":"新增_IC卡号",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":148,
              "y":389},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"c94aedd6ab1041cba39d5f5b0111f8a3",
          "label":"新增_",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":57,
              "y":424},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5431210594f442e0a01b44284697fe25",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":57,
                  "y":424},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c0661a545d0c4313bf07ca32fcba421c",
          "label":"新增_",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":418},
            "size":{
              "width":14,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5740867dbd93457c8cc255e7caf6e5e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":418},
                "size":{
                  "width":14,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c047790065f44b0a8b8b013261003b04",
          "label":"新增_",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":47,
              "y":429},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27318af8e3794afdb63fc2e2a9bff4a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":47,
                  "y":429},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f79989b9f77a4b54acf4f44034a74f28",
          "label":"新增_IC卡号",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":148,
              "y":429},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"5c5cb304cf6f4872bee403159f0595ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":52,
              "y":470},
            "size":{
              "width":88,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45c09e0f29674406b575c9ebb72d4cc9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":52,
                  "y":470},
                "size":{
                  "width":88,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d45822e0b70f421288f6f1be334c6674",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":466},
            "size":{
              "width":400,
              "height":174}},
          "adaptiveStyles":{
}},
{
          "id":"39ddb5fb384742cfa96e3ae7dba8e32e",
          "label":"新增_保存",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":285,
              "y":560},
            "size":{
              "width":130,
              "height":28}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"若某项为空<br> (If 部件文字 不明 = &quot;&quot; 或 部件文字 新增_IC卡号 = &quot;&quot; 或 选中项值 不明 = &quot;请选择&quot; 或 选中项值 不明 = &quot;请选择&quot; 或 选中项值 不明 = &quot;请选择&quot; 或 选中项值 不明 = &quot;全部&quot; 或 选中项值 不明 = &quot;请选择&quot; 或 选中项值 不明 = &quot;请选择&quot; 或 选中项值 不明 = &quot;请选择&quot; 或 选中项值 不明 = &quot;请选择&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"||",
                    "leftExpr":{
                      "exprType":"binaryOp",
                      "op":"==",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetWidgetText",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["205aa56a70094d68871dfb53ae1b370d"]}]},
                      "rightExpr":{
                        "exprType":"stringLiteral",
                        "value":"",
                        "stos":[]}},
                    "rightExpr":{
                      "exprType":"binaryOp",
                      "op":"||",
                      "leftExpr":{
                        "exprType":"binaryOp",
                        "op":"==",
                        "leftExpr":{
                          "exprType":"fcall",
                          "functionName":"GetWidgetText",
                          "arguments":[{
                              "exprType":"pathLiteral",
                              "isThis":false,
                              "isFocused":false,
                              "isTarget":false,
                              "value":["76775f7f5ba54e93975b0489256f07d2"]}]},
                        "rightExpr":{
                          "exprType":"stringLiteral",
                          "value":"",
                          "stos":[]}},
                      "rightExpr":{
                        "exprType":"binaryOp",
                        "op":"||",
                        "leftExpr":{
                          "exprType":"binaryOp",
                          "op":"==",
                          "leftExpr":{
                            "exprType":"fcall",
                            "functionName":"GetSelectedOption",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["ed2d05c358ad461aa42b24262ca78e5e"]}]},
                          "rightExpr":{
                            "exprType":"stringLiteral",
                            "value":"请选择",
                            "stos":[]}},
                        "rightExpr":{
                          "exprType":"binaryOp",
                          "op":"||",
                          "leftExpr":{
                            "exprType":"binaryOp",
                            "op":"==",
                            "leftExpr":{
                              "exprType":"fcall",
                              "functionName":"GetSelectedOption",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["2e5d09a1b7ec445ea188ab353d2ccf72"]}]},
                            "rightExpr":{
                              "exprType":"stringLiteral",
                              "value":"请选择",
                              "stos":[]}},
                          "rightExpr":{
                            "exprType":"binaryOp",
                            "op":"||",
                            "leftExpr":{
                              "exprType":"binaryOp",
                              "op":"==",
                              "leftExpr":{
                                "exprType":"fcall",
                                "functionName":"GetSelectedOption",
                                "arguments":[{
                                    "exprType":"pathLiteral",
                                    "isThis":false,
                                    "isFocused":false,
                                    "isTarget":false,
                                    "value":["bf2437c09dd740fda8c39a7aa70527eb"]}]},
                              "rightExpr":{
                                "exprType":"stringLiteral",
                                "value":"请选择",
                                "stos":[]}},
                            "rightExpr":{
                              "exprType":"binaryOp",
                              "op":"||",
                              "leftExpr":{
                                "exprType":"binaryOp",
                                "op":"==",
                                "leftExpr":{
                                  "exprType":"fcall",
                                  "functionName":"GetSelectedOption",
                                  "arguments":[{
                                      "exprType":"pathLiteral",
                                      "isThis":false,
                                      "isFocused":false,
                                      "isTarget":false,
                                      "value":["8f1393abf5934e77a03acc069dc04b49"]}]},
                                "rightExpr":{
                                  "exprType":"stringLiteral",
                                  "value":"全部",
                                  "stos":[]}},
                              "rightExpr":{
                                "exprType":"binaryOp",
                                "op":"||",
                                "leftExpr":{
                                  "exprType":"binaryOp",
                                  "op":"==",
                                  "leftExpr":{
                                    "exprType":"fcall",
                                    "functionName":"GetSelectedOption",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":false,
                                        "isFocused":false,
                                        "isTarget":false,
                                        "value":["db7aae2299414ac9af71ff1c2529fb6e"]}]},
                                  "rightExpr":{
                                    "exprType":"stringLiteral",
                                    "value":"请选择",
                                    "stos":[]}},
                                "rightExpr":{
                                  "exprType":"binaryOp",
                                  "op":"||",
                                  "leftExpr":{
                                    "exprType":"binaryOp",
                                    "op":"==",
                                    "leftExpr":{
                                      "exprType":"fcall",
                                      "functionName":"GetSelectedOption",
                                      "arguments":[{
                                          "exprType":"pathLiteral",
                                          "isThis":false,
                                          "isFocused":false,
                                          "isTarget":false,
                                          "value":["dbc5031492c243159f28ade0847ba565"]}]},
                                    "rightExpr":{
                                      "exprType":"stringLiteral",
                                      "value":"请选择",
                                      "stos":[]}},
                                  "rightExpr":{
                                    "exprType":"binaryOp",
                                    "op":"||",
                                    "leftExpr":{
                                      "exprType":"binaryOp",
                                      "op":"==",
                                      "leftExpr":{
                                        "exprType":"fcall",
                                        "functionName":"GetSelectedOption",
                                        "arguments":[{
                                            "exprType":"pathLiteral",
                                            "isThis":false,
                                            "isFocused":false,
                                            "isTarget":false,
                                            "value":["50cb0f8762ee4c7180bd74a21e5a5c21"]}]},
                                      "rightExpr":{
                                        "exprType":"stringLiteral",
                                        "value":"请选择",
                                        "stos":[]}},
                                    "rightExpr":{
                                      "exprType":"binaryOp",
                                      "op":"==",
                                      "leftExpr":{
                                        "exprType":"fcall",
                                        "functionName":"GetSelectedOption",
                                        "arguments":[{
                                            "exprType":"pathLiteral",
                                            "isThis":false,
                                            "isFocused":false,
                                            "isTarget":false,
                                            "value":["22beeb103c22409a92adfcbf4e9ba188"]}]},
                                      "rightExpr":{
                                        "exprType":"stringLiteral",
                                        "value":"请选择",
                                        "stos":[]}}}}}}}}}}},
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 新增未填提示",
                      "objectsToFades":[{
                          "objectPath":["066cb00cef654cfdb2c2c47ce6b35d25"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]},
{
                  "description":"若全有<br> (Else If True)",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 变量 yys_name = 选中项值 不明, 且<br> 变量 car_chePai_card = 部件文字 不明, 且<br> 变量 car_chePai_color = 选中项值 不明, 且<br> 变量 car_leixing = 选中项值 不明, 且<br> 变量 car_ICcard = 部件文字 新增_IC卡号, 且<br> 变量 yy_leixing = 选中项值 不明, 且<br> 变量 car_InterNet_leixing = 选中项值 不明, 且<br> 变量 car_jingYingLuXian = 选中项值 不明, 且<br> 变量 car_zhuangTai = 选中项值 不明, 且<br> 变量 quYu = 选中项值 不明",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"car_ICcard"},
{
                                "exprType":"fcall",
                                "functionName":"GetWidgetText",
                                "arguments":[{
                                    "exprType":"pathLiteral",
                                    "isThis":false,
                                    "isFocused":false,
                                    "isTarget":false,
                                    "value":["76775f7f5ba54e93975b0489256f07d2"]}]}]}]}},
{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 车辆基本信息",
                      "target":{
                        "targetType":"page",
                        "url":"车辆基本信息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"e1e388a295b348c6862826df92569040",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":84,
              "y":674},
            "size":{
              "width":29,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c51b73d68204411a517ade7e0eadeac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":84,
                  "y":674},
                "size":{
                  "width":29,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9cb150079c6b42cfa64965d1505c6839",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":148,
              "y":680},
            "size":{
              "width":402,
              "height":120}},
          "adaptiveStyles":{
}},
{
          "id":"85068f128d054d838e1cf7b8e602c144",
          "label":"新增_保存",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":156,
              "y":829},
            "size":{
              "width":130,
              "height":28}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 车辆基本信息",
                      "target":{
                        "targetType":"page",
                        "url":"车辆基本信息.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true},
{
          "id":"167c829b942547748e59d5fbecb945d9",
          "label":"保险新增关闭",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":829},
            "size":{
              "width":125,
              "height":31}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 确认,<br>取消,<br>确认要关闭么",
                      "objectsToFades":[{
                          "objectPath":["0892b22f67264175b91e711e53a78ab8"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["56f2fc661b3d4930b15cbcccaa59b5e7"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["c9fee1cc05ca4b28854ba0de4847e10b"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"0de5df74eb80421bb74470517f3ec1a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":337,
              "y":82},
            "size":{
              "width":31,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac78328eeb3c48c3b7f6a3b569a8d9b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":337,
                  "y":82},
                "size":{
                  "width":31,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b9daf353b614451f9d627a291438d0ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":310,
              "y":273},
            "size":{
              "width":31,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df2b79f6fa7b4612a77e8398d882fbaf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":310,
                  "y":273},
                "size":{
                  "width":31,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8b5f20acac9a4fbead32fe9e07954d95",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":278,
              "y":313},
            "size":{
              "width":31,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3febe93ef93d4433bc9d0a6ed3748ce7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":278,
                  "y":313},
                "size":{
                  "width":31,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5636cd9777984881833a04dfb4bc1e8f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":299,
              "y":351},
            "size":{
              "width":31,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd04968803ca4dd498b9c55ee393e5c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":299,
                  "y":351},
                "size":{
                  "width":31,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"00e009fa052849e3908e7cda3faa63bf",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":156,
              "y":82},
            "size":{
              "width":41,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"21338daae2124bff8a35a57ef8a24a6f",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":197,
              "y":82},
            "size":{
              "width":40,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"aa75f7f27a094d6485182881981efcaa",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":237,
              "y":82},
            "size":{
              "width":90,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"c75a70268bb447eea32c725ed719e130",
          "label":"营运类型框",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":156,
              "y":114},
            "size":{
              "width":107,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"36e1d7014dea4f58876929ae2bedf6d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":61,
              "y":149},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f959d2088d864a8b928d66af0c84cd18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":61,
                  "y":149},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"87995d91a3fa4e2a9b829c6bf5a3ee79",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":155,
              "y":149},
            "size":{
              "width":60,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"eea231321b6947eb8894bdbc2a790785",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":215,
              "y":149},
            "size":{
              "width":60,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"5f6d33389df14de3bbd155d534bb607e",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":275,
              "y":149},
            "size":{
              "width":60,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"a495476545ec4d1b8220e83de05e335b",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":335,
              "y":149},
            "size":{
              "width":100,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"30000bf3e891498f9d013e563539a5eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":266,
              "y":114},
            "size":{
              "width":31,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f6e4d1c40ca4799b6c1d6febd4dd2e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":266,
                  "y":114},
                "size":{
                  "width":31,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"436397fb607646878bc0b3f9091a2e78",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":155,
              "y":193},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"a9dd690a41e74976833edb14d541ee5a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":275,
              "y":193},
            "size":{
              "width":40,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"986f6e8f8ea74c38aed8426e83b8ffa9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":275,
                  "y":193},
                "size":{
                  "width":40,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/车辆保险信息管理/u79.png"}},
{
          "id":"6fd6aecea2e244c0a7b30eb177b7c82a",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":315,
              "y":193},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"ce428d31e0574351bc60114c3af1ab8d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":156,
              "y":235},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"591a931931d74b3fb4419ff2ec65c9b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":276,
              "y":235},
            "size":{
              "width":40,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b77a3970eff48399f530cc840ef6a61",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":276,
                  "y":235},
                "size":{
                  "width":40,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/车辆保险信息管理/u79.png"}},
{
          "id":"76ef0d2988e2489485f3b4017592e119",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":316,
              "y":235},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"a765440ff1224f439c3957b0d0b951f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":445,
              "y":193},
            "size":{
              "width":31,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47060934d9d14194bf801f0b217617c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":445,
                  "y":193},
                "size":{
                  "width":31,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c823e24769f04e498945cb4419042527",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":446,
              "y":235},
            "size":{
              "width":31,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84d84ec3fdcd40b3a9079fb70b1b5ea4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":446,
                  "y":235},
                "size":{
                  "width":31,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3c2b0291d5f740458b5f67f3c834257e",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":156,
              "y":345},
            "size":{
              "width":107,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"0892b22f67264175b91e711e53a78ab8",
          "label":"确认",
          "type":"button",
          "styleType":"button",
          "visible":false,
          "style":{
            "location":{
              "x":460,
              "y":880},
            "size":{
              "width":100,
              "height":25},
            "visible":false},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"closeCurrent",
                      "description":"关闭当前窗口"}]}]}},
          "tabbable":true},
{
          "id":"56f2fc661b3d4930b15cbcccaa59b5e7",
          "label":"取消",
          "type":"button",
          "styleType":"button",
          "visible":false,
          "style":{
            "location":{
              "x":600,
              "y":880},
            "size":{
              "width":96,
              "height":25},
            "visible":false},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 确认要关闭么,<br>确认,<br>取消",
                      "objectsToFades":[{
                          "objectPath":["c9fee1cc05ca4b28854ba0de4847e10b"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["0892b22f67264175b91e711e53a78ab8"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["56f2fc661b3d4930b15cbcccaa59b5e7"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"c9fee1cc05ca4b28854ba0de4847e10b",
          "label":"确认要关闭么",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "horizontalAlignment":"center",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":460,
              "y":810},
            "size":{
              "width":236,
              "height":70},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9d95744a6f547808652df9bb07565f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "horizontalAlignment":"center",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":460,
                  "y":810},
                "size":{
                  "width":236,
                  "height":70},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设备基本信息管理/确认要删除么_u76.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "f96743f327a44fdbbb042f4cd4ee9c38":{
      "scriptId":"u0"},
    "14e84936092d41a58ae31e7cc86b598f":{
      "scriptId":"u1"},
    "9726f5ad526341d6b744b284bbf96bc9":{
      "scriptId":"u2"},
    "348d48641bad4fddba0ee836f9eaba76":{
      "scriptId":"u3"},
    "c26272bb6a62410a9f5bd6ea121fbf82":{
      "scriptId":"u4"},
    "eade1ae6d43a49a48138d96275504a7f":{
      "scriptId":"u5"},
    "8df12f10104745848e5a11462edfdc23":{
      "scriptId":"u6"},
    "f3cbe2675a944e2ea8556111b7ff8c1e":{
      "scriptId":"u7"},
    "e2e21b5c5a454aabbd816bfc26f6a80f":{
      "scriptId":"u8"},
    "8e3d016a25f54f74b5181bf2aaaff65b":{
      "scriptId":"u9"},
    "1318c0a12b484a38bdb639e3961a26da":{
      "scriptId":"u10"},
    "e6abdbdc13a44079b0bf452d0063f3e5":{
      "scriptId":"u11"},
    "41bf881c347e4e228595c32f74cb7fae":{
      "scriptId":"u12"},
    "cace349f305b4a9dbcd0788af0e7c4ed":{
      "scriptId":"u13"},
    "4d5054b14c1e48c8936bfc44af1095ec":{
      "scriptId":"u14"},
    "c843d2666eb1454d8dfe1b8198f58260":{
      "scriptId":"u15"},
    "76775f7f5ba54e93975b0489256f07d2":{
      "scriptId":"u16"},
    "f6cd598c2ebe41439e2bbd9b11618505":{
      "scriptId":"u17"},
    "236a46e22ec946c49c56a293a1583276":{
      "scriptId":"u18"},
    "28912a0317fd440987f583a7e6c9239a":{
      "scriptId":"u19"},
    "066cb00cef654cfdb2c2c47ce6b35d25":{
      "scriptId":"u20"},
    "f6b4f9a28c5c47bbae8d3c63452db4eb":{
      "scriptId":"u21"},
    "9bcb74889495492082ee3ef01967800a":{
      "scriptId":"u22"},
    "cccfb1430a384fef83b2332ebdc2012c":{
      "scriptId":"u23"},
    "86d3daec7cca4e9f90365d57377f350b":{
      "scriptId":"u24"},
    "e4f2ed862eb441528ba93165997442a0":{
      "scriptId":"u25"},
    "c94aedd6ab1041cba39d5f5b0111f8a3":{
      "scriptId":"u26"},
    "5431210594f442e0a01b44284697fe25":{
      "scriptId":"u27"},
    "c0661a545d0c4313bf07ca32fcba421c":{
      "scriptId":"u28"},
    "5740867dbd93457c8cc255e7caf6e5e6":{
      "scriptId":"u29"},
    "c047790065f44b0a8b8b013261003b04":{
      "scriptId":"u30"},
    "27318af8e3794afdb63fc2e2a9bff4a7":{
      "scriptId":"u31"},
    "f79989b9f77a4b54acf4f44034a74f28":{
      "scriptId":"u32"},
    "5c5cb304cf6f4872bee403159f0595ac":{
      "scriptId":"u33"},
    "45c09e0f29674406b575c9ebb72d4cc9":{
      "scriptId":"u34"},
    "d45822e0b70f421288f6f1be334c6674":{
      "scriptId":"u35"},
    "39ddb5fb384742cfa96e3ae7dba8e32e":{
      "scriptId":"u36"},
    "e1e388a295b348c6862826df92569040":{
      "scriptId":"u37"},
    "7c51b73d68204411a517ade7e0eadeac":{
      "scriptId":"u38"},
    "9cb150079c6b42cfa64965d1505c6839":{
      "scriptId":"u39"},
    "85068f128d054d838e1cf7b8e602c144":{
      "scriptId":"u40"},
    "167c829b942547748e59d5fbecb945d9":{
      "scriptId":"u41"},
    "0de5df74eb80421bb74470517f3ec1a9":{
      "scriptId":"u42"},
    "ac78328eeb3c48c3b7f6a3b569a8d9b8":{
      "scriptId":"u43"},
    "b9daf353b614451f9d627a291438d0ca":{
      "scriptId":"u44"},
    "df2b79f6fa7b4612a77e8398d882fbaf":{
      "scriptId":"u45"},
    "8b5f20acac9a4fbead32fe9e07954d95":{
      "scriptId":"u46"},
    "3febe93ef93d4433bc9d0a6ed3748ce7":{
      "scriptId":"u47"},
    "5636cd9777984881833a04dfb4bc1e8f":{
      "scriptId":"u48"},
    "fd04968803ca4dd498b9c55ee393e5c8":{
      "scriptId":"u49"},
    "00e009fa052849e3908e7cda3faa63bf":{
      "scriptId":"u50"},
    "21338daae2124bff8a35a57ef8a24a6f":{
      "scriptId":"u51"},
    "aa75f7f27a094d6485182881981efcaa":{
      "scriptId":"u52"},
    "c75a70268bb447eea32c725ed719e130":{
      "scriptId":"u53"},
    "36e1d7014dea4f58876929ae2bedf6d5":{
      "scriptId":"u54"},
    "f959d2088d864a8b928d66af0c84cd18":{
      "scriptId":"u55"},
    "87995d91a3fa4e2a9b829c6bf5a3ee79":{
      "scriptId":"u56"},
    "eea231321b6947eb8894bdbc2a790785":{
      "scriptId":"u57"},
    "5f6d33389df14de3bbd155d534bb607e":{
      "scriptId":"u58"},
    "a495476545ec4d1b8220e83de05e335b":{
      "scriptId":"u59"},
    "30000bf3e891498f9d013e563539a5eb":{
      "scriptId":"u60"},
    "5f6e4d1c40ca4799b6c1d6febd4dd2e9":{
      "scriptId":"u61"},
    "436397fb607646878bc0b3f9091a2e78":{
      "scriptId":"u62"},
    "a9dd690a41e74976833edb14d541ee5a":{
      "scriptId":"u63"},
    "986f6e8f8ea74c38aed8426e83b8ffa9":{
      "scriptId":"u64"},
    "6fd6aecea2e244c0a7b30eb177b7c82a":{
      "scriptId":"u65"},
    "ce428d31e0574351bc60114c3af1ab8d":{
      "scriptId":"u66"},
    "591a931931d74b3fb4419ff2ec65c9b7":{
      "scriptId":"u67"},
    "1b77a3970eff48399f530cc840ef6a61":{
      "scriptId":"u68"},
    "76ef0d2988e2489485f3b4017592e119":{
      "scriptId":"u69"},
    "a765440ff1224f439c3957b0d0b951f1":{
      "scriptId":"u70"},
    "47060934d9d14194bf801f0b217617c6":{
      "scriptId":"u71"},
    "c823e24769f04e498945cb4419042527":{
      "scriptId":"u72"},
    "84d84ec3fdcd40b3a9079fb70b1b5ea4":{
      "scriptId":"u73"},
    "3c2b0291d5f740458b5f67f3c834257e":{
      "scriptId":"u74"},
    "0892b22f67264175b91e711e53a78ab8":{
      "scriptId":"u75"},
    "56f2fc661b3d4930b15cbcccaa59b5e7":{
      "scriptId":"u76"},
    "c9fee1cc05ca4b28854ba0de4847e10b":{
      "scriptId":"u77"},
    "f9d95744a6f547808652df9bb07565f6":{
      "scriptId":"u78"}}});