$axure.loadCurrentPage({
  "url":"填写单据信息.html",
  "generationDate":new Date(1557736120712.23),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n",
"rl_date",
"rl_day"],
  "page":{
    "packageId":"d3c1d1c268b246b09f286ac632cae217",
    "type":"Axure:Page",
    "name":"填写单据信息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"25242ea3c14f40f99076aa07478c5a6f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":105},
            "size":{
              "width":430,
              "height":835}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9dfaf56f597643abbf8c0cfc936338d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":530,
                  "y":105},
                "size":{
                  "width":430,
                  "height":835}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/填写单据信息/u0.png"}},
{
          "id":"b15ffb8fac514501967ffc9bbfcde4e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":571,
              "y":157},
            "size":{
              "width":97,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22b37c27208943a3ac844507adfe3696",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":571,
                  "y":157},
                "size":{
                  "width":97,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"af40284faacd412285ab562999b73245",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":593,
              "y":218},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f54640169da942288153ea68b68c9d97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":593,
                  "y":218},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e2fc6775a9dd4b1bb80093be701c48f1",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":670,
              "y":213.5},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"1cf3f0f5cc014d74ab907a46871752aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":594,
              "y":270},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c447033854b49e4a114a51a32f3a374",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":594,
                  "y":270},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b259b210522a4b11ad449849f6ee02c3",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":670,
              "y":265},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"302f2db5e12343a3bf4122398a60db2c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":578,
              "y":804},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0320c2af3fa24ed4b33b33d633365985",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":578,
                  "y":804},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"437604ef58e64c599f88d8556ad0873a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":578,
              "y":850},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4dcb3affea642af893ad275b6a9c02a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":578,
                  "y":850},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4c1d662888aa4952ab9e32d1005c1315",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":584,
              "y":430},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"239bcf0c6bd546c2839976765cefbfcc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":584,
                  "y":430},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1b6c5a1361e54427a71477f4622123f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":593,
              "y":410},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a2f78f996cd416a901bb5c157713cf8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":593,
                  "y":410},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6e148bb4555745d09c0185f6390c8089",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":669,
              "y":405},
            "size":{
              "width":131,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"215d86ad24f445d7a0f04feccb61f11d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":593,
              "y":890},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"7b371233963e41b5afbc0706693ed0d0",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":778,
              "y":890},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"c2e218d973d342ae8cbcf7a53b3eb76d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":592,
              "y":720},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9fa6429610244b04b3bac85ff19adfae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":592,
                  "y":720},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f35754de92f542ff8153ec7ef2daa00c",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":670.5,
              "y":720},
            "size":{
              "width":200,
              "height":60}},
          "adaptiveStyles":{
}},
{
          "id":"43d3febb34334d96b4e36554184a8c40",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":561,
              "y":665},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ddededacd7bf4e209a1838dc59ccdcaa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":561,
                  "y":665},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7e9e84852d6540c4b63911766560ebfe",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":670,
              "y":660},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"2af0dd6745d8409a884393d13f2fee70",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":661.5,
              "y":798},
            "size":{
              "width":60,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"e6b2d3eea62b41129a5715ae4f6fd468",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":721.5,
              "y":798},
            "size":{
              "width":55,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"0cc9c0725b1c4654af6efc0feeb6ffb7",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":776.5,
              "y":798},
            "size":{
              "width":55,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"368fd019c5df4372a4cba6f217a4b932",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":841.5,
              "y":798},
            "size":{
              "width":70,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"687c4081b03a46819a9758655bd76be6",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":661.5,
              "y":847},
            "size":{
              "width":60,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"85b6dc65d9784464bed9326771d5b2c4",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":776.5,
              "y":847},
            "size":{
              "width":55,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"2558716f9853484da194d5b16c8ef22a",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":841.5,
              "y":847},
            "size":{
              "width":70,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"5759709be4014ebca724ba84aa0503f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":593,
              "y":578},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7eced95308334c00b49e950a121a2861",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":593,
                  "y":578},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8fcbf6dd4c8f420fb1c39ca31e4d67ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":593,
              "y":320},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6cde582469dc4573a5960eb810b1aa49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":593,
                  "y":320},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e3cdc42f37ef4079b6969ed872755877",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":669,
              "y":315},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"2727519fd7ff4be3ad93c616e44fe9d2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":593,
              "y":365},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c1a6451b0df44c39038185ec973cb63",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":593,
                  "y":365},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0eae63576159480ca621ff99d533575a",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":669,
              "y":360},
            "size":{
              "width":131,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f1114b176840456f9929d034e4dafddd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":603,
              "y":450},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"496ee180bb3f43728389f180e0522c57",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":603,
                  "y":450},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9d883b9dae754ce7bce7ee6c057e8359",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":603,
              "y":494},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d54875e74d5416d91973ab7c7fec662",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":603,
                  "y":494},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fdb6908ffbc84710a47d95cbbafcdcb8",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":669,
              "y":450},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"c47c8889c4144ec19f14833e0fa2e1f4",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":670,
              "y":491},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"bafa319494ec44ad9d678cc03a300767",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":594,
              "y":540},
            "size":{
              "width":35,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56b9d948f072430694b5b6d6afa9e193",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":594,
                  "y":540},
                "size":{
                  "width":35,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"548123c5c40a4e00846a2815a71b1d5d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":670,
              "y":535},
            "size":{
              "width":186,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b891e04731f04254927e708c1ad7e504",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":670,
              "y":575},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"d185d7b7e0a04b6a9c6cc1959e363a29",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":721,
              "y":847},
            "size":{
              "width":55,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"eb59d59782fc4eb09805d746a8f0ac04",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":580,
              "y":620},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90c3f347d91c4713896b3a77a97a7d8d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":580,
                  "y":620},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a3c1be53ed54414e9c837c96582c4389",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":670,
              "y":615},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"c4b4a6ce9f1f46b59aed996a4ff5b5cb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":874,
              "y":218},
            "size":{
              "width":13,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8415419096db406ab80a53bdf9ad169e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":874,
                  "y":218},
                "size":{
                  "width":13,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0976ea6fb1d643aa927c4dfff995bb31",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":874,
              "y":270},
            "size":{
              "width":7,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66b0eeb1aa484a3191dae968b3c5aa48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":874,
                  "y":270},
                "size":{
                  "width":7,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"83fb65b8324c4c358bd0fdd307d85dae",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":874,
              "y":315},
            "size":{
              "width":7,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a9c4b9fba1544658605f609a6686493",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":874,
                  "y":315},
                "size":{
                  "width":7,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6e7c381a1cf84eecb0e2a0b9aabb3153",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":874,
              "y":365},
            "size":{
              "width":7,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1711c8d42b2c4cb68510d1913e1d6bed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":874,
                  "y":365},
                "size":{
                  "width":7,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"53264a55dd7342a3b872ca61737917a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":874,
              "y":410},
            "size":{
              "width":7,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8c2f2156bd04dbaab0f585e55cc7f60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":874,
                  "y":410},
                "size":{
                  "width":7,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"46fbd82ab66741839cb075860e8f0d02",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":874,
              "y":540},
            "size":{
              "width":7,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc59e7c3e28245df9c61fc14cdc8719d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":874,
                  "y":540},
                "size":{
                  "width":7,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7b2d443fb0214eb2ae3fce79763f01de",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":874,
              "y":620},
            "size":{
              "width":7,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a68da9dfe11b4ba7b4aaf0ab613eabc9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":874,
                  "y":620},
                "size":{
                  "width":7,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"89d85356df5b4cc9aca5c1d0c1dd6680",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":874,
              "y":664},
            "size":{
              "width":7,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c66f283651ce404f9d6bf6d7adf3350c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":874,
                  "y":664},
                "size":{
                  "width":7,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7b6cffc086fc47a0bad4d6fd57ef6a1e",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":810,
              "y":360},
            "size":{
              "width":60,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"543707a8057e4dd78879fd11933d6777",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":810,
              "y":405},
            "size":{
              "width":60,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"7111cf5ae69e422ea06d3eda06d8fea4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":856,
              "y":542},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01e3193bb09146aa8b7119f06949510c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":856,
                  "y":542},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"252132398a044fed9fdeaa5be2bd2e1e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
            "fontSize":"36px",
            "fontWeight":"500",
            "location":{
              "x":530,
              "y":54},
            "size":{
              "width":20,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74af9b5f4d1f4817b45d12793991c164",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
                "fontSize":"36px",
                "fontWeight":"500",
                "location":{
                  "x":530,
                  "y":54},
                "size":{
                  "width":20,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/填写单据信息/u76.png"}},
{
          "id":"4bc056ce08314db68ade1778765a9fbb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":560,
              "y":54},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c1446f3654c4026afbdd08779603564",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":560,
                  "y":54},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "25242ea3c14f40f99076aa07478c5a6f":{
      "scriptId":"u0"},
    "9dfaf56f597643abbf8c0cfc936338d7":{
      "scriptId":"u1"},
    "b15ffb8fac514501967ffc9bbfcde4e9":{
      "scriptId":"u2"},
    "22b37c27208943a3ac844507adfe3696":{
      "scriptId":"u3"},
    "af40284faacd412285ab562999b73245":{
      "scriptId":"u4"},
    "f54640169da942288153ea68b68c9d97":{
      "scriptId":"u5"},
    "e2fc6775a9dd4b1bb80093be701c48f1":{
      "scriptId":"u6"},
    "1cf3f0f5cc014d74ab907a46871752aa":{
      "scriptId":"u7"},
    "7c447033854b49e4a114a51a32f3a374":{
      "scriptId":"u8"},
    "b259b210522a4b11ad449849f6ee02c3":{
      "scriptId":"u9"},
    "302f2db5e12343a3bf4122398a60db2c":{
      "scriptId":"u10"},
    "0320c2af3fa24ed4b33b33d633365985":{
      "scriptId":"u11"},
    "437604ef58e64c599f88d8556ad0873a":{
      "scriptId":"u12"},
    "f4dcb3affea642af893ad275b6a9c02a":{
      "scriptId":"u13"},
    "4c1d662888aa4952ab9e32d1005c1315":{
      "scriptId":"u14"},
    "239bcf0c6bd546c2839976765cefbfcc":{
      "scriptId":"u15"},
    "1b6c5a1361e54427a71477f4622123f7":{
      "scriptId":"u16"},
    "7a2f78f996cd416a901bb5c157713cf8":{
      "scriptId":"u17"},
    "6e148bb4555745d09c0185f6390c8089":{
      "scriptId":"u18"},
    "215d86ad24f445d7a0f04feccb61f11d":{
      "scriptId":"u19"},
    "7b371233963e41b5afbc0706693ed0d0":{
      "scriptId":"u20"},
    "c2e218d973d342ae8cbcf7a53b3eb76d":{
      "scriptId":"u21"},
    "9fa6429610244b04b3bac85ff19adfae":{
      "scriptId":"u22"},
    "f35754de92f542ff8153ec7ef2daa00c":{
      "scriptId":"u23"},
    "43d3febb34334d96b4e36554184a8c40":{
      "scriptId":"u24"},
    "ddededacd7bf4e209a1838dc59ccdcaa":{
      "scriptId":"u25"},
    "7e9e84852d6540c4b63911766560ebfe":{
      "scriptId":"u26"},
    "2af0dd6745d8409a884393d13f2fee70":{
      "scriptId":"u27"},
    "e6b2d3eea62b41129a5715ae4f6fd468":{
      "scriptId":"u28"},
    "0cc9c0725b1c4654af6efc0feeb6ffb7":{
      "scriptId":"u29"},
    "368fd019c5df4372a4cba6f217a4b932":{
      "scriptId":"u30"},
    "687c4081b03a46819a9758655bd76be6":{
      "scriptId":"u31"},
    "85b6dc65d9784464bed9326771d5b2c4":{
      "scriptId":"u32"},
    "2558716f9853484da194d5b16c8ef22a":{
      "scriptId":"u33"},
    "5759709be4014ebca724ba84aa0503f5":{
      "scriptId":"u34"},
    "7eced95308334c00b49e950a121a2861":{
      "scriptId":"u35"},
    "8fcbf6dd4c8f420fb1c39ca31e4d67ba":{
      "scriptId":"u36"},
    "6cde582469dc4573a5960eb810b1aa49":{
      "scriptId":"u37"},
    "e3cdc42f37ef4079b6969ed872755877":{
      "scriptId":"u38"},
    "2727519fd7ff4be3ad93c616e44fe9d2":{
      "scriptId":"u39"},
    "8c1a6451b0df44c39038185ec973cb63":{
      "scriptId":"u40"},
    "0eae63576159480ca621ff99d533575a":{
      "scriptId":"u41"},
    "f1114b176840456f9929d034e4dafddd":{
      "scriptId":"u42"},
    "496ee180bb3f43728389f180e0522c57":{
      "scriptId":"u43"},
    "9d883b9dae754ce7bce7ee6c057e8359":{
      "scriptId":"u44"},
    "3d54875e74d5416d91973ab7c7fec662":{
      "scriptId":"u45"},
    "fdb6908ffbc84710a47d95cbbafcdcb8":{
      "scriptId":"u46"},
    "c47c8889c4144ec19f14833e0fa2e1f4":{
      "scriptId":"u47"},
    "bafa319494ec44ad9d678cc03a300767":{
      "scriptId":"u48"},
    "56b9d948f072430694b5b6d6afa9e193":{
      "scriptId":"u49"},
    "548123c5c40a4e00846a2815a71b1d5d":{
      "scriptId":"u50"},
    "b891e04731f04254927e708c1ad7e504":{
      "scriptId":"u51"},
    "d185d7b7e0a04b6a9c6cc1959e363a29":{
      "scriptId":"u52"},
    "eb59d59782fc4eb09805d746a8f0ac04":{
      "scriptId":"u53"},
    "90c3f347d91c4713896b3a77a97a7d8d":{
      "scriptId":"u54"},
    "a3c1be53ed54414e9c837c96582c4389":{
      "scriptId":"u55"},
    "c4b4a6ce9f1f46b59aed996a4ff5b5cb":{
      "scriptId":"u56"},
    "8415419096db406ab80a53bdf9ad169e":{
      "scriptId":"u57"},
    "0976ea6fb1d643aa927c4dfff995bb31":{
      "scriptId":"u58"},
    "66b0eeb1aa484a3191dae968b3c5aa48":{
      "scriptId":"u59"},
    "83fb65b8324c4c358bd0fdd307d85dae":{
      "scriptId":"u60"},
    "2a9c4b9fba1544658605f609a6686493":{
      "scriptId":"u61"},
    "6e7c381a1cf84eecb0e2a0b9aabb3153":{
      "scriptId":"u62"},
    "1711c8d42b2c4cb68510d1913e1d6bed":{
      "scriptId":"u63"},
    "53264a55dd7342a3b872ca61737917a3":{
      "scriptId":"u64"},
    "f8c2f2156bd04dbaab0f585e55cc7f60":{
      "scriptId":"u65"},
    "46fbd82ab66741839cb075860e8f0d02":{
      "scriptId":"u66"},
    "dc59e7c3e28245df9c61fc14cdc8719d":{
      "scriptId":"u67"},
    "7b2d443fb0214eb2ae3fce79763f01de":{
      "scriptId":"u68"},
    "a68da9dfe11b4ba7b4aaf0ab613eabc9":{
      "scriptId":"u69"},
    "89d85356df5b4cc9aca5c1d0c1dd6680":{
      "scriptId":"u70"},
    "c66f283651ce404f9d6bf6d7adf3350c":{
      "scriptId":"u71"},
    "7b6cffc086fc47a0bad4d6fd57ef6a1e":{
      "scriptId":"u72"},
    "543707a8057e4dd78879fd11933d6777":{
      "scriptId":"u73"},
    "7111cf5ae69e422ea06d3eda06d8fea4":{
      "scriptId":"u74"},
    "01e3193bb09146aa8b7119f06949510c":{
      "scriptId":"u75"},
    "252132398a044fed9fdeaa5be2bd2e1e":{
      "scriptId":"u76"},
    "74af9b5f4d1f4817b45d12793991c164":{
      "scriptId":"u77"},
    "4bc056ce08314db68ade1778765a9fbb":{
      "scriptId":"u78"},
    "4c1446f3654c4026afbdd08779603564":{
      "scriptId":"u79"}}});