$axure.loadCurrentPage({
  "url":"车辆违法修改页面.html",
  "generationDate":new Date(1557742049426.42),
  "isCanvasEnabled":false,
  "variables":["yys_name",
"car_chePai_card",
"car_chePai_color",
"car_leixing",
"car_ICcard",
"yy_leixing",
"car_InterNet_leixing",
"car_jingYingLuXian",
"car_zhuangTai",
"quYu",
"phone",
"mail",
"name"],
  "page":{
    "packageId":"23cfd10cccd64525bb492e79cf9283b4",
    "type":"Axure:Page",
    "name":"车辆违法修改页面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"aab3d22526354699ac7c0d32ae0cc756",
          "label":"编辑_弹框",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":350,
              "height":425}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea43ff4135ca499da83c70ed5671d0e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":350,
                  "height":425}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/车辆信息新增页面/编辑_弹框_u0.png"}},
{
          "id":"0a1327c240cc46a5a75d628868e19cc5",
          "label":"新增_",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":38},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2dc0fbf256f410eac3787097b514ef3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":38},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f2676a4504da4245a255dea812d87984",
          "label":"新增_",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":83},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1883e6fd9fba4ccaa6cbfdef5de9f082",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":83},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6af02bbc7a3946a3a8a60a0c580192d3",
          "label":"新增_车牌号",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":118,
              "y":33},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"8a7348bf755d431a84d032b9ff82a793",
          "label":"新增_IC卡号",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":118,
              "y":78},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"d5e55071dcad4f1d83c370887f32e30c",
          "label":"新增_保存",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":378},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"other",
                      "description":"保存成功",
                      "description":"保存成功",
                      "popup":{
                        "left":0,
                        "top":0,
                        "width":300,
                        "height":300,
                        "toolbar":false,
                        "scrollbars":true,
                        "location":false,
                        "status":false,
                        "menubar":false,
                        "directories":false,
                        "resizable":true,
                        "centerwindow":true}}]}]}},
          "tabbable":true},
{
          "id":"c25eeac790ea44b6ab4c49220dcf3129",
          "label":"新增_关闭",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":378},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 车辆违法信息",
                      "target":{
                        "targetType":"page",
                        "url":"车辆违法信息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"43dd86fbdb364155b3be315c237d4719",
          "label":"新增_",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":133},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7a6bd4700fb4e6caccd1be7e4563150",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":133},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e30eb4d1c4e8451186ce67606122c621",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":118,
              "y":128},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b48a8dba91504a12a3defdc0a6c82911",
          "label":"新增_",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":182},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cfbcebff7a064f0fa78527fe4a6747a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":182},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"55696f4afd2f46f2b02b3b4038623ce4",
          "label":"经营路线框",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":118,
              "y":178},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"6fc40c7b39f8458a91e82522028de633",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":270},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9c6949fc20f4962adc09139e6b90cf3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":270},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3263353edaef42ee977d8f726dc86ff8",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":118,
              "y":268},
            "size":{
              "width":200,
              "height":85}},
          "adaptiveStyles":{
}},
{
          "id":"d05993507c9c456ea47b2197996e3d2c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":230},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6e93e90ad6a4dc4a3f83072c8af31d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":230},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ed14e22ffc5b4f32a61f00f92a25ca4d",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":118,
              "y":226},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"d97d108afa3c4c5c8dcb074d29c7827c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":318,
              "y":33},
            "size":{
              "width":22,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec654f62ccda49619099f55cac9594b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":318,
                  "y":33},
                "size":{
                  "width":22,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"68d5bc7ad5a44275a98f4f35cdbb29f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":318,
              "y":78},
            "size":{
              "width":22,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"724cda216e604c25bda18b28872c12a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":318,
                  "y":78},
                "size":{
                  "width":22,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f661a5eabd2e421d86d2722e608987f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":318,
              "y":128},
            "size":{
              "width":22,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"adc8211304fc4275acd280e507f025f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":318,
                  "y":128},
                "size":{
                  "width":22,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6f3c699d949745d6bf88c6d761c05324",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":318,
              "y":178},
            "size":{
              "width":22,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b20b744647854f6aa393f85ef2c26501",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":318,
                  "y":178},
                "size":{
                  "width":22,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bde5b5e9323441168b087f544cb5d48a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":318,
              "y":226},
            "size":{
              "width":22,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8d1271cc29f4258b7a7b7d846ed10de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":318,
                  "y":226},
                "size":{
                  "width":22,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"835c037a1a0646fca229bc55674f9cea",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":318,
              "y":268},
            "size":{
              "width":22,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"935e7d400f664aa59616e0cc513539a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":318,
                  "y":268},
                "size":{
                  "width":22,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "aab3d22526354699ac7c0d32ae0cc756":{
      "scriptId":"u0"},
    "ea43ff4135ca499da83c70ed5671d0e6":{
      "scriptId":"u1"},
    "0a1327c240cc46a5a75d628868e19cc5":{
      "scriptId":"u2"},
    "a2dc0fbf256f410eac3787097b514ef3":{
      "scriptId":"u3"},
    "f2676a4504da4245a255dea812d87984":{
      "scriptId":"u4"},
    "1883e6fd9fba4ccaa6cbfdef5de9f082":{
      "scriptId":"u5"},
    "6af02bbc7a3946a3a8a60a0c580192d3":{
      "scriptId":"u6"},
    "8a7348bf755d431a84d032b9ff82a793":{
      "scriptId":"u7"},
    "d5e55071dcad4f1d83c370887f32e30c":{
      "scriptId":"u8"},
    "c25eeac790ea44b6ab4c49220dcf3129":{
      "scriptId":"u9"},
    "43dd86fbdb364155b3be315c237d4719":{
      "scriptId":"u10"},
    "e7a6bd4700fb4e6caccd1be7e4563150":{
      "scriptId":"u11"},
    "e30eb4d1c4e8451186ce67606122c621":{
      "scriptId":"u12"},
    "b48a8dba91504a12a3defdc0a6c82911":{
      "scriptId":"u13"},
    "cfbcebff7a064f0fa78527fe4a6747a3":{
      "scriptId":"u14"},
    "55696f4afd2f46f2b02b3b4038623ce4":{
      "scriptId":"u15"},
    "6fc40c7b39f8458a91e82522028de633":{
      "scriptId":"u16"},
    "d9c6949fc20f4962adc09139e6b90cf3":{
      "scriptId":"u17"},
    "3263353edaef42ee977d8f726dc86ff8":{
      "scriptId":"u18"},
    "d05993507c9c456ea47b2197996e3d2c":{
      "scriptId":"u19"},
    "b6e93e90ad6a4dc4a3f83072c8af31d1":{
      "scriptId":"u20"},
    "ed14e22ffc5b4f32a61f00f92a25ca4d":{
      "scriptId":"u21"},
    "d97d108afa3c4c5c8dcb074d29c7827c":{
      "scriptId":"u22"},
    "ec654f62ccda49619099f55cac9594b9":{
      "scriptId":"u23"},
    "68d5bc7ad5a44275a98f4f35cdbb29f6":{
      "scriptId":"u24"},
    "724cda216e604c25bda18b28872c12a2":{
      "scriptId":"u25"},
    "f661a5eabd2e421d86d2722e608987f1":{
      "scriptId":"u26"},
    "adc8211304fc4275acd280e507f025f9":{
      "scriptId":"u27"},
    "6f3c699d949745d6bf88c6d761c05324":{
      "scriptId":"u28"},
    "b20b744647854f6aa393f85ef2c26501":{
      "scriptId":"u29"},
    "bde5b5e9323441168b087f544cb5d48a":{
      "scriptId":"u30"},
    "c8d1271cc29f4258b7a7b7d846ed10de":{
      "scriptId":"u31"},
    "835c037a1a0646fca229bc55674f9cea":{
      "scriptId":"u32"},
    "935e7d400f664aa59616e0cc513539a7":{
      "scriptId":"u33"}}});