$axure.loadCurrentPage({
  "url":"设备基本信息管理.html",
  "generationDate":new Date(1557742126064.46),
  "isCanvasEnabled":false,
  "variables":["yys_name",
"car_chePai_card",
"car_chePai_color",
"car_leixing",
"car_ICcard",
"yy_leixing",
"car_InterNet_leixing",
"car_jingYingLuXian",
"car_zhuangTai",
"quYu",
"phone",
"mail",
"name"],
  "page":{
    "packageId":"3e677b9eb87a4ecb868dda55ddb30112",
    "type":"Axure:Page",
    "name":"设备基本信息管理",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a1950340a51945e5822ad12c5841f884",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":285,
              "y":146},
            "size":{
              "width":55,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e3e29e95b0848b6b02ef7ba168792c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":285,
                  "y":146},
                "size":{
                  "width":55,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ee1291401d504fd99ce2de576cc106f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":81,
              "y":146},
            "size":{
              "width":55,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd91c40d9dfb462294cadb7dd85f68e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":81,
                  "y":146},
                "size":{
                  "width":55,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d80ad6501f0347568c6017808b3045ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":505,
              "y":146},
            "size":{
              "width":55,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47825d1f837341718b487335ef84698b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":505,
                  "y":146},
                "size":{
                  "width":55,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"34db0e1a67a1498bbb571be9da07569d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":81,
              "y":198},
            "size":{
              "width":55,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3593b7a3a974539b4f5c8ebedbb0799",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":81,
                  "y":198},
                "size":{
                  "width":55,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"127d14496a484178be637d9f9f95f8e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":285,
              "y":198},
            "size":{
              "width":55,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0fc5ed150ccb4485a7e9fc0d929dc7e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":285,
                  "y":198},
                "size":{
                  "width":55,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f36b75f6d7894b09898bf62dab24894b",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":145,
              "y":142},
            "size":{
              "width":130,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"20ea0f3d825d42569f29b833a0299449",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":351,
              "y":142},
            "size":{
              "width":145,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"7b3f3da2c161430786c694602bcd06f8",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":571,
              "y":142},
            "size":{
              "width":145,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"51a2254eef5f437db698cadcf751eca2",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":145,
              "y":194},
            "size":{
              "width":130,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"2ef5df36a2214bf8bfa9f7d1acc0c1f1",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":351,
              "y":195},
            "size":{
              "width":145,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"7e316fe0853144d1896baa9c2a7304e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":505,
              "y":198},
            "size":{
              "width":55,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb3d596e9db147f29b16f86ac59023c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":505,
                  "y":198},
                "size":{
                  "width":55,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8c6240a025854715a3402a4f92d52484",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":571,
              "y":195},
            "size":{
              "width":145,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"aa9461593bca4f9fb883aa2cd65744cc",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":379,
              "y":250},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"bb2039cf0d114870bcd9344f8f1d0cdb",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":149,
              "y":250},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 部件文字 不明 = &quot;芝罘区&quot;, 且<br> 部件文字 不明 = &quot;运营商test1&quot;, 且<br> 部件文字 不明 = &quot;危险货物运输&quot;, 且<br> 部件文字 不明 = &quot;营业&quot;, 且<br> 部件文字 不明 = &quot;张三&quot;, 且<br> 部件文字 不明 = &quot;12345678900&quot;, 且<br> 部件文字 不明 = &quot;12345678@qq.com&quot;, 且<br> 部件文字 不明 = &quot;admin&quot;, 且<br> 部件文字 不明 = &quot;2019-04-28&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[]}}]}]}},
          "tabbable":true},
{
          "id":"c62f38f9f5ca45848f06e80f95429cbd",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":269,
              "y":250},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"ed97296f23db46508a2d5afbc6d67195",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":599,
              "y":250},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 变量 yys_name = &quot;&quot;, 且<br> 变量 yy_leixing = &quot;&quot;, 且<br> 变量 quYu = &quot;&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"yys_name"},
{
                                "exprType":"stringLiteral",
                                "value":"",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"yy_leixing"},
{
                                "exprType":"stringLiteral",
                                "value":"",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"quYu"},
{
                                "exprType":"stringLiteral",
                                "value":"",
                                "stos":[]}]}]}},
{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"12d481561be04bb68b525f53b9088edb",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":489,
              "y":250},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"45f49cd8a2f14f5a9846ca1734214e8f",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":300},
            "size":{
              "width":820,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7419ebf56a92417685b3b6d9c83d8195",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "size":{
                  "width":117,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"40116bbee88d4fe7ae6fda2fb2980e8f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "size":{
                      "width":117,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备基本信息管理/u24.png"}},
{
              "id":"1162fe3cf5c64adda552f2ca097a44e2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":117,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"559edde05cf249a38f93cb6c8ad70825",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":117,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备基本信息管理/u38.png"}},
{
              "id":"871eb787b9754725a66438a21a71581c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":117,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"468b876b2be54684bd59045f60d6e1bf",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":117,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备基本信息管理/u52.png"}},
{
              "id":"0efda607bb8a4754b9c90887753b6f5e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":117,
                  "y":0},
                "size":{
                  "width":117,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6a913340b5e144039e3edaf0f566f42d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":117,
                      "y":0},
                    "size":{
                      "width":117,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备基本信息管理/u24.png"}},
{
              "id":"0d5cd8d621f64b83a5702b85ef0bed5b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":117,
                  "y":30},
                "size":{
                  "width":117,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"789d879916e740cb9de843b2bde09973",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":117,
                      "y":30},
                    "size":{
                      "width":117,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备基本信息管理/u38.png"}},
{
              "id":"1373b24b94434f26bc133b40f158bf59",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":117,
                  "y":60},
                "size":{
                  "width":117,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c9847017cb0148d49b42c1160bd36204",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":117,
                      "y":60},
                    "size":{
                      "width":117,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备基本信息管理/u52.png"}},
{
              "id":"61d2f7ef62bf44ee81f030ca1b16c676",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":234,
                  "y":0},
                "size":{
                  "width":117,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5d182b42645e4858b848a9ac92d8d8db",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":234,
                      "y":0},
                    "size":{
                      "width":117,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备基本信息管理/u24.png"}},
{
              "id":"c024e90b55004543b46c130129189979",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":234,
                  "y":30},
                "size":{
                  "width":117,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"62cdde7236c14b1a973fbe66e7764b2d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":234,
                      "y":30},
                    "size":{
                      "width":117,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备基本信息管理/u38.png"}},
{
              "id":"0e8fa106ce904e2b8c957bac2cd3f85a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":234,
                  "y":60},
                "size":{
                  "width":117,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5f92c89b1f5043cd955b5040247497a7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":234,
                      "y":60},
                    "size":{
                      "width":117,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备基本信息管理/u52.png"}},
{
              "id":"1966afed350f404ca4402365a393e1a5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":351,
                  "y":0},
                "size":{
                  "width":117,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d92b00595c834ed1be3042003983943d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":351,
                      "y":0},
                    "size":{
                      "width":117,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备基本信息管理/u24.png"}},
{
              "id":"dd437c27add94ddd8741b22ee169210b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":351,
                  "y":30},
                "size":{
                  "width":117,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1b41a2e33bf0404ca969109c47f689e3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":351,
                      "y":30},
                    "size":{
                      "width":117,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备基本信息管理/u38.png"}},
{
              "id":"70d98feb3cae4c47b271a7e6d650ff82",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":351,
                  "y":60},
                "size":{
                  "width":117,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5954b1683aff4f7fb8da9759dcaf2e6e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":351,
                      "y":60},
                    "size":{
                      "width":117,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备基本信息管理/u52.png"}},
{
              "id":"db9272b219ad46b8927d8eb4ea87f0be",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":468,
                  "y":0},
                "size":{
                  "width":117,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6abba312c69c4a7cad9405c95c1cca3c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":468,
                      "y":0},
                    "size":{
                      "width":117,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备基本信息管理/u24.png"}},
{
              "id":"d80ccde694db4fc5be94b2a6b5a390d8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":468,
                  "y":30},
                "size":{
                  "width":117,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e7c75b558b6f4ed1875787fe73a7cde3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":468,
                      "y":30},
                    "size":{
                      "width":117,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备基本信息管理/u38.png"}},
{
              "id":"a61faccd316a4d0d8f151aba2e8eff6b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":468,
                  "y":60},
                "size":{
                  "width":117,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dd617c7b5c2e4a71aec87718bf05696b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":468,
                      "y":60},
                    "size":{
                      "width":117,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备基本信息管理/u52.png"}},
{
              "id":"3752fd6d525147ee8337282ecd2c608e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":585,
                  "y":0},
                "size":{
                  "width":117,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"19cc77b76c214caf9a57aa48a7316f5d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":585,
                      "y":0},
                    "size":{
                      "width":117,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备基本信息管理/u24.png"}},
{
              "id":"b6964fc6a8084bdaa70625de9aa469c4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":585,
                  "y":30},
                "size":{
                  "width":117,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f8704c6445ea4040b679b41b48adacd8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":585,
                      "y":30},
                    "size":{
                      "width":117,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备基本信息管理/u38.png"}},
{
              "id":"a02e8a855d8f4bb18bfd640cfe61e64a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":585,
                  "y":60},
                "size":{
                  "width":117,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"712aa0cefde84a4197f6651211bdac65",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":585,
                      "y":60},
                    "size":{
                      "width":117,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备基本信息管理/u52.png"}},
{
              "id":"200c46cd419c4502b2738ddd30724fb8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":702,
                  "y":0},
                "size":{
                  "width":118,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"02c5f69ed66349aa959f333f6b05c424",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":702,
                      "y":0},
                    "size":{
                      "width":118,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备基本信息管理/u36.png"}},
{
              "id":"1a4b13f9f5ee45c3940619ce312c0a20",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":702,
                  "y":30},
                "size":{
                  "width":118,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"87baa00eccda4b9bb071e95e3b602a37",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":702,
                      "y":30},
                    "size":{
                      "width":118,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备基本信息管理/u50.png"}},
{
              "id":"cf647216e6d6439298ada9984576c01c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":702,
                  "y":60},
                "size":{
                  "width":118,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c8b2e5c98df64654a03c552fa5234000",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":702,
                      "y":60},
                    "size":{
                      "width":118,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/设备基本信息管理/u64.png"}}]},
{
          "id":"7460270549de47a8b407128198e310d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":640,
              "y":400},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea82aef4034a495ba72134dd3a2278b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":640,
                  "y":400},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9ca4cf3a7f384c5f91dd9fe5943b5497",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":690,
              "y":400},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
}},
{
          "id":"5a7636241e514717909c83764f23f79a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":740,
              "y":400},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f871e21e025e41a49e7686ab5c240dd8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":740,
                  "y":400},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bac55fa1c79a44f8a3329cdbf1ed7e3f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0066FF,
                  "opacity":1}}},
            "location":{
              "x":578,
              "y":400},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f4e8853bf6a4636a5506a100e425e9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "underline":true,
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0066FF,
                      "opacity":1}}},
                "location":{
                  "x":578,
                  "y":400},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"8c95f4ca3e054267ae5052fc8b4c8985",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "stateStyles":{
              "mouseOver":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0066FF,
                  "opacity":1}}},
            "location":{
              "x":775,
              "y":400},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67747e209ca445f7bdb195078060e52f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "stateStyles":{
                  "mouseOver":{
                    "underline":true,
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0066FF,
                      "opacity":1}}},
                "location":{
                  "x":775,
                  "y":400},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"f8db2c21abb4426faded61fbbfa93604",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":54,
              "y":400},
            "size":{
              "width":282,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c414d16608ff4c5a989713033b370314",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":54,
                  "y":400},
                "size":{
                  "width":282,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8c5d3423ede045e59b7f7763e67de94c",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":344,
              "y":400},
            "size":{
              "width":72,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"4639e3dd1fef45ee8feb05a29facece2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":427,
              "y":404},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60675e29293c4c9fb537d6079c9dc211",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":427,
                  "y":404},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9bbc6bb1d6a041f380ca318bab472408",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":838,
              "y":400},
            "size":{
              "width":42,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b71c1ba0f134fedb3824a3ebd62835b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":838,
                  "y":400},
                "size":{
                  "width":42,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8d00426625694b1f81ea661d434aa8ca",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":775,
              "y":335},
            "size":{
              "width":40,
              "height":27}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]},
{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 设备信息修改页",
                      "target":{
                        "targetType":"page",
                        "url":"设备信息修改页.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true},
{
          "id":"85ae7205842d47e5ababb5cb0a3a3c85",
          "label":"设备信息删除1",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":825,
              "y":335},
            "size":{
              "width":40,
              "height":27}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 设备信息删除1-1,<br>设备信息删除1-2,<br>设备信息删除1-3,<br>设备信息删除1-4",
                      "objectsToFades":[{
                          "objectPath":["d50fe2928f034882b86d160c2cd6da43"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["e174a882b36b4b2980fbd68b3cb3b720"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["dc708f8d2389402695fcc172802b82ed"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["28609251cbb54a579c0b967c510fb23f"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"6c13d0582c1f4d39bc06f8c8fcaa8bbf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":60,
              "y":110},
            "size":{
              "width":120,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0546b0eb0c0a462fa163c42dca72a6eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":60,
                  "y":110},
                "size":{
                  "width":120,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d50fe2928f034882b86d160c2cd6da43",
          "label":"设备信息删除1-1",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":882,
              "y":198},
            "size":{
              "width":178,
              "height":92},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9bcdd067715843a5a8132db3e27e36fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":882,
                  "y":198},
                "size":{
                  "width":178,
                  "height":92},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设备基本信息管理/设备信息删除1-1_u86.png"}},
{
          "id":"e174a882b36b4b2980fbd68b3cb3b720",
          "label":"设备信息删除1-2",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "location":{
              "x":910,
              "y":214},
            "size":{
              "width":130,
              "height":26},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e729f179dd6432ca108c6b65f47ffd0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":910,
                  "y":214},
                "size":{
                  "width":130,
                  "height":26},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dc708f8d2389402695fcc172802b82ed",
          "label":"设备信息删除1-3",
          "type":"button",
          "styleType":"button",
          "visible":false,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":890,
              "y":250},
            "size":{
              "width":80,
              "height":30},
            "visible":false},
          "adaptiveStyles":{
}},
{
          "id":"28609251cbb54a579c0b967c510fb23f",
          "label":"设备信息删除1-4",
          "type":"button",
          "styleType":"button",
          "visible":false,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":980,
              "y":250},
            "size":{
              "width":70,
              "height":30},
            "visible":false},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "a1950340a51945e5822ad12c5841f884":{
      "scriptId":"u0"},
    "1e3e29e95b0848b6b02ef7ba168792c7":{
      "scriptId":"u1"},
    "ee1291401d504fd99ce2de576cc106f7":{
      "scriptId":"u2"},
    "cd91c40d9dfb462294cadb7dd85f68e6":{
      "scriptId":"u3"},
    "d80ad6501f0347568c6017808b3045ba":{
      "scriptId":"u4"},
    "47825d1f837341718b487335ef84698b":{
      "scriptId":"u5"},
    "34db0e1a67a1498bbb571be9da07569d":{
      "scriptId":"u6"},
    "b3593b7a3a974539b4f5c8ebedbb0799":{
      "scriptId":"u7"},
    "127d14496a484178be637d9f9f95f8e1":{
      "scriptId":"u8"},
    "0fc5ed150ccb4485a7e9fc0d929dc7e3":{
      "scriptId":"u9"},
    "f36b75f6d7894b09898bf62dab24894b":{
      "scriptId":"u10"},
    "20ea0f3d825d42569f29b833a0299449":{
      "scriptId":"u11"},
    "7b3f3da2c161430786c694602bcd06f8":{
      "scriptId":"u12"},
    "51a2254eef5f437db698cadcf751eca2":{
      "scriptId":"u13"},
    "2ef5df36a2214bf8bfa9f7d1acc0c1f1":{
      "scriptId":"u14"},
    "7e316fe0853144d1896baa9c2a7304e6":{
      "scriptId":"u15"},
    "cb3d596e9db147f29b16f86ac59023c4":{
      "scriptId":"u16"},
    "8c6240a025854715a3402a4f92d52484":{
      "scriptId":"u17"},
    "aa9461593bca4f9fb883aa2cd65744cc":{
      "scriptId":"u18"},
    "bb2039cf0d114870bcd9344f8f1d0cdb":{
      "scriptId":"u19"},
    "c62f38f9f5ca45848f06e80f95429cbd":{
      "scriptId":"u20"},
    "ed97296f23db46508a2d5afbc6d67195":{
      "scriptId":"u21"},
    "12d481561be04bb68b525f53b9088edb":{
      "scriptId":"u22"},
    "45f49cd8a2f14f5a9846ca1734214e8f":{
      "scriptId":"u23"},
    "7419ebf56a92417685b3b6d9c83d8195":{
      "scriptId":"u24"},
    "40116bbee88d4fe7ae6fda2fb2980e8f":{
      "scriptId":"u25"},
    "0efda607bb8a4754b9c90887753b6f5e":{
      "scriptId":"u26"},
    "6a913340b5e144039e3edaf0f566f42d":{
      "scriptId":"u27"},
    "61d2f7ef62bf44ee81f030ca1b16c676":{
      "scriptId":"u28"},
    "5d182b42645e4858b848a9ac92d8d8db":{
      "scriptId":"u29"},
    "1966afed350f404ca4402365a393e1a5":{
      "scriptId":"u30"},
    "d92b00595c834ed1be3042003983943d":{
      "scriptId":"u31"},
    "db9272b219ad46b8927d8eb4ea87f0be":{
      "scriptId":"u32"},
    "6abba312c69c4a7cad9405c95c1cca3c":{
      "scriptId":"u33"},
    "3752fd6d525147ee8337282ecd2c608e":{
      "scriptId":"u34"},
    "19cc77b76c214caf9a57aa48a7316f5d":{
      "scriptId":"u35"},
    "200c46cd419c4502b2738ddd30724fb8":{
      "scriptId":"u36"},
    "02c5f69ed66349aa959f333f6b05c424":{
      "scriptId":"u37"},
    "1162fe3cf5c64adda552f2ca097a44e2":{
      "scriptId":"u38"},
    "559edde05cf249a38f93cb6c8ad70825":{
      "scriptId":"u39"},
    "0d5cd8d621f64b83a5702b85ef0bed5b":{
      "scriptId":"u40"},
    "789d879916e740cb9de843b2bde09973":{
      "scriptId":"u41"},
    "c024e90b55004543b46c130129189979":{
      "scriptId":"u42"},
    "62cdde7236c14b1a973fbe66e7764b2d":{
      "scriptId":"u43"},
    "dd437c27add94ddd8741b22ee169210b":{
      "scriptId":"u44"},
    "1b41a2e33bf0404ca969109c47f689e3":{
      "scriptId":"u45"},
    "d80ccde694db4fc5be94b2a6b5a390d8":{
      "scriptId":"u46"},
    "e7c75b558b6f4ed1875787fe73a7cde3":{
      "scriptId":"u47"},
    "b6964fc6a8084bdaa70625de9aa469c4":{
      "scriptId":"u48"},
    "f8704c6445ea4040b679b41b48adacd8":{
      "scriptId":"u49"},
    "1a4b13f9f5ee45c3940619ce312c0a20":{
      "scriptId":"u50"},
    "87baa00eccda4b9bb071e95e3b602a37":{
      "scriptId":"u51"},
    "871eb787b9754725a66438a21a71581c":{
      "scriptId":"u52"},
    "468b876b2be54684bd59045f60d6e1bf":{
      "scriptId":"u53"},
    "1373b24b94434f26bc133b40f158bf59":{
      "scriptId":"u54"},
    "c9847017cb0148d49b42c1160bd36204":{
      "scriptId":"u55"},
    "0e8fa106ce904e2b8c957bac2cd3f85a":{
      "scriptId":"u56"},
    "5f92c89b1f5043cd955b5040247497a7":{
      "scriptId":"u57"},
    "70d98feb3cae4c47b271a7e6d650ff82":{
      "scriptId":"u58"},
    "5954b1683aff4f7fb8da9759dcaf2e6e":{
      "scriptId":"u59"},
    "a61faccd316a4d0d8f151aba2e8eff6b":{
      "scriptId":"u60"},
    "dd617c7b5c2e4a71aec87718bf05696b":{
      "scriptId":"u61"},
    "a02e8a855d8f4bb18bfd640cfe61e64a":{
      "scriptId":"u62"},
    "712aa0cefde84a4197f6651211bdac65":{
      "scriptId":"u63"},
    "cf647216e6d6439298ada9984576c01c":{
      "scriptId":"u64"},
    "c8b2e5c98df64654a03c552fa5234000":{
      "scriptId":"u65"},
    "7460270549de47a8b407128198e310d0":{
      "scriptId":"u66"},
    "ea82aef4034a495ba72134dd3a2278b1":{
      "scriptId":"u67"},
    "9ca4cf3a7f384c5f91dd9fe5943b5497":{
      "scriptId":"u68"},
    "5a7636241e514717909c83764f23f79a":{
      "scriptId":"u69"},
    "f871e21e025e41a49e7686ab5c240dd8":{
      "scriptId":"u70"},
    "bac55fa1c79a44f8a3329cdbf1ed7e3f":{
      "scriptId":"u71"},
    "4f4e8853bf6a4636a5506a100e425e9b":{
      "scriptId":"u72"},
    "8c95f4ca3e054267ae5052fc8b4c8985":{
      "scriptId":"u73"},
    "67747e209ca445f7bdb195078060e52f":{
      "scriptId":"u74"},
    "f8db2c21abb4426faded61fbbfa93604":{
      "scriptId":"u75"},
    "c414d16608ff4c5a989713033b370314":{
      "scriptId":"u76"},
    "8c5d3423ede045e59b7f7763e67de94c":{
      "scriptId":"u77"},
    "4639e3dd1fef45ee8feb05a29facece2":{
      "scriptId":"u78"},
    "60675e29293c4c9fb537d6079c9dc211":{
      "scriptId":"u79"},
    "9bbc6bb1d6a041f380ca318bab472408":{
      "scriptId":"u80"},
    "9b71c1ba0f134fedb3824a3ebd62835b":{
      "scriptId":"u81"},
    "8d00426625694b1f81ea661d434aa8ca":{
      "scriptId":"u82"},
    "85ae7205842d47e5ababb5cb0a3a3c85":{
      "scriptId":"u83"},
    "6c13d0582c1f4d39bc06f8c8fcaa8bbf":{
      "scriptId":"u84"},
    "0546b0eb0c0a462fa163c42dca72a6eb":{
      "scriptId":"u85"},
    "d50fe2928f034882b86d160c2cd6da43":{
      "scriptId":"u86"},
    "9bcdd067715843a5a8132db3e27e36fb":{
      "scriptId":"u87"},
    "e174a882b36b4b2980fbd68b3cb3b720":{
      "scriptId":"u88"},
    "6e729f179dd6432ca108c6b65f47ffd0":{
      "scriptId":"u89"},
    "dc708f8d2389402695fcc172802b82ed":{
      "scriptId":"u90"},
    "28609251cbb54a579c0b967c510fb23f":{
      "scriptId":"u91"}}});