$axure.loadCurrentPage({
  "url":"车辆违法修改.html",
  "generationDate":new Date(1557741993281.51),
  "isCanvasEnabled":false,
  "variables":["yys_name",
"car_chePai_card",
"car_chePai_color",
"car_leixing",
"car_ICcard",
"yy_leixing",
"car_InterNet_leixing",
"car_jingYingLuXian",
"car_zhuangTai",
"quYu",
"phone",
"mail",
"name"],
  "page":{
    "packageId":"40910f979fca4db08634c8d940dfa970",
    "type":"Axure:Page",
    "name":"车辆违法修改",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"01b8c0bed90b4ebb9b28fe433bda6071",
          "label":"编辑_弹框",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":350,
              "height":425}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce40caa6901f41f1be361db999980fb8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":350,
                  "height":425}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/车辆信息新增页面/编辑_弹框_u0.png"}},
{
          "id":"2939e9ab4d614dbaa9c41d676b4762e1",
          "label":"新增_",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":38},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b98acbe5fb904d37b0736f7785c33046",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":38},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"31770efd496b499389aa2a5be426cf0b",
          "label":"新增_",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":83},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1cac58a611d4461dbe837524c8c561de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":83},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7bdd9a47e55246f782b72341937bbcb2",
          "label":"新增_车牌号",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":118,
              "y":33},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"01ba4e48f7554784b871f4a0b0adf67e",
          "label":"新增_IC卡号",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":118,
              "y":78},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"17d5c857f20444c58b8d9bf48a587860",
          "label":"新增_保存",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":378},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"18fe1ba5eb834c0f832ffa3a4d80a1f6",
          "label":"新增_关闭",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":378},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"1d7429b868614f3f8eb0f00a788892c5",
          "label":"新增_",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":133},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb57ad8083c548588afa3978febfe07a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":133},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1cc14eb2915a4dc8acbcfc54b5bc5f32",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":118,
              "y":128},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"87a8bc837df5461f9f88ddd00ce97f47",
          "label":"新增_",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":182},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95d1514196f4449d8fbd2964bed430bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":182},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f0f414db4631485581fe81e9c8d25421",
          "label":"经营路线框",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":118,
              "y":178},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"5d91b5314eb3436c89a8917168837643",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":270},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"522032017f664e0c8279b6d4030cb659",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":270},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6cc6f818779d49bc852ee957928ca12c",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":118,
              "y":268},
            "size":{
              "width":200,
              "height":85}},
          "adaptiveStyles":{
}},
{
          "id":"16f95809169641ddae2dbacd434218e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":230},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ecfc5130844b4cb49978ae8b1856b56f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":230},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d83fd00933b44ce98ce36b097820e2a4",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":118,
              "y":226},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "01b8c0bed90b4ebb9b28fe433bda6071":{
      "scriptId":"u0"},
    "ce40caa6901f41f1be361db999980fb8":{
      "scriptId":"u1"},
    "2939e9ab4d614dbaa9c41d676b4762e1":{
      "scriptId":"u2"},
    "b98acbe5fb904d37b0736f7785c33046":{
      "scriptId":"u3"},
    "31770efd496b499389aa2a5be426cf0b":{
      "scriptId":"u4"},
    "1cac58a611d4461dbe837524c8c561de":{
      "scriptId":"u5"},
    "7bdd9a47e55246f782b72341937bbcb2":{
      "scriptId":"u6"},
    "01ba4e48f7554784b871f4a0b0adf67e":{
      "scriptId":"u7"},
    "17d5c857f20444c58b8d9bf48a587860":{
      "scriptId":"u8"},
    "18fe1ba5eb834c0f832ffa3a4d80a1f6":{
      "scriptId":"u9"},
    "1d7429b868614f3f8eb0f00a788892c5":{
      "scriptId":"u10"},
    "bb57ad8083c548588afa3978febfe07a":{
      "scriptId":"u11"},
    "1cc14eb2915a4dc8acbcfc54b5bc5f32":{
      "scriptId":"u12"},
    "87a8bc837df5461f9f88ddd00ce97f47":{
      "scriptId":"u13"},
    "95d1514196f4449d8fbd2964bed430bf":{
      "scriptId":"u14"},
    "f0f414db4631485581fe81e9c8d25421":{
      "scriptId":"u15"},
    "5d91b5314eb3436c89a8917168837643":{
      "scriptId":"u16"},
    "522032017f664e0c8279b6d4030cb659":{
      "scriptId":"u17"},
    "6cc6f818779d49bc852ee957928ca12c":{
      "scriptId":"u18"},
    "16f95809169641ddae2dbacd434218e0":{
      "scriptId":"u19"},
    "ecfc5130844b4cb49978ae8b1856b56f":{
      "scriptId":"u20"},
    "d83fd00933b44ce98ce36b097820e2a4":{
      "scriptId":"u21"}}});