$axure.loadCurrentPage({
  "url":"ic卡基本信息管理.html",
  "generationDate":new Date(1558324037757.48),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"yys_name",
"car_chePai_card",
"car_chePai_color",
"car_leixing",
"car_ICcard",
"yy_leixing",
"car_InterNet_leixing",
"car_jingYingLuXian",
"car_zhuangTai",
"quYu",
"phone",
"mail",
"name",
"NewVariable"],
  "page":{
    "packageId":"45ddc4fd6d334f27b2a405603687cf42",
    "type":"Axure:Page",
    "name":"IC卡基本信息管理",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e309a38f3dec49d4844505bf9e5e8974",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":50},
            "size":{
              "width":52,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eda9d4de28ca426db0e93edf1df3afd2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":50},
                "size":{
                  "width":52,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9a709d2883ad426aaa36c86895170c20",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":152,
              "y":46},
            "size":{
              "width":148,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"463b7e3709cc4644b9d0778941a97436",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":331,
              "y":50},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e88a3718eff4baa85f61499436c34d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":331,
                  "y":50},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"13021b3ea1084fa1bf99f33bce2c0d46",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":47},
            "size":{
              "width":80,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"37edc6e0eea54717a5fecf6dc4ad4d76",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":428,
              "y":113},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"78e8434a629146818683cddf1ba51a34",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":113},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 部件文字 不明 = &quot;芝罘区&quot;, 且<br> 部件文字 不明 = &quot;运营商test1&quot;, 且<br> 部件文字 不明 = &quot;危险货物运输&quot;, 且<br> 部件文字 不明 = &quot;营业&quot;, 且<br> 部件文字 不明 = &quot;张三&quot;, 且<br> 部件文字 不明 = &quot;12345678900&quot;, 且<br> 部件文字 不明 = &quot;12345678@qq.com&quot;, 且<br> 部件文字 不明 = &quot;admin&quot;, 且<br> 部件文字 不明 = &quot;2019-04-28&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[]}}]}]}},
          "tabbable":true},
{
          "id":"2f18c8b1d6a8471397dd1726688d16c4",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":202,
              "y":113},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"abbf2dcadabc4b6bab0e8c4d7077432e",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":316,
              "y":113},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 IC卡新增页",
                      "target":{
                        "targetType":"page",
                        "url":"ic卡新增页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"13628e0ba2ac4606815ea206501a6248",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":538,
              "y":113},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"ef52bf482fd94a8ba01406c98911222d",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":176},
            "size":{
              "width":942,
              "height":89}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a032a115f68f4bcca6eeffaf2ec05079",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":70,
                  "height":29}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0501fef0aafb423eaba711a8f7416b34",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":70,
                      "height":29}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/ic卡基本信息管理/u12.png"}},
{
              "id":"49a3526a983943448d6b255a3d86144e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":29},
                "size":{
                  "width":70,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"eab3026d8ed54738bcd3ddfaeabec61e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":29},
                    "size":{
                      "width":70,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/ic卡基本信息管理/u30.png"}},
{
              "id":"3b944147a531425783ca9a7ab8d4b9ec",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":59},
                "size":{
                  "width":70,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"00471137629e44848290e05f8db4f7ad",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":59},
                    "size":{
                      "width":70,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/ic卡基本信息管理/u48.png"}},
{
              "id":"ec387c471000417086045d6ed143a50d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":70,
                  "y":0},
                "size":{
                  "width":101,
                  "height":29}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"50a3c97bd5c94a91994d3b045a30fefe",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":70,
                      "y":0},
                    "size":{
                      "width":101,
                      "height":29}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/ic卡基本信息管理/u14.png"}},
{
              "id":"2e7c7fb99c734a8c8f009ce5c1badc35",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":70,
                  "y":29},
                "size":{
                  "width":101,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b4ae7ce162654d40aaf63682b0cfd389",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":70,
                      "y":29},
                    "size":{
                      "width":101,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/运营商管理/表格_所属区域1_u29.png"}},
{
              "id":"c13f1a52f57840938b79cbefd4669323",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":70,
                  "y":59},
                "size":{
                  "width":101,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"42ded6f0341248a08d4f551f01fd1c3e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":70,
                      "y":59},
                    "size":{
                      "width":101,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/运营商管理/u47.png"}},
{
              "id":"4faf6aff458d4327addd322195b2b81e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":171,
                  "y":0},
                "size":{
                  "width":121,
                  "height":29}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6c1906ae31644a93952fd2097f43ed95",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":171,
                      "y":0},
                    "size":{
                      "width":121,
                      "height":29}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/ic卡基本信息管理/u16.png"}},
{
              "id":"ec621ea497124628b9affc6f2ec18ca8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":171,
                  "y":29},
                "size":{
                  "width":121,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ff42e972d56740e8b9da154e1c781cbc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":171,
                      "y":29},
                    "size":{
                      "width":121,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/ic卡基本信息管理/u34.png"}},
{
              "id":"9b0c59fe192c479fa0b995d5a277896b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":171,
                  "y":59},
                "size":{
                  "width":121,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"652237e5a24c4559bde354bba5f0aa41",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":171,
                      "y":59},
                    "size":{
                      "width":121,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/ic卡基本信息管理/u52.png"}},
{
              "id":"607b371bacf342fe8b945f47d3c1c899",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":292,
                  "y":0},
                "size":{
                  "width":85,
                  "height":29}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5931701ca8f44c0a8c8377b1e5f1352c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":292,
                      "y":0},
                    "size":{
                      "width":85,
                      "height":29}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/ic卡基本信息管理/u18.png"}},
{
              "id":"4e97ff1663304f55a2719ca77e3518cb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":292,
                  "y":29},
                "size":{
                  "width":85,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0a3ab309d4d64c5c870376cc44f15838",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":292,
                      "y":29},
                    "size":{
                      "width":85,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/ic卡基本信息管理/u36.png"}},
{
              "id":"63a57ae79da84d15b46ceabaf6e772da",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":292,
                  "y":59},
                "size":{
                  "width":85,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3a431b6717534960a558cd96db29a6a5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":292,
                      "y":59},
                    "size":{
                      "width":85,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/ic卡基本信息管理/u54.png"}},
{
              "id":"25b831fcf8d64db7955047afc4863945",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":377,
                  "y":0},
                "size":{
                  "width":130,
                  "height":29}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"44daf84a43bd4b2bbefb9f6d8d897f0e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":377,
                      "y":0},
                    "size":{
                      "width":130,
                      "height":29}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/ic卡基本信息管理/u20.png"}},
{
              "id":"08fe03573f8443398307e5cec7be195c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":377,
                  "y":29},
                "size":{
                  "width":130,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ea3f271a482742b683896b9a81d1ce86",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":377,
                      "y":29},
                    "size":{
                      "width":130,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/ic卡基本信息管理/u38.png"}},
{
              "id":"4c3216903f2047449ddecda09789fa3a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":377,
                  "y":59},
                "size":{
                  "width":130,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ef11cecd4a37486c8d5dd950d0a575d1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":377,
                      "y":59},
                    "size":{
                      "width":130,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/ic卡基本信息管理/u56.png"}},
{
              "id":"97c97ab51dd34cf9a229c3e153f8ea3b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":507,
                  "y":0},
                "size":{
                  "width":81,
                  "height":29}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cfb41146d3344f479b1a9c2284cfd6fd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":507,
                      "y":0},
                    "size":{
                      "width":81,
                      "height":29}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/ic卡基本信息管理/u22.png"}},
{
              "id":"6c859759c6474cd19ac3e09509d035ca",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":507,
                  "y":29},
                "size":{
                  "width":81,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4d38cb1548204d6a9efdda5cb1cefdec",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":507,
                      "y":29},
                    "size":{
                      "width":81,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/ic卡基本信息管理/u40.png"}},
{
              "id":"9a4950f9c6c84739ba736e7202787352",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":507,
                  "y":59},
                "size":{
                  "width":81,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b905bb5013194942ad3de8f753fbcd92",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":507,
                      "y":59},
                    "size":{
                      "width":81,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/ic卡基本信息管理/u58.png"}},
{
              "id":"869c3fd536244504a4ecf44b88ba76f6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":588,
                  "y":0},
                "size":{
                  "width":112,
                  "height":29}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"581d927dda3b4812a8ec391ae5ccf99f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":588,
                      "y":0},
                    "size":{
                      "width":112,
                      "height":29}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/ic卡基本信息管理/u24.png"}},
{
              "id":"e2de5551a9c24ad3bbe1e31d3334ebca",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":588,
                  "y":29},
                "size":{
                  "width":112,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f42341ab387545378f1f5847927f6eac",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":588,
                      "y":29},
                    "size":{
                      "width":112,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/ic卡基本信息管理/u42.png"}},
{
              "id":"bc00c689d6cd4478980197a0cc227203",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":588,
                  "y":59},
                "size":{
                  "width":112,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"75358e1e31bb4d43843f658b37e978f3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":588,
                      "y":59},
                    "size":{
                      "width":112,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/ic卡基本信息管理/u60.png"}},
{
              "id":"92d2cd1b0bc2483abe45d8716eee1ed2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":700,
                  "y":0},
                "size":{
                  "width":77,
                  "height":29}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"33df2c6e9ac24d5dae8d4ca8b203937d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":700,
                      "y":0},
                    "size":{
                      "width":77,
                      "height":29}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/ic卡基本信息管理/u26.png"}},
{
              "id":"a83fe93fdf7b4f5eabac32130b813bbf",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":700,
                  "y":29},
                "size":{
                  "width":77,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e9af1ddef5ce46bbb9e7533b55dcd196",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":700,
                      "y":29},
                    "size":{
                      "width":77,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/ic卡基本信息管理/u44.png"}},
{
              "id":"28a5d83fd5dd4d5ca3b44f31d51ce5a6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":700,
                  "y":59},
                "size":{
                  "width":77,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d18d9f04724c4fdf84779d3db0097a75",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":700,
                      "y":59},
                    "size":{
                      "width":77,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/ic卡基本信息管理/u62.png"}},
{
              "id":"39b2758c54b74c07b0be573de7d69d34",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":777,
                  "y":0},
                "size":{
                  "width":165,
                  "height":29}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"374b107cb4b642649386fb825b9d0773",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":777,
                      "y":0},
                    "size":{
                      "width":165,
                      "height":29}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/ic卡基本信息管理/u28.png"}},
{
              "id":"d0d4d66d75bb4373ac8f5b2c58442f09",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":777,
                  "y":29},
                "size":{
                  "width":165,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cd3539ae680c4754977f9a15bc77b49a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":777,
                      "y":29},
                    "size":{
                      "width":165,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/ic卡基本信息管理/u46.png"}},
{
              "id":"90db073bc5a0477b9db4d0f3eaefb6b0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":777,
                  "y":59},
                "size":{
                  "width":165,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6727adc913ab4958bc2af9cd4e7b4993",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":777,
                      "y":59},
                    "size":{
                      "width":165,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/ic卡基本信息管理/u64.png"}}]},
{
          "id":"f8dd75fe032e4fefac681c896060e524",
          "label":"1",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":880,
              "y":208},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 IC卡修改页",
                      "target":{
                        "targetType":"page",
                        "url":"ic卡修改页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"b36587b6ebb84f72bc75c32bf6922c60",
          "label":"2",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":960,
              "y":208},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 是否删除,<br>是,<br>否",
                      "objectsToFades":[{
                          "objectPath":["16a5d8dd836240a4885caf785b34ead4"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["ac8090ea9fb34a639c78fbb93c0fe4b1"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["7030f93a11b541698e7892dba13eb773"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"548edef6038943298c30ac75c885e742",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":792,
              "y":275},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ecb4fa66f86457ba8008c2a6e2b312c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":792,
                  "y":275},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a280caf1c28340d9bd29619dfc3e702b",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":842,
              "y":275},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
}},
{
          "id":"73c23b4f25e845d9b5c35da41ffafe0d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":892,
              "y":275},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"97798b2d8be84244b79ea08b2bf76eb8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":892,
                  "y":275},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"23e05691e749444a9323697f3f3c03e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0066FF,
                  "opacity":1}}},
            "location":{
              "x":730,
              "y":275},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4676252f710647919c70af04ca090aab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "underline":true,
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0066FF,
                      "opacity":1}}},
                "location":{
                  "x":730,
                  "y":275},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"7ecc36582e9045f49b7462784b7cbe68",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "stateStyles":{
              "mouseOver":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0066FF,
                  "opacity":1}}},
            "location":{
              "x":927,
              "y":275},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a55e93259f2492e8a053dab9eace3d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "stateStyles":{
                  "mouseOver":{
                    "underline":true,
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0066FF,
                      "opacity":1}}},
                "location":{
                  "x":927,
                  "y":275},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"22fb6e1bf23e4419abd088a491e70e6e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":275},
            "size":{
              "width":282,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8f4eacfba3b40cab7940a3b422a33fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":275},
                "size":{
                  "width":282,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b11b48d5b4e94eec8ade04936ab12074",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":275},
            "size":{
              "width":72,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"b02bb926c8e644afb8877464c70a8f92",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":463,
              "y":279},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84504e7b0c92498b8a5ee95406e46a79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":463,
                  "y":279},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9558f8a7614645d283ec0d3edeadb5a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":990,
              "y":275},
            "size":{
              "width":42,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b56ea1c8e234c4ca8061874502e41df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":990,
                  "y":275},
                "size":{
                  "width":42,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"16a5d8dd836240a4885caf785b34ead4",
          "label":"是否删除",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":496,
              "y":160},
            "size":{
              "width":130,
              "height":145},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18fa86c34eb74ad0a2bbcbf83e9ac938",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":496,
                  "y":160},
                "size":{
                  "width":130,
                  "height":145},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/ic卡基本信息管理/是否删除_u84.png"}},
{
          "id":"ac8090ea9fb34a639c78fbb93c0fe4b1",
          "label":"是",
          "type":"button",
          "styleType":"button",
          "visible":false,
          "style":{
            "location":{
              "x":518,
              "y":233},
            "size":{
              "width":87,
              "height":22},
            "visible":false},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 部件文字 (表格单元) = &quot;&quot;, 且<br> 部件文字 (表格单元) = &quot;&quot;, 且<br> 部件文字 (表格单元) = &quot;&quot;, 且<br> 部件文字 (表格单元) = &quot;&quot;, 且<br> 部件文字 (表格单元) = &quot;&quot;, 且<br> 部件文字 (表格单元) = &quot;&quot;, 且<br> 部件文字 (表格单元) = &quot;&quot;, 且<br> 部件文字 (表格单元) = &quot;&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["eab3026d8ed54738bcd3ddfaeabec61e"]},
{
                                "exprType":"stringLiteral",
                                "value":"",
                                "stos":[]},
{
                                "exprType":"booleanLiteral",
                                "value":true}]},
{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["b4ae7ce162654d40aaf63682b0cfd389"]},
{
                                "exprType":"stringLiteral",
                                "value":"",
                                "stos":[]},
{
                                "exprType":"booleanLiteral",
                                "value":true}]},
{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["ff42e972d56740e8b9da154e1c781cbc"]},
{
                                "exprType":"stringLiteral",
                                "value":"",
                                "stos":[]},
{
                                "exprType":"booleanLiteral",
                                "value":true}]},
{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["0a3ab309d4d64c5c870376cc44f15838"]},
{
                                "exprType":"stringLiteral",
                                "value":"",
                                "stos":[]},
{
                                "exprType":"booleanLiteral",
                                "value":true}]},
{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["ea3f271a482742b683896b9a81d1ce86"]},
{
                                "exprType":"stringLiteral",
                                "value":"",
                                "stos":[]},
{
                                "exprType":"booleanLiteral",
                                "value":true}]},
{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["4d38cb1548204d6a9efdda5cb1cefdec"]},
{
                                "exprType":"stringLiteral",
                                "value":"",
                                "stos":[]},
{
                                "exprType":"booleanLiteral",
                                "value":true}]},
{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["f42341ab387545378f1f5847927f6eac"]},
{
                                "exprType":"stringLiteral",
                                "value":"",
                                "stos":[]},
{
                                "exprType":"booleanLiteral",
                                "value":true}]},
{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["e9af1ddef5ce46bbb9e7533b55dcd196"]},
{
                                "exprType":"stringLiteral",
                                "value":"",
                                "stos":[]},
{
                                "exprType":"booleanLiteral",
                                "value":true}]}]}},
{
                      "action":"fadeWidget",
                      "description":"隐藏 是否删除,<br>是,<br>否,<br>1,<br>2",
                      "objectsToFades":[{
                          "objectPath":["16a5d8dd836240a4885caf785b34ead4"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["ac8090ea9fb34a639c78fbb93c0fe4b1"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["7030f93a11b541698e7892dba13eb773"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["f8dd75fe032e4fefac681c896060e524"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["b36587b6ebb84f72bc75c32bf6922c60"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"7030f93a11b541698e7892dba13eb773",
          "label":"否",
          "type":"button",
          "styleType":"button",
          "visible":false,
          "style":{
            "location":{
              "x":518,
              "y":265},
            "size":{
              "width":87,
              "height":22},
            "visible":false},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 是否删除,<br>是,<br>否",
                      "objectsToFades":[{
                          "objectPath":["16a5d8dd836240a4885caf785b34ead4"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["ac8090ea9fb34a639c78fbb93c0fe4b1"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["7030f93a11b541698e7892dba13eb773"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"524b0e47171945f2b2d31ca16bb1e324",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":658,
              "y":118},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02266c397f064db4b10d1099b52161cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":658,
                  "y":118},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "e309a38f3dec49d4844505bf9e5e8974":{
      "scriptId":"u0"},
    "eda9d4de28ca426db0e93edf1df3afd2":{
      "scriptId":"u1"},
    "9a709d2883ad426aaa36c86895170c20":{
      "scriptId":"u2"},
    "463b7e3709cc4644b9d0778941a97436":{
      "scriptId":"u3"},
    "2e88a3718eff4baa85f61499436c34d6":{
      "scriptId":"u4"},
    "13021b3ea1084fa1bf99f33bce2c0d46":{
      "scriptId":"u5"},
    "37edc6e0eea54717a5fecf6dc4ad4d76":{
      "scriptId":"u6"},
    "78e8434a629146818683cddf1ba51a34":{
      "scriptId":"u7"},
    "2f18c8b1d6a8471397dd1726688d16c4":{
      "scriptId":"u8"},
    "abbf2dcadabc4b6bab0e8c4d7077432e":{
      "scriptId":"u9"},
    "13628e0ba2ac4606815ea206501a6248":{
      "scriptId":"u10"},
    "ef52bf482fd94a8ba01406c98911222d":{
      "scriptId":"u11"},
    "a032a115f68f4bcca6eeffaf2ec05079":{
      "scriptId":"u12"},
    "0501fef0aafb423eaba711a8f7416b34":{
      "scriptId":"u13"},
    "ec387c471000417086045d6ed143a50d":{
      "scriptId":"u14"},
    "50a3c97bd5c94a91994d3b045a30fefe":{
      "scriptId":"u15"},
    "4faf6aff458d4327addd322195b2b81e":{
      "scriptId":"u16"},
    "6c1906ae31644a93952fd2097f43ed95":{
      "scriptId":"u17"},
    "607b371bacf342fe8b945f47d3c1c899":{
      "scriptId":"u18"},
    "5931701ca8f44c0a8c8377b1e5f1352c":{
      "scriptId":"u19"},
    "25b831fcf8d64db7955047afc4863945":{
      "scriptId":"u20"},
    "44daf84a43bd4b2bbefb9f6d8d897f0e":{
      "scriptId":"u21"},
    "97c97ab51dd34cf9a229c3e153f8ea3b":{
      "scriptId":"u22"},
    "cfb41146d3344f479b1a9c2284cfd6fd":{
      "scriptId":"u23"},
    "869c3fd536244504a4ecf44b88ba76f6":{
      "scriptId":"u24"},
    "581d927dda3b4812a8ec391ae5ccf99f":{
      "scriptId":"u25"},
    "92d2cd1b0bc2483abe45d8716eee1ed2":{
      "scriptId":"u26"},
    "33df2c6e9ac24d5dae8d4ca8b203937d":{
      "scriptId":"u27"},
    "39b2758c54b74c07b0be573de7d69d34":{
      "scriptId":"u28"},
    "374b107cb4b642649386fb825b9d0773":{
      "scriptId":"u29"},
    "49a3526a983943448d6b255a3d86144e":{
      "scriptId":"u30"},
    "eab3026d8ed54738bcd3ddfaeabec61e":{
      "scriptId":"u31"},
    "2e7c7fb99c734a8c8f009ce5c1badc35":{
      "scriptId":"u32"},
    "b4ae7ce162654d40aaf63682b0cfd389":{
      "scriptId":"u33"},
    "ec621ea497124628b9affc6f2ec18ca8":{
      "scriptId":"u34"},
    "ff42e972d56740e8b9da154e1c781cbc":{
      "scriptId":"u35"},
    "4e97ff1663304f55a2719ca77e3518cb":{
      "scriptId":"u36"},
    "0a3ab309d4d64c5c870376cc44f15838":{
      "scriptId":"u37"},
    "08fe03573f8443398307e5cec7be195c":{
      "scriptId":"u38"},
    "ea3f271a482742b683896b9a81d1ce86":{
      "scriptId":"u39"},
    "6c859759c6474cd19ac3e09509d035ca":{
      "scriptId":"u40"},
    "4d38cb1548204d6a9efdda5cb1cefdec":{
      "scriptId":"u41"},
    "e2de5551a9c24ad3bbe1e31d3334ebca":{
      "scriptId":"u42"},
    "f42341ab387545378f1f5847927f6eac":{
      "scriptId":"u43"},
    "a83fe93fdf7b4f5eabac32130b813bbf":{
      "scriptId":"u44"},
    "e9af1ddef5ce46bbb9e7533b55dcd196":{
      "scriptId":"u45"},
    "d0d4d66d75bb4373ac8f5b2c58442f09":{
      "scriptId":"u46"},
    "cd3539ae680c4754977f9a15bc77b49a":{
      "scriptId":"u47"},
    "3b944147a531425783ca9a7ab8d4b9ec":{
      "scriptId":"u48"},
    "00471137629e44848290e05f8db4f7ad":{
      "scriptId":"u49"},
    "c13f1a52f57840938b79cbefd4669323":{
      "scriptId":"u50"},
    "42ded6f0341248a08d4f551f01fd1c3e":{
      "scriptId":"u51"},
    "9b0c59fe192c479fa0b995d5a277896b":{
      "scriptId":"u52"},
    "652237e5a24c4559bde354bba5f0aa41":{
      "scriptId":"u53"},
    "63a57ae79da84d15b46ceabaf6e772da":{
      "scriptId":"u54"},
    "3a431b6717534960a558cd96db29a6a5":{
      "scriptId":"u55"},
    "4c3216903f2047449ddecda09789fa3a":{
      "scriptId":"u56"},
    "ef11cecd4a37486c8d5dd950d0a575d1":{
      "scriptId":"u57"},
    "9a4950f9c6c84739ba736e7202787352":{
      "scriptId":"u58"},
    "b905bb5013194942ad3de8f753fbcd92":{
      "scriptId":"u59"},
    "bc00c689d6cd4478980197a0cc227203":{
      "scriptId":"u60"},
    "75358e1e31bb4d43843f658b37e978f3":{
      "scriptId":"u61"},
    "28a5d83fd5dd4d5ca3b44f31d51ce5a6":{
      "scriptId":"u62"},
    "d18d9f04724c4fdf84779d3db0097a75":{
      "scriptId":"u63"},
    "90db073bc5a0477b9db4d0f3eaefb6b0":{
      "scriptId":"u64"},
    "6727adc913ab4958bc2af9cd4e7b4993":{
      "scriptId":"u65"},
    "f8dd75fe032e4fefac681c896060e524":{
      "scriptId":"u66"},
    "b36587b6ebb84f72bc75c32bf6922c60":{
      "scriptId":"u67"},
    "548edef6038943298c30ac75c885e742":{
      "scriptId":"u68"},
    "8ecb4fa66f86457ba8008c2a6e2b312c":{
      "scriptId":"u69"},
    "a280caf1c28340d9bd29619dfc3e702b":{
      "scriptId":"u70"},
    "73c23b4f25e845d9b5c35da41ffafe0d":{
      "scriptId":"u71"},
    "97798b2d8be84244b79ea08b2bf76eb8":{
      "scriptId":"u72"},
    "23e05691e749444a9323697f3f3c03e0":{
      "scriptId":"u73"},
    "4676252f710647919c70af04ca090aab":{
      "scriptId":"u74"},
    "7ecc36582e9045f49b7462784b7cbe68":{
      "scriptId":"u75"},
    "9a55e93259f2492e8a053dab9eace3d7":{
      "scriptId":"u76"},
    "22fb6e1bf23e4419abd088a491e70e6e":{
      "scriptId":"u77"},
    "d8f4eacfba3b40cab7940a3b422a33fc":{
      "scriptId":"u78"},
    "b11b48d5b4e94eec8ade04936ab12074":{
      "scriptId":"u79"},
    "b02bb926c8e644afb8877464c70a8f92":{
      "scriptId":"u80"},
    "84504e7b0c92498b8a5ee95406e46a79":{
      "scriptId":"u81"},
    "9558f8a7614645d283ec0d3edeadb5a9":{
      "scriptId":"u82"},
    "4b56ea1c8e234c4ca8061874502e41df":{
      "scriptId":"u83"},
    "16a5d8dd836240a4885caf785b34ead4":{
      "scriptId":"u84"},
    "18fa86c34eb74ad0a2bbcbf83e9ac938":{
      "scriptId":"u85"},
    "ac8090ea9fb34a639c78fbb93c0fe4b1":{
      "scriptId":"u86"},
    "7030f93a11b541698e7892dba13eb773":{
      "scriptId":"u87"},
    "524b0e47171945f2b2d31ca16bb1e324":{
      "scriptId":"u88"},
    "02266c397f064db4b10d1099b52161cb":{
      "scriptId":"u89"}}});