$axure.loadCurrentPage({
  "url":"查看运单列表信息（已发单）.html",
  "generationDate":new Date(1557736120892.24),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n",
"rl_date",
"rl_day"],
  "page":{
    "packageId":"39762eac1ae54169bbe7f95309937308",
    "type":"Axure:Page",
    "name":"查看运单列表信息（已发单）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"50d4aa8147984246a21fd073889206f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":624,
              "y":162},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41a90330b18343dd90d46ddaa45feb8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":624,
                  "y":162},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8b8a0db62d8845fa85014a033f3b11f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
            "fontSize":"36px",
            "fontWeight":"500",
            "location":{
              "x":434,
              "y":166},
            "size":{
              "width":20,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13bd8e28e8344a2ba28e89390ef84670",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Iaxurefont Regular', 'Iaxurefont'",
                "fontSize":"36px",
                "fontWeight":"500",
                "location":{
                  "x":434,
                  "y":166},
                "size":{
                  "width":20,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/填写单据信息/u76.png"}},
{
          "id":"adac6826f91a4cfa8d4605cd1f9cf639",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":732,
              "y":164},
            "size":{
              "width":32,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"afbab2016b274e11a34ea459b8388638",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":732,
                  "y":164},
                "size":{
                  "width":32,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9154f518544d44f1827c8891fc72c00f",
          "label":"border",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Cursiva', 'Arial'",
            "fontStyle":"italic",
            "location":{
              "x":744,
              "y":158},
            "size":{
              "width":190,
              "height":27},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF009DDA},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a42071875c994b5fa5ec4f97a960e93c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Cursiva', 'Arial'",
                "fontStyle":"italic",
                "location":{
                  "x":744,
                  "y":158},
                "size":{
                  "width":190,
                  "height":27},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF009DDA},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看运单列表信息（全部）/border_u6.png"}},
{
          "id":"680a5c42a14c440588bebc5099ad0c07",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":907,
              "y":160},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee36ff10ceae4f2ca2496d042b4c7b93",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":907,
                  "y":160},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看运单列表信息（全部）/u8.png"}},
{
          "id":"8f7ecb954cd4443291ed44daf6334939",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":434,
              "y":260},
            "size":{
              "width":506,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"978eb1adbf774b1199e017606907cc71",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":506,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c2b5c7eca9e945d19b17e61ee82efc66",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0D0D0D,
                      "opacity":1},
                    "size":{
                      "width":96,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cbbd6ab5839641749a0bfc25fc761299",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0D0D0D,
                          "opacity":1},
                        "size":{
                          "width":96,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/查看运单列表信息（已发单）/u12.png"}},
{
                  "id":"d7ff1cb6a520426f922868d1477d77e9",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":117,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"03b26337105a40739c74712900304c42",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":200,
                          "y":0},
                        "size":{
                          "width":117,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/查看运单列表信息（全部）/u16.png"}},
{
                  "id":"802e84c44c78408ba4e3c6c2827d5b18",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":317,
                      "y":0},
                    "size":{
                      "width":90,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6e4c29ce075b4371838a346c2a420c40",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":317,
                          "y":0},
                        "size":{
                          "width":90,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/查看运单列表信息（全部）/u18.png"}},
{
                  "id":"31e2dc20d5d84d54b0546afdad7282bb",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":407,
                      "y":0},
                    "size":{
                      "width":99,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f759fd018b2f4a319e04368e8855ddce",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":407,
                          "y":0},
                        "size":{
                          "width":99,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/查看运单列表信息（全部）/u20.png"}},
{
                  "id":"e19d37f277a64e11829cf9fead5da495",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0D0D0D,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "location":{
                      "x":96,
                      "y":0},
                    "size":{
                      "width":104,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"049fb7fadb5f40efa83c6ff29c172bbe",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0D0D0D,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF999999},
                        "location":{
                          "x":96,
                          "y":0},
                        "size":{
                          "width":104,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/查看运单列表信息（已发单）/u14.png"}}]}]},
{
          "id":"939f0fb4a36444e397b99f318e9e61b8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":434,
              "y":310},
            "size":{
              "width":506,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8c30ec806b64744a360ddd44a69c027",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":434,
                  "y":310},
                "size":{
                  "width":506,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看运单列表信息（全部）/u22.png"}},
{
          "id":"da196df8525a48f6ad5fcead82825227",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":452,
              "y":334},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b94036c53e7843e1a8fc0ef3e9c47cb5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":452,
                  "y":334},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d3a36495313c4c9d8d7c34625948e0db",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":844,
              "y":334},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89ba9808e53148f6966b04260b77e20a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":844,
                  "y":334},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6244fd03120b4e09be8f3f1ff84f3495",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":458,
              "y":384},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d67fd3c27deb4c23a92edb27594fa5e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":458,
                  "y":384},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"84febc2e4b2e4d068f9ca818577caa09",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":434,
              "y":460},
            "size":{
              "width":506,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e98169bef51b4b0d89fc19c00f677df4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":434,
                  "y":460},
                "size":{
                  "width":506,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看运单列表信息（全部）/u30.png"}},
{
          "id":"b0e98f41906347b783d8107d38c6070b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":434,
              "y":470},
            "size":{
              "width":506,
              "height":160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b3eb18dc98f43b3a7f83765150df910",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":434,
                  "y":470},
                "size":{
                  "width":506,
                  "height":160}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看运单列表信息（全部）/u32.png"}},
{
          "id":"fd39a3afc8054b18a9b44c321cc5ecab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Cursiva', 'Arial'",
            "fontStyle":"italic",
            "location":{
              "x":452,
              "y":542},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e69011d5d01e4b6db8d4b6e60c2e4b88",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Cursiva', 'Arial'",
                "fontStyle":"italic",
                "location":{
                  "x":452,
                  "y":542},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "50d4aa8147984246a21fd073889206f0":{
      "scriptId":"u0"},
    "41a90330b18343dd90d46ddaa45feb8b":{
      "scriptId":"u1"},
    "8b8a0db62d8845fa85014a033f3b11f2":{
      "scriptId":"u2"},
    "13bd8e28e8344a2ba28e89390ef84670":{
      "scriptId":"u3"},
    "adac6826f91a4cfa8d4605cd1f9cf639":{
      "scriptId":"u4"},
    "afbab2016b274e11a34ea459b8388638":{
      "scriptId":"u5"},
    "9154f518544d44f1827c8891fc72c00f":{
      "scriptId":"u6"},
    "a42071875c994b5fa5ec4f97a960e93c":{
      "scriptId":"u7"},
    "680a5c42a14c440588bebc5099ad0c07":{
      "scriptId":"u8"},
    "ee36ff10ceae4f2ca2496d042b4c7b93":{
      "scriptId":"u9"},
    "8f7ecb954cd4443291ed44daf6334939":{
      "scriptId":"u10"},
    "978eb1adbf774b1199e017606907cc71":{
      "scriptId":"u11"},
    "c2b5c7eca9e945d19b17e61ee82efc66":{
      "scriptId":"u12"},
    "cbbd6ab5839641749a0bfc25fc761299":{
      "scriptId":"u13"},
    "e19d37f277a64e11829cf9fead5da495":{
      "scriptId":"u14"},
    "049fb7fadb5f40efa83c6ff29c172bbe":{
      "scriptId":"u15"},
    "d7ff1cb6a520426f922868d1477d77e9":{
      "scriptId":"u16"},
    "03b26337105a40739c74712900304c42":{
      "scriptId":"u17"},
    "802e84c44c78408ba4e3c6c2827d5b18":{
      "scriptId":"u18"},
    "6e4c29ce075b4371838a346c2a420c40":{
      "scriptId":"u19"},
    "31e2dc20d5d84d54b0546afdad7282bb":{
      "scriptId":"u20"},
    "f759fd018b2f4a319e04368e8855ddce":{
      "scriptId":"u21"},
    "939f0fb4a36444e397b99f318e9e61b8":{
      "scriptId":"u22"},
    "f8c30ec806b64744a360ddd44a69c027":{
      "scriptId":"u23"},
    "da196df8525a48f6ad5fcead82825227":{
      "scriptId":"u24"},
    "b94036c53e7843e1a8fc0ef3e9c47cb5":{
      "scriptId":"u25"},
    "d3a36495313c4c9d8d7c34625948e0db":{
      "scriptId":"u26"},
    "89ba9808e53148f6966b04260b77e20a":{
      "scriptId":"u27"},
    "6244fd03120b4e09be8f3f1ff84f3495":{
      "scriptId":"u28"},
    "d67fd3c27deb4c23a92edb27594fa5e8":{
      "scriptId":"u29"},
    "84febc2e4b2e4d068f9ca818577caa09":{
      "scriptId":"u30"},
    "e98169bef51b4b0d89fc19c00f677df4":{
      "scriptId":"u31"},
    "b0e98f41906347b783d8107d38c6070b":{
      "scriptId":"u32"},
    "0b3eb18dc98f43b3a7f83765150df910":{
      "scriptId":"u33"},
    "fd39a3afc8054b18a9b44c321cc5ecab":{
      "scriptId":"u34"},
    "e69011d5d01e4b6db8d4b6e60c2e4b88":{
      "scriptId":"u35"}}});